### ISSUE TITLE
Disable keycloak in helm chart for local kubernetes cluster

### ISSUE THREAD

**Issue by vietk** [microcks/microcks#1001]
### Reason/Context

[Podman desktop](https://github.com/containers/podman-desktop) or docker desktop are popular solutions that allows to install a local kubernetes cluster on developer laptops and deploy as a playground the application they are currently working on. 
We find that microcks is a viable solution to mock external API calls boundaries of an application based on several microservices during development.

As of today, it's already possible [to use microcks helm charts](https://github.com/microcks/microcks/tree/master/install/kubernetes) to install a full fledged version of microcks inside the cluster and it works well. 
But this chart is coming with a keycloak installation that bring friction to the developer workflow:
First it forces to use authentication on a mastered environment and second it uses resources from the laptop.

I know this issue has been discussed in #789, and workaround is proposed, but it would be great if the solution is offered at chart level based on a helm  value.

### Description

Add a new helm value that can enable/disable the keycloak installation 
No breaking changes, default value is that the helm chart install keycloak by default

### Implementation ideas

Introduce the usage of KEYCLOAK_ENABLED in the deployment resource and link this to a helm values

**Comment by vietk** [comment]
Note that I have already a made update to the microcks chart for my local deployments and I can contribute the changes with a PR if contribution is accepted 

Regards

**Comment by lbroudoux** [comment]
Hi @vietk,

Thanks for the issue and your test of Microcks as a mocking solution! 

As explained in issue #789 mentioned above, we try not to have too many combinations/options on deployment methods and are currently in the mindset of having:
* Helm Chart or Operator based deployments targeting shared, "production"-typed environment with Keycloak,
* Docker-compose, Docker Desktop Extension or Testcontainers based deployments targeting standalone, development-typed environment without Keycloak (and without MongoDB in the latest version)

That said, we are always interested in understanding users' motivations regarding deployment options!

Have you considered deploying directly using our Docker Desktop extension? We're also working on making it available as a Podman Desktop extension too... Have you also checked our Microcks module for Testcontainers - https://microcks.io/documentation/installing/running-uber/?

I admit this is a bit different than deploying on a Kube cluster, but as we identified those deployment methods to lower the friction in the developer's day-to-day workflow, we'd really like your thoughts on 'em and check why they wouldn't fit you as well.

Cheers,

**Comment by vietk** [comment]
Hello Laurent, thanks for your fast response 

> Helm Chart or Operator based deployments targeting shared, "production"-typed environment with Keycloak
I understand the motivation but as you shown there's already a workaround solution so it's already possible to bypass the keycloack security.
Also not all production environment are based on keycloack, companies can rely on AzureAD or their own Identity providers, so you'll come one day with user asking for not deploying keycloak and rely on their external identity provider. 
BTW, I don't know if microcks allows to do that, by re-using the `keycloak.url` to target another provider.
Anyway as you are already providing a workaround so people can already use microcks without keycloak ... 

> Have you considered deploying directly using our Docker Desktop extension? We're also working on making it available as > a Podman Desktop extension too... 

We already opt-out from Docker Desktop (because it has been moved to non free licencing model for companies) and adopted podman desktop. I think, globally, we are happy  not to rely on vendor extensions on our migration path. 
As a general rule, I think our k8s local cluster potentially mind all the gaps that would featured by any extensions. 
- telemetry
- db
- even microcks :D
The only condition to that is that we have a helm chart, and for this we can reuse existing one, or crafting our.

> Have you also checked our Microcks module for Testcontainers - https://microcks.io/documentation/installing/running-uber/?
Interesting but this is not the same test environment where want to use microcks, but we could reuse this image in simplified helm chart for local clusters

For integration testing we are using the https://github.com/microcks/microcks-quarkus extension (that probably use the same image as above)

**Comment by lbroudoux** [comment]
It's fantastic to learn you're using our Quarkus DevService! 🤩  It's still so fresh... I'd really really really love to have your feedback on it! 

But back to our initial topic... 😉 

> Also not all production environment are based on keycloack, companies can rely on AzureAD or their own Identity providers, so you'll come one day with user asking for not deploying keycloak and rely on their external identity provider.

We've got users in the community that actually used AzureAD configured as an identity provider in Keycloak. 

> BTW, I don't know if microcks allows to do that, by re-using the `keycloak.url` to target another provider.

In fact, the only adherence to Keycloak is when you're using the "multi-tenancy"/security segmentation feature. Otherwise, you should be able to replace it with any other OIDC compliant provider. We've had discussions to make tests, rename stuff and communicate to full OIDC support in coming releases.

>  I think, globally, we are happy not to rely on vendor extensions on our migration path.

Totally makes sense IMO. I think the point is fair enough to justify adding official support for "Keycloak-less" setup in Helm chart! Would you mind pushing a PR?

**Comment by vietk** [comment]
> Would you mind pushing a PR?

Will do it shortly, thanks for your support.

> It's fantastic to learn you're using our Quarkus DevService! 🤩 It's still so fresh... I'd really really really love to have your feedback on it!

The main motivation is to be able to write mocks based on the openAPI spec [as documented in microcks](https://microcks.io/documentation/using/openapi/#introduction). 
The perfect situation would be that the vendor of the API owns the sample so that every team don't have to rewrite its own mocks ... but this probably lack of dynamism in term of mocking response for all different clients.
 So it's a first try.
The idea is also to have the same mocking solution for QuarkustTest and local k8s cluster (developers laptop) and a real DEV environment (cloud/) before real end2end testing

**Comment by lbroudoux** [comment]
Not closing it yet, because I'll have a review on the chart `README.md`
