### ISSUE TITLE
Customization of labels and annotations

### ISSUE THREAD

**Issue by vietk** [microcks/microcks#1005]
### Reason/Context

To improve standardisation of kubernetes based application, companies are using tools like https://github.com/open-policy-agent/gatekeeper that ensure such standardisation.
If a resource is not valid, the application cannot be installed and must comply with the rules in policy.
The first level of standardisation is often the labelling and annotating part of kubernetes resources such as pod/deployments/services ... 

### Description

Microck chart should allow such labels and annotation customization for all resources defined.

### Implementation ideas

There are many possibilities : 
- provide ad-hoc templating for annotation/label customization
- or the most portable one would be to migrate the chart to [bitnami's common template](https://github.com/bitnami/charts/blob/4683a83b8e8ce9c19e944b59c3f17dfe4a1a43a6/template/README.md)

Note using kustomize would be a valid solution, but would have an impact of helm releases deployment.

**Comment by vietk** [comment]
Note that I have a PR and I can do the contribution if the feature request is accepted

**Comment by lbroudoux** [comment]
This is a great addition! I've started doing the same things in the new `microcks-operator` initiative written in Quarkus. Feel free to push your PR. Thank you!

**Comment by lbroudoux** [comment]
Many thanks @vietk!
