### ISSUE TITLE
[OpenAPI] Test & Mock an endpoint with a query param array

### ISSUE THREAD

**Issue by aeoncl** [microcks/microcks#1016]
### Describe the bug

Hi!
In an OpenAPI contract, when you have an endpoint that defines an array of query params, mocking or testing doesn't seem to work properly:

```yaml
parameters:
  - in: query
    name: ids
    schema:
      type: array
      items:
        type: string
```

**EDIT**: The OpenAPI Spec has multiple ways to handle query parameter arrays, the default one is to repeat the parameter key multiple times. (style: form, explode: true)
see: [https://swagger.io/docs/specification/serialization/](https://swagger.io/docs/specification/serialization)

### Expected behavior

1. In microcks GUI, you should get a correct mocking url:
![image](https://github.com/microcks/microcks/assets/48886723/1389c4b8-e41c-4ec1-80df-09eb305d9dba)
2. Calling this url while changing the ids passed in the array should match correctly against the examples
3. When running a test, it should send those parameters correctly

### Actual behavior

There are multiple weird behaviours at play here:

1. The mocking URL displayed in microcks GUI shows the array as a JSON Array
![image](https://github.com/microcks/microcks/assets/48886723/28b279bb-4b2b-4bd1-a0f1-3a0bce679414)

2. When calling that malformed mock URL, you get an error
![image](https://github.com/microcks/microcks/assets/48886723/7a374925-2c43-487b-9eb3-d39393d14679)

3. Mock answers with an example when you manually create a correct URL but
![image](https://github.com/microcks/microcks/assets/48886723/acee1fea-4c2b-44e3-ad12-261c7ad4ae36)

4. The mock always answers with the same case regardless of which values you pass
![image](https://github.com/microcks/microcks/assets/48886723/b6853174-016c-446e-8bec-7842dcb8f3f1)

5. When testing, Microcks sends the query parameters as a JSON Array too

### How to Reproduce?

To reproduce this, you can just import the following OpenAPI definition: 

```yaml
openapi: 3.0.3
info:
  title: Someone API
  description: Someone API
  version: 1.0.0
servers:
  - url: "{protocol}://{hostname}:{port}/{basePath}/"
    variables:
      protocol:
        enum:
          - https
          - http
        default: http
      hostname:
        default: localhost
      port:
        default: "8080"
      basePath:
        default: api
tags:
  - name: Someone
paths:
  '/someone/something':
    get:
      security:
        - bearerAuth: [ ]
      description: Search someone based on a list of ids
      operationId: searchStuff
      tags:
        - StuffiStuffo
      parameters:
        - in: query
          name: ids
          required: true
          description: |-
            Get stuff using a list of ids
          schema:
            type: array
            items:
              type: string
          examples:
            SINGLE_SUCCESS:
              value: 
                - "123"
                - "1234"
            SECOND_CASE:
              value: 
                - "666"

        - in: query
          name: dataReturned
          schema:
            type: string
            default: 'SUMMARY'
        - $ref: "#/components/parameters/pageParam"
        - $ref: "#/components/parameters/sizeParam"
      responses:
        '200':
          description: SomeoneInfo
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SomeonePage"
              examples:
                SINGLE_SUCCESS:
                  value:
                    pageSize: 10
                    pageNumber: 0
                    totalPage: 1
                    totalElements: 1
                    isFirst: true
                    isLast: true
                    content:
                      - id: "123"
                        firstname: "Avril"
                        lastname: "Lavigne"
                SECOND_CASE:
                  value:
                    pageSize: 10
                    pageNumber: 0
                    totalPage: 1
                    totalElements: 1
                    isFirst: true
                    isLast: true
                    content:
                      - id: "666"
                        firstname: "Jack"
                        lastname: "Black"
components:
  securitySchemes:
    bearerAuth: # arbitrary name for the security scheme
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Page:
      type: object
      properties:
        content:
          type: array
          items:
            type: object
        pageNumber:
          type: integer
        pageSize:
          type: integer
        totalPage:
          type: integer
        totalElements:
          type: integer
        isFirst:
          type: boolean
        isLast:
          type: boolean

    Someone:
      type: object
      description: Someone information
      properties:
        id:
          type: string
        firstname:
          type: string
        lastname:
          type: string
          
    SomeonePage:
      allOf:
        - $ref: "#/components/schemas/Page"
        - type: object
          properties:
            content:
              default: []
              items:
                $ref: '#/components/schemas/Someone'
  parameters:
    pageParam:
      in: query
      name: pageNumber
      schema:
        type: integer
        minimum: 0
        default: 0
    sizeParam:
      in: query
      name: pageSize
      schema:
        type: integer
        default: 10
```

### Microcks version or git rev

9c54fcef9668c749ceb63d1a50f12597d2df5c8a

### Install method (`docker-compose`, `helm chart`, `operator`, `docker-desktop extension`,...)

Docker run latest nightly version of microcks-uber

### Additional information

After looking at the code, the issue seems to lie in the OpenApiImporter class, in extractParametersByExample>getExampleValue.
The example value is considered to be a JsonArray, which it should not be.
I'm down to do a PR for this

**Comment by lbroudoux** [comment]
Hello! Thank you very much for the detailed information on the issue and the reproducer.
Will have a look at it probably on next week (currently trying to catch up with all things late during a period of travels)

**Comment by lbroudoux** [comment]
Thanks for the interest. Marking it as `keep-open`

**Comment by lbroudoux** [comment]
Thanks @aeoncl for the nice contribution!
