### ISSUE TITLE
Ubuntu 22.04 Virtualbox - Failed to initialize authentication subsystem.

### ISSUE THREAD

**Issue by Xanathos** [microcks/microcks#1024]
Hello, 
I have installed Ubuntu 22.04 in a Virtualbox and set network to bridged. After installing microcks 1.7.1, I installed the containers and they al started fine in the vm. Then I took the ip address from the vm and run it from windows using port 8080 to check on microcks from outside the vm but i get the "Failed to initialize authentication subsystem." error.

![image](https://github.com/microcks/microcks/assets/2001719/9f886982-22bd-41be-a6cd-b799c986ee83)

Is there something in the microcks realm I still need to set?

**Comment by lbroudoux** [comment]
Hey there!
Have you installed everything using docker-compose? Is it working from inside the VM? If yes, then it may be a redirection problem... The default redirection URI is `KEYCLOAK_PUBLIC_URL` and is set to `http://localhost:18080` by default in docker-compose mode. You'll have to adapt this to use the VM IP address. Also, you'll need to reconfigure the Keycloak realm to add this IP ad a possible redirect address once the authentication is ok. This should be done at the `microcks-app-js` client level in Keycloak console.
