### ISSUE TITLE
Cannot return a byte array in response

### ISSUE THREAD

**Issue by rakesh-groww** [microcks/microcks#1031]
### Describe the bug

I'm using the following script which calls an endpoint & returns its response to the client as it is. The endpoint i'm calling gives a content of type "mulipart/form-data". I'm putting the response bytes in requestContext & returning it to the client from examples. But in my response im seeing toString representation of the byte array in my response. For example: **[B@266693fc**

Here is the dispatching rule which i am using. 

```
dispatcherRules: |
          def url = 'https://example.org'
         
          def connection = url.toURL().openConnection()
          connection.requestMethod = 'GET'
          
          def responseCode = connection.responseCode
          if (responseCode.equals(200)) {
            def responseData = IOUtils.toByteArray(connection.inputStream)
             //Tried this also
             // def responseData = connection.inputStream.bytes

            requestContext.put("myResponseData", responseData)
          } 
```   

And here is the my response example:

```
responses:
        "200":
          content:
            multipart/form-data:
              examples:
                CREATE_REQUEST:
                  headers:
                    content-disposition: inline;filename=f.txt
                  value: |-
                    {{myResponseData}}
```
                    
 

### Expected behavior

I expect the api to return a byte array in the response. 

### Actual behavior

I'm seeing toString representation of the byte array.

**Comment by lbroudoux** [comment]
I think this one is related to #1093 and being discussed into this thread. Please let me know and reopen this one if it's not the case.
