### ISSUE TITLE
OpenAPI importer has no $ref resolution at the path/operation level

### ISSUE THREAD

**Issue by Apoorva64** [microcks/microcks#1034]
### Describe the bug

Continuation of #1032 
The different  files are now imported but the refs are not correctly resolved in the specification

### Expected behavior

Refs should be resolved correctly 

### Actual behavior

Refs are not resolved correctly
![image](https://github.com/microcks/microcks/assets/60534691/95a4e0b7-9f66-4ccd-b889-dba1477d8973)

### How to Reproduce?

Same as before.
3. Go to Services tab and look at the API definition the exemples defined in the specification won't be available

### Microcks version or git rev

quay.io/microcks/microcks:nightly@sha256:407c2ea2ae8fbaaed792d46ebf90ed7f505e91f745fd852ef0adacf948c0d0e5

### Install method (`docker-compose`, `helm chart`, `operator`, `docker-desktop extension`,...)

docker-compose

### Additional information

it seems that the importing of the files works but the resolving dosen't.
If you go to the documentation url and download the spec we get:
```yaml
openapi: 3.0.0
info:
  title: OpenAPI Car API
  description: Sample OpenAPI API using cars
  version: 1.0.0
  license:
    name: MIT
    url: https://urltolicence.com
security: []
servers:
  - url: server1.car.com
paths:
  /owner/{owner}/car:
    $ref: OpenAPI+Car+API-1.0.0-path.yaml
```
Instead of a fully resolved and dereferenced openapi file

**Comment by lbroudoux** [comment]
Ha ha ha! I was to quick to close the previous one and didn't check everything... my bad.
Coming back to this issue as I absolutely want to have this one closed before releasing `1.8.1` next week.

**Comment by Apoorva64** [comment]
No problem xD. I am free this weekend. You can ping me to test it at any time

**Comment by lbroudoux** [comment]
Got a fix! In fact, there was no `$ref` resolution at the path/operation level. I've just added one and completed the unit test. I'm also gonna change the issue title to better reflect the issue.

**Comment by Apoorva64** [comment]
@lbroudoux in the Contracts we can see that there are 2 contracts with the same name as the file name is the same. But thoses are two different files. We should probably add the path to the name to make it unique

**Comment by lbroudoux** [comment]
Oh! I see the `response.yaml` has been erased

**Comment by lbroudoux** [comment]
Both different responses are correctly imported, though. Let me check

**Comment by Apoorva64** [comment]
Currently we will be using microcks only for testing

**Comment by lbroudoux** [comment]
Now tracked here: #1035

**Comment by lbroudoux** [comment]
Now shipped within the `nightly` tagged image.
