### ISSUE TITLE
Allow full OpenAPI content re-normalization with embedded resources

### ISSUE THREAD

**Issue by lbroudoux** [microcks/microcks#1035]
### Reason/Context

Now that we introduced recursive resolution of external `$ref` in OpenAPI (see #986), imported content should also be reusable to perform full contract-testing.

### Description

Imported specification (OpenAPI specs, JSON schemas, JSON files) should be normalized to reference the resources owned and served by Microcks server in order to perform full schema validation.

As os today, we just adapt the content of the main root OpenAPI specification that is imported but don't change the content of embedded entities. We should do the same thing recursively on every imported content.

**Comment by Apoorva64** [comment]
@lbroudoux if 2 exemples have the same name but are in 2 different Operations. The second exemple gets overriden by the first one.
Can you send the link to the gitlab repository so that i can do a pull request there to provide an exemple.

**Comment by lbroudoux** [comment]
Here's the link: https://gitlab.com/lbroudoux/microcks-tests

**Comment by Apoorva64** [comment]
https://gitlab.com/lbroudoux/microcks-tests/-/merge_requests/1
Here's the MR
Here's the link to the exemple to put in the importer https://gitlab.com/api/v4/projects/53591717/repository/files/complex-example-2%2Fopenapi.yaml/raw?head=main

**Comment by lbroudoux** [comment]
MR has been merged. I was thinking about it this week-end and I'd like to tackle this one before jumping on `1.9.0`. MOving it into `1.8.1`:wink:

**Comment by lbroudoux** [comment]
Finally, I implemented stuff in a proper way using a fully recursive approach. I also introduced a `context` in resource name to avoid collision between resources having the same short name but in different paths.

Having a look at the https://gitlab.com/lbroudoux/microcks-tests/-/tree/main/complex-example-2?ref_type=heads repository, we are now extracting 16 resources that are named:

```
OpenAPI Car API-1.0.0.yaml"
OpenAPI Car API-1.0.0-paths-owner@{owner}-path.yaml"
OpenAPI Car API-1.0.0-paths-owner@{owner}-get-404-response.yaml"
OpenAPI Car API-1.0.0-paths-components-schemas-Error.yaml"
OpenAPI Car API-1.0.0-paths-owner@{owner}-get-404-examples-NOT_FOUND.yaml
OpenAPI Car API-1.0.0-paths-components-parameters-path-owner.yaml
OpenAPI Car API-1.0.0-paths-owner@{owner}-get-200-response.yaml
OpenAPI Car API-1.0.0-paths-owner@{owner}-get-200-examples-maxime.yaml
OpenAPI Car API-1.0.0-paths-components-schemas-Owner.yaml
OpenAPI Car API-1.0.0-paths-owner@{owner}-get-200-examples-laurent.yaml
OpenAPI Car API-1.0.0-paths-owner@{owner}@car-path.yaml
OpenAPI Car API-1.0.0-paths-owner@{owner}@car-get-404-response.yaml
OpenAPI Car API-1.0.0-paths-owner@{owner}@car-get-404-examples-NOT_FOUND.yaml
OpenAPI Car API-1.0.0-paths-owner@{owner}@car-get-200-response.yaml
OpenAPI Car API-1.0.0-paths-owner@{owner}@car-get-200-examples-maxime.yaml
OpenAPI Car API-1.0.0-paths-owner@{owner}@car-get-200-examples-laurent.yam
```

The content of each imported resource is then re-normalized referencing the Microcks owned and named resource.
