### ISSUE TITLE
Missing properties / wrong types in Microcks OpenAPI Spec

### ISSUE THREAD

**Issue by aeoncl** [microcks/microcks#1043]
### Describe the bug

Hi !
I'm using an OpenAPI generator plugin to call the Microcks API and i've noticed some differences between the spec v1,8 and what data microcks actually sends.

1. The property "sourceArtifact" is missing in the Service component
2. In the metadata component, the two properties createdOn and lastUpdate are marked as integer but they are too large to be parsed as a java integer when using a generator, they should be marked as number instead

I'll make a PR with the proposed fix to see what is doable

### Expected behavior

I expect the OpenAPI spec to reflect the truth

### Actual behavior

Some stuff is missing 

### How to Reproduce?

SourceArtifact:
You can call the /services endpoint:
![image](https://github.com/microcks/microcks/assets/48886723/041e0d96-613a-4885-afd8-fcefbf94cd35)
The sourceArtifact property is there, but it's not in the OpenAPISpec:
![image](https://github.com/microcks/microcks/assets/48886723/78da1442-13ad-4c78-a7f7-bf1a6633588e)

Metadata:

![image](https://github.com/microcks/microcks/assets/48886723/4be3690e-9d7a-4525-b0f5-466be761adb1)

### Microcks version or git rev

Microcks Uber tag 701d6149efa0

### Install method (`docker-compose`, `helm chart`, `operator`, `docker-desktop extension`,...)

Test Containers

**Comment by lbroudoux** [comment]
Awesome! Thanks for the issue and the PR to come! 

On that topic, I wondered the other day why we wouldn't provide an official Java client for the API. - like we're doing for Go (see https://github.com/microcks/microcks-go-client).

This client would certainly be helpful:
* internally (if usable/compatible with the new operator we project to write in Quarkus - see https://github.com/microcks/microcks-operator)
* externally - to community users like you who are probably automating/building stuff on top of Microcks

What do you think? It could be great to learn from your experience.

**Comment by aeoncl** [comment]
You're welcome ! Thanks for building a nice product :D

About the clients, we usually just generate our own based on the OpenAPI spec of the providers, this way you don't need to support every framework or HttpClient library or language yourself. Just write a nice contract once and you're all set :D

https://openapi-generator.tech/docs/generators

We are indeed building something on top of Microcks and i'll be glad to come by and tell you all about it because i think you'll be interested ! But to TLDR; we are abusing the API a little to add the ability to create semi-dynamic mocks on the fly orchestrated by our tests. Those mocks are based on the examples from the OpenAPI spec, we take the existing example as a base and change the data we need. This way our mocks are dynamic enough but they are still bound by the provider's examples

It's quite hacky but it works, it would be cool to have first party support for this tho :D

**Comment by lbroudoux** [comment]
Nice! I am definitely hooked and interested in your approach!! Is this something you can share in the open?

We're thinking about scheduling some sort of "Office Hours" open sessions and would like to include/invite community members who would like to explain what they're doing with Microcks. It sounds like a perfect topic! (If you can share it openly, of course)

BTW: have you checked our Testcontainers module for running Microcks from your tests? You can check either https://microcks.io/documentation/installing/running-uber/ or https://testcontainers.com/modules/microcks/.

**Comment by aeoncl** [comment]
Yes we are willing to contribute back and the less we have on our side only, the better :D
Some kind of open sessions would be cool where we can just pop in a room and discuss stuff, or maybe if you have some kind of chatroom like a Matrix room or something :D

I did check your TestContainer module and we are using it !
Our plan is to use microcks for mocking in two different ways:

- For integration tests we use Microcks Uber with the TestContainer module
- For E2E tests, we spin up Microcks Uber through a custom helm chart in our Kubernetes cluster

**Comment by lbroudoux** [comment]
Interesting! Have you seen #1030?

**Comment by aeoncl** [comment]
I did not ! But that would be very cool ! Microcks Uber is perfect as the throwable api mocking server of a ci deployment. So having an already availlable helm chart for it would be nice !

**Comment by lbroudoux** [comment]
The fixed OpenAPI file is here: https://github.com/microcks/microcks/blob/1.9.x/api/microcks-openapi-v1.9.yaml

**Comment by aeoncl** [comment]
Nice thanks ! :D
