### ISSUE TITLE
Some actions of gRPCurl not working

### ISSUE THREAD

**Issue by hguerrero** [microcks/microcks#1045]
### Describe the bug

When trying to use the reflection methods with the grpcurl CLI tool, it just blocks and hangs without returning.

### Expected behavior

For example when running `list` see the methods available in the server

### Actual behavior

If just hangs

### How to Reproduce?

Use the Microcks gRPC example,

Then issue the following command:

```grpcurl -plaintext localhost:9090 list io.github.microcks.grpc.hello.v1.HelloService```

### Microcks version or git rev

1.8.1

### Install method (`docker-compose`, `helm chart`, `operator`, `docker-desktop extension`,...)

docker-desktop-extension

**Comment by lbroudoux** [comment]
Yes, this is a known issue, as we are not enabling Server Reflection in gRPC mocks. There are some [tutorials out there](https://github.com/grpc/grpc-java/blob/master/documentation/server-reflection-tutorial.md) but never tested this feature and don't know if it's compatible with the way we have implemented gRPC request handling...

It could be nice to have a test ride 😉

**Comment by hguerrero** [comment]
Should we add an issue request to implement Server Reflection for the gRPC server and link this issue to that one?

**Comment by lbroudoux** [comment]
It could be a nice addition if feasible.

**Comment by guyguy333** [comment]
I also have interest for gRPC reflection feature :)

**Comment by lbroudoux** [comment]
It looks like the [above-mentioned tutorials](https://github.com/grpc/grpc-java/blob/master/documentation/server-reflection-tutorial.md) provide an implementation with version `v1alpha1` of the reflection protocol. However, `grpcurl` now seems to use version `v1`; unfortunately, this one doesn't seem to be implemented into the Java `grpc-services`...

**Comment by lbroudoux** [comment]
Found it! https://github.com/grpc/grpc-java/issues/6724

**Comment by guyguy333** [comment]
> It looks like the [above-mentioned tutorials](https://github.com/grpc/grpc-java/blob/master/documentation/server-reflection-tutorial.md) provide an implementation with version `v1alpha1` of the reflection protocol. However, `grpcurl` now seems to use version `v1`; unfortunately, this one doesn't seem to be implemented into the Java `grpc-services`... So we can't simply implemented existing interfaces to supply reflection information.
> 
> I will have a look at the Java grpc GitHub repo to check if this is something they have in roadmap. Otherwise, the trick will be to generate our own Stub from the `v1` protobuffer file and then implement the service using generated Java stub interfaces...

Thanks for checking this. In fact, v1alpha1 == v1 (except for version). Content didn't change, just few comments

https://github.com/grpc/grpc/tree/master/src/proto/grpc/reflection

**Comment by lbroudoux** [comment]
Make some progress right here and succeed in making some stuff works with grpcurl. See:

```sh
$ grpcurl -plaintext -d '{"firstname": "Laurent", "lastname": "Broudoux"}' localhost:9090 io.github.microcks.grpc.hello.v1.HelloService/greeting
=== OUTPUT ===
{
  "greeting": "Hello Laurent Broudoux !"
}
```

**Comment by lbroudoux** [comment]
Closing this one as the implementation efforts are now tracked in #1088
