### ISSUE TITLE
Expose the OAuth2ClientContext scope parameter via the UI 

### ISSUE THREAD

**Issue by felipe-alves-moraes** [microcks/microcks#1055]
### Reason/Context

When Integrating with an OAuth Token provider that needs a specific scope we should be able to provide this during the test run configuration.

### Description

Add a field in the OAuth configuration page that allows users to set the scope.

**Comment by lbroudoux** [comment]
This field must also be displayed when accessing the details of a previous test

**Comment by lbroudoux** [comment]
Now done and available in the `nightly` container image.
