### ISSUE TITLE
Add support for AsyncAPI v3

### ISSUE THREAD

**Issue by lbroudoux** [microcks/microcks#1063]
AsyncAPI version 3 is under heavy work. We should prepare its release and support in Microcks.

**Comment by savvyintegrations** [comment]
Thank you for all the recent activity on this! We are actively creating new microservices using OAS and AsyncAPI v3, and Microcks looks like just the tool we need for contract testing and more.

**Comment by lbroudoux** [comment]
Just missing documentation on website, link to actual samples and note on dynamic channels/parameters support now correctly implemented for v3 (see #846)

**Comment by lbroudoux** [comment]
Finally add documentation 😉
