### ISSUE TITLE
Postman v2.1 Collection imported successfully but no mocks or samples generated.

### ISSUE THREAD

**Issue by bongosway** [microcks/microcks#1066]
### Describe the bug

Following the example documentation:

1. Built microck using docker-compose. The only difference was the app port was changed to 9080
2. Imported the attached(schema.proto.txt) file schema.proto successfully.
3. Imported the attached BookAuthorService-postman.json file successfully.

[BookAuthorService-postman.json](https://github.com/microcks/microcks/files/14175705/BookAuthorService-postman.json)
[schema.proto.txt](https://github.com/microcks/microcks/files/14175709/schema.proto.txt)

### Expected behavior

1.  Samples loaded in the operations section like the demo service
<img width="1255" alt="image" src="https://github.com/microcks/microcks/assets/7461869/b684fe0c-257c-4aca-ac6b-5d55d5fba0eb">

2. Expected to see a mock URL like the demo service
<img width="1228" alt="image" src="https://github.com/microcks/microcks/assets/7461869/9c6a4ba6-a949-4ab7-85c4-ee82e8a8eb0c">

### Actual behavior

1. Samples were not loaded.
<img width="1263" alt="image" src="https://github.com/microcks/microcks/assets/7461869/682e3498-edf2-4473-8df3-d43fd91b00ed">

2. Mock URL not generated.
<img width="1260" alt="image" src="https://github.com/microcks/microcks/assets/7461869/1ce32337-2d12-4de2-a610-bb50f5fb74c8">

### How to Reproduce?

1. Build microcks using docker-compose, change the microcks port  9080
2. Import the attached(schema.proto.txt) file schema.proto.
3. Imported the attached BookAuthorService-postman.json file.
[schema.proto.txt](https://github.com/microcks/microcks/files/14175766/schema.proto.txt)
[BookAuthorService-postman.json](https://github.com/microcks/microcks/files/14175767/BookAuthorService-postman.json)

### Microcks version or git rev

1.8.1

### Install method (`docker-compose`, `helm chart`, `operator`, `docker-desktop extension`,...)

`docker-compose`

### Additional information

 microcks port was changed to 9080 in docker-compose file
Also change in the microcks-realms-sample.json
  "redirectUris": [
        "http://localhost:9080/*"
      ],

**Comment by lbroudoux** [comment]
Ok. There's a problem in your Postman collection because the examples url must also match with the name of the gRPC method (as detailed in [our documentation](https://microcks.io/documentation/using/grpc/#specifying-service-examples))

So adapt the URL like in below snippet:

```json
{
	"info": {
		"_postman_id": "2d33ccbb-b791-45eb-ab08-149ceec4464b",
		"name": "BookAuthorService",
		"description": "version=v1 - This collection holds mock messages for BookAuthorService v1 GRPC",
		"schema": "https://schema.getpostman.com/json/collection/v2.1.0/collection.json",
		"_exporter_id": "32759124"
	},
	"item": [
		{
			"name": "getAuthor",
			"item": [
				{
					"name": "getAuthor",
					"request": {
						"method": "GET",
						"header": [],
					"url": {
						"raw": "http:///getAuthor",
						"protocol": "http",
						"host": [
							"localhost"
						],
						"port": "8090",
						"path": [
							"author"
							]
						}
					},
					"response": [
						{
							"name": "Charles",
							"originalRequest": {
								"method": "GET",
								"header": [
									{
										"key": "Content-Type",
										"name": "Content-Type",
										"value": "application/json",
										"type": "text"
									}
								],
								"url": {
									"raw": "http://localhost:8090/author/1",
									"protocol": "http",
									"host": [
										"localhost"
									],
									"port": "8090",
									"path": [
										"author",
										"1"
									]
								}
							},
							"_postman_previewlanguage": "json",
							"header": [
								{
									"key": "Content-Type",
									"value": "application/json"
								}
							],
							"cookie": [],
							"body": "{\n    \"com.devProblems.Author.author_id\": 1,\n    \"com.devProblems.Author.first_name\": \"Charles\",\n    \"com.devProblems.Author.last_name\": \"Dickens\",\n    \"com.devProblems.Author.gender\": \"male\",\n    \"com.devProblems.Author.book_id\": 1\n}"
						}
					]
				}
			]
		}
	]
}
```

And you'll be able to import your Postman collection and get the following result:

![Capture d’écran 2024-02-07 à 16 50 24](https://github.com/microcks/microcks/assets/1538635/7859731d-a3e9-4d04-ba0a-ac980f48da66)

Cheers,

**Comment by bongosway** [comment]
@lbroudoux many thanks for looking into this. I apologise for not updating the issue sooner because I discovered it was my error and fixed it. But I was neck deep into the internals of microcks and I got carried away.
The codebase is nice to work with, hoping I will find more time to contribute. 

All the best 🤝
