### ISSUE TITLE
Documentation not Rendering with multi-OpenApi files

### ISSUE THREAD

**Issue by Apoorva64** [microcks/microcks#1067]
### Describe the bug

When loading a multi-file OpenApi file the documentation does not render properly

### Expected behavior

Renders the documentation correctly

### Actual behavior

Does not render the documentation correctly

### How to Reproduce?
1. import https://gitlab.com/api/v4/projects/53591717/repository/files/complex-example-2%2Fopenapi.yaml/raw?head=main
2. go to the documentation the exemples will be missing

### Microcks version or git rev

1.8.1

### Install method (`docker-compose`, `helm chart`, `operator`, `docker-desktop extension`,...)

docker-compose

**Comment by Apoorva64** [comment]
@lbroudoux the problem comes from using illegal characters in the names of the artifacts.

I have created a simpler exemple of (https://gitlab.com/api/v4/projects/53591717/repository/files/complex-example-2%2Fopenapi.yaml/raw?head=main) without any illegal characters such as "{}@" here(https://gitlab.com/api/v4/projects/53591717/repository/files/complex-example-3%2Fopenapi.yaml/raw?head=main) and it works.

**Comment by Apoorva64** [comment]
Fix Implementation Idea:
Review the generation of artifact names.

- The safest way would be to base64 the whole name but this would be not very user readable.
- Another solution would be to replace the illegal character by a legal character but this technique would bring in collision problems.

**Comment by lbroudoux** [comment]
Now merged. We can close this one.
