### ISSUE TITLE
Secret not set when editing Import Job

### ISSUE THREAD

**Issue by guyguy333** [microcks/microcks#1075]
### Describe the bug

If you edit an existing import jobs, previously selected secret is no longer selected. So if you're not strictly verifying, you can break your config even if you change nothing.

### Expected behavior

Secret select is right during an edit.

### Actual behavior

Secret select is wrong during an edit.

### How to Reproduce?

1. Create an Import Job with a Secret
2. Edit Import Job and check Secret previously selected is not set

### Microcks version or git rev

1.8.1

### Install method (`docker-compose`, `helm chart`, `operator`, `docker-desktop extension`,...)

helm-chart

**Comment by lbroudoux** [comment]
Thank you for reporting this issue! I succeeded in reproducing it and will look at a fix.

**Comment by lbroudoux** [comment]
A new `quay.io/microcks/microcks:nightly` container image embedding the fix is coming!
