### ISSUE TITLE
Unable to sync with SSL certificate check when reusing a Secret with caCert as an empty string

### ISSUE THREAD

**Issue by guyguy333** [microcks/microcks#1076]
### Describe the bug

I added an Import Job which sync a file from a GitLab repository using GitLab API. GitLab is served behind HTTPS with a valid certificate. However, if I don't enable "Disable SSL verification", it always fail.

```
14:30:53.468 [INFO] io.github.microcks.service.ServiceService - Importing service definitions from https://git.example.com/api/v4/projects/123/repository/files/a%2Fb%2Fv1alpha1%2Fmailbox.proto/raw?ref=main
14:30:53.468 [ERROR] io.github.microcks.util.HTTPDownloader - Caught exception while preparing TrustManager for connecting https://git.example.com/api/v4/projects/123/repository/files/a%2Fb%2Fv1alpha1%2Fmailbox.proto/raw?ref=main: Could not parse certificate: java.io.IOException: Empty input
14:30:53.469 [WARN] io.github.microcks.service.JobService - MockRepositoryImportException while importing job 'my-proto' : https://git.example.com/api/v4/projects/123/repository/files/a%2Fb%2Fv1alpha1%2Fmailbox.proto/raw?ref=main cannot be downloaded
14:30:53.475 [INFO] io.github.microcks.service.JobService - Import of job 'my-proto' done
14:
```

### Expected behavior

Success sync for Import Job using SSL

### Actual behavior

Sync failure for Import Job using SSL

### How to Reproduce?

1. Create an Import Job with HTTPS (in my case GitLab)
2. Force import and check logs

### Microcks version or git rev

1.8.1

### Install method (`docker-compose`, `helm chart`, `operator`, `docker-desktop extension`,...)

helm-chart

**Comment by lbroudoux** [comment]
Hey there!

Thanks for creating the issue. I did a test and was not able to reproduce it.

As I don't have any GitLab or even a Https service with a custom certificate at hand, I did a local test.
My test procedure was the following one :
* Generate self-signed certificate and key using `openssl` (`openssl req -x509 -sha256 -nodes -newkey rsa:2048 -days 365 -keyout localhost.key -out localhost.crt`)
* Start a local HTTPS Server using Python and pointing to my local key and cert (I've used code from https://stackoverflow.com/questions/56503241/python-m-http-server-443-with-ssl)
* On Microcks, create a simple secret with the content of `localhost.crt`
* On Microcks, create an importer using `https://localhost:4443` base URL and pointing to a local file, enabling SSL verification (letting the box unchecked) and referencing the previous secret

It works as explained with the logs:

```
17:16:45.699 DEBUG 29911 --- [080-exec-8] i.github.microcks.web.JobController      : Starting job with id 65c4fd67a469f867cba448fa
17:16:45.706  INFO 29911 --- [080-exec-8] i.github.microcks.service.JobService     : Starting import for job 'API Pastries Localhost HTTPS'
17:16:45.706 DEBUG 29911 --- [080-exec-8] i.github.microcks.service.JobService     : Retrieving secret localhost-python-https for job API Pastries Localhost HTTPS
17:16:45.710  INFO 29911 --- [080-exec-8] i.g.microcks.service.ServiceService      : Importing service definitions from https://localhost:4443/apipastries-openapi.yaml
17:16:45.722 DEBUG 29911 --- [080-exec-8] i.g.microcks.util.HTTPDownloader         : Secret for https://localhost:4443/apipastries-openapi.yaml contains a CA Cert, installing certificate into TrustManager
17:16:45.800 DEBUG 29911 --- [080-exec-8] g.m.u.RelativeReferenceURLBuilderFactory : Returning a SimpleReferenceURLBuilder
17:16:45.802  INFO 29911 --- [080-exec-8] i.g.m.u.MockRepositoryImporterFactory    : Found an openapi: 3 pragma in file so assuming it's an OpenAPI spec to import
17:16:45.826 DEBUG 29911 --- [080-exec-8] i.g.microcks.service.ServiceService      : Service [API Pastries, 0.0.1] exists ? false
```

To be sure it works correctly, I've also done a test enabling SSL verification and without providing any secret and got this kind of result in the logs:

```
17:18:46.862 DEBUG 30592 --- [080-exec-9] i.github.microcks.web.JobController      : Starting job with id 65c4fd67a469f867cba448fa
17:18:46.868  INFO 30592 --- [080-exec-9] i.github.microcks.service.JobService     : Starting import for job 'API Pastries Localhost HTTPS'
17:18:46.868  INFO 30592 --- [080-exec-9] i.g.microcks.service.ServiceService      : Importing service definitions from https://localhost:4443/apipastries-openapi.yaml
17:18:46.944  WARN 30592 --- [080-exec-9] i.github.microcks.service.JobService     : MockRepositoryImportException while importing job 'API Pastries Localhost HTTPS' : https://localhost:4443/apipastries-openapi.yaml cannot be downloaded
17:18:46.949  INFO 30592 --- [080-exec-9] i.github.microcks.service.JobService     : Import of job 'API Pastries Localhost HTTPS' done
```

Can you please re-check how you created your secret? From the logs it looks like it fails parsing the certificate PEM representation... Maybe you can also turn DEBUG log level to get more info?

Let me know.

**Comment by guyguy333** [comment]
Hi @lbroudoux,

Thanks for looking at my issue.

I'm not using a self-signed certificate. Certificate is signed with Let's Encrypt and is trusted so I should not need to specify a PEM certificate. Do you confirm ?

Maybe it's the issue, tool try to import an empty certificate whereas it should not because root CA should directly trust it ?

Of course I can provide more debug but I wanted to confirm with you first my understanding and guess :)

**Comment by lbroudoux** [comment]
Oh OK, sorry I read a bit too quickly and thought it was a self-signed cert...
IIRC you shouldn't have to provide any secret and could turn on SSL validation for Let's encrypt. It should work OOTB.
Can you confirm this is actually the test you're doing ?

**Comment by guyguy333** [comment]
> Oh OK, sorry I read a bit too quickly and thought it was a self-signed cert... IIRC you shouldn't have to provide any secret and could turn on SSL validation for Let's encrypt. It should work OOTB. Can you confirm this is actually the test you're doing ?

Yes exactly. In review modal I have: 

> SSL Validation disabled:false

I don't get why it tries to parse certificate. It's just a guess following my previous guess. I use a secret and in the secret I've seen there is a field "CA Certificate" that I don't use, so that is empty. Maybe Microcks try to use it even if it is empty as I use the secret ?

**Comment by lbroudoux** [comment]
Yes, that's the case. If you reuse the previous same secret and reset its `caCert` property, it's still considered as nonnull, and we try to install it within the trust manager for issuing the HTTPS connection.

Good pick! I'm gonna rename the issue a bit and provide a fix so that it will be more robust in the future.

**Comment by lbroudoux** [comment]
The fix is now in the new `quay.io/microcks/microcks:nightly` container image.
