### ISSUE TITLE
Switch to gRPC full service name - instead of short one

### ISSUE THREAD

**Issue by guyguy333** [microcks/microcks#1077]
### Reason/Context

Support multiple gRPC service names with same name.

### Description

When you import a gRPC service, it imports only with its service name. However, and we have the case, you could have the same service name in different micro services but also the same service name in differents companies. Currently, we can't distinguish them in Microcks.
If proto is well constructed, then it must include a kind of absolute package name beginning with company name. It's like a c++ namespace and solve exactly issue about having same name.

Example: 

> package google.container.v1alpha1;

https://github.com/googleapis/googleapis/blob/master/google/container/v1alpha1/cluster_service.proto

### Implementation ideas

It would be great if service name was not service name itself only but the full name. In the example above we could expect to have : 

`google.container.ClusterManager` with version `v1alpha1`

**Comment by lbroudoux** [comment]
You're right: as of today, we're using the short name that is provided by the `ServiceDescriptorProto` provided by protobuf metadata, but it would make more sense to switch to the full qualified name!

Great suggestion!

**Comment by lbroudoux** [comment]
I did a quick test; unfortunately, it broke some unexpected things!
When you want to import some data using a Postman Collection, the service name has changed ans so the collection must be updated too. This has the side effect that our samples, available from the Microcks Hub can no longer be compatible with existing versions of Microcks and the new one that would be released (maybe in `1.9.0`).
We have to carefully think about the way we propagate this change to avoid this kind of weird problems...

**Comment by lbroudoux** [comment]
Thinking out loud: I also considered the differences it brings with how other APIs are managed...
Nothing prevents REST or GraphQL APIs from having the same name, even if provided in different components. However, having a unique name for every API is a best practice. Sure, we don't have any namespace/package structure out there to allow defining a bounded context but..

**Comment by lbroudoux** [comment]
It should now be available in the `quay.io/microcks/microcks:nightly` container image. Thanks for your feedback!

**Comment by guyguy333** [comment]
> Thinking out loud: I also considered the differences it brings with how other APIs are managed... Nothing prevents REST or GraphQL APIs from having the same name, even if provided in different components. However, having a unique name for every API is a best practice. Sure, we don't have any namespace/package structure out there to allow defining a bounded context but..

I think you already have "API type" in Services so I guess an "API type" filter could be useful in that case :)

In our case we also proxy our gRPC API to REST using : https://github.com/grpc-ecosystem/grpc-gateway

In that case, name is could be similar. So filtering on API type could be good enough :)
