### ISSUE TITLE
Enhance trouble shooting openapi model

### ISSUE THREAD

**Issue by eldaduzman** [microcks/microcks#1080]
### Reason/Context

I'm trying to import OPENAPI spec into microcks and I never get the mocks section, probably something is missing or misconfigured in the openapi spec.

The trouble shooting is impossible at this point since there's no reasoning as to why there's no mocking section.

Adding reasoning would make this possible, and will create a single standard across all development groups

### Description

When the mocks section does not appear on the service page (image), there will be a clear message for what is missing from the open api spec and a hint to what should be fixed.

![image](https://github.com/microcks/microcks/assets/55621402/a5fca1a8-347b-41da-912e-61c49c79a9b6)

**Comment by lbroudoux** [comment]
Hi @eldaduzman 

Thanks for trying out Microcks! Linting or detecting incomplete OpenAPI spec that produces no mocks is actually a complex topic we still need to tackle... We want to address this in the future, possibly via our CLI, that is currently being refactored.

In the meantime, I recommend looking at our [101 Guide](https://microcks.io/documentation/guides/openapi-101/) to familiarize yourself with the most common constructions. Also, do not hesitate to ask here or on our [Discord server](https://microcks.io/discord-invite) for some help by providing some small reproducers.

**Comment by eldaduzman** [comment]
Hi @lbroudoux and thank you for the response!

Yes, I agree that creating a whole "linter" is untrivial and might take a lot of efforts.
But I don't think such linter is needed, a "high level" comment like "This endpoint is missing example data" should be enough for most cases.

Another thing that might be helpful is examples of source code that generates OPENAPI spec according to the conventions.

**Comment by lbroudoux** [comment]
Hi @eldaduzman,

Though we didn't work on this task here in this repo, we tackled this topic by creating linting rulesets for tools like [Spectral](https://docs.stoplight.io/docs/spectral) or [Vacuum](https://quobix.com/vacuum). Please check our [microcks-spectral-ruleset](https://github.com/microcks/microcks-spectral-ruleset) repository to see how we propose to ease the pain on this topic.

Feedbacks are more than welcomed!
