### ISSUE TITLE
Cors not working 

### ISSUE THREAD

**Issue by Apoorva64** [microcks/microcks#1082]
### Describe the bug

see https://github.com/microcks/microcks-quarkus/issues/22
When calling a mock from the browser we get a CORS error as non of the CORS headers are present.

### Expected behavior
Dynamically generated CORS headers should be returned by Microcks

### Actual behavior
No CORS headers are being returned by Microcks

### How to Reproduce?
1. Launch nightly version of microcks
2. import a REST mock
3. call the mock in the browser console using "fetch" on https://microcks.io
4. see the cors error in network tab

### Microcks version or git rev

nightly

### Install method (`docker-compose`, `helm chart`, `operator`, `docker-desktop extension`,...)

docker-compose

**Comment by Apoorva64** [comment]
@lbroudoux 
We are handling the CORS in "WebConfiguration.java" but at the same time Spring Security is handling CORS. By disabling CORS handling in Spring Security it works again.

**Comment by lbroudoux** [comment]
Thank you very much for quick resolution and PR! 💪
