### ISSUE TITLE
Logout is not working

### ISSUE THREAD

**Issue by StefanLecho** [microcks/microcks#1086]
### Describe the bug

I'm using Docker Desktop to start microcks and I'm able to upload API definitions with the "Anonymous Admin" user.
When I try to logout to login with the "admin" user mentioned in the Getting Started guide to be able to add tests, nothing happens. 

### Install method (`docker-compose`, `helm chart`, `operator`, `docker-desktop extension`,...)

docker-desktop

**Comment by StefanLecho** [comment]
I do not see the "New Test" button :(

![image](https://github.com/microcks/microcks/assets/131886287/96793889-3079-4556-b2ba-579a7a67c388)

**Comment by StefanLecho** [comment]
When importing the API definition I'm not seeing it, but when I use an Importer I do see the button.

**Comment by lbroudoux** [comment]
Yes, the above description is expected.

What you are doing above is creating a "Direct API". See https://microcks.io/documentation/using/dynamic/
Those are loosely contractualized API that can be used to help the ideation process or to build a "quick-and-dirty" API. As it has a lightweight and simple contract, it makes actually no sense to test them. So there's no test available.

However, when you importing a full API contract, we got enough useful information to realize real tests to the Test button becomes available.

**Comment by lbroudoux** [comment]
I think we have to re-work the UI a bit so that when executed without authentication, the `logout` button (and even perhaps the user name) should be hidden to avoid confusion...

cc @hguerrero What do you think?
