### ISSUE TITLE
Add a test coverage indicator in the UI

### ISSUE THREAD

**Issue by nmasse-itix** [microcks/microcks#109]
The use case would be to know how many methods (or percentage) do / do not have a test associated. 

Maybe a widget in the Service list or in the details of a service ?

**Comment by lbroudoux** [comment]
Having something purely related to test coverage may be hard as the `test` notion may vary a lot according the strategy (`runner` type) used for actually testing an API.

What you could have easily and that makes (imho) more sense for the API provider is a sample coverage indicator. I mean the number of operations into API or Service definition that actually has samples defined. Eg. 75% means "3 operations on 4 have samples defined and can be tested whatever is the test strategy".

What do you think @nmasse-itix ?

**Comment by nmasse-itix** [comment]
Good point. Seems legit ! 👍

**Comment by lbroudoux** [comment]
I think this is now done with https://microcks.io/blog/microcks-1.6.0-release/#governance-with-test-conformance-metrics-and-risk-evaluation
