### ISSUE TITLE
Let the user define metadata when importing a service

### ISSUE THREAD

**Issue by nmasse-itix** [microcks/microcks#110]
The use case is to know who to contact when discovering a service in Microcks.

Metadata could be something as simple as the username that imported the service or a Key/Value list ?

**Comment by lbroudoux** [comment]
Actually, this is already planned through the usage of Metadata domain object. See https://github.com/microcks/microcks/blob/master/src/main/java/io/github/microcks/domain/Service.java#L38 ;-)

**Comment by lbroudoux** [comment]
This is now available into the `0.9.0` branch or using the `nightly` tag of container image.

Labels are attached to a Service object like shown below:

<img width="534" alt="Capture d’écran 2020-02-17 à 07 32 29" src="https://user-images.githubusercontent.com/1538635/74629137-d1146200-5157-11ea-88fa-18dfb4826a8f.png">

User with `manager` or `admin` roles are able to edit labels using simple modal form:

<img width="615" alt="Capture d’écran 2020-02-17 à 07 32 09" src="https://user-images.githubusercontent.com/1538635/74629169-e1c4d800-5157-11ea-9617-45032242e1ca.png">
