### ISSUE TITLE
Add proxy support for the rest controller

### ISSUE THREAD

**Issue by Afanas10101111** [microcks/microcks#1100]
### Reason/Context

Sometimes it may be useful to forward Microcks' client to real endpoint, so we can implement some logic when we need mock and when a real call. With such feature we don't have to change the url on the client's side if we want both (mock or real) behaviors.

### Description

To do this, we can add Spring proxy support and use some header to say that we want proxy behavior
```
      responses:
        "200":
          headers:
            x-microcks-proxy-to:
              schema:
                type: string
              examples:
                proxy:
                  value: 'http://realhost:8080/some-service/v1/real-pastry'
```

### Implementation ideas

<a href="https://github.com/microcks/microcks/pull/1101">Idea</a>

**Comment by lbroudoux** [comment]
Hello. We had some discussions in the past about this feature, but we weren't sure how it fit our target use cases... You give some details above but I'd like to learn more ;-)
Also, on the implementation side, we were thinking about something lighter than this. We try to avoid new dependency when possible ... I'll have a look at this.

**Comment by lbroudoux** [comment]
For the implementation, I found this article a while ago (https://blogs.ashrithgn.com/writing-a-reverse-proxy-service-in-spring-boot/) and I was thinking if it couldn't be a good starting point ... It seems easy, lightweight and would avoid pulling out new dependencies. What do you think?

**Comment by Afanas10101111** [comment]
I've <a href="https://github.com/microcks/microcks/pull/1101/commits/0a2342ab56c05fc670fbf19ce6ff5b0c8f09f4f0">tried</a> this approach and it works just fine. I'll test it a bit more next week. But it's still demo :) Integration into the dispatching mechanism looks more interesting.

**Comment by Afanas10101111** [comment]
> I wonder if we could expand this to their protocol than rest? At least Soap and maybe GraphQL...

I think it's worth at least trying :) If we can make an elegant implementation with the dispatching mechanism, I hope that expanding to other protocols will be a matter of technique.

> Got another question: are you using Microcks at your company? Is that an enhancement suggestion coming from your real-lige experience?

Yes and yes :) Features of Microcks look very interesting, and now I'm working on integrating it into the development process. So all my issues are inspired by integration or users problems.

**Comment by lbroudoux** [comment]
Have you ever considered taking the time to chat with us and joining our adopters list?? 😉

**Comment by Afanas10101111** [comment]
I think it's possible, but there are also several stop factors for acting on behalf of a company at this stage. If you have some kind of communication channel for such discussions, we can disscuss this in more detail.
