### ISSUE TITLE
Reduce the amount of tokens in AI prompt for API Rest example generation whit openAI

### ISSUE THREAD

**Issue by LG-Lopez** [microcks/microcks#1103]
## Reason/Context

When the API specification has a large number of operations, the prompt sent to openAI may cause an error by exceeding the number of tokens supported by the model selected for generating the example.

## Description

I think the prompt to create the example doesn't need the full specification; instead, use only the specification for the operation to create examples.

## Implementation ideas

Extend the functionality of methods such as removeExamplesInNode and removeExamplesFromOpenAPISpec (AICopilotHelper.java) to resolve schema references and return only the JsonNode with the specification of the operation for creating the prompt

**Comment by lbroudoux** [comment]
This is a brilliant idea! 👍
