### ISSUE TITLE
Example installation not working above V1.7.1

### ISSUE THREAD

**Issue by Backdraft2100** [microcks/microcks#1113]
### Describe the bug

When following the instruction on https://microcks.io/documentation/getting-started/ the resulting application is not functional.
The application starts but after passing the login prompt a white screen is displayed.

Looking at the browser console an error is displayed.
**error: "Internal Server Error"
path: "/api/features/config"
message: "Http failure response for http://localhost:8080/api/features/config: 500 OK"**

Updating the docker-compose with quay.io/microcks/microcks:**1.7.1** will fix the issue.

### Expected behavior

Following https://microcks.io/documentation/getting-started should result in working application.

### Actual behavior

The application starts but after passing the login prompt a white screen is displayed.

### How to Reproduce?

Use docker environment running behind a firewall and has no network access.
Following https://microcks.io/documentation/getting-started instruction

**Comment by lbroudoux** [comment]
Hello,

Thanks for trying out Microcks. I've re-tried the getting started page from scratch and could not reproduce your issue. The container images being pulled are from the `1.8.1` version. I can't see any 500 errors in the browser console though.

Would you mind please re-trying and giving details when encountering the error by checking logs with `docker logs microcks`? Thanks a lot!

**Comment by lbroudoux** [comment]
It looks like your microcks container cannot reach the keycloak container...
Can you check that you have both values in `docker-compose.yaml`:
```yaml
      - KEYCLOAK_URL=http://keycloak:8080
      - KEYCLOAK_PUBLIC_URL=http://localhost:18080
```
and that the Keycloak container is actually called `keycloak`?
You can also try to ssh into the microcks container and see if you can curl the `keycloak` one...

**Comment by lbroudoux** [comment]
Thank you very much for the feedback and docker-compose reference. Do you think that some of your changes/adaptations should be integrated as default within our file?
