### ISSUE TITLE
Support AsyncAPI v3 examples without names

### ISSUE THREAD

**Issue by lbroudoux** [microcks/microcks#1115]
### Reason/Context

As of today, a `name` attribute is mandatory on AsyncAPI v3 examples so that Microcks can name mock messages attached to an operation. However, the `name` attribute is not mandatory within AsyncAPI v3 schema. 

### Description

It could be nice to have a default behaviour that generates names with simple counter. eg. something like `Example 1`, `Example 2`, etc... See this [Discord thread](https://discord.com/channels/1162356525969449100/1213621011858067527/1214626683114487859)

### Implementation ideas

Generating standard names like `Example 1`, `Example 2`, etc... is possible but make us lose tracking information or the origin message (operation may now mix messages coming from different channels). It would be better to have something like `turnOn-1`, `turnOff-1`, etc... with the name of the message included.

**Comment by savvyintegrations** [comment]
You rock! That was fast!
