### ISSUE TITLE
NullPointerException on AsyncAPI v3 import: Cannot invoke "String.indexOf(String)" because "messageName" is null

### ISSUE THREAD

**Issue by lbroudoux** [microcks/microcks#1119]
### Describe the bug

Following the #1115 issue, there's a case where we can raise a `NullPointerException` if a channel message `$ref` is absent of empty. See the [Discord thread here](https://discord.com/channels/1162356525969449100/1216897886101573692/1216897886101573692).

### Expected behavior

No runtime exception should be thrown. If invalid, the example should be ignored but the whole import process should not fail.

### Actual behavior

The import process fails with a cryptic error, returning an HTTP 500 response code.

### Microcks version or git rev

nightly - 1.9.x

**Comment by savvyintegrations** [comment]
This error occurs even with a valid AsyncAPI v3 spec, e.g., this file (.txt used to allow upload):
[events.asyncapi.yml.txt](https://github.com/microcks/microcks/files/14575866/events.asyncapi.yml.txt)

This validates in https://studio.asyncapi.com/, and the `$ref`s look good to me.

**Comment by lbroudoux** [comment]
Oh damned! I got it! It's a consequence of #1115, and it is now supposed that channel messages are defined using `$ref`. However they are defined inline within your example and extracting from the message name fails because of no `$ref`!!

I'm fixing it ASAP as the fix I've produced this morning is bad.

**Comment by lbroudoux** [comment]
Now fixed! The importers supports both references and inline definition of channel messages.
