### ISSUE TITLE
Display in the UI the identity of the user that launched a test

### ISSUE THREAD

**Issue by nmasse-itix** [microcks/microcks#112]
Currently, in the test run list there is no mention of who launched that test. 
To foster collaboration, it might be useful to show the identity of the user that launched the test. 
That way, if the test is unsuccessful or the tests need further improvements, we can know who to contact.

**Comment by lbroudoux** [comment]
Hey! Why not, it may be a good idea. However, in case of automated tests launched by a CI/CD pipeline, most of the referenced users will be service accounts used by Jenkins or other CI engine ...

A good practice - to reference in documentation - may be to encourage admins to create different service accounts for different engines / projects / domains. What do you think?
