### ISSUE TITLE
Error Publishing API via CLI

### ISSUE THREAD

**Issue by aymanhouadria** [microcks/microcks#1127]
### Describe the bug

We have three instances of Microcks: dev, pre, and prod. For some reason, publishing APIs via CLI in our dev instance no longer works. In versions 0.5.3 and 0.5.4, no error appears, but it doesn't discover any service. An empty string appears instead: ![image](https://github.com/microcks/microcks/assets/61763166/1e793846-7788-46b1-bece-d72f15b074ef). In version 0.5.5, it throws the following error: 
![image](https://github.com/microcks/microcks/assets/61763166/8d9d00f5-dfba-4957-8df6-606761479fd8)
 We have verified that the client id, client secret, and URLs are correct. The file is also in the correct path. Interestingly, it works in the other instances.

**Comment by aymanhouadria** [comment]
Thank you for the response. Yes, we tried with version 0.5.5 and indeed we are getting an error, both locally and in CI. What we don't understand is that we haven't modified anything in our dev instance of Microcks, yet it has stopped publishing via CLI. The error does not specify the reason, and the client ID, URL, and client secret are correct. The OpenAPI is also in the correct path. I'm asking to see if a similar problem has been reported or if you are aware of an issue like this because we can't think of where to look to understand the reason for the error. Thank you very much.

**Comment by lbroudoux** [comment]
You can try to put the `--verbose=true` flag to get dumps of the requests/responses of API calls.

**Comment by aymanhouadria** [comment]
Thank you again for the response. We have already used the verbose flag, and it throws a 403 with an error="insufficient_scope". The issue is that we haven't changed anything in our client's configuration for months, and upon checking, it is identical to our other instances where the CLI does work. The privileges are the same as before, so honestly, we are running out of ideas on where to look.
![image](https://github.com/microcks/microcks/assets/61763166/06980ae2-fbd8-4806-b3cd-e55562fd8bc9)
![image](https://github.com/microcks/microcks/assets/61763166/3042c890-66a7-417a-9dea-efcf76d708a6)
![image](https://github.com/microcks/microcks/assets/61763166/c95c0ba9-05b3-41cb-b331-25a27237bf7a)

The configuration shown in the screenshots is identical for all our instances, but only the development environment is throwing an error. Do you have any suggestions on where I could look to find the problem?

**Comment by lbroudoux** [comment]
We've fixed a permission issue in latest versions of Microcks so it could effectively make your import no longer work... Please check that the service account used by the CLI holds the `manager` role of microcks resource. Please check https://microcks.io/documentation/automating/service-account/ to verify on your side.

**Comment by aymanhouadria** [comment]
Thank you very much. Last attempt. We have checked and indeed, as before, the assigned roles are correct and we have not updated our Microcks for the moment. I have verified that everything is correct as indicated in the documentation you have provided, and it is. If, for some reason, you think of where the problem might be, we would appreciate the help. Best regards

![image](https://github.com/microcks/microcks/assets/61763166/fbf811a8-3750-4ca1-a61c-b8f2265f1327)
![image](https://github.com/microcks/microcks/assets/61763166/3918f0dd-a9f4-4cdc-9893-1176c85ee9a4)

**Comment by lbroudoux** [comment]
In the above screenshot, I can only see the `default-roles-microcks-dev` being assigned to the service account, and these default roles only embed the `user` role. I think you should explicitly add the `manager` role attached to the `microcks-app` resource to get it working.
