### ISSUE TITLE
Support for object query parameters

### ISSUE THREAD

**Issue by Snorkell** [microcks/microcks#1143]
### Reason/Context

Hello, as always thanks for this awesome project.

I was playing around with the OpenAPI specs when I tried to implement a very specific feature fo the spec -> Object in query parametes

https://swagger.io/docs/specification/serialization/

So by default the specs says that we can use `type: object` in the schema of a query param but it seems that the OpenAPIImporter class is not aware of this feature.

I know it's very specific but it's a default feature of the spec so I thought it could be nice to be able to test and mocks api with this feature in it. 

### Description

So the specs (with the default config) says that any non nested object defined as query parameter will be serialized as the following example
```yaml
User:
  name: bob
  age: 45
```
to something like this un an url
`http://myawesomeAPI/someendpoint?name=bob&age=45`

### Implementation ideas

The idea would be in the case of having a object as query params the dispatch rule won't be tied to the param name but the object fields name as the specs describe.

With that the importer should parse the example as independant parameter and not as a whole json object as it's done right now

A pull request will follow soon with some tests

Agains, thanks for all of this 😄

**Comment by Snorkell** [comment]
Not really, in fact I just added the support for the default configuration for query parameters which is `style: form` and `explode: true`, in the case of the issue 154 the style is set to `style: deepObject`, but I don't really think it should be difficult to implement.
You just need to check what are the style and the explode value when you create the url and choose a serialization strategy based on that 

![image](https://github.com/microcks/microcks/assets/30845775/68b752f5-55d6-42e1-ad26-83585265c65d)

**Comment by lbroudoux** [comment]
Thanks for the above explanation! Makes things clearer.
