### ISSUE TITLE
MIgrate tests to Junit5

### ISSUE THREAD

**Issue by mcruzdev** [microcks/microcks#1151]
### Reason/Context

Working on test issue, I noted that the project is using JUnit4 and JUnit5.

### Description

The idea is to standardize the JUnit version for all application tests.

### Implementation ideas

To use all tests with unique JUnit version

**Comment by lbroudoux** [comment]
Good idea! Project was started JUnit4 a loonng time ago but can definitely switch to JUnit 5.
Issue can be split into more focused ones attached to this main one marked as an `Epic`

**Comment by lbroudoux** [comment]
Now done. Thanks to @gbloquel for awesome contrib!

**Comment by lbroudoux** [comment]
Reopening this one as we still encountering issues in https://github.com/microcks/microcks/pull/1210.
Maven Surefire plugin version used should be more deterministic.
