### ISSUE TITLE
Migrate AsyncAPI samples to AsyncAPI 3.0.0

### ISSUE THREAD

**Issue by lbroudoux** [microcks/microcks#1152]
As AsyncAPI v3.0.0 is going mainstream, we should migrate our samples from `/samples` folder to AsyncAPI v3.

**Comment by lbroudoux** [comment]
It would be great! Thanks!

**Comment by inFocus7** [comment]
If this hasn't been picked up - or if some time passes without updates - could I be next in line to pick this up? 👀

**Comment by inFocus7** [comment]
Awesome! I'll have something up soon (tomorrow latest). I have branch in my fork that I'll just need to convert to a pull request so it can be reviewed 👍

**Comment by lbroudoux** [comment]
Finally, I did check that mocks and tests where still working correctly ;-)
