### ISSUE TITLE
Add static link to the latest OpenAPI spec

### ISSUE THREAD

**Issue by soGit** [microcks/microcks#1157]
### Reason/Context

It would be convenient to have a permanent link to the latest microcks's OpenAPI spec

### Description

No braking changes

### Implementation ideas

We can duplicate https://raw.githubusercontent.com/microcks/microcks/master/api/microcks-openapi-v1.9.yaml
under https://raw.githubusercontent.com/microcks/microcks/master/api/microcks-openapi.yaml

**Comment by yada** [comment]
Hello @soGit,
I appreciate your suggestion, but implementing this workaround might not address other tasks and could disrupt our current upgrade process for each new release. While updating the website is indeed essential, it is relatively simpler compared to altering the overall Microcks build process. Therefore, I will decline the pull request on this particular point. However, we will integrate this task into the build process. Thank you for your understanding and support.
Best regards,
Yacine
