### ISSUE TITLE
Problem SOAP_UI mode test runner

### ISSUE THREAD

**Issue by crismarfr** [microcks/microcks#116]
Hi, I create mock API REST with SOAPUI editor and i configure assertions control in the test step. When i import the project in microcks, i can't select SOAP_UI test runner. I can only select HTTP, POSTMAN or OPEN_API_SCHEMA.
I'm interesting in SOAP_UI mode for testing with assertion validation.

When i import your REST API example (https://raw.githubusercontent.com/microcks/microcks/master/samples/HelloAPI-soapui-project.xml), i have the same issue. But with your SOAP API example (https://raw.githubusercontent.com/microcks/microcks/master/samples/HelloService-soapui-project.xml), i can select SOAP_UI test runner.

Can you help me ? 
Thanks
Cordially

**Comment by crismarfr** [comment]
Hi, in the code source /src/main/webapp/src/app/pages/tests/create/test-create.page.html, the list box of type test runner is :

<select id="runnerType" name="runnerType" class="form-control" [(ngModel)]="runnerType" (ngModelChange)="checkForm()">
            <option value="HTTP">HTTP</option>
            <option value="SOAP_HTTP" *ngIf="service.type === 'SOAP_HTTP'">SOAP</option>
            <option value="SOAP_UI" *ngIf="service.type === 'SOAP_HTTP'">SOAP UI</option>
            <option value="POSTMAN" *ngIf="service.type === 'REST'">POSTMAN</option>
            <option value="OPEN_API_SCHEMA" *ngIf="service.type === 'REST'">OPEN API SCHEMA</option>
          </select>

The service type SOAP_UI is reserved for SOAP HTTP et not REST while SOAP-UI type is authorized for REST HTTP in the documentation (http://microcks.github.io/using/tests/).

It's a bug ?

Cordiallly

**Comment by lbroudoux** [comment]
Hi @crismarfr !

Thanks for raising this issue. This is actually a bug and should be fixed into the UI. `SOAP_UI` tests and assertions may also be run and checked for REST services. I'll try update it soon.

Cheers,

**Comment by lbroudoux** [comment]
Fixed.
