### ISSUE TITLE
Migrate to angular v9

### ISSUE THREAD

**Issue by soGit** [microcks/microcks#1171]
### Reason/Context

To unlock project for migrations to the newest version of angular we need to eliminate patternfly-ng dependency (Library is deprecated and no longer supported, [my MR was rejected](https://github.com/patternfly/patternfly-ng/pull/477) and it is not possible to contribute into project without forking it).

### Description

Bellow you can find list of modules from patternfly-ng:

import { AboutModalModule } from 'patternfly-ng/modal';
import { CardModule } from 'patternfly-ng/card';
import { DonutChartModule, SparklineChartModule } from 'patternfly-ng/chart';
import { ListModule } from 'patternfly-ng/list';
import { NotificationService, ToastNotificationListModule } from 'patternfly-ng/notification';
import { PaginationModule } from 'patternfly-ng/pagination';
import { ToolbarModule } from 'patternfly-ng/toolbar';
import { WizardModule } from 'patternfly-ng/wizard';

### Implementation ideas

We can replace them with (sorted from easy to hard):
- [angular material](https://material.angular.io/)
- use framework agnostic native [web components](https://developer.mozilla.org/en-US/docs/Web/API/Web_components) (something like https://github.com/shoelace-style/shoelace, seems that they are working on new set of components https://www.kickstarter.com/projects/fontawesome/web-awesome maybe microcks can be included into preview / list of early adopters.
Already tried to use shoelace for microcks, it is easy to setup shoelace as CDN resources, but needed to setup custom bundler to use as local resources (current version of angular does not bundle shoelace)  
- create home build components
- fork [patternfly-ng](https://github.com/patternfly/patternfly-ng) to upgrade it

**Comment by lbroudoux** [comment]
Hey @soGit! Thanks for opening the discussion on this topic!

Obviously, the situation is not brilliant, and we need to do something regarding the microcks UI to ensure the long-term viability of the project. As you noticed, our version of Patternfly (v3) is no longer supported, and Patternfly's next version is a totally new beast now supporting React only...

The choices of UI components library as well as frontend framework are hard ones these days... I did a couple of research these last weeks and came to the conclusion that having home-build components would be a better choice. However, I am not sure we should do it now based on our current Angular stack (even if we upgrade it to v9 or latest version of Angular.

As a big advocate for developer productivity and developer joy, I am particularly seduced by Svelte and SvelteKit these days. Also, I had a look at https://ui.shadcn.com/ and particularly like the approach. For those reason, we decided to experiment with this stack on https://github.com/microcks/hub.microcks.io. where we just created a `new-ux` branch a few days ago. As `https://hub.microcks.io` is pretty simple, I think it's a great playground to experiment with this stack and see what it means to move from old Angular and component libraries to his.

I'd like to explore this and see if it's a viable target for Microcks, as we're not at immediate risk with the current stack. But agreed that this is something we need to anticipate and work on. 

What do you think? Do you have any experience with Svelete and/or Shadcnd + Tailwind? Feel free to ask for more and join the initiative if you'd like to.

**Comment by soGit** [comment]
It's a good idea to start with hub, I'm checking it. I tend to think that rewriting everything to Svelte might be time consuming, and does not bring significant benefits. For microcks case, [Astro](https://astro.build/) might be a better choose. So we can upgrade and continue use angular components, and we will able to use other ui frameworks(svelte, react, vue, etc.) along the way.  What do you think?

PS. I have production experience with homebuild components based on angular and react. And did some small projects with shadcnd + tailwind. But only general/theoretical knowledge in Svelte. 
PS. [Astro starlight](https://starlight.astro.build/) potentially can be used for microcks.io as well, if at some point custom ui interactions require and it will be hard to continue with Hugo.

**Comment by lbroudoux** [comment]
Discussion on that topic is opened here: https://github.com/orgs/microcks/discussions/1458
