### ISSUE TITLE
Refine a couple of terms in the Authentication Secrets UI

### ISSUE THREAD

**Issue by savvyintegrations** [microcks/microcks#1177]
### Describe the bug

This is not really a bug, just a suggested refinement of terms.

![Screenshot 2024-05-23 at 14 39 46](https://github.com/microcks/microcks/assets/7103368/1cd2b9bd-5c8c-4e20-a51a-7be9adc5fdaf)

Per https://developer.mozilla.org/en-US/docs/Web/HTTP/Authentication#authentication_schemes, "Token Authentication" would be better as "Bearer Authentication", and then in the field's description, below, say something like "The header to use for sending token. If not specified, assume it is the Authorization header set to "Bearer: { YOUR_TOKEN }". 

IOW, "Authorization", not "Authentication", and a little clearer explanation.

**Comment by lbroudoux** [comment]
Hi @savvyintegrations,

Thanks for opening this issue.

I agree that `The header to use for sending token. If not specified, assume it is the Authorization header set to "Bearer: { YOUR_TOKEN }` is be more accurate. 👍 for this change.

However, as the explanation suggests, the *Token Header* - if provided replaces - `Authorization: Bearer {}` and then is more general-purpose than `Authorization` only. Typically, people use GitLab personal/project/group access tokens with a token header being `PRIVATE-TOKEN` and that serves the purpose of authentication (see https://docs.gitlab.com/ee/api/rest/index.html#personalprojectgroup-access-tokens). 

So I would say that **Token Authentication** sounds more generic and maybe we could stick with this? What do you think?
