### ISSUE TITLE
When Keycloak user has no "first Name" or "last Name". Microcks doesn't show a user.

### ISSUE THREAD

**Issue by Apoorva64** [microcks/microcks#1180]
### Describe the bug

![image](https://github.com/microcks/microcks/assets/60534691/3291f727-346a-4ea9-8eb2-ab95d7341345)

### Expected behavior

It should show the "prefered_username" claim from Keycloak when First Name and Last Name are not available

### Actual behavior

Shows an empty string

### How to Reproduce?

1. Create a user with only a username
2. Login into the Microcks UI

### Microcks version or git rev

nightly

### Install method (`docker-compose`, `helm chart`, `operator`, `docker-desktop extension`,...)

docker-compose

**Comment by lbroudoux** [comment]
It may be related to the upgrade to Keycloak 24.0.4. We also had to update Keycloak-js but stick to 22.0.5 version to have compatibility with both 22 (previous integrated version) and 24 (new one)

**Comment by Apoorva64** [comment]
On Microcks:1.9.1 and Keyclock:22.0.2, using the docker-compose install. 
When we login as Admin(a user that does not specify the First Name or Last Name).
On the top right corner we see
![image](https://github.com/microcks/microcks/assets/60534691/ce5e19cb-7adf-4534-8bf6-b6f6119062c7)
But we should have an indicator showing that we are logged in like this for example.
![image](https://github.com/microcks/microcks/assets/60534691/aa6124ab-71b0-4cfa-a3bd-94d1ba598b47)

Fixed [here](https://github.com/microcks/microcks/pull/1181)

**Comment by lbroudoux** [comment]
Thank you mate! Checking the PR asap.

**Comment by lbroudoux** [comment]
Fixed with #1181. Thanks @Apoorva64 🎉
