### ISSUE TITLE
Add Mandatory Authentication for Mock Endpoints and API Specifications

### ISSUE THREAD

**Issue by yuritur** [microcks/microcks#1182]
### Reason/Context

Currently, when deploying Microcks, the UI access is protected using Keycloak. However, access to the .json API specifications and mock endpoint calls is available to anyone without authentication.
<img width="1281" alt="image" src="https://github.com/microcks/microcks/assets/25751219/04a9ecf8-2a31-4ba5-abb1-988109112104">

**Note**
I am not sure if this feature already exists, and I apologize if I missed it in the documentation.

### Description

I'd like to have a native way to enforce mandatory authentication for mock endpoints.
This change will enhance security by ensuring that only authorized users can access the mock endpoints and API specifications.
The motivation behind this request is to prevent unauthorized access to the mocked APIs, which could lead to potential misuse or data exposure.

### Implementation ideas

Integrate with Keycloak to check the authorization token for each request to mock endpoints and .json specifications.

**Comment by lbroudoux** [comment]
Hey @yuritur,

You're right: access to mock endpoints is not secure as of today, and this was on purpose. As the mocked API may have a totally different security scheme than the one used by Microcks, we didn't tackle this topic and didn't want to overlap/interfere at first.

That said I understand the need if you fear that providing mocks may lead to over-consumption of resources or undesired mock data exposure. IIRC we started such a discussion at the end of #1095 on how to enforce secure access to those endpoints...

I think we need to further discuss the different scenarios as well as the configuration options we may provide => OAuth vs Basic vs API keys? If reusing Keycloak, should we reuse the same realm? Allow you to configure another one? Your thoughts on that are welcome!

cc @Afanas10101111
