### ISSUE TITLE
Separate URLS for keycloak redirection and keycloak internal validation

### ISSUE THREAD

**Issue by sercastiGL** [microcks/microcks#119]
This is related to https://github.com/microcks/microcks/issues/14

a) The config entries for KeyCloak URL should be separate, one for the login redirection, and a different other variable for internal communication, just like these guys did:
https://github.com/hobbit-project/platform/issues/18#issuecomment-341440232
      - KEYCLOAK_AUTH_URL=http://www.mypublicinternetpage.com/auth
      - KEYCLOAK_DIRECT_URL=http://myinternatIP:8080/auth

The solution to #14 will not work as my web instance will not run on localhost, as this a server/public instance, so I need, a public URL for login redirection, and a private URL for internal communication. 

b) https://github.com/microcks/microcks/issues/14 mentions "Keycloak protection is disabled", but there is no example on how to do that. There should be an additional       
        - CHECK_REALM_URL=false

**Comment by sercastiGL** [comment]
Steps to reproduce on a LInux VM (Red Hat)

1. `uname -a`
Linux fivedevserver.synapse.com GNU/Linux
2. `hostname -f`
fivedevserver.synapse.com
3. `git clone https://github.com/microcks/microcks.git`
4. `cd microcks/install/docker-compose`
4. `cp keycloak-realm/microcks-realm-sample.json keycloak-realm/microcks-realm-sample.json.bak`
5. `yum install jq`
6. `jq '.applications |= map(if .name == "microcks-app-js" then .redirectUris = [ "http://fivedevserver.synapse.com:8080/*" ] else . end) | .sslRequired |= "none"' keycloak-realm/microcks-realm-sample.json.bak > keycloak-realm/microcks-realm-sample.json`
7. `perl -i.bak -pe 's|KEYCLOAK_URL=http://localhost:8180/auth|KEYCLOAK_URL=http://fivedevserver.synapse.com:8180/auth|' microcks.yml`
8. `perl -i.bak -pe 's|keycloak.ssl-required=external|keycloak.ssl-required=none|' config/application.properties`
9. `sudo docker-compose -f microcks.yml up -d`

**Comment by lbroudoux** [comment]
Reopen this issue to finalize installation procedure changes
