### ISSUE TITLE
Add support for external url using $ref

### ISSUE THREAD

**Issue by Snorkell** [microcks/microcks#1190]
### Reason/Context

Hi, so the idea is to allow Microcks to resolve Url based reference in open API Schema

Right now as I saw on the source code, the `$ref` keyword only allow to resolve `Local reference` (ex: `#/definition/myElement`) or `Remote reference´ like those ones
![image](https://github.com/microcks/microcks/assets/30845775/0539aeb2-dcf8-4480-a1e0-8b34865c9f77)

### Description

What I would like to have is to be able to use `URL Reference` as specified in the specs 
![image](https://github.com/microcks/microcks/assets/30845775/23d0402c-8a44-4025-8e0f-5664a27903dd)

### Implementation ideas

In the `AbstractJsonRepositoryImporter` class at the line `289` in the method
```java
   private JsonNode getNodeForExternalRef(String externalReference) {
      String path = externalReference;

      // We may have a Json pointer to a specific place in external reference.
      String pointerInFile = null;
      if (externalReference.indexOf("#/") != -1) {
         path = externalReference.substring(0, externalReference.indexOf("#/"));
         pointerInFile = externalReference.substring(externalReference.indexOf("#/"));
      }

      for (Resource resource : externalResources) {
         // Path direct equality is for absolute ref ("http://raw.githubusercontent.com/...")
         // Path equality with resource name if for relative refs that have been re-normalized ("Service name+Service version+...))
         if (path.equals(resource.getPath())
               || path.equals(URLEncoder.encode(resource.getName(), StandardCharsets.UTF_8))) {
            JsonNode resourceNode = externalResourcesContent.computeIfAbsent(resource, k -> {
               try {
                  return ObjectMapperFactory.getYamlObjectMapper().readTree(resource.getContent());
               } catch (JsonProcessingException e) {
                  throw new JsonRepositoryParsingException("Get a JSON processing exception on " + externalReference,
                        e);
               }
            });
            if (pointerInFile != null) {
               return resourceNode.at(pointerInFile.substring(1));
            }
            return resourceNode;
         }
      }
      log.warn("Found no resource for reference {}", externalReference);
      return null;
   }
```
Maybe add a confition if the ref starts with `//` or `http://` or `https://` then we do a small http call to the specified url and maybe do some caching then return the result as a JsonNode. 

And again thanks for all of this 😁

**Comment by Snorkell** [comment]
An alternative could be just to create a new `ReferenceResolver` with an empty string as baseRepositoryUrl `null` as repositorySecret and `true` as disableSSLValidation if the ReferenceResolver is null at the null guard of the method `initializeReferencedResources` in the class `AbstractJsonRepositoryImporter` this way the external reference can be resolved.

Because I found out that importing OpenAPI specs through the `/artifacts/upload` endpoint always set the `ReferenceResolver` as null causing testContainers upload always failing when using url based `$ref`

**Comment by lbroudoux** [comment]
Hi @Snorkell!

We don't support `//` at the moment, but remote HTTP calls on absolute references (`http://` or `https://`) are actually performed before in the external resources resolution process.

The `private void resolveExternalReferences(Service service, Map<String, Resource> referenceResources, String baseRepositoryUrl, String baseContext, JsonNode resourceSpecification)` method is called before and takes care of downloading the content for both relative and absolute references IIRC.

Yes, it's true that import via upload cannot allow us to resolve references as we don't have access to a base repository url. As of today, we must go through the importer creation when a spec has some $refs.
