### ISSUE TITLE
Add more tests for 1.10.0

### ISSUE THREAD

**Issue by lbroudoux** [microcks/microcks#1193]
This task aims to increase the quality and maintainability of the project, adding more unit and integration tests. This is a board scope issue to receive any commits. Feel free to pick your favorite class in Microcks and submit a PR to help the effort!

**Comment by Harsh4902** [comment]
@lbroudoux do we have any specific branch for test cases or just have to make pull request on master branch?

**Comment by lbroudoux** [comment]
Hey @Harsh4902 
You can use the development branch for that. Currently it's `1.10.x`.

**Comment by Harsh4902** [comment]
@lbroudoux Okay, thank you.

**Comment by lbroudoux** [comment]
Hi @Harsh4902!
Any ETA on this issue? Have you solved the issue regarding #1210?

**Comment by Harsh4902** [comment]
@lbroudoux Sorry, I was a bit busy with midterm evaluation of GSoC so couldn't work on it last week. I have to look into this again.

**Comment by lbroudoux** [comment]
No worries! Just asking. Thanks for the visibility!

**Comment by lbroudoux** [comment]
Now closing this one as the release for `1.10.0` is pretty close! Feel free to open another issue for next contributions 😉 
Thanks again to @Harsh4902 !!
