### ISSUE TITLE
Few issues on service page

### ISSUE THREAD

**Issue by stojsavljevic** [microcks/microcks#120]
Hi,

first of all -thanks for this great project.
I started to play with it just recently so I'm not an experienced user.
I'm facing few issues, I tried searching for reported issues but no luck.

I'll just list it here and, if necessary, I'll open separate ones.
I imported API using https://raw.githubusercontent.com/microcks/api-lifecycle/master/beer-catalog-demo/api-contracts/Beer%20Catalog%20API.postman_collection.json

- First issue I faced is that some tests are always displayed as running, e.g. those with bad root endpoint.
- Further, "Mocks invocations" link in service details page doesn't work for me and I get this error in chrome's console: `ERROR Error: Uncaught (in promise): Error: Cannot match any routes. URL Segment: 'admin/invocations/Beer%20Catalog%20API/0.9'`
- test graph above "View Tests Runs" in service details page leads to Spring Boot error page (no error in application's log)
- when I run some test I get info that `null Test #null has been launched`
- only HTTP test works for me while others fail

I tested `0.7.1` version on my VM (binary is built from source) and latest docker image.

Sorry if I missed something obvious. I tried following instructions on http://microcks.github.io/using/

**Comment by lbroudoux** [comment]
Hi @stojsavljevic , 

thanks for trying out Microcks and sorry for late reply. Most of them are known issues and on my TODO list. I'll keep this issue opened to track their resolutions.

Thanks,

**Comment by lucamaf** [comment]
adding a couple of issues on my side in terms of GUI:

- Details button for Services doesn't work or do anything (not clickable)
- Mocks invocation still results in js error

**Comment by lbroudoux** [comment]
Everything should now being fixed so closing this global issue. Will reopen specific ones if there's still some glitches.
