### ISSUE TITLE
Copy community/GOVERNANCE.md to microcks/GOVERNANCE.md

### ISSUE THREAD

**Issue by yada** [microcks/microcks#1217]
Copy the community/GOVERNANCE.md file and document information to microcks' project (main repo).
See #1214 and #1201

**Comment by yada** [comment]
All good, ready to process

**Comment by lbroudoux** [comment]
Is this really a task that takes place on this repo?

**Comment by yada** [comment]
+1 Desc added
The destination repo is the main repo (this one, so the repo impacted), but yes, it could have been created the other way around: on the community repo with "copy to main". 

Let's copy the file and close it ;)

**Comment by yada** [comment]
✅ https://github.com/microcks/microcks/commit/928a67f4c16b4f3a312129e67063e1ed39a311b1
