### ISSUE TITLE
Summary Table (docs)

### ISSUE THREAD

**Issue by yada** [microcks/microcks#1218]
[Update/Provide some information](https://github.com/cncf/landscape/blob/master/docs/item_summary.md) for the Landscape Summary Table: https://github.com/cncf/landscape/blob/master/landscape.yml

**Comment by yada** [comment]
Waiting for CNCF approval from a maintainer.
See: https://github.com/cncf/landscape/pull/3922

**Comment by lbroudoux** [comment]
New rule: it should be forbidden to create issue with no provided description 😉

**Comment by lbroudoux** [comment]
Why creating this issue on main repo though? It should be created on `community` or `.github` one IMHO.

**Comment by yada** [comment]
> New rule: it should be forbidden to create issue with no provided description 😉
+1 updated

**Comment by yada** [comment]
> Why creating this issue on main repo though? It should be created on `community` or `.github` one IMHO.

Created from the task list from https://github.com/microcks/microcks/issues/1201, which explains why it is on this repo. 
As this is an update on the CNCF repo (external) and related to the project health meta issue, I'm not sure it fits in the community or .github repo 🤔

**Comment by yada** [comment]
BTW update, the [preview](https://landscape.cncf.io/?overlay-data=https%3A%2F%2Fraw.githubusercontent.com%2Fyada%2Flandscape%2Fmaster%2Flandscape.yml&overlay-logos=https%3A%2F%2Fraw.githubusercontent.com%2Fyada%2Flandscape%2Fmaster%2Fhosted_logos&item=app-definition-and-development--application-definition-image-build--microcks) is available.

**Comment by yada** [comment]
PR merged; see: https://github.com/cncf/landscape/pull/3922
It should be online here https://landscape.cncf.io/ soon ✅
