### ISSUE TITLE
POST operations / JSON body content dispatching for REST services

### ISSUE THREAD

**Issue by lbroudoux** [microcks/microcks#123]
For now it is not easily possible to have dispatch rules on POST operations for REST Services ... Neither is it possible to dispatch GET request depending on request body content.

As current common dispatchers in Microcks rely on Path or Query parameters, most of the REST API involving creation of entities (thus without a path parameter) cannot have more than 1 request/response pair.

We think about adding some specific dispatcher that will allow to extract a request body element (through JSONPath for example) and determine a corresponding response. We may introduce many operators (`equals`, `range`, `regexp`, `present`, `missing`, ...) so that we could easily have some logic or cases grouping.

These additional `dispatcherRules` may be extracted from specific extensions into Postman Collection or OAS 3 files. They could be also added "manually" as an extra-step of mock configuration through UI or Microcks API.

Ideas welcomed!

**Comment by lbroudoux** [comment]
First implementation done ;-)

**Comment by sleevezip** [comment]
This is exactly what were looking for, works like a charm. 

There is one question, we would like to check if multiple elements are present in the JSON request body, is that currently possible?

And if so, could you share an example dispatcher rule.

**Comment by lbroudoux** [comment]
Hi @sleevezip ,

thanks for feedback ! Currently, there's only one rule with one expression available. However, I was thinking of having the ability to have an array of dispatcher rules that will be evaluated in sequence. This will allow to compose dispatch rules on different elements of the JSON request.

What do you think ?

**Comment by sleevezip** [comment]
Thanks for the info!

An array of dispatcher rules would be perfect. That would suit our needs. 
We actually tried composing multiple rules in an array, so that would be a natural way.

**Comment by lbroudoux** [comment]
Ok, nice! Will try to gather more feedback on current implementation before considering extension though. Hope it will be in good timing for 0.8.0 release (I'm targeting end of March for now).
