### ISSUE TITLE
Allow validation of application/hal+json

### ISSUE THREAD

**Issue by matthieudupuyepi** [microcks/microcks#1233]
### Reason/Context

We are currently investigating the usage of Microcks within our project, and as such we have tried using it at UT level, to perform a validation test of our implementation against our openAPI specification.
Within our project, all our endpoint are returning response with a Content-Type to `application/hal+json`
Diving into the code, we have realized that only response with a content type to `application/json` are validated (https://github.com/microcks/microcks/blob/master/webapp/src/main/java/io/github/microcks/util/openapi/OpenAPITestRunner.java#L148)

### Description

We would expect to have the possibility to validate other format that are very close to application/json, and don't change the semantic validation of the response, like `application/hal+json` or vendor specific schema like `application/vnd.entity.v1+json`

### Implementation ideas

Review the code on [line](https://github.com/microcks/microcks/blob/master/webapp/src/main/java/io/github/microcks/util/openapi/OpenAPITestRunner.java#L148) so that it does a Content type comparison with an equality on the type, and allow extension of subtype `json`

**Comment by lbroudoux** [comment]
Thank you, @matthieudupuyepi, for opening this one. This is definitely something we can improve.

As it's a long time ago I worked with OpenAPI + HAL, I've got a question regarding the way you describe your HAL structure.
Do you describe your `_links` property using JSON Schema as well or do you expect it to be automatically inferred from the content type information? Is there some stnadard HAL `_links` schema definition to be reused here?

**Comment by matthieudupuyepi** [comment]
> Thank you, @matthieudupuyepi, for opening this one. This is definitely something we can improve.
> 
> As it's a long time ago I worked with OpenAPI + HAL, I've got a question regarding the way you describe your HAL structure. Do you describe your `_links` property using JSON Schema as well or do you expect it to be automatically inferred from the content type information? Is there some stnadard HAL `_links` schema definition to be reused here?

As indicated in #1234, we are indeed defining an internal component that we reuse through our openAPI documentation following this schema to describe a `link`:
```
components:
  schemas:
    link:
      type: object
      properties:
        href:
          type: string
          format: uri
        name:
          type: string
      required:
        - href
```
The response always contains a `_links` and a `_embedded` fields.
The `_embedded` fields contains a description of embedded resources that are directly loading within the response, and depends of the context of the parent.
the `_links` contain 1 to n sub properties that use the `link` component, each of them being a link relevant to the parent response, either `self` or to sub resource.

Hope this help :)

**Comment by lbroudoux** [comment]
Just pushed an update. It should be available for tests in the `quay.io/microcks/microcks:nightly` container image in a few minutes.

**Comment by matthieudupuyepi** [comment]
> Just pushed an update. It should be available for tests in the `quay.io/microcks/microcks:nightly` container image in a few minutes.

I'll test first things tomorrow morning

**Comment by matthieudupuyepi** [comment]
So I did a few more tests this morning regarding the first point above. Here are the result:
- with content-type `application/json` response is validated and missing required field is reported
- with content-type `application/json; charset=UTF-8` response is tentatively validate but unable to find the node in the schema. Error `messagePathPointer does not represent an existing JSON Pointer in OpenAPI specification` is return
- with content-type `application/json;charset=UTF-8` response is tentatively validate but unable to find the node in the schema. Error `messagePathPointer does not represent an existing JSON Pointer in OpenAPI specification` is return
- with content-type `application/hal+json` response is not validate, test is successful even with a missing required field
- with content-type `application/hal+json; charset=UTF-8` response is not validate, test is successful even with a missing required field

I look at the good, and I don't understand why with the charset, the matching you implemented is not working.
Same for the application/hal+json 🫤

**Comment by lbroudoux** [comment]
Thanks for the report. I think we still have an issue as there's a missing fallback in the case response has a charset but no charset information found in the spec. WIll have a look at it.

**Comment by lbroudoux** [comment]
I've completed the implementation and pushed it. It should be available in the `nightly` image in a few minutes.

**Comment by matthieudupuyepi** [comment]
All working fine now!
Thanks for the quick feedback
