### ISSUE TITLE
Content-type response validation discard charset, even when charset provided within the API specification

### ISSUE THREAD

**Issue by matthieudupuyepi** [microcks/microcks#1234]
### Describe the bug

Will performing an openAPI validation using Microcks, with a specification such as this one:
```
openapi: 3.0.1
info:
  title: My API
  version: 0.0.0
paths:
  /api/authentication/consumer/challenges:
    get:
      summary: a field
      responses:
        '200':
          description: OK
          content:
            'application/hal+json; charset=UTF-8':
              schema:
                type: object
                properties:
                  field:
                    type: string
                    description: test field
                  _links:
                    type: object
                    description: HAL links to related resources.
                    properties:
                      self:
                        $ref: '#/components/schemas/link'
              examples:
                valid_response:
                  value:
                    field: test
                    _links:
                      self:
                        href: http://api.test/api/self
components:
  schemas:
    link:
      type: object
      properties:
        href:
          type: string
          format: uri
        name:
          type: string
      required:
        - href
```
I have noticed, that even if the response from my server as a contain types to `Content-Type: application/hal+json; charset=UTF-8`, the Charset part if discard at this [line](https://github.com/microcks/microcks/blob/master/webapp/src/main/java/io/github/microcks/util/openapi/OpenAPITestRunner.java#L116), having for consequence a mismatch between the expected response media type `application/hal+json; charset=UTF-8` and the one extracted from the response after sanitization `application/hal+json`

### Expected behavior

Two potential solution:
- When the charset is provided in the expected Content-Type, do not remove the charset from the actual Content-Type
- Perform the same sanitization of both actual and expected Content-Type, by always remove the charset

### Actual behavior

Due to the sanitization of only the response, I am getting the follow error in the test report
```
{
      "success" : false,
      "elapsedTime" : 7,
      "requestName" : "valid_response",
      "message" : "Response Content-Type does not match expected one. Expecting application/hal+json; charset=UTF-8 but got application/hal+json\n"
    }
```

### How to Reproduce?

Exemple of OpenApi specification with a content-type with a charset:
```
openapi: 3.0.1
info:
  title: My API
  version: 0.0.0
paths:
  /api/authentication/consumer/challenges:
    get:
      summary: a field
      responses:
        '200':
          description: OK
          content:
            'application/hal+json; charset=UTF-8':
              schema:
                type: object
                properties:
                  field:
                    type: string
                    description: test field
                  _links:
                    type: object
                    description: HAL links to related resources.
                    properties:
                      self:
                        $ref: '#/components/schemas/link'
              examples:
                valid_response:
                  value:
                    field: test
                    _links:
                      self:
                        href: http://api.test/api/self
components:
  schemas:
    link:
      type: object
      properties:
        href:
          type: string
          format: uri
        name:
          type: string
      required:
        - href
```

### Microcks version or git rev

1.9.1

### Install method (`docker-compose`, `helm chart`, `operator`, `docker-desktop extension`,...)

test container

**Comment by lbroudoux** [comment]
Thank you for opening this one. We'll consider this enhancement for the next `1.10.0` release.

**Comment by lbroudoux** [comment]
Looks like I've found here the answer to my question in #1233 😉

**Comment by lbroudoux** [comment]
On it and implementing this logic:
* If `charset` is specified in the expected Content-Type, then do not remove the charset from the actual Content-Type and do a comparison ignoring case and white spaces,
* If `charset` is not specified in the expected Content-Type and present in the actual response content-type, then remove it from response and do a comparison ignoring case and white spaces,
* If no charset provided at all, do an ignore case comparison.

In any case, charset information should be removed to determine if we can perform validation on content type (ie. content type can be described using JSON Schema only at the moment). This will be also needed for #1233.

**Comment by lbroudoux** [comment]
I've completed the implementation and pushed it. It should be available in the nightly image in a few minutes.
