### ISSUE TITLE
GraphQL schema instrospection not working on native distribution

### ISSUE THREAD

**Issue by lbroudoux** [microcks/microcks#1235]
### Describe the bug

When fetching the GraphQL schema with a GraphQL introspection query, the native image returns an empty response (`{}`))

### Expected behavior

We expected to received the full schema description.

### Actual behavior

The response is a code 200 with empty content. Standard distribution works correctly returning the schema metadata.

### Microcks version or git rev

nightly - 1.9.x

### Install method (`docker-compose`, `helm chart`, `operator`, `docker-desktop extension`,...)

All

**Comment by Harsh4902** [comment]
@lbroudoux can I work on this issue?

**Comment by lbroudoux** [comment]
Yes, for sure 👌

**Comment by Harsh4902** [comment]
@lbroudoux how can I reproduce this issue?

**Comment by lbroudoux** [comment]
You can run the [1st GraphQL mock](https://microcks.io/documentation/tutorials/first-graphql-mock/) tutorial and try to issue an introspection query (see https://graphql.org/learn/introspection/). You can use either curl or a client like Insomnia or Postman.

You should get a correct answer when requesting against the regular or uber distro of Microcks and encounter an issue when using the uber-native distro. You can use `quay.io/microcks/microcks-uber:nightly` and `quay.io/microcks/microcks-uber:nightly-native` for that.

**Comment by Harsh4902** [comment]
@lbroudoux How can I build and run native image?

**Comment by lbroudoux** [comment]
Native image can be built from the `distro/uber/` folder.
Be sure to `mvn install` the whole project from root and then go to this folder.
Edit the `pom.xml` and uncomment line 123 or line 125 depending on your machine.
Run `mvn -Pnative spring-boot:build-image -Dspring-boot.build-image.imageName=<your-handle>/microcks-uber:nightly-native`
This will produce a `<your-handle>/microcks-uber:nightly-native` container image you can run with a single `docker run` like explained in the Getting Started tutorials.

**Comment by Harsh4902** [comment]
@lbroudoux I tried this and successfully built native image, but sometimes I am getting `whitelabel error page`. What can be the issue?

- build of native image:
<img width="1440" alt="Screenshot 2024-08-11 at 12 48 03 PM" src="https://github.com/user-attachments/assets/62f6183f-325b-4b4a-9a70-4e97a5a86d43">

- error page:
<img width="1440" alt="Screenshot 2024-08-11 at 10 11 45 PM" src="https://github.com/user-attachments/assets/af2579e2-2186-4cc3-8102-953555ae1d2f">

**Comment by lbroudoux** [comment]
No idea sorry. It could be so many things. Maybe you could switch the log verbosity to DEBUG in `logback.xml` file? You'll have to do this into the main webapp module...

**Comment by Harsh4902** [comment]
@lbroudoux I am still not able to get it. Still, one time I added below given code to `reflect-config.json` file and built it successfully and got the schema in introspection query.
```
{
    "name": "com.fasterxml.jackson.databind.ObjectMapper",
    "allDeclaredMethods": true,
    "allDeclaredConstructors": true
  }
```
Can you please check?

**Comment by lbroudoux** [comment]
Dammit... I realize I gave you bad build instructions ...
The main webapp component should first be installed using the prod profile : `mvn clean -Pprod install -DskipTest`
Otherwiser the UI is not embeded and you end up with the "Whitelabel Error page"... Sorry!

**Comment by lbroudoux** [comment]
Did some quick experiments and it appears that putting `ObjectMapper` in reflection config is not enough. It looks like the problem comes when `graphql.ExecutionResultImpl` is serialized back as a String...

**Comment by Harsh4902** [comment]
> Dammit... I realize I gave you bad build instructions ...
> The main webapp component should first be installed using the prod profile : `mvn clean -Pprod install -DskipTest`
> Otherwise the UI is not embeded and you end up with the "Whitelabel Error page"... Sorry!

Ahaa, no problem. Now I will check it.

**Comment by Harsh4902** [comment]
@lbroudoux I got the response 🥳.
<img width="1062" alt="Screenshot 2024-08-14 at 10 38 44 PM" src="https://github.com/user-attachments/assets/9d820d0f-7c9e-4fec-bb3f-d5559176dd7f">

I am trying to add minimal changes in `reflect-config.json` then will raise a PR.

**Comment by lbroudoux** [comment]
Cool 👍 1.10.x is the current development branch.

**Comment by lbroudoux** [comment]
PR has just been merged. Waiting for the image to be produced for final check.
