### ISSUE TITLE
provide an explicit link between the importer / postman collection and the relevant service

### ISSUE THREAD

**Issue by lucamaf** [microcks/microcks#124]
at the moment there is no such link and from the GUI they look like disconnected sections

**Comment by lbroudoux** [comment]
Hi @lucamaf ,

currently you've got a link from Importers to Services. There's a `Services` status box on importers page that links to services discovered using the imported artifact.

Would you like to see the opposite link ? From Services to Importers ? Don't see why knowing the importer job for people browsing Services may be important but why not...

Cheers,

**Comment by lucamaf** [comment]
not needed
