### ISSUE TITLE
1.10.x build is broken

### ISSUE THREAD

**Issue by lbroudoux** [microcks/microcks#1255]
### Describe the bug

Since we merged #1210, it appears that build is broken with JUnit tests in `commons/util` failing. Strangely enough, the merge build itself is OK (see https://github.com/microcks/microcks/actions/runs/10059951635) and the build is also OK locally on my machine (Mac OS X laptop).

We need to investigate on the root causes...

### Expected behavior

Build should pass.

### Actual behavior

Build is failing with 3 failings JUnit tests:

```
AsyncAPISchemaValidatorTest.testFullProcedureFromAsyncAPIWithExternalRelativeReference:515 expected: <true> but was: <false>
Error:    OpenAPISchemaValidatorTest.testFullProcedureFromOpenAPIResourceWithRef:355 expected: <true> but was: <false>
Error:    OpenAPISchemaValidatorTest.testValidateJsonWithExternalReferenceSuccess:174 expected: <true> but was: <false>
```

It looks like remote JSON schema reference resolution is involved each and every time....

**Comment by lbroudoux** [comment]
Now fixed.

**Comment by vsblabs** [comment]
My already installed Microck operator is still broken following this upgrade. What action do I need to take without losing my existing openapi docs?

**Comment by flybyray** [comment]
@vsblabs https://github.com/microcks/microcks/commit/3a2529055d932e7dc9b9ebf44ae945a2c5d6549a
There is a postgresql update from 9.5(centos7) to 16(alpine). Operator was running with automatic update. Guess there will be some others complaining soon.

**Comment by lbroudoux** [comment]
Dammit ... We're currently writing the release notes and reviewing the upgrade process. We miss the point that there could be automatic operator upgrades. Sorry for that guys. Did you succeed in rolling back to `1.9.1` or the previous one to get your setup up again?

**Comment by vsblabs** [comment]
@lbroudoux No we are still unable to progress here. What are the possible dates to get this fixed, or can we do any hacks to overcome the current situation, few a many builds are broken due to this.?

**Comment by lbroudoux** [comment]
The broken build issue has nothing to do with is operator stuff. Are you able to roll back to previous operator version and previous microcks version? This should restore previous state and current data should be available again.

**Comment by vsblabs** [comment]
@flybyray 

<img width="1472" alt="Screenshot 2024-08-05 at 11 21 36 PM" src="https://github.com/user-attachments/assets/10dcc530-d6ee-4857-83f8-721335467521">

A new install from the hub is still giving me `CrashLoopBackOff`. I'm I missing something?

**Comment by lbroudoux** [comment]
> On openshift it was only possible to uninstall the operator from the hub. There is no rollback possible. A new install from hub can only deploy the newest version.

Argh 😟 isn't it possible to edit the Subscription to reference the operator version you need?

> We deployed it now manually from sources. That worked as expected. Some customization had issues but those are unrelated to this release and could be fixed by stopping the ansible based operator after deployment.

Is there something we can do to prevent this behavior regarding the customizations you mention?

**Comment by flybyray** [comment]
> @flybyray
> 
> <img alt="Screenshot 2024-08-05 at 11 21 36 PM" width="1472" src="https://private-user-images.githubusercontent.com/68951265/355195897-10dcc530-d6ee-4857-83f8-721335467521.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI4OTQ4MzAsIm5iZiI6MTcyMjg5NDUzMCwicGF0aCI6Ii82ODk1MTI2NS8zNTUxOTU4OTctMTBkY2M1MzAtZDZlZS00ODU3LTgzZjgtNzIxMzM1NDY3NTIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA1VDIxNDg1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI2MzE1OTZkZjgzOTI3NzgxOGZmZGNmNzdkZWU4OTE2MzViMThkMTg1YWYwN2MyZjY0ZjlmZTJhMzI0ZDU3Y2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dWV79xu-j7zM3vZn9z3PkdZno3s0VMdf5IM3JF2ytT4">
> A new install from the hub is still giving me `CrashLoopBackOff`. I'm I missing something?

Yes you misinterpreted my comment. I am not using openshift hub anymore for microcks-operator. It was only possible to walk away from this distribution system. Because there is no rollback. I will wait until there is a release note with a migration guide. Maybe I will enroll it then again to openshifthub distribution of microcks.

**Comment by flybyray** [comment]
> > On openshift it was only possible to uninstall the operator from the hub. There is no rollback possible. A new install from hub can only deploy the newest version.
> 
> Argh 😟 isn't it possible to edit the Subscription to reference the operator version you need?
> 
> > We deployed it now manually from sources. That worked as expected. Some customization had issues but those are unrelated to this release and could be fixed by stopping the ansible based operator after deployment.
> 
> Is there something we can do to prevent this behavior regarding the customizations you mention?

No problem. Lesson learned. Do not trust the supply chain automatism. Still someone loves this software and Ops was asked to fix it. ;-)
