### ISSUE TITLE
content-type application/merge-patch+json appears to be ignored

### ISSUE THREAD

**Issue by savvyintegrations** [microcks/microcks#1256]
### Describe the bug

We have the following OAS 3.10 endpoint:
```
      "patch": {
        "operationId": "updateJobStatus",
        "description": "Update a job status. Moving a job to IN_PROGRESS starts the job. Moving a job to CANCELED will cancel all current executions and end the job.\n",
        "parameters": [
          {
            "name": "jobId",
            "in": "path",
            "required": true,
            "schema": {
              "$ref": "#/components/schemas/Uuid"
            },
            "examples": {
              "66a2afc3-ab5b-4437-ae7c-0bf0d79c72ca": {
                "value": "66a2afc3-ab5b-4437-ae7c-0bf0d79c72ca"
              }
            }
          }
        ],
        "tags": [
          "Job"
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/merge-patch+json": {
              "schema": {
                "description": "Request body for updating a job status",
                "type": "object",
                "properties": {
                  "status": {
                    "type": "string",
                    "enum": [
                      "IN_PROGRESS",
                      "CANCELED"
                    ]
                  }
                }
              },
              "examples": {
                "applyJobRequestExample": {
                  "summary": "Example request to start a job",
                  "value": {
                    "status": "IN_PROGRESS"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "202": {
            "description": "Request to start a job was accepted",
            "x-microcks-refs": [
              "66a2afc3-ab5b-4437-ae7c-0bf0d79c72ca",
              "applyJobRequestExample"
            ]
          }
        }
      }
    },
```
When we run a test for this endpoint the `application/merge-patch+json` appears to be ignored. The only `operationsHeaders` we are setting in the example below is `x-auth-context`:

Here are the test results:
```
{
  "id": "66aada4809ca8206d3700fb3",
  "version": 2,
  "testNumber": 89,
  "testDate": 1722473032969,
  "testedEndpoint": "http://192.168.0.112:8080",
  "serviceId": "663ed02dd74eac1d07f0fc9a",
  "timeout": 3000,
  "elapsedTime": 20,
  "success": false,
  "inProgress": false,
  "runnerType": "OPEN_API_SCHEMA",
  "operationsHeaders": {
    "globals": [
      {
        "name": "x-auth-context",
        "values": [
          "eyJ0ZWFtSWQiOiI5NGJlZTE3MC0xN2IzLTQxN2ItOTQxMS05ZDUzMDI0YzBlMzUiLCJpc05vcmRpY2FuVGVhbSI6ZmFsc2UsInNvdXJjZUFwaVR5cGUiOiJyZXN0IiwicGxhblR5cGUiOiJQcm8iLCJjcmVhdGVkQXQiOiIyMDI0LTA2LTI3VDIzOjE1OjQ0LjY0M1oiLCJhdXRoZW50aWNhdGlvblRva2VuVHlwZSI6ImFwaV9rZXkiLCJjb3JyZWxhdGlvbklkIjoiYjE1MmFhNjktZjk4NS00MWQ5LTlmMjQtMjY0MDA5NTMzZDU5IiwicmVxdWVzdGVySWQiOiIyZDk3ZDc0Ny1hZjM3LTQ4NTgtYjQ4OS0xMzI4ZWNlZjhkMDciLCJyZXF1ZXN0ZXJUeXBlIjoiVGVhbU1lbWJlciIsInVzZXJBY2NvdW50SWQiOiI1YTg3NmJmNy1mMDIxLTQyYTYtOTNiMC02YjhhY2VmOTgxOTIiLCJyb2xlIjoiQWRtaW4iLCJkZXZpY2VHcm91cHMiOltdfQ=="
        ]
      }
    ]
  },
  "testCaseResults": [
    {
      "success": false,
      "elapsedTime": 20,
      "operationName": "PATCH /jobs/{jobId}",
      "testStepResults": [
        {
          "success": false,
          "elapsedTime": 20,
          "requestName": "66a2afc3-ab5b-4437-ae7c-0bf0d79c72ca",
          "message": "Response HttpStatus does not match expected one. Expecting 202 but got 500\n"
        }
      ]
    }
  ]
}
```
And here's what it looks like in the Microcks UI. Notice there is no `Content-Type`:
![Screenshot 2024-07-31 at 18 02 43](https://github.com/user-attachments/assets/b43f0313-3dd3-4ecc-9a54-2e265780b998)

So we tried adding a `Content-Type` header with `application/merge-patch+json` to `operationsHeaders`. This test also failed, but at least the `Content-Type` appears to be passed by Microcks:
![Screenshot 2024-07-31 at 18 27 01](https://github.com/user-attachments/assets/cf0ac6b8-da02-44f1-aa79-cb5b1ad9a8fd)
However, this caused a `500` error that logged:
```
{"message":"Failed to parse request. Bad content-type or invalid body","name":"50000","stack":"50000: Failed to parse request. Bad content-type or invalid body"}
```
So there may be two issues here: ignored header and improperly passed body for this type of request.

**This same endpoint when run by a Postman client using values imported from the OAS doc works just fine.**

Compare what I've described with a `POST` endpoint we have that has this snippet, and with only `x-auth-context` set in `operationsHeaders` :
```
        "requestBody": {
          "required": true,
          "content": {
            "text/plain": {
              "schema": {
                "$ref": "#/components/schemas/Base64EncodedString"
              },
              "examples": {
                "base64ExampleTextPlain": {
                  "value": "UEsDBBQACAAIALh42FgAAAAAAAAAAAwAAAAbACAAbXlfYXBwbGljYXRpb25fdjFfMS5oZXguYmluVVQNAAe97Xlmvu15Zr3teWZ1eAsAAQT1AQAABBQAAADLSM3JyVcozy/KSeECAFBLBwgtOwivDgAAAAwAAABQSwMEFAAIAAgAtXrYWAAAAAAAAAAAKwEAAA0AIABtYW5pZmVzdC5qc29uVVQNAAd38XlmePF5ZnfxeWZ1eAsAAQT1AQAABBQAAABNj8sKwkAMRff9itC1DozLbgV3gnuRMraxDXQeTKYvi/9uZyzUTSDnnlzIkgHkRmnMC8ivMyjnOqpUIGugd7UKmB+iUiNXnlzk0Ty3yjTY2aaAC01YgzJAzD3CSKEF7hAdaFujgJsd0UNlDfc63QNp5+2AGk1g8at/jQN63sqlkBu1Xqtw3CP5w9Qhr9t9XQCWNDccz/Vc/n1RDrKUosVJPMmk2iSH2SX5z9xDpncM5SmBzzof2Sf7AlBLBwjvpMcuuQAAACsBAABQSwMEFAAIAAgAtXrYWAAAAAAAAAAAsAAAABgAIABfX01BQ09TWC8uX21hbmlmZXN0Lmpzb25VVA0AB3fxeWZ48XlmoPF5ZnV4CwABBPUBAAAEFAAAAGNgFWNnYGJg8E1MVvAPVohQgAKQGAMnEBsBcR0Qg/gbGIgCjiEhQVAmSMcCIBZAU8KIEJdKzs/VSywoyEnVy0ksLiktTk1JSSxJVQ4IBiks+FiZBqK7c9YYg2gAUEsHCHtVkvVcAAAAsAAAAFBLAQIUAxQACAAIALh42FgtOwivDgAAAAwAAAAbACAAAAAAAAAAAACkgQAAAABteV9hcHBsaWNhdGlvbl92MV8xLmhleC5iaW5VVA0AB73teWa+7Xlmve15ZnV4CwABBPUBAAAEFAAAAFBLAQIUAxQACAAIALV62FjvpMcuuQAAACsBAAANACAAAAAAAAAAAACkgXcAAABtYW5pZmVzdC5qc29uVVQNAAd38XlmePF5ZnfxeWZ1eAsAAQT1AQAABBQAAABQSwECFAMUAAgACAC1ethYe1WS9VwAAACwAAAAGAAgAAAAAAAAAAAApIGLAQAAX19NQUNPU1gvLl9tYW5pZmVzdC5qc29uVVQNAAd38XlmePF5ZqDxeWZ1eAsAAQT1AQAABBQAAABQSwUGAAAAAAMAAwAqAQAATQIAAAAA"
                }
              }
            },
```
The `Content-Type` gets properly set by the Microcks Test API, as you can see in the screenshot of the results:
![Screenshot 2024-07-31 at 18 02 57](https://github.com/user-attachments/assets/7b1d8572-7cd2-4f57-ad2e-c985fccefadd)

### Expected behavior

Microcks should call our API with the `application/merge-patch+json` content-type, if set.

### Actual behavior

See above.

### Additional information

Additionally, I have a question: Do I assume correctly that the test results page in the Microcks UI shows `Content-Type` based on what is specified in `operationsHeaders`, and if nothing specified, it pulls it from the OAS doc? I ask b/c the headers sent by the Test API to the tested endpoint don't appear in the test results JSON.

**Comment by lbroudoux** [comment]
Hey @savvyintegrations,

I think there's a mismatch in the snippet you sent because the `jobId` param example has the `66a2afc3-ab5b-4437-ae7c-0bf0d79c72ca` name and the request body is named `applyJobRequestExample `. This makes Microcks consider it a 2 different samples at import time and this made that the request with `jobId` only has no content-type attached... This is what should cause the failure on your side when trying to test with the `66a2afc3-ab5b-4437-ae7c-0bf0d79c72ca` as reported by your test result snippet.

I think the two fragments have to be joined in a single request like below:

![Capture d’écran 2024-08-01 à 09 12 31](https://github.com/user-attachments/assets/53d12685-f613-4b22-aef0-8653a8e119d0)

Then, when launching a test in this configuration, the content-type is correctly set and appears in the test results:

![Capture d’écran 2024-08-01 à 09 13 31](https://github.com/user-attachments/assets/b563a518-418c-4d9e-ba73-d5b7e9e1f1b3)

BTW your guess is correct: `opeationsHeaders` must override what's pulled from the OAS doc.

Let me know if I missed something.

**Comment by savvyintegrations** [comment]
You are correct! Thank you for your time in troubleshooting this, and so quickly! 

Oof, that was challenging. I have some experience with Microcks now, yet I thought this was a bug. Is this kind of thing catchable via a lint rule?

**Comment by lbroudoux** [comment]
Hum ... I think you're right and we should be able to do something as both param and request body are marked as required. We should be able to detect that they're missing fragments to form a complete sample. Great idea! And a new issue to create in [microcks-spectral-ruleset](https://github.com/microcks/microcks-spectral-ruleset) 😉

**Comment by savvyintegrations** [comment]
Thank you @lbroudoux! https://github.com/microcks/microcks-spectral-ruleset/issues/12
