### ISSUE TITLE
Error Importing gRPC Proto with Enum Reference from Another File

### ISSUE THREAD

**Issue by hersentino** [microcks/microcks#1262]
### Describe the bug

Unable to import gRPC proto that contains an enum from another proto file

The bug is not present with `microcks:1.8.1`

### How to Reproduce?

https://github.com/hersentino/microcks-issue

1. Run `docker compose up`.
2. Connect, then go to `http://localhost:8080/#/importers`.
3. Import `protos/test-service.proto` => crash

   ```
   com.google.protobuf.Descriptors$DescriptorValidationException: hello.UnaryRequest.type: ".hello.EnumTest" is not an enum type.
   ```

4. Comment out line `13` inside `protos/test-service.proto`.
5. Retry the import => works flawlessly.

### Microcks version or git rev

quay.io/microcks/microcks:1.10.0

### Install method (`docker-compose`, `helm chart`, `operator`, `docker-desktop extension`,...)

docker compose

**Comment by lbroudoux** [comment]
Thanks a lot for taking the time putting this together! I'll try to have a look at it as soon as possible.

**Comment by lbroudoux** [comment]
I succeeded in reproducing it. I guess this exception is now raised because we're loading the FileDescriptor at https://github.com/microcks/microcks/blob/1.10.0/webapp/src/main/java/io/github/microcks/util/grpc/ProtobufImporter.java#L128 to get extra information on the operation arguments to guess if `QUERY_ARGS` dispatcher can be applied (see #1224).

In any case, this exception occurs because the reference to the `EnumTest` type is not resolved because the `common.proto` file is not found. So it also related to #449.

Before jumping on #449, I'll try to see if we can locally avoid this error and extract the information we need for `QUERY_ARGS` in another way.

**Comment by hersentino** [comment]
> In any case, this exception occurs because the reference to the EnumTest type is not resolved because the common.proto file is not found. So it also related to https://github.com/microcks/microcks/issues/449.

I don't think so because there is an other field `Filters` (witch is not an enum) also imported from the same file, and it works perfectly

**Comment by lbroudoux** [comment]
Yes you're right but I've got a clear `com.google.protobuf.Descriptors$DescriptorValidationException: hello.UnaryRequest.type: ".hello.EnumTest" is not an enum type.` as the exception message... 

I'm in the process in trying to reproduce this in a unit tests. WIll let you know.

**Comment by lbroudoux** [comment]
oh oh my bad, I didn't see that your local `/protos` dir was mounted into `/tmp/protos`... That trick allow finding the reference during the `protoc` compilation ... Still diving in ...

**Comment by lbroudoux** [comment]
OK, got it. When reloading the FileDescription, we specify `allowUnknownDependencies = true` to avoid problems on missing dependencies. But, I just find these comments in `Descriptor` implementation:

```java
// We create a dummy message descriptor here regardless of the
// expected type. If the type should be message, this dummy
// descriptor will work well and if the type should be enum, a
// DescriptorValidationException will be thrown later. In either
// case, the code works as expected: we allow unknown message types
// but not unknown enum types.
```

So basically, that's why it's working with the `Filters` field.

**Comment by lbroudoux** [comment]
A fix is on its way. A new `quay.io/microcks/microcks:nightly` should be available soon for testing.

**Comment by lbroudoux** [comment]
Hi @hersentino 
Cna you confirm the fix works as expected when using the `nightly` tagged image?

**Comment by hersentino** [comment]
Hi @lbroudoux

I just tested it and it works flawlessly
