### ISSUE TITLE
Helm : name the ports and dont use latest for microcks-postman-runtime ( it breaks many policy engines )

### ISSUE THREAD

**Issue by stecullum** [microcks/microcks#1270]
### Reason/Context

Can you update the helm charts to remove the "latest" container and name the ports

### Description

Policy engines on kubernetes will fall over with these simple omissions

Currently the manifests dont name all ports ( the majority are ) and microcks-postman-runtime  uses latest

### Implementation ideas

Allows the helm chart to be deployed when simple kubernetes policys are applied. 

Update the helm template to fix

**Comment by lbroudoux** [comment]
Nice feedback on breaking policy engine. We'll ship that in the next `1.10.0-fix-2` Helm charts as it's a trivial one.
