### ISSUE TITLE
[APIExamples] - Incoherency between schema and code 

### ISSUE THREAD

**Issue by SylvainDumas** [microcks/microcks#1278]
### Describe the bug

There are an incoherency in expected key for status code of the response

- In schema expected key is **code** [link](https://github.com/microcks/microcks/blob/1.10.x/api/APIExamples-v1alpha1-schema.json#L174)
- In code expected key is **status** [link](https://github.com/microcks/microcks/blob/1.10.x/webapp/src/main/java/io/github/microcks/util/metadata/ExamplesImporter.java#L233)

So when merging example artifact, status code of the response is not taken in account (in interface and url reponse)

### Expected behavior

Fix the key for **code**, **status** or **other** to have correct response status code that appears in interface and returned by api call

**Comment by lbroudoux** [comment]
Thanks a lot for noticing this inconsistency! Will realign things asap.

**Comment by lbroudoux** [comment]
`status` is the way to go as we want to be aligned on our internal domain. Fixing the schema.
