### ISSUE TITLE
Problem redirection keycloak from microcks UI and microcks containers in Openshift

### ISSUE THREAD

**Issue by crismarfr** [microcks/microcks#128]
Hi
Can you tell me when this issue is resolved ? Problem of redirection keycloak from microcks UI and microcks containers in Openshift
Link to the problem : Separate URLS for keycloak redirection and keycloak internal validation #119
Thank you fo your help .
Cordially

**Comment by lbroudoux** [comment]
Hi, I think issue #119 is related to Docker Compose and not to OpenShift configuration.
As you're may be looking for a specific OpenShift problem, I've recently fixed and HTTPS issue on OpenShift here : #129.

Please let me know if it helps, otherwise let me know your specific configuration and issues.

**Comment by crismarfr** [comment]
Hi, 
I solved the problem : i disable security contraints in application.properties for api url /api/services/* and /api/jobs/* like this : 
 
application.properties: |-
      # Application configuration properties
      tests-callback.url=${TEST_CALLBACK_URL}
      postman-runner.url=${POSTMAN_RUNNER_URL}

      network.username=
      network.password=

      validation.resourceUrl=http://${APP_ROUTE_HOSTNAME}/api/resources/

      # Logging configuration properties
      logging.config=/deployments/config/logback.xml

      # Keycloak configuration properties
      keycloak.auth-server-url=${KEYCLOAK_URL:http://localhost:8180/auth}
      keycloak.realm=microcks
      keycloak.resource=microcks-app
      keycloak.bearer-only=true
      keycloak.ssl-required=NONE

      keycloak.security-constraints[0].authRoles[0]=admin
      keycloak.security-constraints[0].authRoles[1]=manager
      keycloak.security-constraints[0].authRoles[2]=user
      keycloak.security-constraints[0].securityCollections[0].name=Insecure stuffs
      #keycloak.security-constraints[0].securityCollections[0].patterns[0]=/api/services
      #keycloak.security-constraints[0].securityCollections[0].patterns[1]=/api/services/count
      #keycloak.security-constraints[0].securityCollections[0].patterns[2]=/api/jobs
      #keycloak.security-constraints[0].securityCollections[0].patterns[3]=/api/jobs/count

Thank you 

Cordially

**Comment by lbroudoux** [comment]
Ok nice. What I don't understand is why you have to disable it because, they're already disabled in provided `application.properties` ? See https://github.com/microcks/microcks/blob/master/install/docker-compose/config/application.properties
