### ISSUE TITLE
Link to the doc is broken ("Learn more")

### ISSUE THREAD

**Issue by oliviernguyenquoc** [microcks/microcks#1280]
### Describe the bug

![image](https://github.com/user-attachments/assets/d9064947-10ab-4435-a98d-9fe9a0207e50)

The "learn more" link is pointing to an non-existing page: https://microcks.io/documentation/using/tests/

### Microcks version or git rev

1.10.0

### Install method (`docker-compose`, `helm chart`, `operator`, `docker-desktop extension`,...)

helm chart

**Comment by lbroudoux** [comment]
Thanks for opening this issue. We totally forgot to update all the doc links in the UI after our latest major documentation refactoring... Sorry for this.
