### ISSUE TITLE
OpenAPI Version Check is Too Strict

### ISSUE THREAD

**Issue by yahehe** [microcks/microcks#132]
When the OpenAPI version is quoted, Microcks fails to upload the API, despite displaying a partial success message:
```
openapi: '3.0.0'
info:
  description: 'Super bare bones API'
  version: '1.0.0'
  title: 'Example Microcks API'
```
Results in: 
![image](https://user-images.githubusercontent.com/6528050/55361579-a967cd00-54a5-11e9-9f31-127d0601589c.png)
In this case there is no new entry in the API & Services tab, which is unexpected.

Unquoting the version:
```
openapi: 3.0.0
info:
  description: 'Super bare bones API'
  version: '1.0.0'
  title: 'Example Microcks API'
```
Results in:
![image](https://user-images.githubusercontent.com/6528050/55362015-cfda3800-54a6-11e9-9aa6-087470f2896c.png)
In this case the new service appears in the API & Services tab as expected.

This seems related to #107 but not entirely since in this case the version *is* valid

**Comment by lbroudoux** [comment]
Hi,
thanks for this one. I think this is a regression due to #127. We have to relax the check for detecting YAML using one of the first attributes (`openapi:`) but not forcing the version check.
