### ISSUE TITLE
Allow recursive import resolution in Protobuf importer

### ISSUE THREAD

**Issue by lbroudoux** [microcks/microcks#1322]
### Reason/Context

As discovered in #1285, it appears that we haven't implemented recursive imports resolution in the GRPC/Protobufer importer.

### Description

If all your dependency files are referenced from the main service files, everything is OK but if you have dependencies with their own dependencies, Microcks does not follow the link.

See use-case description here: https://github.com/microcks/microcks/issues/1285#issuecomment-2348718324

### Implementation ideas

We should mimic the way that `OpenAPIImporter` is working as it correctly follows links recursively.

**Comment by lbroudoux** [comment]
Hey @camaral ! Did you get the opportunity to check the fix I've put here on `nightly`? Recursive imports are now expected to work. Ideally, I would love to ship this into the `1.10.1` next week. It would be awesome to get your feedback before that. Thanks a lot!

**Comment by camaral** [comment]
Hey @lbroudoux,
Sorry, I missed the commits. Thank you for tagging me.
It's working like a charm ⭐ 
I'm looking forward to the new version.

**Comment by lbroudoux** [comment]
Awesome! Thank you very much for the quick reply!
