### ISSUE TITLE
Apicurio and Microcks integration not working - no response content

### ISSUE THREAD

**Issue by damianlezcano** [microcks/microcks#135]
I try to reproduce the simple example of the video ->

[video](https://www.youtube.com/watch?time_continue=69&v=trU2-CUouYU)

and I can not register the response ->

`[
	{
		"foo":"some text",
		"bar": 12
	},
		"foo":"some text",
		"bar": 99
	}
]`

in the response panel that you see in the second 37 of the video. For this same reason when I try to do the curl ->

`http://localhost:9000/Test/1.0.0/tests`

so that I return the response that I configure in a apicurio, it does not return anything, only an http 200 but without content.

I hope to be clear. Thanks in advance for the work done.

**Comment by lbroudoux** [comment]
Hi,

Thanks for trying Microcks. I think that Apicurio has recently changed its
export format and payload are expressed as Yaml évent for application/json
content. On the Microcks side, there should be a cohérence check preventing
response body to be imported ...

But these are only guesses for now as I am away from keyboard on vacations
;-) I’ll check this up on next week. Sorry for this little delay.

Cheers,

Le mer. 10 avr. 2019 à 02:48, damianlezcano <notifications@github.com> a
écrit :

**Comment by damianlezcano** [comment]
Hi ibroudoux,

(sorry but my inglish)

In the next url ->

https://github.com/damianlezcano/microcks/blob/master/microcks-branch_master-patch-14042019.zip?raw=true

There is a patch with the correction of this incident (# 135). I do not have permission to generate pull request, for that reason, I generate this patch.

The incident was that since jackson converted from ymel to json, he did not treat it as a string but as a DOM tree and for that reason he identified it as an array, and for that case in the method that processed it, it was not considering this type of JsonNode.ARRAY. Then from the UI an additional method is added so that it formats the output to JSON and can be displayed correctly.

There were 3 files that were modified

1. File: OpenAPIImporter.java

```java
git diff src/main/java/io/github/microcks/util/openapi/OpenAPIImporter.java
    /** Get the value of an example. This can be direct value field of those of followed $ref */
    private String getExampleValue(JsonNode example) {
-      if (example.has("value")) {
-         return example.path("value").asText();
-      }
+         if(example.has("value")) {
+                 if(example.path("value").getNodeType() == JsonNodeType.ARRAY) {
+                         return example.path("value").toString();
+                 }else{
+                         return example.path("value").asText();
+                 }
+         }
       if (example.has("$ref")) {
          // $ref: '#/components/examples/param_laurent'
          String ref = example.path("$ref").asText();

```
*where you add ARRAY as a condition*

2. File: service-detail.page.ts
```javascript
git diff src/main/webapp/src/app/pages/services/{serviceId}/service-detail.page.ts
+  public prettyFormatJSON(text: string): string{
+    return JSON.stringify(JSON.parse(text),null,2); 
+  }
```
*where you add the method that formats the output of the string to json*

3. File: service-detail.page.html

``` html
git diff src/main/webapp/src/app/pages/services/{serviceId}/service-detail.page.html
-   <pre *ngIf="pair.response.content"><code highlight>{{ pair.response.content }}</code></pre>
+   <pre *ngIf="pair.response.content"><code highlight>{{ prettyFormatJSON(pair.response.content)}}</code></pre>
```
*where I make the call to the method created above*

I hope you have understood me.

A big greeting and happy holidays !.

**Comment by lbroudoux** [comment]
Hey ! Thanks a lot for this patch !! Seems clear to me. I should be able to merge it by the end of this week. Thanks again !

**Comment by lbroudoux** [comment]
Thank you very much for this patch that is working as expected. However, problem seems to be bigger as it concers Array representation but also simple Object representation. Will handle this through #134 .
