### ISSUE TITLE
Add escape character on dynamic response

### ISSUE THREAD

**Issue by gozen59** [microcks/microcks#1353]
### Reason/Context

We have fields in API responses based on UUIDs between { }. I write the following line in the example in my reply: “myfield”: “{{{uuid()}}}” and I get “myfield”: “}” back. On the other hand, if I write: “myfield”: “{ {{uuid()}} }”, I get a UUID, but there's too much space between it and the braces. I try to put \ to escape if I paste to get the right format but it doesn't change much : “ myfield”: “\}”

### Description

Possibility to add escape \ for special caracters like { or } on response template.

Ex : “myfield”: “\{{{uuid()}}\}” will give “myfield”: "{82777902-E163-4DA3-A27C-EED07500DC92}" on response mock call.

**Comment by lbroudoux** [comment]
Now available in `nightly` container image! Thanks to @Harsh4902 🎉
