### ISSUE TITLE
[gRPC] Support mocked failure responses

### ISSUE THREAD

**Issue by camaral** [microcks/microcks#1359]
### Reason/Context

Oftentimes, one wants to simulate edge cases in order to verify the application behavior. Because of that, mocks more often than not support returning errors. Microcks does support that for REST, but it doesn't for gRPC.

### Description

From what I could see, Microcks has no support to returning mocked error responses on gRPC.
[This code](https://github.com/microcks/microcks/blob/master/webapp/src/main/java/io/github/microcks/web/GrpcServerCallHandler.java#L331) shows that only success responses are returned.

### Implementation ideas

My suggestion is to use response.code from APIExamples as the [gRPC status code](https://grpc.github.io/grpc/core/md_doc_statuscodes.html) and copy the content of response.body into the error description. This would solve my use case, but I am not sure how other companies use the error responses.

So instead of 

```
streamObserver.onNext(outMsg.toByteArray());
streamObserver.onCompleted();
```

You should implement something like:
```
if (response.status == Status.OK) {
  streamObserver.onNext(outMsg.toByteArray());
  streamObserver.onCompleted();
} else {
  streamObserver.onError(response
    .status
    .withDescription(outMsg)
    .asRuntimeException());
}
```

**Comment by lbroudoux** [comment]
Looks super interesting! Thanks for the enhancement suggestion!

**Comment by lbroudoux** [comment]
Because we don't use `response.status` as of today, it's possible this one will be null or, I suspect, equal to `200` (when people used a Postman Collection and didn't pay attention to the default response status).

As a consequence, to not break existing stuff, I would put something like:
```java
if (response.status == null || response.status == Status.OK || response.status.equals("200")) {
  streamObserver.onNext(outMsg.toByteArray());
  streamObserver.onCompleted();
} else {
  streamObserver.onError(response
    .status
    .withDescription(outMsg)
    .asRuntimeException());
}
```
What do you think?

**Comment by camaral** [comment]
Good thinking! That makes complete sense. 
Since gRPC error codes are from 0 to 16, you could even assume that if `status >= 100`, it's is probably someone using HTTP codes by mistake. Make sure you print a warning log.

**Comment by lbroudoux** [comment]
Hey @camaral 
This is now implemented and available in the `nightly` build. Let me know if you can check it out!

**Comment by camaral** [comment]
It works! Thank you ❤️

**Comment by camaral** [comment]
Hey @lbroudoux , could you release this feature, please? 
The latest(1.10.1) doesn't contain it.

**Comment by lbroudoux** [comment]
Sorry @camaral but we took time finalizing stuff on `1.11.0`. The plan is to release it in mid-January. Working hard before Xmas break to make it possible!
