### ISSUE TITLE
OpenShift - evaluate service account rather than OauthClient

### ISSUE THREAD

**Issue by dhartford** [microcks/microcks#137]
Hi everyone,
I'm a little outside of my comfort zone, but wanted to at least ask the question -
As a *non* cluster admin, I can get tools like Jenkins up and running with oauth integration on openshift.

Is it possible that Microcks can do that as well with their keycloak integration?  Right now, the oauthclient requires the installer to run as a cluster admin versus as a service account similar to how jenkins is setup:

https://docs.openshift.com/container-platform/3.11/architecture/additional_concepts/authentication.html#service-accounts-as-oauth-clients

The ask:  Does microcks (or keycloak) need more permissions than what a non-cluster-admin created service account could provide?

**Comment by lbroudoux** [comment]
Hi Darren,

you're totally right : Microcks should be able to use Service accounts as
OAuth clients, it does not need extra privileges.
Actually, this evolution is on my mind for a long time but recent Operator
creation as supersedes this enhancement. It should be re-integrated into
Microcks Operator
roadmap as we'd like to converge to this installation mean.

Thanks for reminding us this enhancement ;-)

Le lun. 29 avr. 2019 à 21:25, Darren Hartford <notifications@github.com> a
écrit :

**Comment by lbroudoux** [comment]
As we no longer providing specific OpenShift templates and integration through OAuth clients, this issue does not make sense anymore. Closing it.
