### ISSUE TITLE
Update to Keycloak 26.0.0

### ISSUE THREAD

**Issue by lbroudoux** [microcks/microcks#1374]
Bump our embedded version of Keycloak from `24.0.4` to `26.0.0` (latest one as of writing)
Some specific things to not forget:
* Check JS library to see if it must be upgraded
* Change the way hostname is configured as installation time (see https://www.keycloak.org/server/hostname#_utilizing_an_internal_url_for_communication_among_clients)
* Upgrading or Integration Tests using the test containers too,
* Check permissions with `manager` and simple `user` role
* Check groups creation and synchronization from the Admin UI

**Comment by gim-** [comment]
I believe the project should plan to replace Keycloak JS adapter with something vendor agnostic if possible.

These adapters are deprecated for quite some time:
- https://www.keycloak.org/2022/02/adapter-deprecation.html
- https://www.keycloak.org/2023/03/adapter-deprecation-update

**Comment by lbroudoux** [comment]
Hi @gim- 

Yes, this is something we'll have to look at. We already replaced the Java adapter some versions ago and the Javascript one will certainly come once they confirm its deprecation and suggest some alternatives. Do you have experience with some other vendor agnostic OIDC lib on the client side?

Latest update to Keycloak JS 26 is particularly tricky because we also have an outdated frontend stack that cannot handle modern module packaging or types... We'll probably have to integrate some nasty bugs until we tackle we re-writing of frontend on another stack.

**Comment by lbroudoux** [comment]
Think everything is ok now as I've done extensive tests with it. Do not hesitate to re-open if I missed something.
