### ISSUE TITLE
Update to Strimzi 0.43.0

### ISSUE THREAD

**Issue by lbroudoux** [microcks/microcks#1375]
The version of Strimizi we embed in docker-compose or the version the CR we create in Helm chart is pretty old. Update this to latest Strimzi version.

**Comment by Harsh4902** [comment]
@lbroudoux I am working on this issue.

**Comment by Harsh4902** [comment]
@lbroudoux According to [Microcks installation on kind with helm](https://microcks.io/documentation/guides/installation/kind-helm/) documentation, we are using `$ kubectl apply -f 'https://strimzi.io/install/latest?namespace=microcks' -n microcks` to install latest version of `Strimzi`. So do we need any change in helm chart?

**Comment by lbroudoux** [comment]
Yes, we create `Kafka` and `KafkaTopic` from the Helm chart and those properties should be aligned by newest version as well.

**Comment by brunseba** [comment]
Working on kubernetes 1.30

Two more question about upgrade to the latest version of strimizi operator. 
- I don't see any KafkaUser CRD into the templates folder.  How you authenticate to kafka from microcks without this user ?
- My Kafka cluster never switch to ready state when i execute a  "kubectl get kafka", so the minion pod cannot connect/consume topics because it never switch to ready so.

**Comment by lbroudoux** [comment]
Hey there!

> I don't see any KafkaUser CRD into the templates folder. How you authenticate to kafka from microcks without this user ?

The Kafka broker that is created by Microcks install is a very basic one (1 node - no authentication). You should consider we provide this for convenience purposes only and it it not intended to provide a secure and scalable deployment in the case your want to generalize Microcks in your organization. We'd recommend provisioning a Kafka cluster independently for this and then configuring a secure connection using `MicrocksInstall` CRD information.

> My Kafka cluster never switch to ready state when i execute a "kubectl get kafka", so the minion pod cannot connect/consume topics because it never switch to ready so.

I haven't found time yet to check the new version of the Strimizi operator. Maybe @Harsh4902, who worked on this, can help with this test?

**Comment by brunseba** [comment]
@Harsh4902 , it's a microk8s 1.30 version based cluster with 4 CPU and 16GB of RAM.

No ram or cpu issue.

> Hey there!
> 
> > I don't see any KafkaUser CRD into the templates folder. How you authenticate to kafka from microcks without this user ?
> 
> The Kafka broker that is created by Microcks install is a very basic one (1 node - no authentication). You should consider we provide this for convenience purposes only and it it not intended to provide a secure and scalable deployment in the case your want to generalize Microcks in your organization. We'd recommend provisioning a Kafka cluster independently for this and then configuring a secure connection using `MicrocksInstall` CRD information.
> 
> > My Kafka cluster never switch to ready state when i execute a "kubectl get kafka", so the minion pod cannot connect/consume topics because it never switch to ready so.
> 
> I haven't found time yet to check the new version of the Strimizi operator. Maybe @Harsh4902, who worked on this, can help with this test?

Ok, thank's for your reply regarding authentication. I'll continue to troubleshoot the kafka cluster creation issue and came back to you.

**Comment by brunseba** [comment]
> @brunseba Sorry for the late response. Could you please let me know how you're running your Kubernetes cluster? Are you using Kind, Minikube, or another tool? I faced a similar issue with Kind on Docker because the Kind cluster wasn't getting enough memory. If you're using the same setup, try increasing the memory limit to 6 GB in Docker Desktop.

I'm running on a 1.30 version of kubernetes with the microk8s distribution. 4 CPU and 16 GB of RAM. I don't see any RAM or CPU issue.

**Comment by Harsh4902** [comment]
> > @brunseba Sorry for the late response. Could you please let me know how you're running your Kubernetes cluster? Are you using Kind, Minikube, or another tool? I faced a similar issue with Kind on Docker because the Kind cluster wasn't getting enough memory. If you're using the same setup, try increasing the memory limit to 6 GB in Docker Desktop.
> 
> I'm running on a 1.30 version of kubernetes with the microk8s distribution. 4 CPU and 16 GB of RAM. I don't see any RAM or CPU issue.

Okay, then I have to test it. Can you please share steps to configure microcks on microk8s?

**Comment by Harsh4902** [comment]
@brunseba can you please share the configuration steps? I am not able to do ingress setup on microk8s.

**Comment by lbroudoux** [comment]
Closing this one as I think we're done and made several tests. Please, don't hesitate to re-open if facing any issue.
