### ISSUE TITLE
Hardcoded Scheduler to update definitions should be configurable

### ISSUE THREAD

**Issue by sercastiGL** [microcks/microcks#138]
I'm working on a team that uses mock responses intensively, and waiting for 2 hours for microcks to update service definitions is just painful. This value should be configurable:
 https://github.com/microcks/microcks/blob/2e982996d4be02e88213185a8f0a4f6916070ab9/src/main/java/io/github/microcks/task/ImportServiceDefinitionTask.java#L72

I'll post a PR to fix this, if you agree

**Comment by lbroudoux** [comment]
Thanks @sercastiGL for this enhancement! Will have a look at it as soon as possible.

**Comment by lbroudoux** [comment]
Now merged.
