### ISSUE TITLE
Allow validation of incoming REST request payloads on mocks

### ISSUE THREAD

**Issue by lbroudoux** [microcks/microcks#1390]
### Reason/Context

As exposed in #1361, Microcks doesn't perform validation of incoming REST payload on mock endpoints as of today. Request payload validation was actually implemented on the SOAP side but not reported in REST mocks.

To enable it on SOAP endpoints, you have to put an additional `?validate=true` in the endpoint URL - but it appears that this information has been lost during the latest documentation refactoring ... Obviously we cannot use the same trick here as query parameters have a direct meaning in REST and it would put us at risk regarding a semantic collision...

### Description

I propose implementing a new REST endpoint that would include the validation of the incoming request payload if any.

For example:
* We have the regular, existing `/rest/API+Pastry/1.0/...` endpoints without request payload validation,
* We would have a new `/rest-valid/API+Pastry/1.0/...` endpoints that perform request payload validation before routing to the first one if the payload conforms to the schema.

### Implementation ideas

This would be just another entry point in the `RestController` component with would perform the validation first and then route to the existing execution.

**Comment by kaos** [comment]
It would be great if there's an option on what action to take in case of validation errors, such as returning an immediate error response, or merely adding some validation result header (and logging) and then forward the request as usual to make the checking transparent to the normal client/server request flow.

**Comment by lbroudoux** [comment]
A small toggle has been added on the UI to enable the generation of a Mock URL integrating incoming request validation: 

![Capture d’écran 2024-11-04 à 14 13 00](https://github.com/user-attachments/assets/4c1b3047-a668-40c4-9f35-b284301a69e0)

**Comment by kaos** [comment]
IIUC so far this requires to pass `?validate=true` for the request?
So unless the client gets the URL from Microcks, the validation is not something that can be toggled besides adjusting the request issued by the client, right?

**Comment by lbroudoux** [comment]
`?validate=true` is for SOAP endpoint.

For REST endpoints, you will have to use `/rest-valid/` instead of `/rest/` in the endpoints URL.
eg: `http://localhost:8080/rest-valid/API+Pastry+-+2.0/2.0.0/pastry/Eclair+Cafe` instead of `http://localhost:8080/rest/API+Pastry+-+2.0/2.0.0/pastry/Eclair+Cafe`

**Comment by kaos** [comment]
Ah thanks, somehow I only noticed the second of the two commits 🤔
