### ISSUE TITLE
Automatically add query and header constraints from OpenAPI import

### ISSUE THREAD

**Issue by lbroudoux** [microcks/microcks#1402]
### Reason/Context

Following #1366 and #1371, I think we should go a step further and automatically add parameter constraint when a parameter is marked as `required` with an OpenAPI specification. This will produce mocks that are closer to the reality applying the same sanity check that any descent server-side framework for deployed APIs.

### Description

This feature will all automatic parameter constraint on an operation when detecting parameters marked as `required` during an OpenAPI specification import. This should apply for `query` and `header` based parameter. `path` makes no to little sense has the absence of the path will have a direct impact on the mock routing and operation identification. 

### Implementation ideas

This should be integrated into the `OpenAPIImporter` and in the `SwaggerImporter` as well if we have everything to do so.

**Comment by lbroudoux** [comment]
Now available in `nightly` tagged image.

**Comment by kaos** [comment]
Regarding `path`, I do think it makes sense to still validate it, when provided. Consider we have a spec indicating the `path` parameter should be `number` but we pass `foo`, it would be great if that would result in a 4xx response rather than being routed, I think. (unless there's an explicit example for that value, of course.)

**Comment by lbroudoux** [comment]
Yes, I only addressed the easy cases at the moment. Validating this kind of stuff would imply adding a regexp validation constraint too - I just handled the `required` case at the moment.

Also, we need to check if parameter constraint validation on the controller side currently checks the path as weel. I suspect I only implemented the `query` and `header` things as well there...
