### ISSUE TITLE
GraphQL Single query alias support

### ISSUE THREAD

**Issue by glitchy** [microcks/microcks#1415]
### Reason/Context

Current GraphQL functionality allows for single query alias support. For example, the following request:
```
curl --location '{some graphql api}' \
--header 'Content-Type: application/json' \
--data '{"query":"query SomeQuery {MYALIAS: getHockeyTeam(team: "Red Wings") {name rink location}}","variables":{}}'
```
should produce the following response:
```
{"data":{"MYALIAS":[{"team":"red wings","rink":"little caesars arena","location":"detroit, mi"}]}}
```
Currently, Microcks returns:
```
{"data":{"getHockeyTeam":[{"team":"red wings","rink":"little caesars arena","location":"detroit, mi"}]}}
```

### Description

You need to remove a single conditional--no breaking changes result.

## the fix
The issue is a conditional at `webapp/src/main/java/io/github/microcks/web/GraphQLController.java:280`. To fix, remove the conditional, replacing:
```java
      // If multi-queries and aliases were used, recompose an aggregated result.
      if (graphqlResponses.size() > 1) {
         ObjectNode aggregated = mapper.createObjectNode();
         ObjectNode dataNode = aggregated.putObject("data");
         for (GraphQLQueryResponse response : graphqlResponses) {
            dataNode.set(StringUtils.defaultIfBlank(response.getAlias(), response.getOperationName()),
                  response.getJsonResponse().path("data").path(response.getOperationName()).deepCopy());
         }
         responseNode = aggregated;
      }
```
with:
```java
      // Aggregate GraphQL query responses into a unified response object.
      // By setting each response under its alias (or operation name if no alias is provided),
      // we ensure that aliasing applies consistently even for single queries, matching actual
      // graphql behavior.
      ObjectNode aggregated = mapper.createObjectNode();
      ObjectNode dataNode = aggregated.putObject("data");
      for (GraphQLQueryResponse response : graphqlResponses) {
         dataNode.set(StringUtils.defaultIfBlank(response.getAlias(), response.getOperationName()),
               response.getJsonResponse().path("data").path(response.getOperationName()).deepCopy());
      }
      responseNode = aggregated;
```
No breaking changes result.

**Comment by glitchy** [comment]
I would be more than happy to!

**Comment by lbroudoux** [comment]
Awesome! Just be sure to start your PR and to then target branch `1.11.x` where developments happen at the moment.

**Comment by glitchy** [comment]
@lbroudoux i think i need write access
```
microcks on  FEAT-single-query-alias-support is 📦 v1.11.0-SNAPSHOT via ☕ v23 on ☁️  (us-east-1) 
❯ git push -u origin FEAT-single-query-alias-support
ERROR: Permission to microcks/microcks.git denied to glitchy.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

microcks on  FEAT-single-query-alias-support is 📦 v1.11.0-SNAPSHOT via ☕ v23 on ☁️  (us-east-1) 
❯ git remote -v
origin	git@github.com:microcks/microcks.git (fetch)
origin	git@github.com:microcks/microcks.git (push)
```

**Comment by lbroudoux** [comment]
Not really. The process is as follow:
- you should first fork this repo to have your own copy
- you clone it locally on your machine
- you create a new branch from the 1.11.x one to collect the changes
- you commit and the push the changes on this branch
- you submit a Pull Request from your repo to this one targeting the 1.11.x branch 
- I review and accept your PR so that I report your commit on this repo. 

Be careful to sign your commit
with --signoff so that you're clearly identified.

**Comment by glitchy** [comment]
@lbroudoux i should have just read the directions :man_facepalming:, sorry about that. PR is up and hopefully adheres to criteria.

**Comment by lbroudoux** [comment]
Hello! Your PR has been merged and the change is now available in `quay.io/microcks/microcks:nightly` (and `quay.io/microcks/microcks-uber:nightly`). Could you give it a try (executing `docker rmi quay.io/microcks/microcks:nightly` before) and tell if everything is now ok?

**Comment by glitchy** [comment]
I just tested and everything works wonderfully! Thank you so much @lbroudoux! :tada: :raised_hands:

**Comment by lbroudoux** [comment]
Excellent!
