### ISSUE TITLE
Support headers in gRPC APIs

### ISSUE THREAD

**Issue by anika-apel** [microcks/microcks#1418]
We recently started using Microcks for our gRPC APIs and really love the functionality and extensibility. 
One feature we are currently missing for gRPC APIs are headers. Since headers (or in gRPC lingo: gRPC Metadata) are used for authentication, custom headers, tracing or other internal usages, it would be great to support headers in mocks and especially in tests. 

I currently see the following points that would need to be addressed to fully support headers for gRPC APIs: 
- API Testing: Pass headers specified in gRPC Test Runs through to the gRPC call
- API Mocking:  Make headers available in `SCRIPT_DISPATCHER` (currently, it is always an empty list)

It would be great to see this feature in microcks! I am also happy to support here and work on a PR 🙂

**Comment by lbroudoux** [comment]
Thanks for the nice words! This enhancement request makes total sense - even if I have no idea yet about how to implement this and will have to deep dive in `grpc-java` low-level layers 😉. 

Suggestions or PR contribution are more than welcome! I will need some time to find free cycles to look at it.

**Comment by lbroudoux** [comment]
Actually had a quick look at it and find a bunch of useful posts:
* https://www.tutorialspoint.com/grpc/grpc_send_receive_metadata.htm
* https://medium.com/@kn2414e/java-grpc-part-3-metadata-headers-134ac6127874

Propagation from `ServerInterceptor` to actual `Server` (and in our case, the fallback call handler) seems to be done via the `Context` class.

**Comment by anika-apel** [comment]
Exactly, my initial idea was as well to implement it with `Interceptors` and together with your hints I was able to implement the support for gRPC headers in mocks (especially for SCRIPT dispatchers) with a `ServerInterceptor`. 

I will have a look at the testing nex. I found [this issue](https://github.com/grpc/grpc-java/issues/1800) about a configurable ClientInterceptor and think it might be a good starting point to implement a `ClientInterceptor` with varying headers per call.

**Comment by anika-apel** [comment]
Absolutely, the functionality does not overlap at all and I agree that a second PR makes it easier to manage 👍

**Comment by lbroudoux** [comment]
Set the milestone to `1.11.0` has @anika-apel is rocking it!

**Comment by lbroudoux** [comment]
Looks like everything is now merged and available in the `nightly` tagged container images. Well done @anika-apel!
Would you be open to writing a small blog post introducing this feature and/or sharing your usage of Microcks? It would be awesome to share this with the community.

Feel free to DM me on [our Discord](https://microcks.io/discord-invite/) or [LinkedIn](https://www.linkedin.com/in/laurentbroudoux/) if you'd like to discuss this. I'd be happy to connect!
