### ISSUE TITLE
Support embedded Avro schema + schema registry integration

### ISSUE THREAD

**Issue by lbroudoux** [microcks/microcks#1422]
### Reason/Context

For the full context of this issue, please check #1411 

### Description

It appears that this feature is only working today if your Avro schema is actually in an external file (see https://raw.githubusercontent.com/microcks/api-lifecycle/refs/heads/master/cloud-events-demo/animal-sensor-1.0.0-bin-asyncapi.yaml as an example) and thus your AsyncAPI file imported into Microcks using an importer (to allow references resolution).

Looking quickly at the code, I think we should be able to also add support for embedded Avro schemas like in #1411 use-case. 

The process would be to check first - like today - is a specific external Schema Entry is bound to the operation. If nothing is found, then default to extract the Avro schema information from the current operation in the spec.

**Comment by lbroudoux** [comment]
Hi @brunodomenici
I finally found some time to work on this and will have something very soon. Still interested in helping testtng this?

**Comment by brunodomenici** [comment]
Hello. Yes, I still interested, but I'll only have time to work on it mid January...

**Comment by lbroudoux** [comment]
This is now working correctly on my side and I added a bunch of integration tests in the CI pipeline (please check the `KafkaProducerManagerIT` class). This feature is now available in `nightly` tagger container images.

I'm closing this issue for now. Do not hesitate re-opening it in January of you're encountering some issues.

**Comment by brunodomenici** [comment]
Hello @lbroudoux
I don't why, but I'm not able to see the branch `1.11.x` in my local git, odd.
So, I gave a try with the `nightly` build and it looks better. Now I see the records are being produced in my topic but, they are encoded in `bytes` (plain Avro, I guess). I believe it should use `KafkaAvroSerializer` in order to use Schema Registry.
Regards.

**Comment by lbroudoux** [comment]
Hi @brunodomenici 
It might be because the default Avro encoding is still set to `RAW` in your settings. Can you check you set `minion.default-avro-encoding=REGISTRY`? (see https://microcks.io/documentation/references/configuration/application-config/#behavior) 

Depending on how you deploy Microcks, it could be in a single `application.properties` for docker compose (the property has to be prefixed with `%docker-compose.` then), or in Helm `values.yaml` or in Operator CRD...

**Comment by brunodomenici** [comment]
It works! Thanks @lbroudoux 
I'll do more tests...
Is there any doc in specific you'd me to update?

**Comment by lbroudoux** [comment]
Nothing comes to my mind at the moment. I'll think about it.
It's much more about what kind of doc you needed or were expecting when you got started... 
Or it could be a standalone doc just sharing your use case and setup.
