### ISSUE TITLE
📝 A lot of broken `404` documentation links in the "Help menu"

### ISSUE THREAD

**Issue by adriens** [microcks/microcks#1423]
### Describe the bug

# ❔ About

We are currently using Microcks (and we 😍  it, blog post in the pipe, we'll let you know) and found some broken links within `microcks` itself.

## `Help menu` section

| How to access                                         | URL                                                                                                           | Screenshot                            |
|-------------------------------------------------------|---------------------------------------------------------------------------------------------------------------|---------------------------------------|
| Help menu                                             | [Defining REST mocks in OpenAPI](https://microcks.io/documentation/using/openapi/)                            | ![Image](https://github.com/user-attachments/assets/7a948ef9-8e0e-44dd-9d27-93396e8c6c71)   |
| Help menu                                             | [Defining Event-driven mocks in AsyncAPI](https://microcks.io/documentation/using/asyncapi/)                  |                                       |
| Help menu                                             | [Using Postman Collections](https://microcks.io/documentation/using/postman/)                                 |                                       |
| Help menu                                             | [Using SoapUI Projects](https://microcks.io/documentation/using/soapui/)                                      |                                       |
| Help menu                                             | [Mocking GraphQL API](https://microcks.io/documentation/using/graphql/)                                       |                                       |
| Help menu                                             | [Mocking gRPC Service](https://microcks.io/documentation/using/grpc/)                                         |                                       |
| Help menu                                             | [Generating Direct API](https://microcks.io/documentation/using/dynamic/)                                     |                                       |
| Help menu                                             | [Mocking Reference](https://microcks.io/documentation/using/mocks/)                                           |                                       |
| Help menu                                             | [Directly upload a new Service/API definition](https://microcks.io/documentation/using/upload/)               |                                       |
| Help menu                                             | [Managing Secrets for private repositories](https://microcks.io/documentation/administrating/secrets/)        |                                       |
| Help menu                                             | [Defining and Managing Jobs](https://microcks.io/documentation/using/jobs/)                                   |                                       |
| Help menu                                             | [Getting Started with Tests](https://microcks.io/documentation/getting-started-tests/)                        |                                       |
| Help menu                                             | [Understanding Conformance Index & Score](https://microcks.io/documentation/using/tests/#conformance-metrics) |                                       |
| Help menu                                             | [Defining tests with Postman](https://microcks.io/documentation/using/postman/#defining-tests)                |                                       |
| Help menu                                             | [Defining assertions with SoapUI](https://microcks.io/documentation/using/soapui/#defining-tests)             |                                       |
| Help menu                                             | [Testing Reference](https://microcks.io/documentation/using/tests/)                                           |                                       |
| Help menu                                             | [Launching tests from Jenkins](https://microcks.io/documentation/automating/jenkins/)                         |                                       |
| Help menu                                             | [Launching tests from GitHub Actions](https://microcks.io/documentation/automating/github-actions/)           |                                       |
| Help menu                                             | [Using Microcks tests from Tekton](https://microcks.io/documentation/automating/tekton/)                      |                                       |
| Help menu                                             | [Microcks CLI](https://microcks.io/documentation/automating/cli/)                                             |                                       |
| Help menu                                             | [Microcks API](https://microcks.io/documentation/automating/api/)                                             |                                       |

## `APIs | Services`

| How to access                                         | URL                                                                                                           | Screenshot                            |
|-------------------------------------------------------|---------------------------------------------------------------------------------------------------------------|---------------------------------------|
| APIs \| Services > Select an API                      | [Learn More](https://microcks.io/documentation/using/tests/#conformance-metrics)                              | ![Image](https://github.com/user-attachments/assets/4d86f829-1967-4297-aa17-5888c6117379)|
| APIs \| Services > Select an API > Select an Endpoint | [Learn More](https://microcks.io/documentation/using/dispatching/)                                            | ![Image](https://github.com/user-attachments/assets/ee6e0619-0209-4af1-8d04-721cac960388)|

# 🔖 Related issues

- https://github.com/microcks/microcks/issues/1350

### Expected behavior

- Not have `404` while clicking of documentation refs

### Actual behavior

- We get `404`

### How to Reproduce?

See the issue body request that points all the refs that lead to `404`

### Microcks version or git rev

1.10.1-fix-1

### Install method (`docker-compose`, `helm chart`, `operator`, `docker-desktop extension`,...)

from quarkus

### Additional information

We run `microcks` from Quarkus DEVUI, below our current `pom.xml`: 

```xml
<dependency>
    <groupId>io.github.microcks.quarkus</groupId>
    <artifactId>quarkus-microcks</artifactId>
    <version>0.2.6</version>
    <scope>provided</scope>
</dependency>
```

**Comment by adriens** [comment]
Current live version : 

![image](https://github.com/user-attachments/assets/c0393bca-bcae-4587-b6a7-10c5062c3726)

**Comment by lbroudoux** [comment]
Hey @adriens

Thanks a lot for opening this issue and for the kind words! You're right: this issue is related to #1350 - we forgot to update the contextual help from the application after our documentation migration.

We'll try to spend some time updating this, but it will be done on the `1.11.x` branch, which currently produces `nightly` tagged container images.

**Comment by adriens** [comment]
Hi @lbroudoux is there a gh milestone so we can follow 1.11 features that are in the pipe?

**Comment by lbroudoux** [comment]
Yes sure. There is this milestone: https://github.com/microcks/microcks/milestone/45 
You can see that a bunch of issues are already closed.

**Comment by adriens** [comment]
Yep
We have reviewed them this afternoon with my team
Thanks à lot for pointing us the milestone

**Comment by adriens** [comment]
We are waiting to produce a content to make you a Nice pr to be part of adopters

**Comment by lbroudoux** [comment]
This is now fixed, but it will only appear if you select a `nightly` Microcks image in your Quarkus application.properties configuration file.

**Comment by adriens** [comment]
Would you share some examples on how to do this from the pom ?

**Comment by lbroudoux** [comment]
You can not configure this via the pom but have to add something like the snippet below in `application.properties`:

```properties
quarkus.microcks.devservices.image-name=quay.io/microcks/microcks-uber:nightly
```

See for example: https://github.com/microcks/microcks-quarkus-demo/blob/main/src/main/resources/application.properties

**Comment by adriens** [comment]
:pray: thanks a lot for the code snippet, we'll use it :star_struck:

**Comment by Supervinh** [comment]
Hello, I am a dev working with @adriens. I am currently using microcks for testing, so like you said I tried the 

```ini
quarkus.microcks.devservices.image-name=quay.io/microcks/microcks-uber:nightly
```

But then microcks doesn't load anymore, I have a 404 error.

![image](https://github.com/user-attachments/assets/af12f7af-12fb-450a-b311-6f038ebc5188)

If I remove the line from my application.properties, it is working properly.

**Comment by adriens** [comment]
> If I remove the line from my application.properties, it is working properly.

As it uses the `pom.xml` as main configuration source right @lbroudoux ?

**Comment by lbroudoux** [comment]
OMG... I think you have something here as I've done a quick test and it looks like a packaging issue on the recent `quay.io/microcks/microcks-uber:nightly` container image. I have to investigate on this.

**Comment by lbroudoux** [comment]
Ok. I've opened #1444 and a fix is on its way. Please `docker rmi quay.io/microcks/microcks-uber:nightly` on your machine and try it again.

**Comment by Supervinh** [comment]
Yes it's working now thanks. 
There is still one 404 error in the help menu [Mocking Reference](https://microcks.io/documentation/using/mocks/), otherwise everything else is working :+1: .

**Comment by adriens** [comment]
Btw... we are on podman
