### ISSUE TITLE
APIExamples: fallback template for null/blank values

### ISSUE THREAD

**Issue by paulRbr** [microcks/microcks#1446]
### Reason/Context

When using an existing value from a request body inside a template response example, e.g. `{ "my_boolean_attribute": {{request.body/my_boolean_attribute}} }` the value can easily be empty (if the `my_attribute` parameter is optional).

This can lead to incorrect mocking response such as:
```json
{
  "my_boolean_attribute":
}
```

### Description

Could we implement a “fallback” expression to execute another template expression if the first one is null. Syntax wise we could write something like `{{ request.body/my_boolean_attribute || randomBoolean() }}`?

**Comment by lbroudoux** [comment]
Now available in `nightly` tagged container image. Documentation should land there: https://microcks.io/documentation/references/templates/#fallback soon.

**Comment by paulRbr** [comment]
Amazing how quick you've added this! Thank you very much @lbroudoux :bow:
