### ISSUE TITLE
OpenAPI support - Cannot get responses examples in $ref

### ISSUE THREAD

**Issue by simon435500** [microcks/microcks#149]
When I import Openapi spec, I found there is a problem that microcks cannot get the examples when responses is reference by $ref.

Here is a part of my spec yaml:
```yaml
...
    responses:
      '401':
        $ref: '#/components/responses/JWTAuthExpired'
...
components:
  responses:
    JWTAuthExpired:
      ...
      examples:
        JWTAuthExpired:
          value:
          ...
```

**Comment by lbroudoux** [comment]
Hi @simon435500

Thanks for this issue. You're totally right: `$ref` were not followed when used within response elements. I should commit this support shortly. Stay tuned and tell me if it solves your issue.

Many thanks,
