### ISSUE TITLE
Add proper support for PATCH operation

### ISSUE THREAD

**Issue by sleevezip** [microcks/microcks#156]
We have a couple of PATCH operations we would like to mock, however it seems like Microcks does not support PATCH operations.

1. We create our mocks using Postman Collections
2. We create PATCH operations in Postman
3. We import the Postman Collection using Importer
4. PATCH operation is not showing up

**Comment by lbroudoux** [comment]
Hi @sleevezip, thanks for raising this issue. `PATCH` support should be ok event if you should have some glitches into the frontend UX. I'll check that and try to produce and updated sample.
