### ISSUE TITLE
Unable to generate mock for simple OpenAPI 3.0 spec

### ISSUE THREAD

**Issue by mhockelberg** [microcks/microcks#157]
The import indicates it's successful.  No mock endpoint is generated.  No errors in the logs.  There is an example in the spec for the operation.  Need help on why this isn't creating the mock endpoint.  Spec attached.
[openapi-spec.json.zip](https://github.com/microcks/microcks/files/3432568/openapi-spec.json.zip)

**Comment by yada** [comment]
@mhockelberg : thanks for this feedback, most core devs are taking a summer break currently but will check it out asap and see if we have something wrong around OpenAPI 3.0... stay tuned ;)

**Comment by nmasse-itix** [comment]
Hi @mhockelberg,

No error is generated when examples cannot be found for an operation. That's a choice since the OAS might be under design and those examples could be added later. 

In your specific example, Microcks could not find a valid example for your operation "GetLocationById" since there is no matching example for your path parameter "id". 
 
Also, you will have to modify your OpenAPI Specification file to move the path parameter "id" into the "path object" rather than in the "operation object". 

Please find below the modified OAS. 

```json
{
  "openapi": "3.0.0",
  "info": {
    "title": "LocationById",
    "description": "A brand new API with no content.  Go nuts!",
    "contact": {},
    "version": "1.0"
  },
  "servers": [
    {
      "url": "https://{defaultHost}",
      "variables": {
        "defaultHost": {
          "default": "www.example.com"
        }
      }
    }
  ],
  "paths": {
    "/location/{id}": {
      "parameters": [
        {
          "name": "id",
          "in": "path",
          "description": "Location identifier",
          "required": true,
          "style": "simple",
          "explode": false,
          "schema": {
            "type": "string"
          },
          "examples": {
            "location": {
              "value": "83"
            }
          }
        }
      ],
      "get": {
        "summary": "getLocationById",
        "description": "Get location",
        "operationId": "GetLocationById",
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/RootTypeforlocation"
                },
                "examples": {
                  "location": {
                    "value": "{\n    \"id\": 83,\n    \"name\": \"some text\",\n    \"location\": {\n        \"lat\": 55.93,\n        \"lng\": 97.05\n    },\n    \"type\": \"some text\",\n    \"status\": \"some text\"\n}"
                  }
                }
              }
            }
          }
        },
        "deprecated": false
      }
    }
  },
  "components": {
    "schemas": {
      "RootTypeforlocation": {
        "title": "RootTypeforlocation",
        "description": "The root of the location type's schema.",
        "type": "object",
        "properties": {
          "id": {
            "format": "int32",
            "type": "integer"
          },
          "name": {
            "type": "string"
          },
          "location": {
            "$ref": "#/components/schemas/Location"
          },
          "type": {
            "type": "string"
          },
          "status": {
            "type": "string"
          }
        }
      },
      "Location": {
        "title": "Location",
        "type": "object",
        "properties": {
          "lat": {
            "type": "number"
          },
          "lng": {
            "type": "number"
          }
        }
      }
    }
  }
}
```

**Comment by lbroudoux** [comment]
Hi @mhockelberg : I'm now back from summer break. Also thanks @nmasse-itix for help. Did this solve your issue and allows you to create needed mock endpoints ?

**Comment by mhockelberg** [comment]
Hi @lbroudoux I'm looking at this now.  I think it does, but I want to verify a few things.  Thank you and @nmasse-itix for the quick turnaround.  Much appreciated.

**Comment by mhockelberg** [comment]
@lbroudoux and @nmasse-itix I looked into this more ...using Apicurio to create the API with the and it seems to be in the right place, but no mock is created for that operation.  I did notice that Apicurio does not provide a GUI facility for adding a parameter example value and I'll be reporting that issue to them.  But I added the parameter example in the source and no luck.  I attached the example.  What am I missing?
[Locations-user1.json.zip](https://github.com/microcks/microcks/files/3483457/Locations-user1.json.zip)

**Comment by lbroudoux** [comment]
Hi,

you’re right : Apicurio does not offer the ability to edit parameters examples yet but I contribute it few days ago => https://github.com/Apicurio/apicurio-studio/pull/869

Pet store sample in Apicurio has also been updated to embed parameter example definition so that sample can be directly imported into Microcks with working mocks. You may want to check it out. 

I’ll have a look at you contract on tomorrow. 

Cheers,

**Comment by lbroudoux** [comment]
Hi @mhockelberg,

for Microcks being able to gather examples and associate request and response example fragments, these fragments should have the same name (see https://microcks.github.io/using/openapi/). However in your file, response example fragment is called `single` and request fragment (the `id` parameter example) is called `location`. So there's a mismatch...

Just rename the example `single` on line 60 of your file and Microcks will be able to build a mock.

**Comment by mhockelberg** [comment]
@lbroudoux thank you!  It works now.  I didn't realize that the param example names had to match their related request and/or response example names.  Really appreciate your help :)
