### ISSUE TITLE
Path parameters examples are not found when defined at the operation level

### ISSUE THREAD

**Issue by nmasse-itix** [microcks/microcks#158]
As discovered in #157, the path parameters examples are only taken into account if they are defined at the path object level. When defined at the operation object level, they are ignored. 

The specification says that path parameters can be defined at both levels:
https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md#path-item-object

*"A list of parameters that are applicable for all the operations described under this path. These parameters can be overridden at the operation level, but cannot be removed there. "*

If the parameters can be overridden it means it can be defined there.

**Comment by lbroudoux** [comment]
Now done.

**Comment by lbroudoux** [comment]
Now done and merged
