### ISSUE TITLE
Import of postman collection failed if url is using {{variable}}

### ISSUE THREAD

**Issue by samsd21** [microcks/microcks#166]
Define a variable (exemple baseUrl}} at the collection level
Use this variable for the path of a request ex : {{baseUrl}}/my/path/:ressourceid

export collection 
import it in microcks  : failed
Importation error on server side (Runtime exception for MY_API: Illegal repetition {{baseUrl}}/my/path/:(.+)) 

works fine if i put a fictive host in the url

related to issue 24 25 ?

**Comment by lbroudoux** [comment]
Hi @samsd21 ,

Thanks for opening this issue. I try to reproduce it using a Postman collection where I used `{{baseUrl}}` prefix when defining the path of my operations but did not manage to...

Here's my exported collection : https://gist.github.com/lbroudoux/12c3a2e685f9d723985e9431716bd06e. Feel free to share yours too.

**Comment by samsd21** [comment]
I confirm that your collection works fine.
here is a short version of mine which fails:
https://gist.github.com/samsd21/abcd0933e3cccfb9d9188e9c58a37e26

**Comment by lbroudoux** [comment]
Hi @samsd21 ,

just found what was going wrong within your collection: variable in base path in URL is not supported right now. I'm committing a patch to allow this kind of URL construction. Stay tuned for availability in few minutes ;-)

**Comment by lbroudoux** [comment]
Done and now packaged into container images on Docker Hub.
