### ISSUE TITLE
keycloak-openshift image removed

### ISSUE THREAD

**Issue by NissesSenap** [microcks/microcks#169]
Hi

I'm trying to install microcks using openshift using:  https://raw.githubusercontent.com/microcks/microcks/master/install/openshift/openshift-ephemeral-full-template.yml 
but keycloak-openshift:3.4.0.Final have been removed, for more info see: https://github.com/keycloak/keycloak-containers/pull/164

As they say it's available in: jboss/keycloak on dockerhub, but it seems like they haven't ported the old one keycloak-openshift to the new repo.

I tried the never 3.1 version as well but no luck. I have also tried the keycloak 4.8.3.Final but it seems like they don't use start-keycloak.sh any more or i can't find it at least.

I haven't given this super much time on this but if anyone has knowledge of what you need to change in to make keycloak work please share.

If not i will try to take a deeper look as soon as i have time.

**Comment by lbroudoux** [comment]
Hi @NissesSenap,

sorry for this, I hadn't notice the images will be removed from Docker Hub... Keycloak upgrade was on my todo list and is now high priority. I've got a working setup using `jboss/keycloak:4.8.3.Final` and changing the `Deployment` stuffs. I'll commit it as soon as my tests will be complete.

**Comment by lbroudoux** [comment]
Just committed the new templates for OpenShift and Chart for Helm. Feedback is welcome before closing the issue ;-) Thanks,

**Comment by NissesSenap** [comment]
It happens, thank you for prioritizing it.
My shiti hotel wifi is unable to pull down the images to my crc before the timeout.
But i will try the first thing i do when i get to the office tomorrow.

**Comment by NissesSenap** [comment]
I have managed to deploy it now and it works fine, thanks.

**Comment by NissesSenap** [comment]
Hi
The keycloak was solved.

But i found the following issue:
        from:
          kind: ImageStreamTag
          name: postgresql:9.5

This needs to be updated to postgresql:9.6

https://github.com/sclorg/postgresql-container

I will create a PR for this.
