### ISSUE TITLE
Dynamic mocks : transferring values from the request to the response

### ISSUE THREAD

**Issue by crismarfr** [microcks/microcks#170]
Hi,
Can you explain a solution of my issue : i want to make dynamic mocks and transfer values from parameter catch in the request, body, header to the response body.
For example, for a request /api/v1/calcul?input=1, i want to transfert input value 1 into the response body.
I try with a groovy script but requestContext doesn't work in microcks engine
Thanks for your help
Cordially

**Comment by crismarfr** [comment]
Hi
In microcks, can we used log, context, requestContext, mockRequest and mockOperation objects in a Groovy script ?
Thank you for your help
Cordially

**Comment by lbroudoux** [comment]
Hi @crismarfr 

currently it is not possible to have dynamic mock content and reuse input parameters as value for building a new response body. The script evaluation engine we have is limited to returning the name of the response to send back to the caller.

For now, you can only use `log` and `mockRequest` object from within your Groovy script but I'd be happy to add more if it make sense.

Best regards,

**Comment by crismarfr** [comment]
Hi @lbroudoux 
Thank you for your help and i think that microcks is a very good tools.
I am studying microcks and I would like to know the limits in the mocks variabilization. If i understand, we can't  in a groovy script, generate variabilized responses based on queries input data as the soapui tool does : insert value parameter directly in the example response. This need is urgent to avoid defining static answers ... 
Best regards

**Comment by lbroudoux** [comment]
Some kind of dynamic content generation is on the TODO for a while (see #94) and I hope to have the opportunity to tackle this topic in the coming month. Please follow this reference issue and thread for any follow-up or contribution ;-)
