### ISSUE TITLE
CORS preflight OPTIONS request fails with status 403 forbidden

### ISSUE THREAD

**Issue by bodograumann** [microcks/microcks#172]
Automatic CORS was implemented in #144, but there is still an issue with it.

We have not defined any CORS handling in our API, but assume it is handled automatically.
The browser sends a preflight OPTIONS request, like the following:
```http
OPTIONS https://microcks.████████/rest/████████+v1+as+OpenAPI+v3/1.0.0/users
Host: microcks.████████
User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:70.0) Gecko/20100101 Firefox/70.0
Accept: /
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate, br
Access-Control-Request-Method: POST
Access-Control-Request-Headers: authorization,content-type
Referer: http://localhost:8080/create-customer
Origin: http://localhost:8080
DNT: 1
Connection: keep-alive
```

The microcks server then sends a “403 forbidden” response.
```http
HTTP/1.1 403
Server: nginx/1.10.3 (Ubuntu)
Date: Wed, 06 Nov 2019 09:37:40 GMT
Content-Length: 20
Connection: keep-alive
X-Application-Context: application:prod
Allow: GET, HEAD, POST, PUT, DELETE, OPTIONS, PATCH
```

According to the comments in #151 and our own understanding of the code, the OPTIONS request does not reach the custom handling code in `src/main/java/io/github/microcks/web/RestController.java`, but is blocked by SpringBoot itself.

CC @t-rap

**Comment by lbroudoux** [comment]
Hi @bodograumann ,

Thanks for opening this issue. You're right : we're still having issue properly handling CORS pre-flight requests. In case of different Origin from server, Spring Boot is handling request and does not invoke the controller method. I'm currently investigating on how to disable this.

I've reopened #151 as it was the original issue and will follow resolution on this later.

Thanks again.
