### ISSUE TITLE
Failed to initialize authentication subsystem

### ISSUE THREAD

**Issue by fab66m** [microcks/microcks#177]
Microcks 0.8.0 on Openshift 3.11 / Red Hat SSO 7.3.4.GA / Apicurio Studio 0.2.44

I'm struggling to get the browser to log into Microcks when the Keycloak realm 's access type is set to confidential, see error message in the title.

I need this setting for a generating a client secret that Apicurio Studio requires to create mocks via Microcks and that works (https://apicurio-studio.readme.io/docs/integrate-microcks-for-mocking-your-api). 
If I set the access type to public I can login to Microcks again, but without client secret Apicurio cannot access Microcks anymore.

I would appreciate if someone can point me into the right direction.

**Comment by lbroudoux** [comment]
Hi,

You actually do not need to change authentication settings to make Apicurio talk to Microcks. 

Microcks realm definition comes by default with the `microcks-service-account` clientId that is used to issue a Grant OpenID connect flow. Just retrieve the associated clientSecret into Microcks keycloak realm configuration and put it into Apicurio config. 

Tell me if you need more clarifications - travelling at the moment. 

Cheers,

**Comment by fab66m** [comment]
I have compared the realm settings for the microcks clients from one of the templates with my external SSO server and made some adjustments, it works now. 

Need to spend some minutes on understanding the role of microcks-app, microcks-app-js and microcks-serviceaccount and their respective settings.

Thanks for your work on this project!

**Comment by lbroudoux** [comment]
My pleasure ! Please give us some news and feedbacks ;-)
