### ISSUE TITLE
Make the Helm chart available on Helm Hub

### ISSUE THREAD

**Issue by wilmardo** [microcks/microcks#189]
Hosting a chart as a Helm repository makes it easier to install and maintain (separate versioning for the chart for example). 
Adding the chart to the Helm Hub makes it easy to find for users looking for a way to install Microcks.

This involves two steps:
- Setup a site to host the charts on (can be Github Pages)
- Add chart to Helm Hub (hub.helm.sh)

Some examples:
- https://github.com/helm/chart-releaser
- https://github.com/drupalwxt/helm-drupal/blob/master/.travis.yml
- https://github.com/ceph/ceph-csi/blob/master/deploy.sh

**Comment by lbroudoux** [comment]
Hi ! Great idea and great links for examples !

I'm quite new to Helm charts having a background on OKD/OpenShift Templates and Operators but setup seems simple. Will definitely consider and have a deeper look at it.

**Comment by lbroudoux** [comment]
Now available here: https://hub.helm.sh/charts/microcks/microcks ;-)
