### ISSUE TITLE
Params are not loaded to context from request

### ISSUE THREAD

**Issue by lahiruk** [microcks/microcks#209]
https://github.com/microcks/microcks/commit/2e67391aea155207f64b7194febf763cd741ca86#r38746957

**Comment by lbroudoux** [comment]
Damn! Thanks for opening this one. Will fix and release a `0.9.1` in few days.

**Comment by lbroudoux** [comment]
Should now be available into the `latest` container image on Docker hub.

**Comment by lbroudoux** [comment]
Thanks a lot @lahiruk !!
