### ISSUE TITLE
Help in installing the docker version on EC2

### ISSUE THREAD

**Issue by LevinGuy** [microcks/microcks#229]
Hi,

First, this project looks great :)

I am trying to install the microcks on an EC2 machine.
Running the docker-compose / setup-tls-run.sh works ok.
But then I want to access it (from external IP) it is not working.
I am accessing the 8080 port with the external IP but then it redirects to the keycloak server which is not working and getting : 

> This page isn’t working right now
> sent an invalid response.
> ERR_INVALID_HTTP_RESPONSE

I am accessing with `https://IP:8080/` but then getting: 

`http://IP:8543/auth/realms/microcks/protocol/openid-connect/auth?client_id=microcks-app-js&redirect_uri=.....`

but I think that keycloak is not installed with the external IP or there is an SSL issue.

Perhaps there is something I am not configuring correctly?

Thanks,
Guy

**Comment by LevinGuy** [comment]
All worked, sorry

**Comment by lbroudoux** [comment]
Happy to read this! Do not hesitate letting us know how the things are going.

Cheers,

**Comment by LevinGuy** [comment]
Still having some problems - getting some 401s with "Didn't find publicKey for specified kid" messages. Went over the closed issues and trying some of the suggestions there.

Will keep you informed :)

**Comment by LevinGuy** [comment]
Hi @lbroudoux ,

Still no luck:

[ERROR] org.keycloak.adapters.rotation.AdapterRSATokenVerifier - Didn't find publicKey for kid: ftfMUh10BxUe8HA-gjH96YyQ4IJF_D4i1wMIOZg26ho
[ERROR] org.keycloak.adapters.BearerTokenRequestAuthenticator - Failed to verify token
org.keycloak.common.VerificationException: Didn't find publicKey for specified kid
        at org.keycloak.adapters.rotation.AdapterRSATokenVerifier.getPublicKey(AdapterRSATokenVerifier.java:47)
        at org.keycloak.adapters.rotation.AdapterRSATokenVerifier.verifyToken(AdapterRSATokenVerifier.java:55)
        at org.keycloak.adapters.rotation.AdapterRSATokenVerifier.verifyToken(AdapterRSATokenVerifier.java:37)
        at org.keycloak.adapters.BearerTokenRequestAuthenticator.authenticateToken(BearerTokenRequestAuthenticator.java:87)
        at org.keycloak.adapters.BearerTokenRequestAuthenticator.authenticate(BearerTokenRequestAuthenticator.java:82)
        at org.keycloak.adapters.RequestAuthenticator.authenticate(RequestAuthenticator.java:68)
        at org.keycloak.adapters.tomcat.AbstractKeycloakAuthenticatorValve.authenticateInternal(AbstractKeycloakAuthenticatorValve.java:203)
        at org.keycloak.adapters.tomcat.KeycloakAuthenticatorValve.authenticate(KeycloakAuthenticatorValve.java:50)
        at org.keycloak.adapters.tomcat.KeycloakAuthenticatorValve.doAuthenticate(KeycloakAuthenticatorValve.java:57)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:575)
        at org.keycloak.adapters.tomcat.AbstractKeycloakAuthenticatorValve.invoke(AbstractKeycloakAuthenticatorValve.java:181)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:800)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:806)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1498)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:748)


Perhaps you will be able to help?

Thanks,
Guy

**Comment by lbroudoux** [comment]
I think that default setup using cert auto generation is only suitable for local dev (if I remember well). I will try having a look at it on tomorrow and help you finish the setup.

**Comment by LevinGuy** [comment]
Thank you very much @lbroudoux

**Comment by lbroudoux** [comment]
That is was I suspected : `setup-tls-run.sh` is only for development mode having `docker.for.mac.localhost docker.for.win.localhost localhost localhost.localdomain` server names hard-coded in it.

I've redone a successful installation today and I'm gonna upgrade the `setup-microcks-apt.sh` script to automate this.

Please refer to the other issue.

**Comment by LevinGuy** [comment]
Hi @lbroudoux ,

Thank you very much for your help.
Going to try that today

Best Regards,
Guy

**Comment by LevinGuy** [comment]
Hi @lbroudoux ,
Still no luck :(

From scratch it is not working.
The Mickrocks UI is trying to redirect you to localhost:8180/auth.

Did some changes in the application properties but still getting the 401's :(

Btw,

Started recording the steps I did - perhaps it can be of service to others installing on an EC2:


1. Create an EC2
2. Connect to the EC2 using SSH
3. Run the following command to install docker, git and docker-compose:

`sudo amazon-linux-extras install -y docker && sudo service docker start && sudo usermod -a -G docker ec2-user && sudo chkconfig docker on && sudo yum install -y git && sudo curl -L https://github.com/docker/compose/releases/download/1.22.0/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose && sudo chmod +x /usr/local/bin/docker-compose && docker-compose version && sudo reboot`

4. Get the latest from github

`git clone https://github.com/microcks/microcks.git`

5. Go to the docker-compose directory:

`cd microcks/install/docker-compose`

6. Add execute rights to the setup microcks file:

`sudo chmod +x setup-microcks-apt.sh`

7. Execute the setup file:

`sudo ./setup-microcks-apt.sh EC2_IP_OR_DNS`

8. Start the dockers:

`docker-compose -f microcks.yml up -d`

9. Check that all the dockers are up and running:

`docker ps`

you should see 4 dockers:

CONTAINER ID        IMAGE                                              COMMAND                  CREATED             STATUS              PORTS                                            NAMES
3ba1d8fcdb84        lbroudoux/microcks:latest                          "/deployments/run-ja…"   2 minutes ago       Up 10 seconds       8778/tcp, 0.0.0.0:8080->8080/tcp, 9779/tcp       microcks
4087184b4a27        jboss/keycloak:10.0.1                              "/opt/jboss/tools/do…"   2 minutes ago       Up 2 minutes        0.0.0.0:8180->8080/tcp, 0.0.0.0:8543->8443/tcp   microcks-keycloak
960c2419c0a4        mongo:3.4.23                                       "docker-entrypoint.s…"   2 minutes ago       Up 2 minutes        27017/tcp                                        microcks-mongo
56c2ec0d5160        quay.io/microcks/microcks-postman-runtime:latest   "node app.js"            2 minutes ago       Up 2 minutes        3000/tcp   


Thanks,
Guy

**Comment by LevinGuy** [comment]
Maybe it has to do with me taking the 1.0.x branch?

**Comment by lbroudoux** [comment]
Oh yes ! The `1.0.x` branch is not stable for the moment... I have to work on the installation procedure upgrade following addition of Async API mocking. Please try the `master` branch.

**Comment by LevinGuy** [comment]
Hi @lbroudoux ,

A small fix suggestion: when running getting this error:

./setup-microcks-apt.sh: line 33: [: !=: unary operator expected

So it is better to put the ${VERSION} in quotes in lines 13 and 33:
if [ "${VERSION}" != "latest" ]; 

Thanks,
Guy

**Comment by lbroudoux** [comment]
Will apply it !

**Comment by LevinGuy** [comment]
also, a small change is needed in the port instead of 8180 it should be 8543 (since in the yaml file it is localhost:8543)

perl -i.bak -pe 's|#- KEYCLOAK_URL=https://localhost:8543/auth|- KEYCLOAK_URL=http://'${HOSTNAME}':8543/auth|' microcks.yml

**Comment by LevinGuy** [comment]
Hi @lbroudoux ,
a small question - should it be KEYCLOAK_URL=http://'${HOSTNAME}':8543/auth|' microcks.yml or KEYCLOAK_URL=http**s**://'${HOSTNAME}':8543/auth|' microcks.yml?

**Comment by lbroudoux** [comment]
Yes you’re right. My bad sorry...

**Comment by LevinGuy** [comment]
Hi @lbroudoux ,

sorry for all the questions/inconvenience. 
Installed from scratch again:

But still getting an issue with the keyclock when redirected from the mickrocks UI :(

![image](https://user-images.githubusercontent.com/8510784/84884101-f8455680-b099-11ea-8829-710b848453b5.png)

btw, added the following to the sh file:
apt-get install -y jq **docker.io** docker-compose

**Comment by lbroudoux** [comment]
No worries ! I already had this kind of issue but I thought it was my VM being in a bad mood ... restarting from scratch makes everything right again ...

What is your docker version ? Are you using an EC2 Ubuntu t2.small ?

**Comment by LevinGuy** [comment]
Hi @lbroudoux ,

docker -v
Docker version 19.03.6, build 369ce74a3c

Yes, this is ubuntu t2.small.

Restarted the EC2, and run the 
sudo docker-compose -f microcks.yml up -d

now it seems that the KeyCloak is not getting up:
![image](https://user-images.githubusercontent.com/8510784/84886237-d00b2700-b09c-11ea-953b-7862a849c6a8.png)

Thanks,
Guy

**Comment by lbroudoux** [comment]
Hi @LevinGuy,

sorry for long time responding but busy on many other things ... Looks like I've already got this issue with bad or malformed keystore or truststore. Please try re-generating your certs and restart everything. 

Procedure I will follow in such cases (from the `/install/docker-compose` directory on my VM):

```sh
$ docker-compose -f microcks.yml down
$ rm -rf keystore/
$ mkdir keystore
$ docker run -v $PWD/keystore:/certs -e SERVER_HOSTNAMES="$HOSTNAME" -it nmasse/mkcert:0.1
$ mv ./keystore/server.crt ./keystore/tls.crt
$ mv ./keystore/server.key ./keystore/tls.key
$ mv ./keystore/server.p12 ./keystore/microcks.p12
$ docker-compose -f microcks.yml up -d
```

In the mean time, I am gonna document the whole process from scratch starting at the AWS console. Hope it will help.

**Comment by lbroudoux** [comment]
Hi @LevinGuy !

There was some troubles with the scripts when generating certificates. I've re-tested everything from scratch on documented everything on https://medium.com/microcksio/install-microcks-on-aws-for-a-test-ride-bfb8bfd3feb2. 

Hope you'll find it useful ;-)

**Comment by LevinGuy** [comment]
Hi @lbroudoux ,

It is working, followed your video in the post (great post btw) and it is working great :)

Thank you very much

Guy
