### ISSUE TITLE
Allow reusing existing Keycloak realm - Maybe prefix Keycloak roles with microcks- ?

### ISSUE THREAD

**Issue by cs0978** [microcks/microcks#237]
We want to use an existing Keycloak realm where the roles admin and manager are already defined for another scope. This leads to conflicts with the Microcks roles.

We don't want to create a separate realm for Microcks since we have a quite complex User Federation / Identity Brokering setup.

Easy solution: Prefix the roles, e.g. microcks-admin, microcks-manager and so on
Gold solution: Make the roles configurable

**Comment by lbroudoux** [comment]
Hi @cs0978 ! 
That is a great idea I had in mind for some months ;-) I'm now available for implementing for next `1.0.0` release.
What about simply moving Microcks related roles from Realm roles to Clients/Applications roles ? I do think this is a best practice when having multiple clients defined into the same realm, will avoid renaming existing roles whilst still avoiding collisions with some other roles. 

What do you think ? I've got a working prototype for this and should be able to apply it in coming days.

**Comment by cs0978** [comment]
Hi @lbroudoux 
I think that would be the best solution to use client / application roles (not thought of that when writing the issue). Thanks.

**Comment by lbroudoux** [comment]
Implementation has been pushed to `1.0.x` branch as well as Help chart, OpenShift templates, Docker-config and operator have been upgraded. Let me know of you're able to test and if it suit your needs.

**Comment by cs0978** [comment]
I‘m on vacation for the next two weeks, but as soon as I‘m back at work I‘ll test it out.
To make the real name configurable is a good idea. At the moment we set it manually after deploying the template, and so since we‘re planning to switch to the operator that would be a nice feature.

**Comment by cs0978** [comment]
Works like expected... thank you.
