### ISSUE TITLE
Helm chart 1.0.0 ignore `async.enabled=false` and tries installing Kafka

### ISSUE THREAD

**Issue by dannyvargas23** [microcks/microcks#245]
Hi, when installing version 1.0.0 of microcks using helm chart I receive the following error.

Error: unable to build kubernetes objects from release manifest: [unable to recognize "": no matches for kind "Kafka" in version "kafka.strimzi.io/v1beta1", unable to recognize "": no matches for kind "KafkaTopic" in version "kafka.strimzi.io/v1beta1"]

**Comment by lbroudoux** [comment]
Hi !

Thanks for testing Microcks ! I think that you there's a little problem with currently published Chart ... it is still under review and the issue #240 not closed .... Would you try setting `features.async.kafka.install=false` and retrying the install ? Let me know the results.

Cheers,

**Comment by lbroudoux** [comment]
There was clearly a bug because `features.async.kafka.enabled=false` flag was ignored in certain cases. Fix this for final - updated - release. Thanks a lot @dannyvargas23 !
