### ISSUE TITLE
OpenAPI 3: Cannot create example from empty response

### ISSUE THREAD

**Issue by my-flow** [microcks/microcks#253]
I want to create examples with an [empty response body](https://swagger.io/docs/specification/describing-responses/). However, Microcks does not recognize the example at all, possibly because there is no matching response.

What's the best way to achieve this?

### Example
```
  openapi: 3.0.1
  info:
    title: sample
    version: '1.0'

  paths:
    /accounts/{accountId}:
      delete:
        parameters:
        - name: accountId
          in: path
          required: true
          schema:
            $ref: "#/components/schemas/accountId"
          examples:
            "Example 1":
              value: 396be545-e2d4-4497-a5b5-700e89ab99c0
        responses:
          204:
            $ref: "#/components/responses/NO_CONTENT_204"

  components:
    responses:
      NO_CONTENT_204:
        description:  No Content

    schemas:
      accountId:
        type: string
        format: uuid
      accountDetails:
        type: object
        properties:
          resourceId:
            type: string
```

**Comment by lbroudoux** [comment]
I think that current import logic is ignoring the sample if no `example` provided for the response.

Have you tried adding such an example called `Example 1` with empty value ?

**Comment by lbroudoux** [comment]
Hi @my-flow 
I tried this last one this week-end and seems to do the job: no content is actually returned. The `Content-Length` response header is not set ; while the `Content-Type` is set to `application/json`. Reading the RFC again : it does seem to be a violation having a content-type.

**Comment by lbroudoux** [comment]
Hi @my-flow 
Does it makes the trick for you ? Can I close the issue ?
Thanks,

**Comment by my-flow** [comment]
@lbroudoux Thanks, this work-around makes the trick for now. You can close this issue.
