### ISSUE TITLE
Add support for AsyncAPI schema validation of messages

### ISSUE THREAD

**Issue by lbroudoux** [microcks/microcks#258]
As part of the Addition of asynchronous API testing support (#257), we should be able to validate that an incoming message against an AsyncAPI contract.

**Comment by derberg** [comment]
@lbroudoux fyi there is a node.js library that one can use for messages validation. I know Microcks is on Java stack, but maybe https://github.com/WaleedAshraf/asyncapi-validator can as least give you some inspiration. Maybe @WaleedAshraf also has some suggestions basing on his experience writing and using such validator in production.

**Comment by WaleedAshraf** [comment]
We had to do AsyncAPI validation in Java in one service. What we did was, 

- use [AsyncAPI Validator](https://github.com/WaleedAshraf/asyncapi-validator) to convert/parse/de-ref the schema into JSON.
- Use [Jackson-databind](https://github.com/FasterXML/jackson-databind) to parse JSON in java lib
- use [json-schema-validator](https://github.com/networknt/json-schema-validator) to validate data.

Would be good to have if all this can be done in a single java library. 👍

**Comment by lbroudoux** [comment]
> Would be good to have if all this can be done in a single java library. 👍

Agreed! For now it is `io.github.microcks:microcks-util-1.1.0-SNAPSHOT` ;-) 

I think we start on similar bases. See how we're using it in https://github.com/microcks/microcks/blob/master/commons/util/src/test/java/io/github/microcks/util/asyncapi/AsyncAPISchemaValidatorTest.java

**Comment by lbroudoux** [comment]
Now done!

**Comment by jagadeeshkoka** [comment]
> We had to do AsyncAPI validation in Java in one service. What we did was,
> 
> * use [AsyncAPI Validator](https://github.com/WaleedAshraf/asyncapi-validator) to convert/parse/de-ref the schema into JSON.
> * Use [Jackson-databind](https://github.com/FasterXML/jackson-databind) to parse JSON in java lib
> * use [json-schema-validator](https://github.com/networknt/json-schema-validator) to validate data.
> 
> Would be good to have if all this can be done in a single java library. 👍

I am looking for java library which helps me to generate POJO out of AsynchApi-spec.yaml file and validates the message against that spec. 

And I didnt find any, and also I dont see any feature which will generate JSON schema out of Asynch-spec.yaml file in this library  [AsyncAPI Validator](https://github.com/WaleedAshraf/asyncapi-validator) or am I missing something here?

Please help to point a right direction, your help is very much appreciated.

Thanks You.

**Comment by WaleedAshraf** [comment]
@jagadeeshkoka I think you are looking for this. https://github.com/WaleedAshraf/asyncapi-validator#schema
