### ISSUE TITLE
Importing OpenAPI 3.0 spec not generating a mock endpoint

### ISSUE THREAD

**Issue by kivesCA** [microcks/microcks#275]
Hi, 

I'm importing an OpenAPI 3.0 spec JSON into microcks. The API is generated, but there is no mock endpoints in the mocks section, as in the screenshot below. 
![image](https://user-images.githubusercontent.com/72277152/95879566-8083f180-0d44-11eb-9df7-dd184380783b.png)

Here is the spec I am uploading. 

```
{
  "openapi": "3.0.2",
  "info": {
    "title": "mocktesting",
    "version": "1.0.0",
    "description": "mocktesting"
  },
  "paths": {
    "/experience/wipo/{pct}": {
      "get": {
        "responses": {
          "200": {
            "content": {
              "application/json": {
                "schema": {
                  "type": "string"
                },
                "examples": {
                  "Fake patent": {
                    "value": "\"some text\""
                  }
                }
              }
            },
            "description": "Success"
          }
        },
        "summary": "Gets patent info basaed on a PCT"
      },
      "parameters": [
        {
          "examples": {
            "fakeID": {
              "value": "1234"
            }
          },
          "name": "pct",
          "description": "patent identifier",
          "schema": {
            "type": "string"
          },
          "in": "path",
          "required": true
        }
      ]
    }
  }
}
```

**Comment by lbroudoux** [comment]
Hi @kivesCA and thanks for the question. 

To build complete mocks, Microcks is aggregating different example fragments as explained [here](https://microcks.io/documentation/using/openapi/#conventions).

In your case, you've got an example fragment called `Fake patent` for a response example. But your operation using a path parameter, you should also have a path parameter example named `Fake patent` that gives an example value corresponding to the expected response. 

The documentation [here](https://microcks.io/documentation/using/openapi/#path-parameters) is giving illustration on how to use path parameter examples.

Hope it helps,

**Comment by kivesCA** [comment]
Thank you so much this is exactly what I was looking for :)
