### ISSUE TITLE
Maven DependencyResolutionException while mvn spring-boot:run

### ISSUE THREAD

**Issue by RoopaVenkatesh** [microcks/microcks#28]
[ERROR] Failed to execute goal on project microcks: Could not resolve dependencies for project io.github.microcks:microcks:jar:0.5.1-SNAPSHOT: The following artifacts could not be resolved: com.smartbear.soapui:soapui:jar:5.1.1, gnu.cajo:cajo:jar:1.142: Could not transfer artifact com.smartbear.soapui:soapui:jar:5.1.1 from/to soapui (http://smartbearsoftware.com/repository/maven2): GET request of: com/smartbear/soapui/soapui/5.1.1/soapui-5.1.1.jar from soapui failed: Premature end of Content-Length delimited message body (expected: 11584277; received: 9071652 -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

Can someone please share the maven settings.xml?

**Comment by RoopaVenkatesh** [comment]
settings.xml in maven include proxy configuration and as per the below I have included a server declaration as well.    I am trying to set this up on Windows 10.

The repository you have configured requires authentication and Maven failed to provide the correct credentials to the server. In this case, make sure your ${user.home}/.m2/settings.xml contains a <server> declaration whose <id> matches the <id> of the remote repository to use. See the Maven Settings Reference for more details.

**Comment by lbroudoux** [comment]
Hi, 

I've checked SmartBear repository and it seems that `http://smartbearsoftware.com/repository/maven2/com/smartbear/soapui/soapui/5.1.1/` is public and does not require any credential.

Could you just check regular HTTP call like `curl -O http://smartbearsoftware.com/repository/maven2/com/smartbear/soapui/soapui/5.1.1/soapui-5.1.1.pom` to check how things are going?

Thanks,

**Comment by RoopaVenkatesh** [comment]
This issue is solved as I was trying it behind corporate proxy, with my personal hotspot its working fine.

Thank you.

**Comment by RoopaVenkatesh** [comment]
Maven DependencyResolutionException is solved but ends with the below error.


[INFO] org.mongodb.driver.cluster - Exception in monitor thread while connecting to server localhost:27017
com.mongodb.MongoSocketOpenException: Exception opening socket
        at com.mongodb.connection.SocketStream.open(SocketStream.java:63)
        at com.mongodb.connection.InternalStreamConnection.open(InternalStreamConnection.java:114)
        at com.mongodb.connection.DefaultServerMonitor$ServerMonitorRunnable.run(DefaultServerMonitor.java:128)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.ConnectException: Connection refused: connect
        at java.net.DualStackPlainSocketImpl.waitForConnect(Native Method)
        at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:85)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
        at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:589)
        at com.mongodb.connection.SocketStreamHelper.initialize(SocketStreamHelper.java:50)
        at com.mongodb.connection.SocketStream.open(SocketStream.java:58)
        ... 3 common frames omitted
[INFO] io.github.microcks.MicrocksApplication - Started MicrocksApplication in 11.105 seconds (JVM running for 265.892)
[INFO] -----Terminate batch job (Y/N)?

**Comment by lbroudoux** [comment]
Hi, 

documentation on how to build and run from sources is not yet complete. As mentioned on [README](https://github.com/microcks/microcks/blob/master/README.md), you must have a MongoDB 3.2 database running on your localhost for local building and run. `mvn spring:boot-run` is launching Microcks in local so it is expecting a running MongoDB on 27017 port.

For a quick local test if your do not have Kubernetes / OpenShift ar hand, `docker-compose` option should be ok on Windows and MacOS if you update the platform specific URL. Have a look and uncomment the correct line [here](https://github.com/microcks/microcks/blob/master/install/docker-compose/microcks.yml#L54).

Cheers,

**Comment by lbroudoux** [comment]
Network and setup issues.
