### ISSUE TITLE
chart requires kubeVersion: >=1.17.0 which is incompatible with Kubernetes v1.17.9-gke.6300

### ISSUE THREAD

**Issue by tstmrk** [microcks/microcks#281]
When I install microcks through the helm chart I get the following error.

`chart requires kubeVersion: >=1.17.0 which is incompatible with Kubernetes v1.17.9-gke.6300`

Where version 1.17.9-gke.6300 >=  than 1.17.0, but it is still saying the it's incompatible. 

We are running kubernetes at Google.

**Comment by lbroudoux** [comment]
Hum seems weird ... I don’t have a GCP Kube cluster at hand to check unfortunately. Though I don’t think 1.17 is a strong requirement ...

Have you tried getting the chart locally and removing this constraint to see what’s going on ?

**Comment by tstmrk** [comment]
Thanks for your suggestion. I fixed it by fetching the chart and commenting out the kubeVersion. in Chart.yaml.

**Comment by lbroudoux** [comment]
Gréât. Let us know how your tests are going.
