### ISSUE TITLE
version 1.0.0 install fails on macOS with docker-compose

### ISSUE THREAD

**Issue by slessard** [microcks/microcks#283]
I followed the installation instructions at https://microcks.io/documentation/installing/docker-compose/. Specifically I...

1. Run `git clone https://github.com/microcks/microcks.git`
1. Run `cd microcks `
1. Run `git checkout 1.0.0`
1. Run `cd install/docker-compose`
1. Verify that Microcks.yml has KEYCLOAK_URL=https://docker.for.mac.localhost:8543/auth
1. Run `./setup-tls-run.sh`

At this point I see some warnings coming from (I believe) the mkcert container about the CA not being installed in either the system or Java trust store.

After a while longer all of the images are downloaded and containers have started, but the Microcks-keycloak container always exits immediately. The logs for that container are as follows.

> Added 'admin' to '/opt/jboss/keycloak/standalone/configuration/keycloak-add-user.json', restart server to load user
-b 0.0.0.0 -Dkeycloak.import=/microcks-keycloak-config/microcks-realm-sample.json
/opt/jboss/tools/docker-entrypoint.sh: line 156: DB_ADDR: unbound variable

Two issues:
1. What value should DB_ADDR have?
1. the Keycloak documentation at https://hub.docker.com/r/jboss/keycloak/ doesn't say it supports MongoDB

Docker version 19.03.13, build 4484c46d9d

OS and machine info...
ProductName:	Mac OS X
ProductVersion:	10.15.7
BuildVersion:	19H2
Darwin TD-C02XR8YEJG5J 19.6.0 Darwin Kernel Version 19.6.0: Mon Aug 31 22:12:52 PDT 2020; root:xnu-6153.141.2~1/RELEASE_X86_64 x86_64
Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz

**Comment by lbroudoux** [comment]
Hi !
You should not have to set `DB_ADDR` as Keycloak default to use embedded H2 database. These are the first logs lines of my Keycloak container:

```
Added 'admin' to '/opt/jboss/keycloak/standalone/configuration/keycloak-add-user.json', restart server to load user
-b 0.0.0.0 -Dkeycloak.import=/microcks-keycloak-config/microcks-realm-sample.json
=========================================================================

  Using Embedded H2 database

=========================================================================

Creating HTTPS keystore via OpenShift's service serving x509 certificate secrets..
HTTPS keystore successfully created at: /opt/jboss/keycloak/standalone/configuration/keystores/https-keystore.jks
```

Why you are not having those lines is the question ... ?
Maybe you could check the hash of your Keycloak image ?

```
$ docker inspect --format='{{index .RepoDigests 0}}' jboss/keycloak:10.0.1                                                                                               
jboss/keycloak@sha256:0bf1fc2fde730a34bae4bd47ca29877977910a436265238a8d99caeb1558ab82
```

I've checked my docker version and running an older than yours but it's hard to think that could be the root cause...

```
$ docker -v
Docker version 19.03.5, build 633a0ea
```

Anyway, retrying all of these just highlight an issue with some recent updates of browser regarding security policy, it may happen that you encounter endless reload of page (every 5 sec) due to Keycloak JS adapter. Will open another issue to work on that. Let us know of your findings.

**Comment by lbroudoux** [comment]
BTW we're very close to `1.1.0` release and I advise you starting using the `master` branch instead of `1.0.0` tag. 
Fix for the issue regarding page reaload will also be applied there. See #286 for tracking this.

**Comment by slessard** [comment]
I have the same hash of keycloak that you have

    ➞  docker inspect --format='{{index .RepoDigests 0}}' jboss/keycloak:10.0.1                                   [git:3e79b33] ✖  
    jboss/keycloak@sha256:0bf1fc2fde730a34bae4bd47ca29877977910a436265238a8d99caeb1558ab82

I chose the 1.0.0 tag because as a first time user I wanted to avoid potential pitfalls of nightly builds and use a release that I thought would be guaranteed to work. I'm still not sure what the problem is with 1.0.0 but I did notice some potential for version inconsistencies. The quay.io/microcks/microcks:nightly container has the "nightly" tag. The quay.io/microcks/microcks-postman-runtime:latest container has the "latest" tag.

I just tried with the latest from master and I still have the same problem. I will attach the entire console output from my host machine.

**Comment by slessard** [comment]
[microcks-latest-failed.txt](https://github.com/microcks/microcks/files/5410448/microcks-latest-failed.txt)

**Comment by lbroudoux** [comment]
Yes I saw there was inconsistencies on 1.0.0 branch ... sorry. Master is clean and works well : retried it today and got some confirmations from other users. Will check your log ASAP.

**Comment by Jessfer68** [comment]
I have the same problem but on linux, i'm using the master branch

**Comment by hguerrero** [comment]
The new version of the docker-compose install should have addressed this problems. Can you take a look and check if the problem is still there? 

https://microcks.io/documentation/getting-started/

**Comment by slessard** [comment]
I verified that today's master branch works up to logging in and viewing the microcks UI. I did not try anything beyond that

**Comment by hguerrero** [comment]
Thanks for the update @slessard Do you think we can close this issue?

**Comment by slessard** [comment]
yes, I think you can close this issue
