### ISSUE TITLE
Add a FALLBACK dispatcher for REST mocks

### ISSUE THREAD

**Issue by gkleij** [microcks/microcks#287]
As mentioned on Gitter, is it possible to make a new dispatcher type for a GET request with value('s) as part of the URL (per example `/api/v1/account/:firstname/:lastname`, where `firstname` and `lastname` are variables), where the dispatcher first checks all available specific values and if none of them apply, a default response is used.
Kind regards, 
gkleij

**Comment by lbroudoux** [comment]
Hi @gkleij !

Implementation of `FALLBACK`dispatcher now done and in `master` branch. 
Here's below a screenshot that shows and explain how to use it.

<img width="1373" alt="Capture d’écran 2021-01-06 à 17 11 07" src="https://user-images.githubusercontent.com/1538635/103791009-3a3be700-5042-11eb-8cca-cf15abdc33d0.png">

Would you be able to give it a try?
