### ISSUE TITLE
Partial test failure display inconsistent results in inititial result overview

### ISSUE THREAD

**Issue by ChristianHauwert** [microcks/microcks#289]
Hi Laurent,

While using the in-build test feature (http-runner), the initial result overview is not accurate. In case of the PET-STORE example, focussing on operation 'petId' it shows 2 failures while it should be 1. As soon as the full-results link is clicked it shows the results in a proper fashion (1 fail, 1 pass. as expected).

See for more details:
[microcks-defect - test result.docx](https://github.com/microcks/microcks/files/5475398/microcks-defect.-.test.result.docx)

Kind regards, Chris

**Comment by lbroudoux** [comment]
Thanks for opening this issue. A fix is on its way ;-)

**Comment by ChristianHauwert** [comment]
Nice! Thnx for the quick follow-up!
