### ISSUE TITLE
Include instructions on how to setup Microcks on a server

### ISSUE THREAD

**Issue by nmasse-itix** [microcks/microcks#29]
Current documentation explains how to setup Microcks on a docker client instance (on the developer workstation). However, it would be nice to have also instructions on how to set it up on a dedicated server using Docker Compose. 

To make it work, it is required to update the URLs:
```
$ hostname -f 
ec2-35-180-113-122.eu-west-3.compute.amazonaws.com
$ cd microcks/install/docker-compose/
$ cp keycloak-realm/microcks-realm-sample.json keycloak-realm/microcks-realm-sample.json.bak
$ apt-get install jq
$ jq '.applications |= map(if .name == "microcks-app-js" then .redirectUris = [ "http://ec2-35-180-113-122.eu-west-3.compute.amazonaws.com:8080/*" ] else . end) | .sslRequired |= "none"' keycloak-realm/microcks-realm-sample.json.bak > keycloak-realm/microcks-realm-sample.json
$ perl -i.bak -pe 's|KEYCLOAK_URL=http://localhost:8180/auth|KEYCLOAK_URL=http://ec2-35-180-113-122.eu-west-3.compute.amazonaws.com:8180/auth|' microcks.yml
$ sudo docker-compose -f microcks.yml up -d
```

**Comment by nmasse-itix** [comment]
If you plan to deploy it on AWS, you can pick a `t2.micro` instance, based on AMI `Ubuntu Server 16.04 LTS (HVM), SSD Volume Type - ami-1960d164`. Like this you can stay on your free tier ! 

Do not forget to edit your Security Group to allow port 8080 and 8180 !

**Comment by lbroudoux** [comment]
Done ! Thanks @nmasse-itix
