### ISSUE TITLE
Broken Link to CAR API YAML file

### ISSUE THREAD

**Issue by intltechventures** [microcks/microcks#290]
On this page:
https://microcks.io/documentation/using/openapi/

The "here" link to the CAR API, in this sentence: "The specification file in YAML format can be found here."

Returns a 404 Not Found for this URL
https://github.com/microcks/microcks/blob/master/src/test/resources/io/github/microcks/util/openapi/cars-openapi.yaml

**Comment by lbroudoux** [comment]
Thanks for opening this issue! We forgot to change the link to sample after refactoring and move it to `webapp` component. Now fixed!
