### ISSUE TITLE
Display all services and APIs by default

### ISSUE THREAD

**Issue by aoudiamoncef** [microcks/microcks#297]
Hi @lbroudoux,

I'm using Microcks and I have a small issue with the UI.

![image](https://user-images.githubusercontent.com/22281426/99951144-e3be6600-2d7d-11eb-9539-a04050e934b0.png)

I have 7 APIs and by default it doesn't show anything, I need to change filtering by domain to name and do a search. When I left and back to this page, it's completely reset it's state and I should do the same previous step to find my API.

It could be very interesting to improve this behavior. 

Thanks

**Comment by lbroudoux** [comment]
HI @aoudiamoncef,

This is definitely not the expected behavior ... All services and APIs should be there by default and then you should be able to apply filter on them. I suspect there should be a problem with querying the number of pages and APIs in repository. Could you pleases turn on the network traces in the browser to see if any call is failing ?

Thanks,

**Comment by aoudiamoncef** [comment]
You are right. I'm using docker-compose setup in a remote server.
![microcksFail](https://user-images.githubusercontent.com/22281426/99952384-dbffc100-2d7f-11eb-89b7-e65eec322d46.png)

**Comment by lbroudoux** [comment]
Are you using the latest `1.1.0` version of the container image ? This make me think of an old bug we had because of a failing query when no labels where already defined ... 

Maybe remove cached image and try refreshing it ?

**Comment by aoudiamoncef** [comment]
![Uploading image.png…]()

**Comment by aoudiamoncef** [comment]
![image](https://user-images.githubusercontent.com/22281426/99953378-76143900-2d81-11eb-8f44-9c67f0442f4c.png)

**Comment by lbroudoux** [comment]
Hum .... Could you also please check the logs in the microcks pod ? I'll try reproduce on my side. I regularly test starting from scratch on Kubernetes and have not seen that behavior. Will try on a fresh docker-compose install.

**Comment by lbroudoux** [comment]
Hi @aoudiamoncef,

Just setup everything from scratch and it seems to work fine.
Here's the Microcks version I'm using (the latest that was produced on Saturday):

<img width="548" alt="Capture d’écran 2020-11-23 à 17 21 06" src="https://user-images.githubusercontent.com/1538635/99987174-6f50ea80-2db0-11eb-8991-992267394678.png">

And the network requests:

<img width="975" alt="Capture d’écran 2020-11-23 à 17 21 25" src="https://user-images.githubusercontent.com/1538635/99987206-78da5280-2db0-11eb-837d-9ddc94f75c2d.png">

As I'm looking at your network screenshot above, I wonder why you do not have a URL using `https://` ? The `setup-tls-run.sh` scripts takes care of generating self-signed certificates for dev usage only and you have to use `https://` endpoint ..

Could you please check that point ?

**Comment by aoudiamoncef** [comment]
I'll check all the configurations on the remote server and I'll be back ASAP.

**Comment by lbroudoux** [comment]
Hi @aoudiamoncef ! Any news on that issue ? Were you able to check the HTTPS endpoint ?

Thanks,

**Comment by aoudiamoncef** [comment]
Hi @lbroudoux,

I didn't have access to remote server, I'm still waiting, I'll update this issue with the results. 

Thanks

**Comment by lbroudoux** [comment]
Hi @aoudiamoncef !

Any news on your tests ? We did tremendous simplification to the docker-compose installation last weeks...

Let us know how it is going on your side.

**Comment by aoudiamoncef** [comment]
Hi @lbroudoux,

I'll test the new setup ASAP. 

Thanks

**Comment by aoudiamoncef** [comment]
Hi @lbroudou,

I'm back, we are going to have a complete reinstallation in a new environment using the [Quarkus based variant](https://github.com/Apicurio/apicurio-studio/blob/master/distro/quarkus/docker-compose/Readme.md)

Stay tuned.

Thanks

**Comment by aoudiamoncef** [comment]
I'm agree with you, feel free to close this issue.
