### ISSUE TITLE
Decouple the backend keycloak URL from the frontend

### ISSUE THREAD

**Issue by hguerrero** [microcks/microcks#298]
Currently the web frontend application is using the configuration coming from the API using a the same information that the backend service is using[1]. However this becomes a problem when you want to access different endpoints for each application. So it would be suggested o use at least 2 different properties for this. It could be that you can default to reuse the same if one is not specified, but you need to have the option to use a different one. 

[1] https://github.com/hguerrero/microcks/blob/d99660720a4959931d39225010d91200e9340b72/webapp/src/main/java/io/github/microcks/web/KeycloakConfigController.java#L43

**Comment by lbroudoux** [comment]
Seems to be a duplicate to #119

**Comment by hguerrero** [comment]
If you want to follow the conversation in that issue, I'm fine closing this one.
