### ISSUE TITLE
Local installation based on podman and podman-compose

### ISSUE THREAD

**Issue by dmarrazzo** [microcks/microcks#299]
docker is really annoying.
Can you help me running it with podman and podman-compose?

I tried replacing `docker` with `podman` in the `setup-tls-run.sh`.
It seem running correctly but I noticed that `keystore` folder is empty.

Then I get this:
```sh
> podman ps
CONTAINER ID  IMAGE                             COMMAND  CREATED      STATUS                 PORTS                                                                   NAMES
61970afd928c  quay.io/microcks/microcks:latest           2 hours ago  Up About a minute ago  0.0.0.0:8180->8080/tcp, 0.0.0.0:8543->8443/tcp, 0.0.0.0:8080->8080/tcp  microcks
f561bf9c948d  k8s.gcr.io/pause:3.2                       2 hours ago  Up About a minute ago  0.0.0.0:8180->8080/tcp, 0.0.0.0:8543->8443/tcp, 0.0.0.0:8080->8080/tcp  ecd18370738c-infra
```

**Comment by lbroudoux** [comment]
Hey ! That is an excellent idea ! 
However I do not have a Linux box at hand cause only running Mac box for the moment ...

If the `keystore` folder is empty, that should mean that the first step of generating certs is failing ...
Have you tried to start only with this and check if it succeeds generating stuffs ?
Just running `podman run -v $PWD/keystore:/certs -t nmasse/mkcert:0.1` ??

**Comment by dmarrazzo** [comment]
Hi @lbroudoux ,

strangely enough mkcert lead to the following error:

```
ERROR: failed to save CA key: open /certs/rootCA-key.pem: permission denied
```

However, I workaround this skipping the file system mapping and coping the certs dir:

```
podman run -t nmasse/mkcert:0.1
podman cp 55d0abf2137c:/certs/ keystore/
```

I found the certificates in `_data` folder, so I had to move the files:

```
cd keystore
mv _data/* .
```

Finally, I was able to run the remaining part of the script:
```
mv ./keystore/server.crt ./keystore/tls.crt
mv ./keystore/server.key ./keystore/tls.key
mv ./keystore/server.p12 ./keystore/microcks.p12
podman-compose -f microcks.yml up -d
```

Here the running containers:

```
❯ podman ps
CONTAINER ID  IMAGE                                             COMMAND      CREATED         STATUS             PORTS                                                                   NAMES
27665a53372d  quay.io/microcks/microcks:latest                               15 minutes ago  Up 15 minutes ago  0.0.0.0:8180->8080/tcp, 0.0.0.0:8543->8443/tcp, 0.0.0.0:8080->8080/tcp  microcks
f047a621214c  quay.io/microcks/microcks-postman-runtime:latest  node app.js  16 minutes ago  Up 16 minutes ago  0.0.0.0:8180->8080/tcp, 0.0.0.0:8543->8443/tcp, 0.0.0.0:8080->8080/tcp  microcks-postman-runtime
08637b08d697  k8s.gcr.io/pause:3.2                                           16 minutes ago  Up 16 minutes ago  0.0.0.0:8180->8080/tcp, 0.0.0.0:8543->8443/tcp, 0.0.0.0:8080->8080/tcp  d3ec8289e093-infra
```

When I try to launch the Web UI, I'm not able to connect to it.
I've noticed that the browser is redirected on the following URL:
`https://docker.for.mac.localhost:8543/auth/realms/microcks/protocol/openid-connect/auth?client_id=microcks-app-js&redirect_uri=http%3A%2F%2Flocalhost%3A8080%2F&state=e6ff2f83-2990-42ad-99b8-ca848cfa889a&response_mode=fragment&response_type=code&scope=openid&nonce=817663ea-3eb3-4a46-9c11-15fe969966aa`

In the javascript console I can read the following:

```
location.origin: http://localhost:8080 main.9e6d967ef0d0d6d7817a.js:1:2185135
[Microcks launch] Running locally so disabling Keycloak checkLogin Iframe to respect modern browser restrictions main.9e6d967ef0d0d6d7817a.js:1:2185229
XHRGEThttp://localhost:8080/api/keycloak/config
[HTTP/1.1 200  3ms]

This error page has no error code in its security info
```

**Comment by lbroudoux** [comment]
Good, you've got a workaround for 1st step 😉 

However the Keycloak and MongoDB pods are not launched. Also we're using the `docker.for.mac.localhost` alias to be able to reach Keycloak fomr withing the browser and from within the microcks container. Don't know if podman is supporting the same kind of aliases ... ❓

**Comment by dmarrazzo** [comment]
Hi @lbroudoux ,

it looks that podman does not support network alias, but podman-compose put all the image on the same pod so they should be able to communicate to each other.

However I was able to fix the volume permission problem that was causing the failure of `mkcert` and `mongo` as well.

Basically, **podman** for security reason cannot access to the host filesystem (this is enforced by SELinux).
To relax the constraint I issued the following command:
```
mkdir -p ~/tmp/microcks-data
sudo chcon -Rt svirt_sandbox_file_t ~/tmp/microcks-data
```

So now all is up and running:

```
❯ podman ps
CONTAINER ID  IMAGE                                             COMMAND               CREATED         STATUS             PORTS                                                                   NAMES
11fa927f79a6  docker.io/library/mongo:3.4.23                    mongod                4 minutes ago   Up 4 minutes ago   0.0.0.0:8180->8080/tcp, 0.0.0.0:8543->8443/tcp, 0.0.0.0:8080->8080/tcp  microcks-mongo
7312d2d9b1e4  quay.io/microcks/microcks:latest                                        25 minutes ago  Up 25 minutes ago  0.0.0.0:8180->8080/tcp, 0.0.0.0:8543->8443/tcp, 0.0.0.0:8080->8080/tcp  microcks
57e53440ed0d  docker.io/jboss/keycloak:10.0.1                   -b 0.0.0.0 -Dkeyc...  25 minutes ago  Up 25 minutes ago  0.0.0.0:8180->8080/tcp, 0.0.0.0:8543->8443/tcp, 0.0.0.0:8080->8080/tcp  microcks-keycloak
6a80b51e8c36  quay.io/microcks/microcks-postman-runtime:latest  node app.js           25 minutes ago  Up 25 minutes ago  0.0.0.0:8180->8080/tcp, 0.0.0.0:8543->8443/tcp, 0.0.0.0:8080->8080/tcp  microcks-postman-runtime
17476ce74091  k8s.gcr.io/pause:3.2                                                    25 minutes ago  Up 25 minutes ago  0.0.0.0:8180->8080/tcp, 0.0.0.0:8543->8443/tcp, 0.0.0.0:8080->8080/tcp  2f382b50455b-infra
```

But I cannot access to the WebUI yet.
Same problem of the alias.

Do you have an idea of how to workaround this?

BTW I guess that when you run in OpenShift you cannot rely on this alias, maybe I should go down the same road.

Thank you

**Comment by lbroudoux** [comment]
Yes you're right. When running on Kubernetes we rely on Ingress or Routes : the operator or Helm chart take care of setting everything. 

Have you tried replacing the alias with just localhost in the microcks.yaml file ? I imagine that podman may bind container ports to the host on so maybe localhost could do the trick ?

**Comment by lbroudoux** [comment]
Hi @dmarrazzo !

We've got a contributor that push a `podman-compose` adaptation of the docker-compose that can be used to run Microcks as root or as rootless pods ! Please check #304 as it should now fulfill your request ;-) 

Do not hesitate sending any feedback or comments!
