### ISSUE TITLE
Adding support for importing referenced schema files

### ISSUE THREAD

**Issue by lbroudoux** [microcks/microcks#302]
As of today, the AsyncAPI and OpenAPI importers are not able to import external schema files that are referenced within specification file. Begin able to do that is mandatory in order to support a broader scope of this specifications and if we want to have the ability to manage advance serialization formats like Apache Avro.

**Comment by skirankumars31** [comment]
Hei @lbroudoux , Is it possible to provide a sample openapi and asyncapi with external schema file references ?. It would save a lot of time for people trying this
