### ISSUE TITLE
Provide safe defaults when loading a collection that has no version number

### ISSUE THREAD

**Issue by nmasse-itix** [microcks/microcks#31]
Currently, if a Postman collection is loaded into Microcks without the version number annotation in the description field, the service is loaded but unusable because of the missing version. 

I think we should provide safe defaults for such cases if a version number cannot be found :
- either reject the service with an error message
- or add a default version
- or allow service without version number

**Comment by prouwens** [comment]
Well I find having a version is good anyway, but yes I agree having a message telling so would be good and we should catch the exception as it s causing a null pointer exception.

**Comment by lbroudoux** [comment]
Safe default is not really "safe"' as it opens the door for collisions when importing service definition. I thing going with a clear and explicit error message regarding `Missing version property in the collection` is the right way to go.

**Comment by nmasse-itix** [comment]
With the error message, would it be possible to have a short help message explaining the required syntax "version=x.y - something" and where to set it (in the postman collection properties, field "description") ?

**Comment by lbroudoux** [comment]
@nmasse-itix I think having this kind of message, displayed on the line corresponding to Job for service: 

<img width="292" alt="version-property-misssing" src="https://user-images.githubusercontent.com/1538635/41521879-25bd65e0-72d4-11e8-81b2-6efcec06d55d.png">

What do you think?

**Comment by jcordes73** [comment]
According to https://schema.getpostman.com/json/collection/v2.1.0/docs/index.html, Postman supports a version field starting from Collections 2.1 (maybe). Could we use this one, instead?

**Comment by lbroudoux** [comment]
That's a really good point and a definitive enhancement for Postman Collection! For now, we only support `2.0` Collection format but it deserves an enhancement to support `2.1`.

**Comment by forceedge01** [comment]
Where exactly does one specify a version? I've just created a postman collection to test microcks out - I am getting the error but not much what to do about it (on the web and your resources).
