### ISSUE TITLE
Add resouce request and limits to Kafka

### ISSUE THREAD

**Issue by hguerrero** [microcks/microcks#314]
When deploying using strimzi, the kafka resource is not setting limits.

**Comment by lbroudoux** [comment]
Thanks for reporting this issue ! Any ideas of what could be typical default values for them ?

**Comment by hguerrero** [comment]
It will depend on the load, but I think 2Gi for broker and 1Gi for ZK, and 500mi for CPU should do.

**Comment by lbroudoux** [comment]
Now done
