### ISSUE TITLE
Disable the profile review in Keycloak

### ISSUE THREAD

**Issue by nmasse-itix** [microcks/microcks#32]
When logging in Microcks for the first time using the embedded Keycloak and the OpenShift IdP, the user is asked to confirm the retrieved information. 

This step is not very useful and quite confusing for the user. I think we should configure Keycloak to bypass it. 

It's not very useful because the entered information are not verified in any way. 
And it's confusing because the commonly agreed behavior for social login/registration is to map automatically the user profile information without asking the user to check. 

In the `Microcks` Realm: 
 - go to `Authentication`
 - pick the `First Broker Login` flow
 - set `Review Profile (review profile config)` to `DISABLED`

**Comment by lbroudoux** [comment]
Do you have any idea on how to easily inject that parameter into `microcks-realm-config.json` file ? It seems that disabling profile review makes all the authentication flows explicitely mandatory within file ...

**Comment by lbroudoux** [comment]
Postponing this after 0.7.0 as there some concerns around auto-keycloak configuration

**Comment by lbroudoux** [comment]
Won't fix as Keycloak identity provider configuration is now out of Microcks installation scope. Default does not require any action.
