### ISSUE TITLE
Add resource limits for microcks pod

### ISSUE THREAD

**Issue by willemm** [microcks/microcks#321]
The Helm chart currently sets resource limits for all deployments, except for the microcks deployment (spring container) itself.
Also, there is no place to add any custom settings (using something like adding a 'toyaml' bit where you then can add any kind of config in the values.yaml)

This makes it impossible to run this chart on any cluster that has default resourcelimits in place (at least where these are smaller than what microcks needs), and I imagine it also interferes with kubernetes scheduling, which uses those requests/limits to make scheduling decisions.

**Comment by lbroudoux** [comment]
Thanks for the issue! This is definitely something we have to add to Helm chart and Operator. Thanks for the reminder, planning it for next release. Is it a blocker on your side?

**Comment by willemm** [comment]
It's not a blocker anymore; I managed to find a workaround.  Thanks for the quick reply.

**Comment by lbroudoux** [comment]
Now available for Helm chart installation and Operator.
