### ISSUE TITLE
XPath expressions with functions are incorectly parsed as function expressions

### ISSUE THREAD

**Issue by robvalk** [microcks/microcks#329]
The Xpath with namesapces example https://microcks.io/documentation/using/advanced/templates/#xml-body-xpath-expression doesn't actually work. The Xpath `local-name()` function caused Microcks to interpret the variable expression as a function expression instead.

**Comment by lbroudoux** [comment]
Thanks a lot for reporting this issue! Will have a look at it as soon as possible.

**Comment by lbroudoux** [comment]
Thanks a lot for the fix!

**Comment by lbroudoux** [comment]
Fix should now be available into the `latest` container image.
