### ISSUE TITLE
Detail of event type service should display correct Kafka endpoint

### ISSUE THREAD

**Issue by hguerrero** [microcks/microcks#332]
In the service and APIs detail page for _event_ type services the information of the endpoint (in the case of kafka for example) is showing an incomplete value.

If the broker is being provisioned by microcks using strimzi, for example, it needs to reflect the bootstrap server endpoint created by strimzi. For example: `microcks-kafka-kafka-bootstrap.127.0.0.1.nip.io` instead of just only the domain.

![image](https://user-images.githubusercontent.com/1001939/106322636-20a64d80-6244-11eb-9a41-dcb085f151c9.png)

**Comment by lbroudoux** [comment]
Hi Hugo! Is the installation was done with the Operator? What is the Kubernetes distrib? Vanilla or OpenShift?

**Comment by lbroudoux** [comment]
Could you also drop here the Kafka portion of the CR?

**Comment by lbroudoux** [comment]
This will require an Operator update. See https://github.com/microcks/microcks-ansible-operator/issues/28

**Comment by lbroudoux** [comment]
Fixed in Operator (Helm chart was already behaving correctly).
