### ISSUE TITLE
Properties page does not refresh after save (service type event)

### ISSUE THREAD

**Issue by hguerrero** [microcks/microcks#333]
When changing the frequency value from `10s` to `30s` and click on the save button, the information is updated but the page is not reloaded/refreshed still showing the old value. If you navigate out and then get back, the value is updated.

**Comment by lbroudoux** [comment]
Actually this was intended to work that way to give people a chance to get back to original configuration in case they were not sure of that they were doing... But this behavior seems to be more confusing than helping ;-)

**Comment by lbroudoux** [comment]
Maybe `Current Dispatching Properties` is not the correct term and we should update to `Original`? So that people may figured out that they can go back to original when hitting the `Reset` button on the form?
