### ISSUE TITLE
There is no way to "pause" a mock service of type event

### ISSUE THREAD

**Issue by hguerrero** [microcks/microcks#334]
In the case of an event API, there is no way to _pause_ the service to stop sending messages. 

Suggested options could be, a general pause button for the whole service, or at the operation level. Another option could be to use the frequency value and select 0s to mark it as disabled or paused.

**Comment by lbroudoux** [comment]
Setting the frequency value to `0s` would actually un-schedule the publication of mock messages for the operation. That's because no async minion is actually configured to manage this frequency. So like this idea 😉 

We shall also associate this value to an `Inactive` label marker on the UI.

**Comment by lbroudoux** [comment]
I did some modifications to implement this.

Here's the new button you'll have on Operation properties form to disable mocks for this operation:

<img width="607" alt="Capture d’écran 2021-02-03 à 09 38 38" src="https://user-images.githubusercontent.com/1538635/106720483-d33f2d00-6603-11eb-90d5-71d904ff8a23.png">

Then below the button to re-activate them. You'll see that frequency selection is disabled when not active, it is enabled once the green button hit:

<img width="608" alt="Capture d’écran 2021-02-03 à 09 38 48" src="https://user-images.githubusercontent.com/1538635/106720598-f23dbf00-6603-11eb-93ee-bb4210a408b3.png">

Finally, the status marker for the operation on the service summary page:

<img width="719" alt="Capture d’écran 2021-02-03 à 09 39 03" src="https://user-images.githubusercontent.com/1538635/106720643-fff34480-6603-11eb-8908-994d32e6bc2e.png">
