### ISSUE TITLE
The link to download an event type specification returns f.txt file instead

### ISSUE THREAD

**Issue by hguerrero** [microcks/microcks#335]
When clicking on the link to download the spec for a service of type _event_ the API service returns a header that overrides the file name:

```
HTTP/1.1 200
Access-Control-Allow-Headers: *
Access-Control-Allow-Methods: POST, PUT, GET, OPTIONS, DELETE
Access-Control-Allow-Origin: *
Access-Control-Max-Age: 3600
Connection: keep-alive
Content-Disposition: inline;filename=f.txt
Content-Length: 1872
Content-Type: text/yaml
Date: Fri, 29 Jan 2021 20:35:27 GMT
Server: nginx/1.19.1
Strict-Transport-Security: max-age=15724800; includeSubDomains
Vary: Origin
Vary: Access-Control-Request-Method
Vary: Access-Control-Request-Headers
```

The `Content-Disposition` headers is using `f.txt` as the file making Firefox browser to save the file in the incorrect format.

**Comment by lbroudoux** [comment]
Hey! Thanks for the issue, that's a good pick. Actually the problem seems just to be for YAML files ... I think that is because Content-Type or extension are not registered as default within Spring so it default to `f.txt`. Will override this.
