### ISSUE TITLE
If one expression of the template for the response is wrong, it does not give any advise

### ISSUE THREAD

**Issue by jonathanvila** [microcks/microcks#349]
When adding a sample message with a wrong expression, the mock will simply not expand any expression on the message and a Java exception will appear in the log of the running container. 

No message saying there's an issue appears anywhere.

**Comment by lbroudoux** [comment]
Thanks for opening this issue. 

You're right : currently there's no user feedback to inform of incorrect message templating issues.

That would be a nice enhancements. Need to think about it but definitely a valuable information to display to user.
