### ISSUE TITLE
Response template expressions can not be added manually when integrated with Apicurio

### ISSUE THREAD

**Issue by jonathanvila** [microcks/microcks#350]
I have created a sample API with one endpoint ,with a sample response.
In order to have a dynamic response, that sample response json includes microcks expressions.
``` json 
{
"date":"{{ now(yyyyMMdd-HHmmss) }}",
"uptime":"{{ randomInt(1000, 8000) }}"
}
```

But then this example will appear on the documentation, which we don't want
![image](https://user-images.githubusercontent.com/1836434/108352291-ebf43900-71e6-11eb-9ac1-50fa56484108.png)

So I was expecting to add "good" examples to Apicurio, but templated examples to Microcks..... is there any way ?

**Comment by lbroudoux** [comment]
Yeah I see what you mean ... These are ugly in documentation ...
Problem is that there is no "good" or "bad" examples, all of them are treated equally by tooling.

What I use to tell people is to not lose sight that examples should help users to understand business semantics so do not abuse of dynamic functions in example.

Often, I recommend keeping a full static example with real life value and then other examples with functions if it makes sense.
