### ISSUE TITLE
AsyncAPi Test fails when defaultContentType is not set in the spec

### ISSUE THREAD

**Issue by 195858** [microcks/microcks#369]
It happens here, results in a NullPointerException if defaultContentType is omitted.

https://github.com/microcks/microcks/blob/c18eb14ba7afb4951fe79b12d66a85d8e0d43f1c/minions/async/src/main/java/io/github/microcks/minion/async/AsyncAPITestManager.java#L253

Omitting the default content type seems to be allowed, the Async API specs validate in the playground.

**Comment by lbroudoux** [comment]
Yes you're right. `defaultContentType` is not mandatory in the spec. Will fix that !

**Comment by lbroudoux** [comment]
Fix is now available in latest container image.
