### ISSUE TITLE
AsyncAPI - Strimzi topic name does not support underscore character

### ISSUE THREAD

**Issue by mouachan** [microcks/microcks#371]
Seems that asynapi topic name is a concatenation of title, version and "channels name" asyncapi custom resource attributes, thoses attributes are separated  by an underscore. 

KafkaTopic.kafka.strimzi.io "Price_0.1.4_price" is invalid:
        metadata.name: Invalid value: "Price_0.1.4_price": a DNS-1123 subdomain
        must consist of lower case alphanumeric characters, '-' or '.', and must
        start and end with an alphanumeric character (e.g. 'example.com', regex
        used for validation is
        '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')
![Capture d’écran 2021-03-24 à 16 09 43](https://user-images.githubusercontent.com/12033900/112334048-68cd7380-8cbb-11eb-8eda-c21c90163eec.png)

**Comment by lbroudoux** [comment]
This push a big +1 in favor of switching to Kebab style notation @hguerrero I agree 😉

**Comment by lbroudoux** [comment]
Now changed!
