### ISSUE TITLE
gRPC support

### ISSUE THREAD

**Issue by molteninjabob** [microcks/microcks#372]
Would love to know if/when you might be adding support for grpc communication. Thanks!

**Comment by lbroudoux** [comment]
Hi @molteninjabob, thanks for asking this question !

gRPC is one protocol we consider adding to Microcks as it follows the spirit of strongly typed and contractualized interface definition language. 

Actually I did some research on how to implement this and it should involve some low level librairies as we obviously do not want to go through the stub code-generation phase. It should be all dynamically interpreted from the proto file as we are doing we OpenAPI for the like.

However we do have a major concern for now : how one can specify examples (request/response) using gRPC? Microcks API mocking is all driven by real-life examples as we think that it's the cornerstone for useful documentation and endpoint mocking. As of today, illustrating gRPC contract with examples is not covered by the spec afaik... so it would mean having another file/asset/artifact to rely on to get this precious examples? What format could we use to represent the actual textual value of those? JSON/YAML? Maybe everything could be put together within a Postman Collection?

Please join-in the conversation if you have any idea or existing process around gRPC sampling and mocking.

**Comment by lbroudoux** [comment]
Hi @molteninjabob,

I've done some tests lately now that #400 is on its way... Here are below some teasing captures to illustrate that GRPC support is on its way for mocking unary calls at the moment. Please let me know if interested in playing a bit with it, I would be very interested to get your feedback on this!!

<img width="491" alt="Capture d’écran 2021-05-27 à 13 47 06" src="https://user-images.githubusercontent.com/1538635/119827209-2ca3d280-bef9-11eb-864f-afe26e7bad30.png">
<img width="1133" alt="Capture d’écran 2021-05-27 à 13 48 03" src="https://user-images.githubusercontent.com/1538635/119827220-2f9ec300-bef9-11eb-97d3-e486a4fd3f67.png">

**Comment by molteninjabob** [comment]
@lbroudoux I would actually be very interested in trying this out!

**Comment by lbroudoux** [comment]
Great! I've also starting the testing part ;-) Let me cleanup and commit everything this weekend. 

We'll keep in touch next week so that I'll give you explanations on how to use it.

**Comment by lbroudoux** [comment]
Hi @molteninjabob 

Initial contribution has been committed in `master` branch and `quay.io/microcks/microcks:latest` container image now contains the feature. As discussed last week, here are below some informations on how to activate, use and evaluate it.

First thing: the installation. At the moment, the docker-compose installation method will be the easier to setup. So start with [Installing with docker-compose](https://microcks.io/documentation/installing/docker-compose/) but before starting everything, you'll need to add a new port binding to access the `9090` port from the container that is the one exposing HTTP/2 - GRPC mocking. You'll need to add such line in `docker-compose.yml`:

```yaml
    container_name: microcks
    ports:
      - "8080:8080"
      - "9090:9090"
```

You can now start the container. You can check that GRPC is running looking at the `microcks` containers log and spotting this line:

```
14:10:57.274  INFO 28691 --- [      main] i.g.m.util.grpc.GrpcServerStarter        : GRPC Server started on port 9090
```

Next thing: importing a new Service. Because we rely on #400 feature, this is a 2 step process. 

1 - First import a `.proto` file that will handle the Service definition (name, package, operations). You can use https://github.com/microcks/microcks/blob/master/webapp/src/test/resources/io/github/microcks/util/grpc/hello-v1.proto as a quickstart, just uploading it **without** ticking the *Secondary Artifact* box. See below:

<img width="668" alt="Capture d’écran 2021-06-01 à 09 15 33" src="https://user-images.githubusercontent.com/1538635/120283585-a05c2b80-c2bb-11eb-885c-3cd6d3d007a2.png">

2 - Then import a Postman Collection that will handle your mock examples dataset. Example requests and responses must be described using JSON. You can use https://github.com/microcks/microcks/blob/master/webapp/src/test/resources/io/github/microcks/util/grpc/HelloService.postman.json as a quickstart, uploading it **with** the *Secondary Artifact* box ticked. See below:

<img width="668" alt="Capture d’écran 2021-06-01 à 09 15 50" src="https://user-images.githubusercontent.com/1538635/120283885-f5983d00-c2bb-11eb-814d-af4c7a820a94.png">

This will merge the examples definition into previously loaded GRPC/Protobuf service. You should now be able to see in your repository the complete service definition as illustrated in screenshots in above comments in thread.

There's a final step from here to get something working: configure a dispatcher. For GRPC, we'll use the `JSON_BODY` dispatcher as [introduced here](https://microcks.io/documentation/using/advanced/dispatching/#json-body-dispatcher). To setup the dispatcher you'll need to access the **Edit Operation Properties** page in Microcks console and set your dispatching rules as illustrated below:

<img width="1540" alt="Capture d’écran 2021-06-01 à 09 17 06" src="https://user-images.githubusercontent.com/1538635/120284504-98e95200-c2bc-11eb-82fb-597a294d7d59.png">

On the `HelloService`, we're are looking the `firstname` attribute. Once saved, you can use your mocks.

I'm using the BloomRPC client to quickly check everything is running.

<img width="1271" alt="Capture d’écran 2021-06-01 à 09 36 37" src="https://user-images.githubusercontent.com/1538635/120284833-f8476200-c2bc-11eb-8be6-544063bf29f5.png">

> Note: this is just a simple example but [Templating / Dymamic content](https://microcks.io/documentation/using/advanced/templates/) is also available for GRPC mocking. 

Eager to have your feedback on all of this!

**Comment by molteninjabob** [comment]
@lbroudoux I'm brand new to Microcks, but I'm excited to see what this could look like for us. Give me a couple days to work through getting it set up and I'll post here if I have any questions or run into any issues.

**Comment by molteninjabob** [comment]
@lbroudoux I ran through the steps you outlined, but immediately ran into issues when the grpc server did not start as you referenced here:
`14:10:57.274  INFO 28691 --- [      main] i.g.m.util.grpc.GrpcServerStarter        : GRPC Server started on port 9090`

That line never appeared. In fact there is no reference to grpc at all in the output. I continued on adding the .proto sample and the postman secondary artifact, the import jobs ran and the files were scanned, but the service was never created. 

Here are the logs from the microcks service and some screenshots:

`exec java -javaagent:/opt/agent-bond/agent-bond.jar=jolokia{{host=0.0.0.0}},jmx_exporter{{9779:/opt/agent-bond/jmx_exporter_config.yml}} -XX:+UseParallelGC -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -XX:MinHeapFreeRatio=20 -XX:MaxHeapFreeRatio=40 -XX:+ExitOnOutOfMemoryError -cp . -jar /deployments/app.jar`
`I> No access restrictor found, access to any MBean is allowed`
`Jolokia: Agent started with URL http://172.20.0.5:8778/jolokia/`
`  .   ____          _            __ _ _`
` /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \`
`( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \`
` \\/  ___)| |_)| | | | | || (_| |  ) ) ) )`
`  '  |____| .__|_| |_|_| |_\__, | / / / /`
` =========|_|==============|___/=/_/_/_/`
` :: Spring Boot ::        (v2.2.5.RELEASE)`
`18:06:49.621  INFO 1 --- [      main] i.g.microcks.MicrocksApplication         : Starting MicrocksApplication on 89be73f49ee3 with PID 1 (/deployments/app.jar started by ? in /deployments)`
`18:06:49.625 DEBUG 1 --- [      main] i.g.microcks.MicrocksApplication         : Running with Spring Boot v2.2.5.RELEASE, Spring v5.2.4.RELEASE`
`18:06:49.626  INFO 1 --- [      main] i.g.microcks.MicrocksApplication         : The following profiles are active: prod`
`18:06:52.516 DEBUG 1 --- [      main] i.m.c.u.i.l.InternalLoggerFactory        : Using SLF4J as the default logging framework`
`18:06:52.890  INFO 1 --- [      main] org.mongodb.driver.cluster               : Cluster created with settings {hosts=[mongo:27017], mode=SINGLE, requiredClusterType=UNKNOWN, serverSelectionTimeout='30000 ms', maxWaitQueueSize=500}`
`18:06:52.987  INFO 1 --- [ongo:27017] org.mongodb.driver.connection            : Opened connection [connectionId{localValue:1, serverValue:1}] to mongo:27017`
`18:06:52.991  INFO 1 --- [ongo:27017] org.mongodb.driver.cluster               : Monitor thread successfully connected to server with description ServerDescription{address=mongo:27017, type=STANDALONE, state=CONNECTED, ok=true, version=ServerVersion{versionList=[3, 4, 23]}, minWireVersion=0, maxWireVersion=5, maxDocumentSize=16777216, logicalSessionTimeoutMinutes=null, roundTripTimeNanos=1428600}`
`18:06:53.431  INFO 1 --- [      main] i.g.microcks.config.WebConfiguration     : Starting web application configuration, using profiles: [prod]`
`18:06:53.433  INFO 1 --- [      main] i.g.microcks.config.WebConfiguration     : Web application fully configured`
`18:06:55.173  INFO 1 --- [      main] i.g.microcks.MicrocksApplication         : Started MicrocksApplication in 6.25 seconds (JVM running for 7.526)`
`18:07:40.539 DEBUG 1 --- [080-exec-2] i.g.m.web.KeycloakConfigController       : Returning 'microcks' realm config, for http://localhost:18080/auth`
`18:07:41.794 DEBUG 1 --- [080-exec-4] i.g.m.web.VersionInfoController          : Returning '1.3.0-SNAPSHOT' version information`
`18:07:41.839 DEBUG 1 --- [080-exec-5] i.g.microcks.web.ServiceController       : Retrieving available services labels...`
`18:07:41.969  INFO 1 --- [080-exec-5] org.mongodb.driver.connection            : Opened connection [connectionId{localValue:2, serverValue:2}] to mongo:27017`
`18:07:42.153  INFO 1 --- [080-exec-7] o.k.adapters.KeycloakDeployment          : Loaded URLs from http://keycloak:8080/auth/realms/microcks/.well-known/openid-configuration`
`18:07:42.161  INFO 1 --- [080-exec-6] o.k.adapters.KeycloakDeployment          : Loaded URLs from http://keycloak:8080/auth/realms/microcks/.well-known/openid-configuration`
`18:07:42.249 DEBUG 1 --- [080-exec-7] i.g.microcks.web.ServiceController       : Counting services...`
`18:07:42.265 DEBUG 1 --- [080-exec-6] i.g.microcks.web.ServiceController       : Getting service list for page 0 and size 20`
`18:07:49.909 DEBUG 1 --- [080-exec-9] io.github.microcks.web.JobController     : Getting job list for page 0 and size 20`
`18:07:49.912 DEBUG 1 --- [080-exec-8] io.github.microcks.web.JobController     : Counting jobs...`

![image](https://user-images.githubusercontent.com/11509961/120370924-68141780-c2d2-11eb-8eaf-e358326a32f7.png)

**Comment by lbroudoux** [comment]
Hum... seems to be an issue with the container image that is not up-to-date. Let me check that tonight.

**Comment by lbroudoux** [comment]
When creating the importers on proto and postman files, you should point to the raw.githubusercontent url.

**Comment by molteninjabob** [comment]
> When creating the importers on proto and postman files, you should point to the raw.githubusercontent url.

Updated to use the raw.

**Comment by lbroudoux** [comment]
Yep, I think this is a side effect of the bad container image version.
Just retest this morning and the image from quay.io is correct - you should have an older image that has been previously pulled. After having removed it and pull the fresher one, you should have:

```sh
$ docker inspect --format='{{index .RepoDigests 0}}' quay.io/microcks/microcks:latest                                                                                                                          
quay.io/microcks/microcks@sha256:fd052cd732bfada940c6f31f4382a368ca7f74ce052878852ddbdaef46ee2d5a
```

With the following specific lines in startup logs:

Spring version 2.4.5:
```
 .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::                (v2.4.5)
```

and GRPC feature:

```
06:51:15.981  INFO 1 --- [      main] i.g.m.util.grpc.GrpcServerStarter        : GRPC Server started on port 9090
```

**Comment by molteninjabob** [comment]
@lbroudoux Ok, this appears to be working with the example you provided! I'll take some time to try and set this up with some of our proto definitions. I'll let you know how it goes.

**Comment by molteninjabob** [comment]
@lbroudoux Well, I've tried several of our own proto files, but they've all resulted in a parsing error. Here's the error message I'm getting:

`17:11:46.546 DEBUG 1 --- [080-exec-4] io.github.microcks.web.JobController : Removing job with id 60b7bb8bd49dcb3124f225c1`
`17:11:46.558 DEBUG 1 --- [080-exec-5] io.github.microcks.web.JobController : Getting job list for page 0 and size 20`
`17:12:02.031 DEBUG 1 --- [080-exec-2] i.g.m.web.UploadArtifactController : Content type of authv1.proto is application/octet-stream`
`17:12:02.032 INFO 1 --- [080-exec-2] i.g.m.u.MockRepositoryImporterFactory : Found a syntax = proto3 pragma in file so assuming it's a GRPC Protobuf spec to import`
`protoc-jar: protoc version: 3.11.4, detected platform: linux-x86_64 (linux/amd64)`
`protoc-jar: embedded: bin/3.11.4/protoc-3.11.4-linux-x86_64.exe`
`protoc-jar: executing: [/tmp/protocjar7466642068792190358/bin/protoc.exe, --proto_path=/tmp, --descriptor_set_out=/tmp/microcks-1622653922032.artifact.pbb, microcks-1622653922032.artifact]`
`17:12:02.075 ERROR 1 --- [080-exec-2] i.g.m.util.grpc.ProtobufImporter : Exception while parsing Protobuf schema file /tmp/microcks-1622653922032.artifact`
`java.io.FileNotFoundException: /tmp/microcks-1622653922032.artifact.pbb (No such file or directory)`
`at java.base/java.io.FileInputStream.open0(Native Method)`
`at java.base/java.io.FileInputStream.open(FileInputStream.java:219)`
`at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)`
`at io.github.microcks.util.grpc.ProtobufImporter.<init>(ProtobufImporter.java:81)`
`at io.github.microcks.util.MockRepositoryImporterFactory.getMockRepositoryImporter(MockRepositoryImporterFactory.java:85)`
`at io.github.microcks.service.ServiceService.importServiceDefinition(ServiceService.java:127)`
`at io.github.microcks.web.UploadArtifactController.importArtifact(UploadArtifactController.java:112)`

**Comment by lbroudoux** [comment]
Hum... would have been too easy... but we now have a baseline for improvements 😁 

Seems like the protoc compiler fails and that's just the regular protoc that I embed and use at import time.

Would you be able to share some failing proto file? Of course after having anonymised/removed sensitive data. 

Thanks,

**Comment by molteninjabob** [comment]
Sorry for the delayed responses. Here's a sample proto that should be clean enough.
[authv1.txt](https://github.com/microcks/microcks/files/6587089/authv1.txt)

**Comment by lbroudoux** [comment]
My bad ... I have forgotten to include standard protobuf libraries. Once fixed, I am able to import your proto definition.

<img width="1720" alt="Capture d’écran 2021-06-03 à 10 31 45" src="https://user-images.githubusercontent.com/1538635/120613959-0630ea80-c457-11eb-89cd-501a15e85803.png">

I've pushed the fix and it should be available in few minutes on `quay.io/microcks/microcks:latest`. Be sure to refresh your local images ;-)

**Comment by molteninjabob** [comment]
Ok, that worked! I'll continue playing with it and let you know.

**Comment by molteninjabob** [comment]
@lbroudoux This is very promising! I do have a question. We are a Go shop and have a rather large proto repo where we store our proto definitions, but some common elements are separated out into their own files. For example: 

```
syntax = "proto3";

package authproto;

option go_package="weavelab.xyz/protorepo/auth/authproto";

import "weavelab.xyz/protorepo/shared/uuid.proto";

service AuthV2 {
    rpc User(shared.UUID) returns (UserResponse) {}
}

message UserResponse {
    UserProfileResponse Profile = 1;
    repeated UserAccess Access = 2;
}

message UserProfileResponse {
    shared.UUID UserID = 1;
    string Username = 2;
    UserType Type = 3;
    string FirstName = 4;
    string LastName = 5;
}
```

This proto file imports a separate proto definition `uuid.proto` that simply looks like this:

```
syntax = "proto3";

package shared;

message UUID {
    bytes Bytes = 1;
}
```
I've simplified this example a bit, but hopefully it's not too contrived. How should we handle proto files that are split out like this?

**Comment by lbroudoux** [comment]
Thanks for feedback. I have to think about it but I already have written a ReferenceResolver for the AsyncAPI part. It should be somewhat reusable to gather all references proto files...

**Comment by lbroudoux** [comment]
Hi @molteninjabob 

I've made some tests and we should be able to include local dependencies. What I mean by "local" is those that live in the same repository (considering HTTP location) as the main proto file.

To illustrate this, I've made the following test: imagine that we have a `https://myrepo.myorg.com/myproject` repo with 2 files like this:
```
/src
  /shared
    uuid.proto
  main.proto
```

`main.proto` having a `import "shared/uuid.proto"` directive.

I wanted to know if that suits your way to organize dependencies or if you have more complex organization? Considering the Go way to resolve dependencies, could they be spanned on multiple Git repos? How do you manage versioining in that case? Let me know if those questions are relevant...

**Comment by molteninjabob** [comment]
@lbroudoux I apologize or being MIA. I had a couple days of vacation and a new hire last week, and haven't been able to re-visit this until now. I will take a look at the changes you made as well as trying to build out examples in Postman for use with one of our proto definitions and update you with my findings.

**Comment by lbroudoux** [comment]
No worries 😉 For now I do not have implemented anything else just prototyped.

However I have implemented the testing part since our last chat: you can now make Microcks call an external GRPC endpoint and it will check if operations and protobuf serialization are implemented as described. 

Take time to read and think about my previous questions, I'll try to get some time to code things by the end of the week.

**Comment by lbroudoux** [comment]
Hi @molteninjabob 

Just have implemented a dependency resolution mechanism. You can test it using the `https://github.com/microcks/microcks/blob/master/webapp/src/test/resources/io/github/microcks/util/grpc/goodbye-v1.proto` artifact file that has a dependency on `shared/uuid.proto` file.

**Comment by lbroudoux** [comment]
Event if dependency mechanism can be later on enhanced, I'm closing this issue for now as we now have something stable to release. Let's open new issues to keep bringing new idea of improvement on gRPC support!
