### ISSUE TITLE
Copy button for Topic is copying wrong text

### ISSUE THREAD

**Issue by hguerrero** [microcks/microcks#377]
When clicking in the `copy` button in the AsyncAPI service it copies the text without the _kebab_ format.

Expected:
`UsersignedupAvroAPI-0.1.2-user-signedup`

Actual:
`UsersignedupAvroAPI-0.1.2-user/signedup`

**Comment by lbroudoux** [comment]
This is a regression after implementing #364 and differenciation on destination name generation.
