### ISSUE TITLE
Why my response body is not being fully displayed 

### ISSUE THREAD

**Issue by matheussbernardo** [microcks/microcks#382]
In my mock the body response is totally showing
but when I do a request in the mock it is cut in the middle of my JSON

**Comment by lbroudoux** [comment]
Hi @matheussbernardo ! Thanks for trying out Microcks.

**Comment by lbroudoux** [comment]
However if you have trouble with Zulip we can still use GH. It's just that much more people are monitoring Zulip and may be of great help...
