### ISSUE TITLE
Add possibility to mock unmapped requests in OpenAPI

### ISSUE THREAD

**Issue by ex324** [microcks/microcks#386]
We're using Microcks for a while now and would support this feature to create/edit example responses inside Microcks.

We have the issue that for some verbs, especially DELETE, an empty response (e.g. 204 No Content or 202 Accepted) is defined.
In the OpenAPI specs (https://swagger.io/docs/specification/describing-responses/), it's said in this case, just leave / omit the content property (and therefore have no examples).

In this case, no mocks for these verbs are generated. So it would help us to have the option to create manual (in our case empty) mocks.

As I understand your OpenAPI Importer correctly, you create a list of Request/Response Pairs only for Responses with content/examples.

My idea is you create Request/Response Pairs for unmapped Requests too but with empty Responses and save them.
In the UI, you can add these unmapped Requests to the Mock (with a button or so) and edit the according empty response (e.g. add a response code, payload).

I'm actually looking into it and try to contribute to this feature.

**Comment by lbroudoux** [comment]
Hi @ex324 

We had a talk through Zulip on this but find useful to replicate here elements of our conversation...

On April 21th:

> We're working on something different that can help you... Let’s call it « multi-artifacts support ». The goal is to be able to have 1 OpenAPI doc + other Postman collections enriching the same mock definition. That way you may have a full OpenAPI compliant doc for your 204 issue and then addition request / response samples in Postman collection to handle mocking cases. What do you think ? Could this help your use-case ?

Since then we have pursued thoughts around this idea and it is now tracked into #400. This will be one of the major item of the upcoming `1.3.0` Milestone.

Did you have time looking at any implementation of your solution? This could be a nice complement.

**Comment by ex324** [comment]
Hi @lbroudoux 

Sorry for the delay. Was on vacations and had a new assignment and for that reason no time to work on this issue.
I added a pull request for my idea.

I think, it will be possible to enhance this solution to allow a permanent possibility to edit responses (or even requests).
At least it would allow us to simply add 'empty' responses to the mocks without adding additional Postman collections.

**Comment by saritapol13** [comment]
@lbroudoux In our API documentation also there are PATCH requests with 204 No Content. Here the examples are not mocked given that there is no response body to it

**Comment by akadnikov** [comment]
Hi! Will it be merged or implement another solution?
