### ISSUE TITLE
Show request query string on every Test summary

### ISSUE THREAD

**Issue by jonathanvila** [microcks/microcks#390]
Now there are few elements shown in every test executed , but the full URL with params sent is not visible

![image](https://user-images.githubusercontent.com/1836434/115836902-4d6b9a80-a418-11eb-84b3-fd9582130e8f.png)

**Comment by lbroudoux** [comment]
Thanks Jonathan for the suggestion, seems totally legit. Don't know why it's not displayed already ;-) 
Though I don't think we persist this information into database, this could be easily re-computed for display.
