### ISSUE TITLE
JsonPath assertions from SOAPUI are not working

### ISSUE THREAD

**Issue by efpee** [microcks/microcks#399]
I imported the HelloAPI sample SOAPUI project and modified it so the mock (in microcks) always returns the 'Gavin' response. 

The SOAPUI testcase has some assertions, 1 of them is on the greeting message. When running the test from microcks using SOAP_UI Runner, both tests pass. Checking the full results I verified that the response to the 'David request' does indeed return:

```
{
	'name':'Gavin',
	'greeting':'Hello Gavin !'
}
```
so the assertion should fail.

**Comment by lbroudoux** [comment]
Hi @efpee!

Thanks for reporting this issue. I've tried reproducing it and see the same behavior. Actually, it seems that we're missing something on the SoapUI side to be able to realize the JsonPath matching... See the following warning in logs:

```
log4j:WARN No appenders could be found for logger (com.eviware.soapui.SoapUI).
log4j:WARN Please initialize the log4j system properly.
16:13:50,524 ERROR [TestAssertionRegistry] Missing assertion for type [JsonPath Match]
```
I know that we exclude a bunch of conflicting libraries from SoapUI dependencies. Maybe we've excluded the wrong one! Another option is that our internal version of SoapUI being too old (we're using the `5.1.1` at the moment) and needing to be upgraded to allow this assertion.

To be investigated.

**Comment by efpee** [comment]
Thanks for coming back so quickly, I was using SoapUI 5.6.0 for the tests.

**Comment by lbroudoux** [comment]
This is now tracked into #405 that is planned for the upcoming `1.3.0` Milestone.

**Comment by lbroudoux** [comment]
Hi! Just investigate a bit on that and it appears that the `JsonPath Match` assertion from the sample was not yet present into SoapUI `5.1.1`. I'm in the middle of upgrading to `5.6.0` on `master` branch so expect something working to validate in few days ;-)

**Comment by lbroudoux** [comment]
Now that #405 is addressed, `JsonPath Match` assertions are working and I've polished some error display in the UI. Check on the screenshot below.

<img width="1395" alt="Capture d’écran 2021-05-21 à 16 53 30" src="https://user-images.githubusercontent.com/1538635/119157664-b82ee680-ba55-11eb-8b64-a2b4204f79af.png">

New container image tagged `latest` should be available within minutes for validating if you want. Let me know and do not hesitate reopening the issue if something goes wrong.
