### ISSUE TITLE
Add the full hostname URL to the Mocks URL

### ISSUE THREAD

**Issue by hguerrero** [microcks/microcks#40]
To simplify the copy and paste of the testing URLs, add the serving hostname to the "Mocks URL" under the services operations.

**Comment by lbroudoux** [comment]
This issue is being considered when implementation #5 - the refactoring of GUI using PatternFly. Stay tuned.

**Comment by lbroudoux** [comment]
This is now solved and present into `new-ux-0.7.x` branch. Consider having a try by using `new-ux-latest` tag on the container image of building from source using this branch.
