### ISSUE TITLE
GraphQL support

### ISSUE THREAD

**Issue by lbroudoux** [microcks/microcks#401]
Would love to add support for GraphQL mocking and testing. Please vote and share ideas or practices on how you want that to be implemented!

**Comment by niraveen** [comment]
I would love to contribute on this idea.

**Comment by lbroudoux** [comment]
Hey @niraveen! That would be awesome! 

I think we got all the prerequisites now in Microcks engine to develop that one. I think we should extend multi-artifacts support for managing GraphQL in the same way we've done with GRPC. If you have take a look at it yet, please check https://microcks.io/documentation/using/grpc/

The main artifact could of course be the Schema definition and then we could use some Postman Collection if we want a simple mapping engine for finding responses OR we could maybe rely on a plain JSON dataset and elaborate some dynamic data fetching mechanism OR ...

Do not hesitate sharing any ideas here or joining the Zulip Chat at https://microcksio.zulipchat.com.

**Comment by lbroudoux** [comment]
Hey @niraveen,

Have you started thinking / working on this issue? I spent some time thinking about it this week-end and have some ideas about it... Let me know if still interested. I think it's the next big thing for Microcks and should be easily feasible.

Cheers,

**Comment by niraveen** [comment]
I have cleared the problems in my dev environment. I think loading up of schema definition(primary artifact) along with postman collection (secondary artifact) will work. This can also work when microcks supports integration with APICurio GraphQL.

**Comment by lbroudoux** [comment]
Hey @blackPanther39 !

Did some investigations and I think that [graphql-java](https://www.graphql-java.com/) could be a nice fit for:
* Initial parsing of GraphQL SDL And discovery of queries and mutation with dispatch rules and criteria (invocation arguments),
* Parsing of incoming GraphQL query to retrieve:
  * query or mutation name to find operation,
  * invocation arguments values to compute dispatch criterion,
  * response field selection to later filter out response content using Jackson for example.

Postman Collection graphql example holding is quite nice and could be a great support for queries and mutations example specification.

**Comment by blackPanther39** [comment]
yep started using it.(graphql-java)

**Comment by lbroudoux** [comment]
I pushed some initial work on GraphQL support on `1.5.x` branch today! Time to target a release !

@blackPanther39 I have made some tests related to the mocking controller part. If you're still on it and want to go further, you could deal with the import part. Of course, we'd had to set some conventions regarding stuffs related to `dispatcher`, `dispatcherRules` and `dispatcherCriteria` as these are the link between the import and the mocking part.
