### ISSUE TITLE
Mocked API from Apicurio not listed in Microcks APIs section

### ISSUE THREAD

**Issue by haf-tech** [microcks/microcks#416]
I have integrated Microcks with Apicurio in OpenShift. After mocking an API in Apicurio I see in the Dashboard, that I have 1 REST services. But in the APIs page I still do not see the imported REST service.
What is missing?

Importing manually the REST/OpenAPI json file works

* OCP 4.5
* Microcks Operator 1.2.1
* Apicurio Studio 0.2.48.Final

I see in the logs of Microcks

```
[INFO] io.github.microcks.util.MockRepositoryImporterFactory - Found an openapi: 3 pragma in file so assuming it's an OpenAPI spec to import
[INFO] io.github.microcks.service.ServiceService - Having imported 1 services definitions into repository
```

What is missing? A permission issues?

**Comment by lbroudoux** [comment]
Hi @haf-tech, thanks for raising this issue.

Hum... I think it should be a permission issue ... Would you check the browser Developer Console when accessing the APIs page? I suspect that your user (nor the microcks-serviceaccount used from Apicurio) do not have the required permissions. Also it would be great introspecting the JWT Bearer with a service like jwt.io to see what are the actual roles retrieved from Keycloak ...

Let me know your findings.

**Comment by haf-tech** [comment]
@lbroudoux good point with the dev console. The first issue was a 401, cause I added in the `MicrocksInstall` `privateURL` field the k8s internal URL to Keycloak. After switching to the public URL I receive now 403.
An excerpt of the JWT

```
{
  "jti": "7f2012fc-b30d-48cb-91b3-6aec65f2a229",
  "exp": 1620916623,
  "nbf": 0,
  "iat": 1620916323,
  "iss": "https://apicurio-studio-auth.....appdomain.cloud/auth/realms/microcks",
  "aud": "microcks-app-js",
  "sub": "7f7db457-43ce-447e-ac1e-5cf1da38928b",
  "typ": "Bearer",
  "azp": "microcks-app-js",
  "nonce": "c204acc5-3eed-4ce4-96ca-1ae6374fedd4",
  "auth_time": 1620915511,
  "session_state": "844aa295-d943-4851-9700-42e178f69c50",
  "acr": "1",
  "allowed-origins": [
    "https://my-microcksinstall-apicurio...appdomain.cloud"
  ],
  "resource_access": {},
  "scope": "openid email profile",
  "email_verified": false,
  "preferred_username": "admin"
}
```

I have a central Keycloak and installed the realm using the [default template](https://github.com/microcks/microcks/blob/master/install/docker-compose/keycloak-realm/microcks-realm-sample.json). 
I logged in with the default Microcks user (admin) - but I do not find them in the Keycloak realms?

Any further details hints? :-)

**Comment by lbroudoux** [comment]
Could you check that the ´user´ role from microcks-app client is set as default role for realm users? It appears that sometimes Keycloak is skipping that part when importing a realm definition... Not having this role assigned may lead to 403 responses.

**Comment by haf-tech** [comment]
one of the main problem is the old keycloak version in the Apicurio Auth, 4.1.0.Final. otherwise the import of the config files would work
Do you know how to update the version or use an existing one? like the one from Microcks? :-)

**Comment by lbroudoux** [comment]
Sometimes ago I succeed making Microcks using Apicurio Keycloak but for that I added the realm elements manually (import did not work). In theory, you should be able to do the opposite and make Apicurio reuse Microcks Keycloak but I hadn't try this yet...

Aside the broken import, is it working now after having competed elements in the realm?

**Comment by haf-tech** [comment]
no, I stopped the manual adjustments into the Keyloak of Apicurio, due the fact, that both versions are different and not all elements/fields are visible/same - for me is not clear, which elements/roles etc are relevant and important.

The idea, to integrate Apicurio into the Microcks Keycloak was also in my mind, but was unclear how change the Apicurio config.
Generally the integration between Apicurio and Microcks regarding Keycloak could be improved. Are there any enhancement planned? Before I spent more time in figuring out the right configuration :)

**Comment by lbroudoux** [comment]
Yeah definitely: enhancements are planned!

First step at the moment is to write an operator for easy setup of Apicurio. This is a WIP that you may track here: https://github.com/lbroudoux/apicurio-studio-operator

Then we will provide some kind of meta operator that orchestrates both Apicurio and Microcks one to realise that setup.

However I don't think we will have something in the month to come... In the meantime I could try send you detailed instructions on how to realise this setup. And we could try validate this one out together ;-)

**Comment by haf-tech** [comment]
nice point with the Operator!

And also nice, if you could provide any details, I am happy to validate in my environments! :-)
