### ISSUE TITLE
Support for "repeat" in mock templating

### ISSUE THREAD

**Issue by hguerrero** [microcks/microcks#430]
Having a way to template mocks is great!

However, when dealing with mocks that need to produce arrays, it can be difficult to deal with many object templates. Could it be possible to define a way to repeat the content of an example several times using the template functions?

**Comment by lbroudoux** [comment]
Ideally the loop/repeat syntax should preserve initial message structure .ie. still produce a valid JSON.
Do you have a syntax proposition on mind?
