### ISSUE TITLE
Invalid parameter: redirect_uri

### ISSUE THREAD

**Issue by a459787545** [microcks/microcks#434]
![image](https://user-images.githubusercontent.com/16471580/121774577-91c41d00-cbb5-11eb-9789-bf8f2080a1ac.png)

docker-compose.yml:

version: '2'

services:
  mongo:
    image: mongo:3.4.23
    container_name: microcks-db
    volumes:
      - "~/tmp/microcks-data:/data/db"

  keycloak:
    image: jboss/keycloak:10.0.1
    container_name: microcks-sso
    ports:
      - "18080:8080"
    environment:
      KEYCLOAK_USER: "admin"
      KEYCLOAK_PASSWORD: "admin"
      KEYCLOAK_IMPORT: "/tmp/microcks-realm.json"
      KEYCLOAK_FRONTEND_URL: "http://10.1.1.11:18080/auth"
    volumes:
      - "./keycloak-realm/microcks-realm-sample.json:/tmp/microcks-realm.json"

  postman:
    image: quay.io/microcks/microcks-postman-runtime:latest
    container_name: microcks-postman-runtime

  app:
    depends_on:
      - mongo
      - keycloak
      - postman
    image: quay.io/microcks/microcks:latest
    container_name: microcks
    ports:
      - "8080:8080"
      - "9090:9090"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017
      - SPRING_DATA_MONGODB_DATABASE=microcks
      - POSTMAN_RUNNER_URL=http://postman:3000
      - TEST_CALLBACK_URL=http://microcks:8080
      - SERVICES_UPDATE_INTERVAL=0 0 0/2 * * *
      - KEYCLOAK_URL=http://keycloak:8080/auth
      - KEYCLOAK_PUBLIC_URL=http://10.1.1.11:18080/auth

**Comment by a459787545** [comment]
![Uploading image.png…]()

**Comment by ghz-max** [comment]
For anyone wondering what would cause this.

I had to modify the file `keycloak-realm/microcks-realm-sample.json`

```
  "clients": [
    {
      "clientId": "microcks-app-js",
      "enabled": true,
      "publicClient": true,
      "redirectUris": [
        "http:/localhost:8080/*" <======== here to something different if you don't use localhost as the default domain
      ],
      "webOrigins": [
        "+"
      ],
[...]
```
