### ISSUE TITLE
Can't create a job by uploading a JSON compact file (1 line JSON) 

### ISSUE THREAD

**Issue by jorgeromeral** [microcks/microcks#440]
Hi everyone, I started few weeks ago using microcks and found that when I try to create a new job by uploading a JSON file in a compact format, the job doesn't create any service. However, uploading the same file but in a "pretty" format, it creates the service perfectly.

-The given error:
[error.txt](https://github.com/microcks/microcks/files/6685593/error.txt)

-Pretty file (Converted from the yaml file "User signed-up API" from microcks's docs into a json file, using this [converter](https://onlineyamltools.com/convert-yaml-to-json)):
[pretty.txt](https://github.com/microcks/microcks/files/6685650/pretty.txt)

-Compact file (Formatted using this [formatter](https://jsonformatter.curiousconcept.com)):
[compact.txt](https://github.com/microcks/microcks/files/6685670/compact.txt)

Microcks:
-Version 1.3.0-SNAPSHOT
-Build timestamp 2021-06-21T07:52:13Z

Thanks for the support, best regards.

**Comment by lbroudoux** [comment]
Hi @jorgeromeral !

Thanks for raising this issue. This is obviously a bug as I think we assume `asyncapi` pragma to be on a new line. We have to enrich the set of patterns to better detect the format. This is a minor one and should be shippable within the `1.3.0` release coming soon.

**Comment by jorgeromeral** [comment]
Ok, thanks for fast reply!

**Comment by lbroudoux** [comment]
Support is now added!
As a personal thought, I would not say that one-lining a specification is specifically a good idea ... IMHO one of specifications goal is to be human-readable ... and one-liner spec are no longer readable ;-)
