### ISSUE TITLE
Help - Response with value passed in path

### ISSUE THREAD

**Issue by Alekzsccp** [microcks/microcks#442]
I would like to know if it is possible to return a value received in path

Example:

https://test.mock.com/v1/worked/12345678910/search (Where the value 12345678910 is variable)

would like something like this:

Response:

xxx
200
   response:
      id: 12345678910
      state: "Success"

xxx

**Comment by lbroudoux** [comment]
Hi @Alekzsccp ! This is possible using Templating expressions and functions. Please have a look at [the documentation](https://microcks.io/documentation/using/advanced/templates/#simple-array-and-map) ; adding `{{ request.path[1] }}` in the example response should suit your needs ;-)

**Comment by Alekzsccp** [comment]
Thanks a lot for the help. I was able to extract the information and return it to the response =)
