### ISSUE TITLE
Multiple dispatch rule not working. 

### ISSUE THREAD

**Issue by geekdeb** [microcks/microcks#444]
Let's say I have request body like below. 
`{
     "mobile":"6756453476",
     "Email":"abc@xyz.com"
}
`
I am using JSON_BODY dispatch rule to validate 'Mobile's field using regexp. 

But is there any option, so that I can validate both the fields(multiple fields) from a request body. ?

**Comment by lbroudoux** [comment]
Hi @geekdeb, thanks for your question.

`JSON_BODY` dispatcher is intended to remain simple and to only manage a single property rule dispatch.
For more complex dispatching rules - like multi-properties - we aim to provide the `SCRIPT` dispatcher that virtually allows you to describe any dispatching logic.

Despite this dispatcher not being yet officially released and documented, its usage is straightforward as it is plain Groovy scripting that can reuse [Json parsing features](https://groovy-lang.org/json.html).

Thus you can use this dispatcher with scripts like this one below:

```groovy
def jsonSlurper = new groovy.json.JsonSlurper()
def body = jsonSlurper.parseText(mockRequest.requestContent)

if (body.fullName == "Chuck Norris" && body.email == "chuck@norris.com") {
  return "chuck"
}
return "unknown"
```

Let me know if it suits your need.

**Comment by lbroudoux** [comment]
Hi @geekdeb 

Any update on how this proposition fits your requirements?

**Comment by geekdeb** [comment]
@lbroudoux Sorry for late response. It did my work. I am good here. If possible post a small blog with short tutorial on this. That will be really helpful.

**Comment by lbroudoux** [comment]
Thanks! Will do but If you're interested in writing such a blog post, your contribution would be very welcome too ;-)
