### ISSUE TITLE
Error making grpc request against mock

### ISSUE THREAD

**Issue by molteninjabob** [microcks/microcks#448]
Hey Laurent!

I'm finally getting back to this after a crazy few weeks where I had some other priorities pop up (new hires, reports, etc.).

I have a proto file for an authentication service and trying to import Postman examples for it. They both import successfully,  but when trying to hit the mock from BloomRPC, microcks throws an exception. I tried this with a couple different `JSON_BODY` dispatch rules and then finally without a dispatcher. All of them seem to throw the same exception. The short error is this:

`22:55:27.474 ERROR 1 --- [executor-4] i.g.m.web.GrpcServerCallHandler : Unexpected throwable during GRPC input request processing`

Attaching the stack trace, proto file and postman example files.

[AuthV2.postman_collection.json.txt](https://github.com/microcks/microcks/files/6804826/AuthV2.postman_collection.json.txt)
[authv2.proto.txt](https://github.com/microcks/microcks/files/6804827/authv2.proto.txt)
[stack.txt](https://github.com/microcks/microcks/files/6804828/stack.txt)

**Comment by lbroudoux** [comment]
Will try to reproduced in coming days.

**Comment by lbroudoux** [comment]
Hi @molteninjabob,

The error you encounter is due to bad dispatcher rules and bad exception handling on Microcks side :-( 

I have imported your artifacts and first run the mock. I just added a `JSON_BODY` dispatcher with following rules:
```json
{
  "exp": "/Username",
  "operator": "equals",
  "cases": {
    "coltonshields@gmail.com": "UserByUsername",
    "default": "UserByUsername"
 }
```

Then, I've used BloomRPC to issue a simple request and encounter a serialization issue:
```
19:06:47.655 DEBUG 28977 --- [executor-0] i.g.m.web.GrpcServerCallHandler          : Request body: {
  "Username": "Hello"
}
19:06:47.680 ERROR 28977 --- [executor-0] i.g.m.web.GrpcServerCallHandler          : Unexpected throwable during GRPC input request processing

com.google.protobuf.InvalidProtocolBufferException: Expect message object but got: "3b710082-a1a5-4c69-8655-9924d73fbb43"
        at com.google.protobuf.util.JsonFormat$ParserImpl.mergeMessage(JsonFormat.java:1481)
```

With correct dispatcher, Microcks can found a response but the `UserID` and `LocationID` from example in Postman collection is not correctly encoded as JSON. To conform proto file, you should add an extra `Bytes` property like below:

```json
"UserID": {"Bytes": "3b710082-a1a5-4c69-8655-9924d73fbb43"}
```

Here's the fixed Postman collection: 
[AuthV2.postman_collection_2.json.txt](https://github.com/microcks/microcks/files/6873027/AuthV2.postman_collection_2.json.txt)

That said, we still have a bad exception handling on mock controller side. The `java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0` exception is due to unchecked array read and thus I'll create an issue to track enhancement.

**Comment by lbroudoux** [comment]
Better handling has now been implemented.

**Comment by molteninjabob** [comment]
I pulled down the latest images and tried this again using the Postman collection you provided, but I'm now getting a different error (not `java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0`). Attaching screenshots and stack trace:

![image](https://user-images.githubusercontent.com/11509961/127349583-ef1cf47a-3e17-4484-a245-7e9d35ce9618.png)

```
microcks | 15:20:13.100 INFO 1 --- [executor-3] i.g.m.web.GrpcServerCallHandler : Servicing mock response for service [AuthV2, authv2proto] and method UserByUsername
microcks | 15:20:13.103 DEBUG 1 --- [executor-3] i.g.m.web.GrpcServerCallHandler : Found a valid operation UserByUsername with rules: {
microcks | "exp": "/Username",
microcks | "operator": "equals",
microcks | "cases": {
microcks | "coltonshields@gmail.com": "UserByUsername",
microcks | "default": "UserByUsername"
microcks | }
microcks | 15:20:13.105 DEBUG 1 --- [executor-3] i.g.m.web.GrpcServerCallHandler : Request body: {
microcks | "Username": "Hello"
microcks | }
microcks | 15:20:13.115 ERROR 1 --- [executor-3] i.g.m.web.GrpcServerCallHandler : Dispatching rules of operation cannot be interpreted as JsonEvaluationSpecification
microcks |
microcks | io.github.microcks.util.dispatcher.JsonMappingException: Given JSON string cannot be interpreted as valid JsonEvaluationSpecification
microcks | at io.github.microcks.util.dispatcher.JsonEvaluationSpecification.buildFromJsonString(JsonEvaluationSpecification.java:73)
microcks | at io.github.microcks.web.GrpcServerCallHandler.computeDispatchCriteria(GrpcServerCallHandler.java:225)
microcks | at io.github.microcks.web.GrpcServerCallHandler$MockedUnaryMethod.invoke(GrpcServerCallHandler.java:165)
microcks | at io.github.microcks.web.GrpcServerCallHandler$MockedUnaryMethod.invoke(GrpcServerCallHandler.java:90)
microcks | at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:182)
microcks | at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:331)
microcks | at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:797)
microcks | at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
microcks | at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
microcks | at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
microcks | at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
microcks | at java.base/java.lang.Thread.run(Thread.java:829)
microcks |
microcks | 15:20:13.115 DEBUG 1 --- [executor-3] i.g.m.web.GrpcServerCallHandler : Dispatch criteria for finding response is null
microcks | 15:20:13.117 INFO 1 --- [executor-3] i.g.m.web.GrpcServerCallHandler : No appropriate response found for this input {
microcks | "Username": "Hello"
microcks | }, returning an error
```

**Comment by lbroudoux** [comment]
I think it's an issue with the JSON of the dispatcher rules. I forgot a } to close the one I have pasted above.

**Comment by molteninjabob** [comment]
Doh, I should have caught that. That's what I get for just copy/pasting without checking. This is now working! Thank you!
