### ISSUE TITLE
Add the posibility to deploy mickrocks using an existing RHSSO/Keycloak

### ISSUE THREAD

**Issue by fmenesesg** [microcks/microcks#45]
Maybe generate a new template that let you use another RHSSO/Keycloak with the realm pre-created

**Comment by hguerrero** [comment]
I believe this was solve with #35

**Comment by lbroudoux** [comment]
Perfectly right @hguerrero ! There's `*-no-keycloak-template.yaml*` templates within `/install/openshift` directory of distribution. However documentation if not yet referencing them.
