### ISSUE TITLE
Can't helm install with service.type=NodePort

### ISSUE THREAD

**Issue by john873950** [microcks/microcks#450]
I was trying to helm install ([using these instructions](https://microcks.io/documentation/installing/kubernetes/#helm-3)) to a Kube cluster hosted on AWS. As our cluster is using the AWS load balancer controller, I need the services to be of type NodePort. It looks like the service types are hard coded in the service.yaml file but I think it would be good practice to allow them to be overridden using the --set command line option.

## Steps to recreate
`% helm install microcks microcks/microcks —-version 1.1.0 --namespace microcks --set microcks.url=microcks.$(minikube ip).nip.io --set keycloak.url=keycloak.$(minikube ip).nip.io --set microcks.service.type=NodePort --set microcks-keycloak.service.type=NodePort`

`% kubectl describe services microcks`
`...`
`Type:              ClusterIP` <-------Still ClusterIP!
`...`

## Work around
I worked around this by cloning the code, editing the service.yaml directly and installing from there, but it would be great if it could be done using the standard process.

**Comment by john873950** [comment]
One way of addressing this is here https://github.com/microcks/microcks/pull/455

**Comment by lbroudoux** [comment]
Thanks for opening this issue. Actually, we are just managing `ClusterIP` services for both Helm Chart install and Operator install. It could be a great enhancement and thank a lot for pushing it in #455. Will have a look at it as soon as possible.

**Comment by lbroudoux** [comment]
Thanks a lot! This is now merged.

**Comment by john873950** [comment]
Awesome, thanks!
