### ISSUE TITLE
How to start microcks with kafka using docker

### ISSUE THREAD

**Issue by tillias** [microcks/microcks#451]
Hello folks, many thanks for a very nice product!

What is the easiest way to start microcks with kafka using docker compose? I'd like to mock few asyncAPIs locally 

Many thanks in advance.

**Comment by tillias** [comment]
I have tried adding few env variables, but it doesn't work

  app:
    depends_on:
      - mongo
      - keycloak
      - postman
    image: quay.io/microcks/microcks:latest
    container_name: microcks
    ports:
      - "8080:8080"
      - "9090:9090"
    environment:
      - KAFKA_INSTALL=false
      - FEATURES_ASYNC_ENABLED=true
      - FEATURES_ASYNC_KAFKA_URL=kafka:9092

**Comment by lbroudoux** [comment]
Whilst begin reluctant at first on implementing this - as it is an additional configuration to support with many consumed resources - there's frequent demand to support this. We'll provide an alternative docker-compose file with the async features on.

**Comment by tillias** [comment]
Hi Laurent, if it helps, there is Kompose: https://kubernetes.io/docs/tasks/configure-pod-container/translate-compose-kubernetes or https://github.com/kubernetes/kompose

So probably it is easier to make docker-compose first and then translate it into openshift / kubernetes?

**Comment by lbroudoux** [comment]
Hi @tillias ! Thanks for the link. I found since our last conversation that I had already included the property to configure the Keycloak URL from the minion side. I am finalizing some tests but things seem to work well till now. I should commit some stuffs in few minutes ;-)

**Comment by lbroudoux** [comment]
So to use if you just have to `cd install/docker-compose` and then execute:
```sh
$ docker-compose -f docker-compose-with-async.yml up -d
Creating network "docker-compose_default" with the default driver
Creating microcks-zookeeper       ... done
Creating microcks-db              ... done
Creating microcks-sso             ... done
Creating microcks-postman-runtime ... done
Creating microcks                 ... done
Creating microcks-kafka           ... done
Creating microcks-async-minion    ... done
```

After few seconds, you should have something like:
```sh
$ docker ps
CONTAINER ID        IMAGE                                              COMMAND                  CREATED             STATUS              PORTS                                                                NAMES
6563591f360c        quay.io/microcks/microcks-async-minion:latest      "/deployments/run-ja…"   7 seconds ago       Up 5 seconds        8080/tcp                                                             microcks-async-minion
38eb12982ae3        strimzi/kafka:0.17.0-kafka-2.4.0                   "sh -c 'bin/kafka-se…"   8 seconds ago       Up 6 seconds        0.0.0.0:9092->9092/tcp, 0.0.0.0:19092->19092/tcp                     microcks-kafka
581db7bb470c        quay.io/microcks/microcks:latest                   "/deployments/run-ja…"   8 seconds ago       Up 6 seconds        0.0.0.0:8080->8080/tcp, 8778/tcp, 0.0.0.0:9090->9090/tcp, 9779/tcp   microcks
edac773e0a29        strimzi/kafka:0.17.0-kafka-2.4.0                   "sh -c 'bin/zookeepe…"   10 seconds ago      Up 8 seconds        0.0.0.0:2181->2181/tcp                                               microcks-zookeeper
57cb601a5264        mongo:3.4.23                                       "docker-entrypoint.s…"   10 seconds ago      Up 8 seconds        27017/tcp                                                            microcks-db
4b2887aad930        quay.io/microcks/microcks-postman-runtime:latest   "docker-entrypoint.s…"   10 seconds ago      Up 8 seconds        3000/tcp                                                             microcks-postman-runtime
5b459ebfb2f4        jboss/keycloak:10.0.1                              "/opt/jboss/tools/do…"   10 seconds ago      Up 8 seconds        8443/tcp, 0.0.0.0:18080->8080/tcp                                    microcks-sso
```

Please notice that the Kafka broker is advertised on `19092` and that you should use that port for consuming messages from your localhost machine. You can use `kafkacat` like below:

```sh
$ kafkacat -b localhost:19092 -t UsersignedupAPI-0.1.1-user-signedup -o end                                                                                        
% Auto-selecting Consumer mode (use -P or -C to override)
% Reached end of topic UsersignedupAPI-0.1.1-user-signedup [0] at offset 22
{"id": "AQrUJz3WMyaahaa1kvEPfrqzvRA2QqFw", "sendAt": "1627068002250", "fullName": "Laurent Broudoux", "email": "laurent@microcks.io", "age": 41}
{"id":"6mboBiWtFhfeVfMjqsHFpxuw2kIVx8Kx","sendAt":"1627068002270","fullName":"John Doe","email":"john@microcks.io","age":36}
% Reached end of topic UsersignedupAPI-0.1.1-user-signedup [0] at offset 24
{"id": "PnKzf8w3LtCQwKBxSZDMHbAZy5s8tpX9", "sendAt": "1627068005251", "fullName": "Laurent Broudoux", "email": "laurent@microcks.io", "age": 41}
{"id":"kFkXcw2XSwhUlVuoCkgwnCMeOupg1IyV","sendAt":"1627068005257","fullName":"John Doe","email":"john@microcks.io","age":36}
% Reached end of topic UsersignedupAPI-0.1.1-user-signedup [0] at offset 26
```

I will finalize some tests in the forthcoming days and then add descent documentation to this.

**Comment by hguerrero** [comment]
Adding another docker-compose file looks like a duplication of maintenance. What do you think about using docker-compose multi files to just _ complement_ the original `docker-compose.yml` file?

My proposal is to have the original file and then another called `docker-compose.async.yml`  where the async configuration exists and then provide another for example to use Strimzi container images, but pluggable enough to use other Kafka images.

To call the compose would be 

```sh
docker-compose -f docker-compose.yml -f docker-compose.async.yml -f docker-compose.strimzi.yml up -d
```

It will basically merge the configuration from all three files into a single deployment. This way people can use their own and we can keep track of the docker-compose.yml in 1 single place for future releases.

wdyt @lbroudoux ?

**Comment by tillias** [comment]
There is similar approach in https://github.com/Apicurio/apicurio-studio/tree/master/distro/docker-compose with startup script like this https://github.com/Apicurio/apicurio-studio/blob/master/distro/docker-compose/start-mysql-environment.sh

**Comment by lbroudoux** [comment]
Good point @hguerrero ! Will refactor using a `docker-compose-async-addon.yml` file.

**Comment by lbroudoux** [comment]
Done! Now you can run it using `docker-compose -f docker-compose.yml -f docker-compose-async-addon.yml up -d`

**Comment by tillias** [comment]
Looks great! Do you accept PRs?

**Comment by lbroudoux** [comment]
@tillias Could you please confirm it is working as expected?

**Comment by tillias** [comment]
Sure, I can mock asyncAPIs locally now without need to setup Kubernetes cluster

**Comment by lbroudoux** [comment]
Just have to write down documentation now!

**Comment by lbroudoux** [comment]
Now done and deployed on microcks.io !
