### ISSUE TITLE
mocks are not generated in gke

### ISSUE THREAD

**Issue by tillias** [microcks/microcks#453]
Hello folks,

I have deployed microcks in gke and tried adding sample openAPI document I have created with apicurio-studio: https://pastebin.com/ZiwYFgiL

For POST there is mock generated and for GET examples section is ignored:
https://raw.githubusercontent.com/microcks/microcks/master/samples/APIPastry-openapi.yaml and example are directly bellow the schema

Can you please advise what I'm doing wrong?

**Comment by tillias** [comment]
Here is output
```
22:18:57.902 DEBUG 1 --- [080-exec-1] i.g.microcks.service.MessageService : Found 0 request(s) for operation 60f205cb604cb04062dfee0e-POST /register

22:18:57.903 DEBUG 1 --- [080-exec-1] i.g.microcks.service.MessageService : Found 0 response(s) for operation 60f205cb604cb04062dfee0e-POST /register

22:18:57.903 DEBUG 1 --- [080-exec-1] i.g.microcks.service.MessageService : Emitting 0 request/response pair(s) as result

22:18:57.910 DEBUG 1 --- [080-exec-1] i.g.microcks.service.MessageService : Found 0 request(s) for operation 60f205cb604cb04062dfee0e-GET /claim/{claimId}

22:18:57.911 DEBUG 1 --- [080-exec-1] i.g.microcks.service.MessageService : Found 0 response(s) for operation 60f205cb604cb04062dfee0e-GET /claim/{claimId}

22:18:57.911 DEBUG 1 --- [080-exec-1] i.g.microcks.service.MessageService : Emitting 0 request/response pair(s) as result

22:18:57.925 DEBUG 1 --- [080-exec-3] i.g.microcks.web.ServiceController : Retrieving service with id 60f205cb604cb04062dfee0e

22:18:57.936 DEBUG 1 --- [080-exec-3] i.g.microcks.service.MessageService : Found 0 request(s) for operation 60f205cb604cb04062dfee0e-POST /register

22:18:57.937 DEBUG 1 --- [080-exec-3] i.g.microcks.service.MessageService : Found 0 response(s) for operation 60f205cb604cb04062dfee0e-POST /register

22:18:57.937 DEBUG 1 --- [080-exec-3] i.g.microcks.service.MessageService : Emitting 0 request/response pair(s) as result

22:18:57.943 DEBUG 1 --- [080-exec-3] i.g.microcks.service.MessageService : Found 0 request(s) for operation 60f205cb604cb04062dfee0e-GET /claim/{claimId}

22:18:57.943 DEBUG 1 --- [080-exec-3] i.g.microcks.service.MessageService : Found 0 response(s) for operation 60f205cb604cb04062dfee0e-GET /claim/{claimId}

22:18:57.943 DEBUG 1 --- [080-exec-3] i.g.microcks.service.MessageService : Emitting 0 request/response pair(s) as result

22:18:57.967 DEBUG 1 --- [80-exec-10] i.g.microcks.web.ResourceController : Request resources for service 60f205cb604cb04062dfee0e

22:18:57.969 DEBUG 1 --- [080-exec-9] i.github.microcks.web.TestController : Getting tests list for service 60f205cb604cb04062dfee0e, page 0 and size 20


```

**Comment by tillias** [comment]
I have uploaded second openAPI and examples there are also ignored: https://pastebin.com/qqyG95Ha

**Comment by tillias** [comment]
It seems it doesn't like path parameters like 

```
paths:
  '/amount/{claimId}':
```

**Comment by molteninjabob** [comment]
@tillias When you say the GET example is ignored, do you mean that the GET mock endpoint does not show up at all? I tried the two pastebin examples you provided in my local set up and both of them created the mock endpoints. Here are screenshots. Please advise if this looks different from what you are seeing.

What version of microcks are you running? How are you running it? 

![image](https://user-images.githubusercontent.com/11509961/126185471-00a9017a-a003-4dcf-adbf-b042b0ccbd4f.png)
![image](https://user-images.githubusercontent.com/11509961/126185594-f88c4315-7b99-47a4-bcb3-8ad4de7bd5be.png)

**Comment by tillias** [comment]
Do you have mock urls generated as well? On the screenshot you don't have those. I have the same result as you btw

**Comment by lbroudoux** [comment]
Hey guys!

I think you didn't get a valid mock for the `GET` operation because of example fragments having different names. On the parameter side, you have `Example Claim Id` and on the response side you have `Example Claim`. In order to build full and coherent mocks is assembling the example fragment names that are matching. Please check the [OpenAPI conventions doc](https://microcks.io/documentation/using/openapi/#specifying-request-params) for examples using my cars.

To make it work here you'll probably just have to change `Example Claim Id` into `Example Claim`.

Note: I did not have the opportunity to test it out, just replying from my phone ;-)

**Comment by tillias** [comment]
Yes, now it works. Thanks!
