### ISSUE TITLE
Enable / disable mocks without removing them

### ISSUE THREAD

**Issue by tillias** [microcks/microcks#454]
Please consider possibility of enabling / disabling mocks without deleting them (both from UI and REST API)

This can be especially usefully for manual tests where people can simulate failure scenarios (e.g. some sub-system not available)

**Comment by lbroudoux** [comment]
Good idea! We also have discussed previously about adding more generic chaos engineering features to Microcks like random delays or failures, random unavailability... Maybe implementing this feature could be thought of in a more global framework?

What do you think?

**Comment by tillias** [comment]
Sound good! Something like https://www.gremlin.com  ?

**Comment by akakarikos** [comment]
Adding chaos engineering features would be awesome and it will distinguish Microcks from its alternatives! @lbroudoux is there any estimate of when such features will make it to development?
