### ISSUE TITLE
Incorrect topic name and broker when using the async docker-compose

### ISSUE THREAD

**Issue by hguerrero** [microcks/microcks#456]
When starting Microcks using the `docker-compose-with-async.yml` and uploading the tutorial async API, the topic and broker names that are deployed in the UI does not match the ones created by the async minion. 

Basically, the topic created is using kebab notation: `UsersignedupAPI-0.1.1-user-signedup` meanwhile the one showing in the UI is using the old format with underscores.

**Comment by lbroudoux** [comment]
Hi @hguerrero,
docker-compose references the `latest` container image and you may re-use a previous latest one that may not have the change to kebab notation. Could you check you have the latest `latest` container image?

**Comment by lbroudoux** [comment]
Hey @hguerrero! Did you have the opportunity to check this one?

**Comment by lbroudoux** [comment]
Checked on latest: topic name is correct.
