### ISSUE TITLE
Openshift GRPC Server cannot be started Bug

### ISSUE THREAD

**Issue by ALMARRI** [microcks/microcks#461]
Greetings, 

I tried to install Microcks Operator on OC 4.7 and I noticed the Storage Claims were pending for a long time. After looking deeper into the VPC I noticed they were missing the Storage class, it might be specific to the way we set up our OC cluster.
After deleting the VPC and reproducing a new YAML with the storage class and all resources were deployed successfully. 

However, 
I noticed keycloak pod and microcks pods were restarting many times until status CrashLoopBackOff

this part of the log in Microcks pod might be the root cause , and in the other hand keycloack pod receives a kill signal

`
10:12:24.826 [WARN] org.springframework.data.convert.CustomConversions - Registering converter from class java.time.LocalDateTime to class org.joda.time.LocalDateTime as reading converter although it doesn't convert from a store-supported type! You might want to check your annotation setup at the converter implementation.
10:12:25.221 [WARN] org.springframework.data.convert.CustomConversions - Registering converter from class java.time.LocalDateTime to class org.joda.time.LocalDateTime as reading converter although it doesn't convert from a store-supported type! You might want to check your annotation setup at the converter implementation.
10:12:38.024 [INFO] io.github.microcks.util.grpc.GrpcServerStarter - GRPC Server started on port 9090
10:12:38.026 [ERROR] io.github.microcks.util.grpc.GrpcServerStarter - **GRPC Server cannot be started**
java.lang.IllegalStateException: Shutdown in progress
	at java.base/java.lang.ApplicationShutdownHooks.add(ApplicationShutdownHooks.java:66)
	at java.base/java.lang.Runtime.addShutdownHook(Runtime.java:216)
`

I am still looking into it, and open for any suggestions.

**Comment by lbroudoux** [comment]
Thanks for creating the issue.

You're correct: we do not set any storage class on the VPC for the moment - but it's something we could easily add if you need it. BTW did you install Microcks using Operator of Helm Chart?

I think the storage class issue is not relate to the GRPC issue you're facing. I suspect it might be an issue with the GRPC certificate generation ... we faced an issue lately about people having long cluster URL (>  64) that breaks the OpenSSL certificate generation in the Operator ... It has been fixed lately but not yet propagated to your cluster ...

Could you please check if you have a Secret called `microcks-microcks-grpc-secret` or something like that? If it exists can you ensure that its `tls.crt` and `tls.key` entries are correctly set?

Let me know.

**Comment by ALMARRI** [comment]
Hello @lbroudoux 
`You're correct: we do not set any storage class on the VPC for the moment - but it's something we could easily add if you need it. BTW did you install Microcks using Operator of Helm Chart?`

Adding storage class support would be great, especially for creating multiple instances for separate teams without the need to hack our way around 😄 
As per the installation, we installed Microcks using the Operator. 

`Could you please check if you have a Secret called microcks-microcks-grpc-secret or something like that? If it exists can you ensure that its tls.crt and tls.key entries are correctly set?`


my-microcks-microcks-grpc-secret.yaml was created.
the tls.crt has the below: 
- Issuer: CN=my-microcksinstall-microcks.apps.XXXXXX.XXXXXXX.com
- Subject: CN=my-microcksinstall-microcks.apps.XXXXXX.XXXXXXX.com
- DNS:my-grpc-microcksinstall-microcks.apps.XXXXXX.XXXXXXX.com, DNS:my-microcksinstall-grpc.microcks.svc.cluster.local, DNS:localhost

Are we missing keycloak? 

One Note: when we create a new instance with a different name ( metadata name & spec name ) the tls info above does not reflect the new name, CNs and DNS would always be the same as the above. 

any suggestions?

**Comment by lbroudoux** [comment]
Hello,

sorry for late reply but being very busy this week. 

The DNS names you have in `my-microcks-microcks-grpc-secret` secret are perfectly normal : we just have the 3 ways of reaching the GRPC service. So nothing's wrong. Keycloak has its own secret and certificate. 

When you create a new instance with a different, the operator should create a new specific secret and certificate set for the other instance. That is maybe why you do not see the CN and DNS change I think. 

I have to admit that for the moment, I do not have any idea on what can go wrong on the GRPC Server startup. Maybe we could start putting some more log levels? In the CRD spec, there's a `microcks.logLevel` property you can put to `DEBUG` for being more verbose. Please set it up, wait some minutes for the operator to change the `microcks-config` ConfigMap and restart the microcks pod. You should have then more informations in the log.

Let me know your findings.

**Comment by lbroudoux** [comment]
Wa wondering if that could be the same issue as #492? Weird things being that we have clear logs of what's going wrong on 492... Do you any news @ALMARRI ?

**Comment by lbroudoux** [comment]
Hi,
I faced the same issue yesterday as I was working on a very constrained Kubernetes cluster with low default resources assigned to pods. I encounter this message because Pod takes too long to start when having low cpu resources. The workaround was to set and increase the requested cpu resource to `200m`. This is now possible through the Helm chart or operator based installation. If you're constrained and cannot allow that amount of CPU, the other way to get through this would be to increase delays for readiness and liveness probes.
