### ISSUE TITLE
Allow configuration of storage classes associated to both Microcks DB and Keycloak

### ISSUE THREAD

**Issue by lbroudoux** [microcks/microcks#464]
Nice enhancement suggestion coming from #461 : allow configuration of storage classes. As of today, we do not specify storage classes in Persistent Volume Claims so that only the default-one is used. This configuration should be made available through Helm Chart and Operator.

**Comment by supermani97** [comment]
Hello 
i am new to this platform could you please explai much better. So that i can contribute in it.
Thanks in Advance

**Comment by lbroudoux** [comment]
Hey @supermani97 ! It's a matter of adding new `storageClass` configuration attributes in Helm and Operator configuration` so that if defined we can print them into the generated Kubernetes resources.

Helm Chart sources are in this current repository: https://github.com/microcks/microcks/tree/master/install/kubernetes
Operator sources are located here: https://github.com/microcks/microcks-ansible-operator

**Comment by lbroudoux** [comment]
Done. Check Helm chart and operator README for instructions.
