### ISSUE TITLE
Can't set SERVICES_UPDATE_INTERVAL

### ISSUE THREAD

**Issue by essential-randomness** [microcks/microcks#474]
Hello,
I've been trying to set SERVICES_UPDATE_INTERVAL to refetch the open api specification from my server every minute, but can't seem to get it working.

This is on localhost, using docker-compose.

What I tried:

1. Setting `SERVICES_UPDATE_INTERVAL=* * * * *` on `docker-compose.yml`
2. Setting `services.update.interval=* * * * * ` on `application.properties`
3. Setting these to `* * * * * *` (* x 6) since your default value on `docker-compose` (`0 0 0/2 * * *`) has 6 values

I did log into the main panel in case that made a difference, but it doesn't seem to. No specification request is ever sent to my server, unlike when I "Force Import" through the UI.

What am I missing?

**Comment by essential-randomness** [comment]
Some related notes that might be helpful:

1. I had a lot of trouble finding the documentation of `SERVICES_UPDATE_INTERVAL`. I knew I had seen it somewhere, but had no idea where (and I had to go scour github issues for the name, which wasn't easy). It would be helpful to have a documentation section dedicated to configuration options.
2. In a similar fashion, I wanted to set the log level to `INFO` in case that helped with debugging this issue. I don't know whether you have that option and where to set it if necessary.
3. I didn't see anything about "startup configuration" in your logs, except one about `microcks-sso` that does not contain any of the ones in `application.properties`. That visibility would go a long way in helping pinpoint potential issues.
4. My ideal flow would allow me to "force update" the service configuration from within the service page itself (see picture). I haven't used your software enough to know whether there's an easy mapping from import job to service, but it'd greatly help developing and testing mocks/specs on localhost if these could be manually re-imported without switching page.

![image](https://user-images.githubusercontent.com/47095486/131208652-261bcf97-1ed9-4477-8cd9-6ae543da483e.png)

**Comment by lbroudoux** [comment]
Hi @essential-randomness !

It appears that the scheduling of API specification import does no longer work in current `master` version... Seems like we loose the feature enablement - maybe of a the latest Spring Boot upgrade?  I'll create a dedicated issue for the fix and produce a `latest` container image as possible.

Regarding the other points:
1. Documentation on the scheduling update interval is on the doc page dedicated to Importers. See https://microcks.io/documentation/using/importers/#configure-scheduling-interval
2. Log levels cannot be changed using the docker-compose installation methods to keep the things very easy. It can be adjusted only using the Kubernetes install methods.
3. The `application.properties` found in `install/docker-compose/config` folder is only intended to be use when enabling the Async features for docker-compose. See https://microcks.io/documentation/installing/docker-compose/#enabling-asynchronous-api-features.
4. Nice suggestion! Will think about how to easily enable this. Would you mind creating a dedicated issue for this suggestion? It will make tracking of it easier.

**Comment by lbroudoux** [comment]
Hi! Fix is now available into `quay.io/microcks/microcks:latest`. Could you please try and let me know.

**Comment by essential-randomness** [comment]
I don't know how I missed `SERVICES_UPDATE_INTERVAL` on the importers page! Now that you say it, it makes perfect sense. 

Regardless, I would expect to find all the options on a dedicated page, without having to look for them jumping around the documentation. It's fine if the explanations are simple links to the right places in the larger docs, but I'm missing a larger picture of what's configurable. This would also be a good place to concisely explain the difference between the various configuration files.

Filed #477!

**Comment by lbroudoux** [comment]
Thanks !
