### ISSUE TITLE
Import of API specifications scheduling no longer works

### ISSUE THREAD

**Issue by lbroudoux** [microcks/microcks#475]
It appears that due to past Spring Boot upgrades, we've lost the scheduled import of API definitions... This is a regression we do not detect as - unfortunately - scheduling is not part of unit tests.

**Comment by lbroudoux** [comment]
Thanks to @essential-randomness for having spot this in #474

**Comment by lbroudoux** [comment]
Fix is now available into `quay.io/microcks/microcks:latest`

**Comment by essential-randomness** [comment]
Thank you so much for the quick fix as usual!

This is working great, but I'd like to call out one source of confusion: traditional Unix cron has 5 digits, while Spring cron has 6. As far as I can tell 6-digits cron has no accepted standard definition with [some libraries using the additional digit as year](http://www.nncron.ru/help/EN/working/cron-format.htm) and [Spring using the additional digit as seconds](https://docs.oracle.com/cd/E12058_01/doc/doc.1014/e12030/cron_expressions.htm).

Not a big deal (initial confusion aside), but I'd add some clarification about the type of cron format you're using somewhere in your documentation. I can make a pull request for it.

**Comment by lbroudoux** [comment]
The precision on cron expression format is a good point 👍 Happy to review a PR if you have time in this. 👌
