### ISSUE TITLE
Can't import mocks from AsyncAPI spec for WebSocket protocol with messages polymorphism

### ISSUE THREAD

**Issue by ivanboytsov** [microcks/microcks#487]
When trying to import my AsyncAPI spec for WebSocket protocol I get zero mocks despite messages have examples.
It is happening because of multiple messages for each publisch/subscribe operation, which are described using "oneOf" property.
For example, such description in parsed correctly:
```
    subscribe:
      message:
        $ref: '#/components/messages/subscribed_unread_counter_update'
```
But this one resulted in 0 mocks:
```
    publish:
      message:
        oneOf:
        - $ref: '#/components/messages/subscribe_unread_counter_update'
        - $ref: '#/components/messages/subscribed_unread_counter_update'
```
I assume that importer doesn't consider that there may be multiple messages for one operation.
Example spec is attached.
![Снимок](https://user-images.githubusercontent.com/70232503/133050057-b1428160-5b04-41e5-94cd-82cf586f10d9.PNG)

[mockingest-asyncapi.txt](https://github.com/microcks/microcks/files/7162241/mockingest-asyncapi.txt)

**Comment by lbroudoux** [comment]
Hi @ivanboytsov 
Thanks for creating this issue. You're right : we are not handling `oneOf`, `allOf` or `anyOf` at this level - just `$ref` for the moment. It would be a nice enhancement.

**Comment by lbroudoux** [comment]
Hey @ivanboytsov 👋 
I've pushed some enhancements to the AsyncAPI importer/parser and polymorphism is now correctly managed.
Fix should be available in few minutes in `quay.io/microcks/microcks:latest` container image.
