### ISSUE TITLE
Fail to publish msgs on topic using async and avro on docker-compose

### ISSUE THREAD

**Issue by shavo007** [microcks/microcks#493]
Hi all,

I have been testing out the new blog recently using docker-compose
https://microcks.io/blog/async-features-with-docker-compose/

What i am trying to achieve is to use async API with an avro schema and onboard to schema registry. Similar to the post that was published before:
https://microcks.io/documentation/guides/avro-messaging/

## Step 1
What I initially wanted to do is onboard my API via the importer.
I worked out how to define a scheduler to pull in both files (async and avro)

NB: This link is broken btw where it mentions the importer job in the article https://microcks.io/documentation/documentation/using/importers/#scheduled-import

See scnshots below:

<img width="1523" alt="Screen Shot 2021-09-28 at 3 09 03 pm" src="https://user-images.githubusercontent.com/5466825/135026837-7dead76f-1d0d-445e-bfd9-f01a1b603400.png">

<img width="1525" alt="Screen Shot 2021-09-28 at 3 09 17 pm" src="https://user-images.githubusercontent.com/5466825/135026858-12378ed8-1ab9-4ca5-b9ec-50a4026df7be.png">

As you can see i import the raw file on a schedule

`https://raw.githubusercontent.com/shavo007/kafka-tutorial/main/asyncapi/src/main/resources/avro/io/confluent/examples/clients/basicavro/payment-avro-ref-asyncapi.yaml`

And it picks up both files in the API which is nice. So first part complete!

## Step 2

When I set this up I was initially confused by the logging as it mentions schema registry but none existed.
Example of log output:
```bash
2021-09-28 05:03:16,248 INFO  [io.git.mic.min.asy.SchemaRegistry] (main) Updating Schema registry for 'Payment Avro API - 0.1.2' with 2 entries

```

But there is no schema registry running. So then when i looked at the docker-compose files I dont see a container running the schema registry. So I added that in:

```yaml
  schema-registry:
    image: confluentinc/cp-schema-registry:6.2.0
    hostname: schema-registry
    container_name: schema-registry
    depends_on:
      - zookeeper
      - kafka
    ports:
     - "8888:8081"
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: "zookeeper:2181"
```

And i updated the `application.properties` 

```
kafka.schema.registry.url=http://localhost:8888
```

And then ran that:

```
docker-compose -f docker-compose.yml -f docker-compose-async-addon.yml up -d
```

Just to test this out I used my repos existing producer to send messages with an avro schema and that all worked:
https://github.com/shavo007/kafka-tutorial/blob/10c93d0a9cf080705ab1c0a81bdd8e481538995a/asyncapi/src/main/java/io/confluent/examples/clients/basicavro/ProducerExample.java

I can then verify the schema exists:

```
curl --silent -X GET http://localhost:8888/subjects/transactions-value/versions/latest | jq .
{
  "subject": "transactions-value",
  "version": 1,
  "id": 1,
  "schema": "{\"type\":\"record\",\"name\":\"Payment\",\"namespace\":\"io.confluent.examples.clients.basicavro\",\"fields\":[{\"name\":\"id\",\"type\":\"string\"},{\"name\":\"amount\",\"type\":\"double\"}]}"
}
```

But i cant see mirocks creating a new schema even tho it is publishing payment events to the topic `PaymentAvroAPI-0.1.2-transactions`

i can see the topic is created with events but no schema

```
kcat -b localhost:9092 -L
kcat -b localhost:9092 -t PaymentAvroAPI-0.1.2-transactions -o end
```

Am i missing something?? What i was expecting to see is microcks publishing sample events to topic and publishing the schema to the registry also.

**Comment by shavo007** [comment]
Actually, i got a bit further..

i added in the config `minion.default-avro-encoding=REGISTRY`

Now i see its logging in the producermanager trying to convert message to avro but it throws an exception:

```
2021-09-28 06:56:15,629 DEBUG [io.git.mic.min.asy.pro.ProducerManager] (QuarkusQuartzScheduler_Worker-25) Using a registry and converting message to Avro record
2021-09-28 06:56:15,630 INFO  [io.git.mic.min.asy.pro.KafkaProducerManager] (QuarkusQuartzScheduler_Worker-25) Publishing on topic {PaymentAvroAPI-0.1.2-transactions}, record: {"id": "100", "amount": 100.0} 
	at org.apache.kafka.clients.producer.KafkaProducer.doSend(KafkaProducer.java:902)
	at org.apache.kafka.clients.producer.KafkaProducer.send(KafkaProducer.java:862)
	at org.apache.kafka.clients.producer.KafkaProducer.send(KafkaProducer.java:750)
	at io.github.microcks.minion.async.producer.KafkaProducerManager.publishMessage(KafkaProducerManager.java:197)
	at io.github.microcks.minion.async.producer.KafkaProducerManager_ClientProxy.publishMessage(KafkaProducerManager_ClientProxy.zig:429)
	at io.github.microcks.minion.async.producer.ProducerManager.produceAsyncMockMessagesAt(ProducerManager.java:112)
	at io.github.microcks.minion.async.producer.ProducerManager_ClientProxy.produceAsyncMockMessagesAt(ProducerManager_ClientProxy.zig:156)
	at io.github.microcks.minion.async.ProducerScheduler$AsyncMockProducerJob.execute(ProducerScheduler.java:95)
2021-09-28 06:56:15,632 ERROR [io.git.mic.min.asy.pro.ProducerManager] (QuarkusQuartzScheduler_Worker-25) Exception while converting {{"id": "100", "amount": 100}} to Avro using schema {{
```

**Comment by shavo007** [comment]
One step closer!

I changed the schemaFormat to `schemaFormat: application/vnd.apache.avro+json;version=1.9.0`

Now i can see its trying to publish to the schema registry but failing:

```
2021-09-28 07:17:20,655 INFO  [io.git.mic.min.asy.pro.KafkaProducerManager] (QuarkusQuartzScheduler_Worker-22) Publishing on topic {PaymentAvroAPI-0.1.2-transactions}, record: {"id": "100", "amount": 100.0} 
2021-09-28 07:17:20,656 DEBUG [io.con.kaf.sch.cli.res.RestService] (QuarkusQuartzScheduler_Worker-22) Sending POST with input {"schema":"{\"type\":\"record\",\"name\":\"Payment\",\"namespace\":\"io.confluent.examples.clients.basicavro\",\"fields\":[{\"name\":\"id\",\"type\":\"string\"},{\"name\":\"amount\",\"type\":\"double\"}]}"} to http://localhost:8888/subjects/PaymentAvroAPI-0.1.2-transactions-io.confluent.examples.clients.basicavro.Payment/versions
2021-09-28 07:17:20,657 ERROR [io.con.kaf.sch.cli.res.RestService] (QuarkusQuartzScheduler_Worker-22) Failed to send HTTP request to endpoint: http://localhost:8888/subjects/PaymentAvroAPI-0.1.2-transactions-io.confluent.examples.clients.basicavro.Payment/versions: java.net.ConnectException: Connection refused (Connection refused)
```

if its on the same network i did change the url from localhost to service but also failed:

```
kafka.schema.registry.url=http://schema-registry:8888
```

**Comment by lbroudoux** [comment]
Hi @shavo007 

Sorry for being busy and not replying before ... you'd discover all the different steps by yourself! 😉 
Docker-compose setup is not complete enough for this use-case but you manage to bring all the additional requirements. Bravo!
As a reference, have you checked: https://microcks.io/documentation/guides/avro-messaging/ ?

Regarding your above configuration, shouldn't you use the `http://schema-registry:8081` url instead? From within the same docker managed network, I would think you have to use container port and not host exposed one...

**Comment by shavo007** [comment]
hi @lbroudoux  thanks for the reply. Was on wellness day today so will try and look at this tomorrow.

You are right, docker networking 101! I was using the wrong port. I'll report back here when I get the chance.

**Comment by shavo007** [comment]
got it all working nicely! ill update my repo later with the changes so if anyone needs to test avro out with docker-compose can save them time.

**Comment by shavo007** [comment]
https://github.com/shavo007/kafka-tutorial/tree/main/asyncapi

**Comment by lbroudoux** [comment]
Hey @shavo007! That's awesome! Would you be interested sharing your use-case and work with community through a blog post? We run a blog on https://microcks.io/blog/ and welcome anyone that like to share their story about using Microcks. We'd very happy!

**Comment by shavo007** [comment]
can do! ill add it to my backlog. I'm only kicking off evaluating different tools for EDA currently. I'll reach out if we come to that decision.
