### ISSUE TITLE
Test multiple messages with AsyncApi test runner

### ISSUE THREAD

**Issue by zlb323** [microcks/microcks#496]
At current, it seems that I am able to start the AsyncApi test runner to verify messages on a specific Kafka topic. However, the test will only run until it receives a single message and passes/fails. Is there a way to configure the test runner to listen for a larger number of messages or an unspecified number of messages for a specific number of time? and if not are there currently any plans for this sort of functionality?

This would be very useful for validating several our contracts.

Great work on Microcks so far BTW, it is looking to be a very useful application.

**Comment by lbroudoux** [comment]
Now done.
