### ISSUE TITLE
No mocks generated from Visma Severa OpenAPI 3

### ISSUE THREAD

**Issue by lopezvit** [microcks/microcks#503]
We are creating an application that would connect to Visma Severa API to perform some operations.
For testing it, we figure out that the best way is to construct a mock server and send request to it to check that it does what it should.
Unfortunately, when trying to generate the server, after importing this URL:
https://api.severa.visma.com/rest-api/openapidocs/v0.2/doc.json
No mock URLs are generated and no errores are shown (not in the UI, not in the logs)

![image](https://user-images.githubusercontent.com/7526995/136546149-9cd6f0fa-0d82-40bf-a0ff-2cc89d0647db.png)

We first tried with Postman and it was working correctly, but wanted to use an Open source instead, since you are limited to 1000 requests in the free tier.
The installation that we are using is docker-composer, but I don't know if that makes any difference.

**Comment by lbroudoux** [comment]
Hi @lopezvit,

Any news or thoughts on this issue?
