### ISSUE TITLE
Mock URL with no dispatcher does not work - OpenAPI import issue

### ISSUE THREAD

**Issue by igorrecioh** [microcks/microcks#505]
Hi all,

I am following [this way](https://github.com/Apicurio/apicurio-studio/tree/master/distro/docker-compose) for having Apicurio + Microcks + Keycloak with Docker.

I have created a dummy API just for testing, with examples. I can Mock it from Apicurio.

The problem comes when I copy the Mock URL and I try to make a request to that endpoint. I get this in the console:

```bash
i.github.microcks.web.RestController: No valid operation found and Microcks configured to not apply CORS policy
```
No matter if I make the request from RESTED, using cURL or directly from my browser (I am trying a GET request)

Am I missing something in the configuration?

Thanks a lot in advance

**Comment by lbroudoux** [comment]
Hum... it's supposed to work as is. Usually you got this issue when an API operation cannot be deduced from incoming request. Could you share a simple OpenAPI spec that reproduces it?

**Comment by lbroudoux** [comment]
Hi @igorrecioh 

Thanks a lot for the reproducer. It appears that #311 brings a regression into OpenAPI importer : the operation with no dispatcher (as `POST` and `DELETE` ones in your case) have no `resourcePath` set. This means that mock controller cannot find their matching with incoming request. I'll produce a `1.4.1` fix as soon as possible. This fix will replace previous container image tagged as `1.4.1`.

**Comment by igorrecioh** [comment]
Hi @lbroudoux!

Sounds good then, thank you for that. Let me know if you need more info from my side related to this issue, if it can help.

**Comment by lbroudoux** [comment]
Fix is available on `quay.io/microcks/microcks:latest`. Proceeding to release now.
