### ISSUE TITLE
Allow setting of annotations on pvcs from the values file

### ISSUE THREAD

**Issue by john873950** [microcks/microcks#507]
We need to be able to annotate our keycloak pvc with a resource-policy of keep. This is so we don't loose all our keycloak configuration between reinstalls.

It would be great if we can use the values.yaml to set pvc annotations and pick those up in claims.yaml.

**Comment by lbroudoux** [comment]
Thanks @john873950 for raising this one. Considering it for next release.

**Comment by john873950** [comment]
I think this PR should allow it: https://github.com/microcks/microcks/pull/514

**Comment by lbroudoux** [comment]
Now merged ;-)
