### ISSUE TITLE
Tests timeout not workin

### ISSUE THREAD

**Issue by mjgomesvix** [microcks/microcks#508]
The Test timeout is not working when it has been changed. The 10000 milliseconds, default value, keeps although its changes. Does anybody could help me?!

**Comment by lbroudoux** [comment]
Hi @mjgomesvix,

What kind of tests are you launching? What do you mean by not working when changed? Do you mean that value is not correctly persisted in database or the test runner does not really use it? 

Thanks for details,

**Comment by lbroudoux** [comment]
Closing it without being able to reproduce it.
