### ISSUE TITLE
Docker-compose setup on MacOS: the microcks service is occured the error

### ISSUE THREAD

**Issue by zion3mx** [microcks/microcks#51]
@lbroudoux Hi 
1. using docker run and i was connected microcks service. 
`http://myserver.example.com:8080/#/services`
2. the microcks service is occured the error when i was connected Service List page. i think Registration function is normal, but it can't find the keycloak's public key when lookup Serivce List page. 
```
[ERROR] org.keycloak.adapters.rotation.JWKPublicKeyLocator - Error when sending request to retrieve realm keys
org.keycloak.adapters.HttpClientAdapterException: IO error
	at org.keycloak.adapters.HttpAdapterUtils.sendJsonHttpRequest(HttpAdapterUtils.java:58)
	at org.keycloak.adapters.rotation.JWKPublicKeyLocator.sendRequest(JWKPublicKeyLocator.java:99)

or 
[ERROR] org.keycloak.adapters.rotation.AdapterRSATokenVerifier - Didn't find publicKey for kid: 2g_AIcWsxQRBAfWoGJwgknUuf2bFLE8UhKFZQ4.....
```
3. Please let me know solution
- Is it not working with the Keycloak system?
- Or should I have to register public key in the Keycloak system? or Are there additional interworking tasks?

**Comment by zion3mx** [comment]
reference page : http://microcks.github.io/installing/docker-compose/
im using `docker-compose`. 

`git clone https://github.com/microcks/microcks.git
cd microcks/install/docker-compose
docker-compose -f microcks.yml up -d

$ hostname -f myserver.example.com
$ cd microcks/install/docker-compose/
$ cp keycloak-realm/microcks-realm-sample.json keycloak-realm/microcks-realm-sample.json.bak
$ apt-get install jq
$ jq '.applications |= map(if .name == "microcks-app-js" then .redirectUris = [ "http://myserver.example.com:8080/*" ] else . end) | .sslRequired |= "none"' keycloak-realm/microcks-realm-sample.json.bak > keycloak-realm/microcks-realm-sample.json
$ perl -i.bak -pe 's|KEYCLOAK_URL=http://localhost:8180/auth|KEYCLOAK_URL=http://myserver.example.com:8180/auth|' microcks.yml
$ perl -i.bak -pe 's|keycloak.ssl-required=external|keycloak.ssl-required=none|' config/application.properties
$ sudo docker-compose -f microcks.yml up -d`

My OS Platform : mac OS High Sierra 10.13.6
docker version
Client:
 Version:           18.06.0-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        0ffa825
 Built:             Wed Jul 18 19:05:26 2018
 OS/Arch:           darwin/amd64
 Experimental:      false

**Comment by lbroudoux** [comment]
On MacOS, it is really simple and do not need to go through the `Server Install` section.

Just edit the `microcks.yml` file and change the `KEYCLOAK_URL` value to the Docker alias for localhost on Mac. Comment the `localhost` one and uncomment `the docker.for.mac` one, like this:

```
     #- KEYCLOAK_URL=http://localhost:8180/auth
     - KEYCLOAK_URL=http://docker.for.mac.localhost:8180/auth
```

Save and then just run `docker-compose -f microcks.yml up -d` and it should be ok.

**Comment by zion3mx** [comment]
Oh my god!!! i solved it.
It was an easy solution... ㅜㅜ  Thank you and sorry..

I had the same problem when I installed microcontroller 0.6.0 source from Git-hub and installed Mongo db and etc.. 
Thank you :-)

**Comment by zion3mx** [comment]
1. created job
This api is maded  using Apicurio Studio.
Repository URL : https://github.com/zion3mx/apicurio_test
![microcks mocks for your micro-services 2018-08-31 15-50-29](https://user-images.githubusercontent.com/2899108/44897138-9fc28f00-ad35-11e8-9b3d-694146ae3c8a.png)

2. execute Job Start after Activate. 
But occured as blow xmlException.
The same error occurs when i was created other job. Do you know why this is happening?

```
[DEBUG] sun.net.www.protocol.http.HttpURLConnection - sun.net.www.MessageHeader@249e673023 pairs: {null: HTTP/1.1 200 OK}{Date: Fri, 31 Aug 2018 06:52:31 GMT}{Content-Type: text/html; charset=utf-8}{Transfer-Encoding: chunked}{Server: GitHub.com}{Status: 200 OK}{Cache-Control: no-cache}{Vary: X-PJAX}{Set-Cookie: has_recent_activity=1; path=/; expires=Fri, 31 Aug 2018 07:52:31 -0000}{Set-Cookie: _octo=GH1.1.1360721753.1535698351; domain=.github.com; path=/; expires=Mon, 31 Aug 2020 06:52:31 -0000}{Set-Cookie: logged_in=no; domain=.github.com; path=/; expires=Tue, 31 Aug 2038 06:52:31 -0000; secure; HttpOnly}{Set-Cookie: _gh_sess=SWtCL3VrKzBzbTZrUFNDdkpWSVFCNGUvMWxucW9nTVdBRGJMMHpzWW4xRHJDSWJ6NmFibngzSmdta0xuSklIN0U0emFrSEdnVkFvRHVwZkhRMEtyazArVHVJQWJyTEdacWNid2ZDTE40Yk92bDV0bnVtazg2TlRyQ0JPZ3FsQnRRQ0JnY0w0Zm95QkJLZW1sc1hINFg5aUg4WUF0ZWZQTWhFOVhUd1dWNW1tYkphN0xTWmw5MXIzSEFvWlZxY2FZMUluVjVMbUtBaTBoRVFPeTJidjhzazFiaGVXa3Y1YS8zcytySDdFNE03ZjczdVZCckRFbWZhWENUb2xXRWVuYUFUdmVTd0JrZ3BUMFB4UVM5Q0pPaFJWR0gvY2pxWFFVTEl6bWdLam8zRjg9LS1yaHErVE5CSVRoWHl4MVppdWc3b3lnPT0%3D--c40b6377831a594767d2f3cdafa7353c88fab43f; path=/; secure; HttpOnly}{X-Request-Id: 9134e748-8977-4d66-af4b-0df603d191da}{X-Runtime: 0.138506}{Strict-Transport-Security: max-age=31536000; includeSubdomains; preload}{X-Frame-Options: deny}{X-Content-Type-Options: nosniff}{X-XSS-Protection: 1; mode=block}{Expect-CT: max-age=2592000, report-uri="https://api.github.com/_private/browser/errors"}{Content-Security-Policy: default-src 'none'; base-uri 'self'; block-all-mixed-content; connect-src 'self' uploads.github.com status.github.com collector.githubapp.com api.github.com www.google-analytics.com github-cloud.s3.amazonaws.com github-production-repository-file-5c1aeb.s3.amazonaws.com github-production-upload-manifest-file-7fdce7.s3.amazonaws.com github-production-user-asset-6210df.s3.amazonaws.com wss://live.github.com; font-src assets-cdn.github.com; form-action 'self' github.com gist.github.com; frame-ancestors 'none'; frame-src render.githubusercontent.com; img-src 'self' data: assets-cdn.github.com identicons.github.com collector.githubapp.com github-cloud.s3.amazonaws.com *.githubusercontent.com; manifest-src 'self'; media-src 'none'; script-src assets-cdn.github.com; style-src 'unsafe-inline' assets-cdn.github.com}{X-Runtime-rack: 0.146476}{Vary: Accept-Encoding}{X-GitHub-Request-Id: B898:606B:C054A:120D75:5B88E5AF}
Error at line 43, column 89
org.apache.xmlbeans.XmlException: error: Unexpected character encountered (lex state 10): '>'
	at org.apache.xmlbeans.impl.store.Locale$SaxLoader.load(Locale.java:3486)
	at org.apache.xmlbeans.impl.store.Locale.parseToXmlObject(Locale.java:1276)
	at org.apache.xmlbeans.impl.store.Locale.parseToXmlObject(Locale.java:1263)
	at org.apache.xmlbeans.impl.schema.SchemaTypeLoaderBase.parse(SchemaTypeLoaderBase.java:345)
	at com.eviware.soapui.config.SoapuiProjectDocumentConfig$Factory.parse(SoapuiProjectDocumentConfig.java:71)
	at com.eviware.soapui.impl.wsdl.WsdlProject.loadProjectFromInputStream(WsdlProject.java:337)
	at com.eviware.soapui.impl.wsdl.WsdlProject.loadProject(WsdlProject.java:298)
	at com.eviware.soapui.impl.wsdl.WsdlProject.<init>(WsdlProject.java:217)
	at com.eviware.soapui.impl.wsdl.WsdlProject.<init>(WsdlProject.java:198)
```
![microcks mocks for your micro-services 2018-08-31 15-52-39](https://user-images.githubusercontent.com/2899108/44897419-90901100-ad36-11e8-8e8b-33a86db7b9ca.png)

**Comment by lbroudoux** [comment]
Hi there, it seems like your repository URL is not complete. It should be the complete URL for accessing your API contract (the GitHub user content one, referencing the branch you are using). 

Microcks is not aware of Git repository it just need a valid HTTP URL. Please check the getting started section for examples. 

And do not hesitate using Gitter when w bring to quick chat about usage questions. 

Thanks for testing Microcks !

**Comment by zion3mx** [comment]
@lbroudoux  Thank you!!!
I mistook the url path. This problem was solved!
This is an complete contract generated by Apicurio Studio!! and url is 
`https://raw.githubusercontent.com/zion3mx/apicurio_test/master/test.json`
-----------
This is hosts file included `127.0.0.1   myserver.example.com`
Do you think this is caused? I will check now

**Comment by lbroudoux** [comment]
Yes this is the cause.

First I am not sure that Docker engine inherits from your host file. Second if it inherits, it will resolve local host to container itself ! 

Host name must be resolvable using a regular external DNS.

**Comment by zion3mx** [comment]
@lbroudoux Thanks you, I had able to finish the server configuration whin your advice !!

**Comment by lbroudoux** [comment]
Nice ! Do not hesitate using Gitter Microcks/Microcks channel or chat room for joining community and asking help.
