### ISSUE TITLE
Any support for running microcks on Apple Silicon ?

### ISSUE THREAD

**Issue by gayanper** [microcks/microcks#523]
I tried to run using docker compose and also minikube on Apple Silicon. But it fails due to certain containers are not running. For example on docker compose mode the keycloak is failing to run under docker x86_64 emulation. Any plans to support aarch64 for these containers ?

**Comment by lbroudoux** [comment]
Hi @gayanper !

Unfortunately GitHub Actions do not offer Apple Silicon runners yet and I don't have the chance to own a M1 yet ...

We've heard about this Keycloak issue in microcksio.zulipchat.com lately and the only way for now would be to reproduce a local image from the source... However, we're also working on bypassing Keycloak when running on a developer laptop => Check #515 that summarize this. We already pushed everything's needed for this on `1.5.x` branch but no documentation yet... Have a look at the `install/docker-compose/docker-compose-devmode.yml` file if interested.

**Comment by gayanper** [comment]
@lbroudoux i tried the new branch with mentioned docker compose file. I have to change the microcks images to use linux/amd64 platform. But once i did that seems it fails on redrection of keycloack. I don't see a keycloak container now.

**Comment by lbroudoux** [comment]
Oh yes... my bad! It is not fully ready yet. You have to change the Microcks images from _latest_ to _nightly_ tags. The nightly images accept the KEYCLOACK_ENABLED variable when set to false and should no longer redirect to Keycloak.

**Comment by gayanper** [comment]
> Oh yes... my bad! It is not fully ready yet. You have to change the Microcks images from _latest_ to _nightly_ tags. The nightly images accept the KEYCLOACK_ENABLED variable when set to false and should no longer redirect to Keycloak.

switched to nighlies and then change few images to linux/amd64 as the platform. Its working now. So i will also give this a try with lima project as well. let me know if you need a PR with the changes i did to see if it looks correct.

**Comment by lbroudoux** [comment]
Gréât! Just to be curious: what is Lima project? Could you share a link?

**Comment by gayanper** [comment]
> Great! Just to be curious: what is Lima project? Could you share a link?
https://github.com/lima-vm/lima

**Comment by lbroudoux** [comment]
@gayanper I've fixed the docker-compose switching to `nightly` images. I would be awesome if you could contribute a PR adding a `docker-compose-devmode-silicon.yml` with the changes you made to make it work on M1. Thanks !

**Comment by pmamico** [comment]
@gayanper  created a PR for that on #524!
can i help somehow to speed up the merge?

**Comment by lbroudoux** [comment]
Will have a look at it right now. I was looking to get some time to have a deeper look at [Docker buildx](https://docs.docker.com/buildx/working-with-buildx/) to produce real `linux/arm64` compatible images. Unfortunately, I don't have time for the `1.5.x` stream... I'm gonna merge the PR as is and will create another issue for later.
