### ISSUE TITLE
Uploaded OpenAPI-Specification.json is not listed on dashboard or Apis | services

### ISSUE THREAD

**Issue by smtdmrll** [microcks/microcks#526]
Although I have successfully uploaded OpenAPI-Specification.json, I can't see it either on the dashboard or in the APIs | Services.
I logged in as admin user to override, but no difference.

Why can't I see? can you help me?
 

-       Ocp version : 4.8.20
-       Microcks version: 1.4.1

**Comment by lbroudoux** [comment]
Do you get any error messages in the UI or at least in Pod logs? Could you share an OpenAPI reproducer file?

**Comment by smtdmrll** [comment]
I didn't get any error on ui.
I attached pod logs and openapi 
[openapi.docx](https://github.com/microcks/microcks/files/7704330/openapi.docx)
[my-microcksinstall-574f48b75d-bz59c-spring.log](https://github.com/microcks/microcks/files/7704336/my-microcksinstall-574f48b75d-bz59c-spring.log)

**Comment by lbroudoux** [comment]
Looking at the logs, it seems that the OpenAPI has been correctly identified and imported. Could it be a security issue when fetching the Services list from the UI ? Could you please check at the Network tab in the dev tools of your browser to see if fetching occurs and succeeds ?

**Comment by lbroudoux** [comment]
Another issue seems to be related to same behavior. See #528. 
I'm in the process of rebuilding a cluster to test this out.

**Comment by smtdmrll** [comment]
Thank you for help.
Issue has been solved.

**Comment by Arthuriuss** [comment]
> Thank you for help. Issue has been solved.

Hello @smtdmrll, could you explain how did you solved your problem please ? We are facing to the same issue.

**Comment by smtdmrll** [comment]
> > Thank you for help. Issue has been solved.
> 
> Hello @smtdmrll, could you explain how did you solved your problem please ? We are facing to the same issue.

Hi @Arthuriuss,I solved the problem when I gave admin role.

**Comment by Arthuriuss** [comment]
Thanks for the reply, I'm gonna try.
