### ISSUE TITLE
Encoding of automatic path generation for mocks URL

### ISSUE THREAD

**Issue by lucamaf** [microcks/microcks#53]
At the moment the base path for the mocked URL is generated based on the description field in the swagger definition. Whitespaces are encoded (as it should be) as `%20` but this encoding can cause problems for some programs. I suggest exchange the whitespace for `-` or `_` or `+` character

**Comment by lbroudoux** [comment]
`+` characters seems a good candidate as `-` or `_` maybe used into API name.
Will start implemeting this one shortly, keeping backward compatibility with existing form where spaces are encoded using regular `%20`.

**Comment by lbroudoux** [comment]
Hi @lucamaf ! It's now done.
