### ISSUE TITLE
Error storing daily statistics

### ISSUE THREAD

**Issue by miguelchicoespin** [microcks/microcks#540]
Hi,

I'm getting this error below when calling to a REST mock.
I'm running microcks on k8s with 3 pods and trying to find the performance of the application.

`11:14:28.072 [ERROR] org.springframework.aop.interceptor.SimpleAsyncUncaughtExceptionHandler - Unexpected exception occurred invoking async method: public void io.github.microcks.listener.DailyStatisticsFeeder.onApplicationEvent(io.github.microcks.event.MockInvocationEvent)
org.springframework.dao.IncorrectResultSizeDataAccessException: Query { "$java" : Query: { "day" : "20220103", "serviceName" : "First Mock API", "serviceVersion" : "1.0.0"}, Fields: {}, Sort: {} } returned non unique result.
	at org.springframework.data.mongodb.core.ExecutableFindOperationSupport$ExecutableFindSupport.oneValue(ExecutableFindOperationSupport.java:139)
	at org.springframework.data.mongodb.repository.query.AbstractMongoQuery.lambda$getExecution$4(AbstractMongoQuery.java:159)
	at org.springframework.data.mongodb.repository.query.AbstractMongoQuery.doExecute(AbstractMongoQuery.java:132)
	at org.springframework.data.mongodb.repository.query.AbstractMongoQuery.execute(AbstractMongoQuery.java:107)
	at org.springframework.data.repository.core.support.RepositoryMethodInvoker.doInvoke(RepositoryMethodInvoker.java:137)
	at org.springframework.data.repository.core.support.RepositoryMethodInvoker.invoke(RepositoryMethodInvoker.java:121)
	at org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.doInvoke(QueryExecutorMethodInterceptor.java:152)
	at org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.invoke(QueryExecutorMethodInterceptor.java:131)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.data.projection.DefaultMethodInvokingMethodInterceptor.invoke(DefaultMethodInvokingMethodInterceptor.java:80)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:215)
	at com.sun.proxy.$Proxy106.findByDayAndServiceNameAndServiceVersion(Unknown Source)
	at io.github.microcks.listener.DailyStatisticsFeeder.onApplicationEvent(DailyStatisticsFeeder.java:71)
	at io.github.microcks.listener.DailyStatisticsFeeder.onApplicationEvent(DailyStatisticsFeeder.java:38)
	at jdk.internal.reflect.GeneratedMethodAccessor67.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.interceptor.AsyncExecutionInterceptor.lambda$invoke$0(AsyncExecutionInterceptor.java:115)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)`

In case this is not easy to solve, would it be possible to disable daily statistics?
I've checked the code and there is no property to do it right now

**Comment by lbroudoux** [comment]
Hi and thanks for reporting this issue.

You should have faced a race condition where 2 `DailyStatistics` for same day and same service should have created concurrently. Actually, we do not put any lock on the database nor want to use compound key in order to keep things lightweight (with accuracy in balance).

I'm gonna add guards on this process to avoid such things to happen.

BTW I'd be very interested into your performance insights when running your tests.

**Comment by lbroudoux** [comment]
Fix should now be present into `quay.io/microcks/microcks:nightly` container image.

**Comment by miguelchicoespin** [comment]
Ey @lbroudoux 
Thank you very much for the quick fix. I can confirm the error is not present anymore.

On the other hand, I think the performance has decreased a lot. Let me explain our tests.

We were using version 1.4.1 and we just configured one mock and we used https://k6.io/ to write a simple load test.
With version 1.4.1 we were getting 1K+ transactions per second. Using the nightly version we only can get around 400 transactions per second.

Besides all that we have the impression the async event mechanism microcks is using is not helping with performance either. After our tests finish, microcks requires a lot of time to finish processing all the messages for statistics.

Would it be possible to add an env variable to disable the statistics and be able to compare performance without them?

Thank you!!

**Comment by lbroudoux** [comment]
Hum... these are very insightful information, thank you.
Major difference between `1.4.1` and `nightly` versions is the upgrade to Spring Boot `2.6`. Maybe the way Spring handles `applicationContext.publishEvent(event)` has changed? Will have a deep dive look at it. 
Meanwhile I'll see how to disable that to allow comparison.

**Comment by miguelchicoespin** [comment]
Perfect!! I would be happy to do some performance testing with different options to understand the impact of each change.
Maybe we can check with and without statistics in both spring boot versions if that's available.

I would love to help!

**Comment by lbroudoux** [comment]
Just thinking about a "detail" : how do you have installed your kube deployment ? Have you used recent versions of Helm Chart of Operator ? (<1 week). We did some changes in bootstrap parameters to allow faster startup and low memory consumptions but this certainly has impact on throughput... 

Could you share and compare the environment variables of the `microcks` main pod Deployment?

**Comment by miguelchicoespin** [comment]
Sure no problem!!

I used Helm Chart. Sadly I'm running an outdated Kubernetes version (v1.18.5) and recent changes to the Kubernetes Operator (to support new Ingress kind versions) are not compatible with my cluster (that's ok, I need to upgrade my test cluster).
So using the latest version of the Helm Chart and doing some manual changes I was able to install Microcks.

These are the variables used by the Microcks deployment

`
 Environment:
      JAVA_OPTIONS:
      SPRING_PROFILES_ACTIVE:        prod
      SPRING_DATA_MONGODB_URI:       mongodb://${SPRING_DATA_MONGODB_USER}:${SPRING_DATA_MONGODB_PASSWORD}@microcks-mongodb:27017/${SPRING_DATA_MONGODB_DATABASE}
      SPRING_DATA_MONGODB_USER:      <set to the key 'username' in secret 'microcks-mongodb-connection'>  Optional: false
      SPRING_DATA_MONGODB_PASSWORD:  <set to the key 'password' in secret 'microcks-mongodb-connection'>  Optional: false
      SPRING_DATA_MONGODB_DATABASE:  microcks
      POSTMAN_RUNNER_URL:            http://microcks-postman-runtime:8080
      TEST_CALLBACK_URL:             http://microcks:8080
      KEYCLOAK_URL:                  http://microcks-keycloak.microcks-helm.svc.cluster.local:8080/auth
      KEYCLOAK_PUBLIC_URL:           https://public-keycloak/auth
      KAFKA_BOOTSTRAP_SERVER:        microcks-kafka-kafka-bootstrap:9092
`


I just checked the operator code and I can see some JAVA_OPTIONS configured there that are not present on the Helm Chart.
I can use them in my installation and report metrics to you in case you need it, just let me know.

Thank you!

**Comment by lbroudoux** [comment]
Ok thanks. So no relation to the new `JAVA_OPTIONS` and `JAVA_MAJOR_VERSION` we introduced lately...

I ran some very basic benchmark this morning using `siege` utility and did not see any differences. I've used the `docker-compose` setup on my local Mac Book. Here are the figures I collected:

**Version 1.4.1**

```sh
$ curl localhost:8080/api/version/info -s | jq .
{
  "versionId": "1.4.2-SNAPSHOT",
  "buildTimestamp": "2021-10-08T07:46:32Z"
}
$ siege -t30s http://localhost:8080/rest/API+Pastry+-+2.0/2.0.0/pastry
{
	"transactions":			       16336,
	"availability":			      100.00,
	"elapsed_time":			       29.63,
	"data_transferred":		        0.00,
	"response_time":		        0.04,
	"transaction_rate":		      551.33,
	"throughput":			        0.00,
	"concurrency":			       20.15,
	"successful_transactions":	           0,
	"failed_transactions":		           0,
	"longest_transaction":		        0.47,
	"shortest_transaction":		        0.00
}
``` 

**Version 1.5.0 nightly**

```sh
$ curl localhost:8080/api/version/info -s | jq .
{
  "versionId": "1.5.0-SNAPSHOT",
  "buildTimestamp": "2022-01-03T14:10:27Z"
}
$ siege -t30s http://localhost:8080/rest/API+Pastry+-+2.0/2.0.0/pastry
{
	"transactions":			       16322,
	"availability":			      100.00,
	"elapsed_time":			       29.49,
	"data_transferred":		        0.00,
	"response_time":		        0.04,
	"transaction_rate":		      553.48,
	"throughput":			        0.00,
	"concurrency":			       22.57,
	"successful_transactions":	           0,
	"failed_transactions":		           0,
	"longest_transaction":		        0.50,
	"shortest_transaction":		        0.00
}
```

Anyway, I will introduce the flag we talked about to check if asynchronous processing of statistics can have any impact on throughput as you suggest. I'll let you know.

**Comment by lbroudoux** [comment]
Ok thanks. So no relation to the new `JAVA_OPTIONS` and `JAVA_MAJOR_VERSION` we introduced lately…

I ran some very basic benchmark this morning using `siege` utility and did not see any differences. I’ve used the
`docker-compose` setup on my local Mac Book. Here are the figures I collected:

**Version 1.4.1** (Spring Boot 2.4.5)

```sh
$ curl localhost:8080/api/version/info -s | jq .
{
  "versionId": "1.4.2-SNAPSHOT",
  "buildTimestamp": "2021-10-21T07:33:33Z"
}
$ siege -t30s http://localhost:8080/rest/API+Pastry+-+2.0/2.0.0/pastry/Millefeuille
{
	"transactions":			       12465,
	"availability":			      100.00,
	"elapsed_time":			       29.84,
	"data_transferred":		        1.52,
	"response_time":		        0.06,
	"transaction_rate":		      417.73,
	"throughput":			        0.05,
	"concurrency":			       24.95,
	"successful_transactions":	       12465,
	"failed_transactions":		           0,
	"longest_transaction":		        0.29,
	"shortest_transaction":		        0.00
}
```

**Version 1.5.0 nightly** (Spring Boot 2.6.0)

```sh
$ curl localhost:8080/api/version/info -s | jq .
{
  "versionId": "1.5.0-SNAPSHOT",
  "buildTimestamp": "2022-01-03T14:10:27Z"
}
$ siege -t30s http://localhost:8080/rest/API+Pastry+-+2.0/2.0.0/pastry/Millefeuille
{
	"transactions":			       12468,
	"availability":			      100.00,
	"elapsed_time":			       29.88,
	"data_transferred":		        1.52,
	"response_time":		        0.06,
	"transaction_rate":		      417.27,
	"throughput":			        0.05,
	"concurrency":			       24.95,
	"successful_transactions":	       12468,
	"failed_transactions":		           0,
	"longest_transaction":		        0.24,
	"shortest_transaction":		        0.00
}
```

Anyway, I will introduce the flag we talked about to check if asynchronous processing of statistics can have any impact on throughput as you suggest. I’ll let you know.

**Comment by miguelchicoespin** [comment]
Hi @lbroudoux 
Maybe the decrease in performance I found might be caused by other situations, I can double-check with that tool you mentioned and share some results if you need them.

Anyway, that flag we are talking about will give us the final response about the impact on performance so I will stay tuned and will perform as many checks as we need once it is introduced if you are ok with that.

**Comment by lbroudoux** [comment]
Instead of pushing a new flag, I pushed a slightly modified image just right here: `quay.io/lbroudoux/microcks:nightly`.
In this image I just commented the publication of invocation, so no processing will occur.

Let me know.

**Comment by lbroudoux** [comment]
Closed by mistake, re-opening it.

**Comment by miguelchicoespin** [comment]
I've just checked the new image and the performance is outstanding!

I can manage to get 1.5k+ transactions per second with the same configuration as before. (3 pods in a k8s cluster with limit cpu to 1 core)
I think there is no problem at all with Spring Boot upgrade and probably the event processing was consuming resources and decreasing general performance.

I'll keep a longer test running to ensure performance is not degrading along time and come back with more results, but I can say that right now without that even processing it is performing absolutely great! 

I would say you can implement that flag to enable or disable statistics and people interested in them would be able to benefit for that future and maybe users like me looking for pure performance will be able to get the best from the tool.

What do you think?

**Comment by lbroudoux** [comment]
Your proposition sounds nice: we could add this flag to disable invocation stats in case of raw perf needs. Seems like you got a quite interesting use-case to cover ... it could be nice to share it later with community don't you think ? 😉 

However I'm still concerned on why you got such poor performance results with the `nightly` image coming from repo ? I'd be very interested with results if you have the opportunity to re-launch some other longer tests.

**Comment by miguelchicoespin** [comment]
Hi,

I've been doing more performance testing with the two versions, let me share my findings here.
Before raw data just a reminder that I've installed Microcks using the latest version of Helm Chart in a Kubernetes Cluster.

I've configured a super simple mock using OpenAPI:
[First Mock API-1.0.0.yaml.txt](https://github.com/microcks/microcks/files/7809472/First.Mock.API-1.0.0.yaml.txt)

I've used `siege` this time for all the tests just to align with your findings.

These are my results for different versions of Microcks:

### 1.5.0-SNAPSHOT with Statistics disabled
* 1 Pod with 1cpu and 1Gi memory
* **30 seconds with 500 concurrent users** (`siege -t30s -c500 http://microcks:8080/rest/First+Mock+API/1.0.0/hello\?name\=Testing`)
#### Results
```
Transactions:		       23238 hits
Availability:		      100.00 %
Elapsed time:		       29.74 secs
Data transferred:	        0.58 MB
Response time:		        0.14 secs
Transaction rate:	      781.37 trans/sec
Throughput:		        0.02 MB/sec
Concurrency:		      111.99
Successful transactions:       23238
Failed transactions:	           0
Longest transaction:	        1.39
Shortest transaction:	        0.03
``` 

### 1.5.0-SNAPSHOT with Statistics disabled
* 3 Pod with 1cpu and 1Gi memory
* **30 seconds with 500 concurrent users** (`siege -t30s -c500 http://microcks:8080/rest/First+Mock+API/1.0.0/hello\?name\=Testing`)
#### Results
```
Transactions:             25516 hits
Availability:             100.00 %
Elapsed time:	          29.27 secs
Data transferred:         0.63 MB
Response time:            0.07 secs
Transaction rate:         871.75 trans/sec
Throughput:               0.02 MB/sec
Concurrency:	          65.04
Successful transactions:  25516
Failed transactions:      0
Longest transaction:      1.49
Shortest transaction:     0.03
``` 

### 1.5.0-SNAPSHOT with Statistics disabled
* 3 Pod with 1cpu and 1Gi memory
* **30 seconds with 750 concurrent users** (`siege -t30s -c750 http://microcks:8080/rest/First+Mock+API/1.0.0/hello\?name\=Testing`)
#### Results
```
Transactions:             39021 hits
Availability:             100.00 %
Elapsed time:             29.12 secs
Data transferred:         0.97 MB
Response time:            0.06 secs
Transaction rate:         1340.01 trans/sec
Throughput:               0.03 MB/sec
Concurrency:              76.10
Successful transactions:  39021
Failed transactions:      0
Longest transaction:      1.64
Shortest transaction:     0.03
``` 

### 1.5.0-SNAPSHOT with Statistics disabled
* 3 Pod with 1cpu and 1Gi memory
* **5 minutes with 750 concurrent users** (`siege -t30s -c750 http://microcks:8080/rest/First+Mock+API/1.0.0/hello\?name\=Testing`)
#### Results
```
Transactions:		      416860 hits
Availability:		      100.00 %
Elapsed time:		      299.95 secs
Data transferred:	       10.34 MB
Response time:		        0.04 secs
Transaction rate:	     1389.76 trans/sec
Throughput:		        0.03 MB/sec
Concurrency:		       53.65
Successful transactions:      416860
Failed transactions:	           0
Longest transaction:	        1.20
Shortest transaction:	        0.03
``` 

### 1.5.0-SNAPSHOT with Statistics enabled
* 1 Pod with 1cpu and 1Gi memory
* **30 seconds with 500 concurrent users** (`siege -t30s -c500 http://microcks:8080/rest/First+Mock+API/1.0.0/hello\?name\=Testing`)
#### Results
```
Transactions:		       13595 hits
Availability:		      100.00 %
Elapsed time:		       29.76 secs
Data transferred:	        0.34 MB
Response time:		        0.60 secs
Transaction rate:	      456.82 trans/sec
Throughput:		        0.01 MB/sec
Concurrency:		      274.32
Successful transactions:       13595
Failed transactions:	           0
Longest transaction:	        1.91
Shortest transaction:	        0.11
``` 

### 1.5.0-SNAPSHOT with Statistics enabled
* 3 Pod with 1cpu and 1Gi memory
* **30 seconds with 500 concurrent users** (`siege -t30s -c500 http://microcks:8080/rest/First+Mock+API/1.0.0/hello\?name\=Testing`)
#### Results
```
Transactions:		       20779 hits
Availability:		      100.00 %
Elapsed time:		       29.29 secs
Data transferred:	        0.52 MB
Response time:		        0.22 secs
Transaction rate:	      709.42 trans/sec
Throughput:		        0.02 MB/sec
Concurrency:		      152.74
Successful transactions:       20779
Failed transactions:	           0
Longest transaction:	        1.14
Shortest transaction:	        0.03
``` 

### 1.5.0-SNAPSHOT with Statistics enabled
* 3 Pod with 1cpu and 1Gi memory
* **30 seconds with 750 concurrent users** (`siege -t30s -c750 http://microcks:8080/rest/First+Mock+API/1.0.0/hello\?name\=Testing`)
#### Results
```
Transactions:		       27382 hits
Availability:		      100.00 %
Elapsed time:		       29.30 secs
Data transferred:	        0.68 MB
Response time:		        0.30 secs
Transaction rate:	      934.54 trans/sec
Throughput:		        0.02 MB/sec
Concurrency:		      283.59
Successful transactions:       27382
Failed transactions:	           0
Longest transaction:	        1.60
Shortest transaction:	        0.03
``` 

### 1.5.0-SNAPSHOT with Statistics enabled
* 3 Pod with 1cpu and 1Gi memory
* **5 minutes with 750 concurrent users** (`siege -t30s -c750 http://microcks:8080/rest/First+Mock+API/1.0.0/hello\?name\=Testing`)
#### Results
```
Transactions:		      290363 hits
Availability:		      100.00 %
Elapsed time:		      299.93 secs
Data transferred:	        7.20 MB
Response time:		        0.27 secs
Transaction rate:	      968.10 trans/sec
Throughput:		        0.02 MB/sec
Concurrency:		      264.41
Successful transactions:      290363
Failed transactions:	           0
Longest transaction:	        1.80
Shortest transaction:	        0.03
``` 

In a summary, I can see a penalty in performance due to statistics. As I mentioned before after each test with statistics enabled I needed to wait for a period of time (higher the longer the tests were executed) until pods cpu usages went back to 0.

**Comment by miguelchicoespin** [comment]
About my use case, it might be a bit different from other users but I think is quite valid.
I'm planning to use Microks to decouple dependencies between several services during Load Testing. Basically, I want to exercise different parts of my system individually in different Load Tests and I want to configure mock APIs using Microcks.

The reason for this is to have a clear understanding of how my components will perform individually before checking the whole system.

I think Microcks will be able to do this work quite well using the flag we've been discussing.

I have a few more ideas if you want I'll be happy to discuss (ideas which will involve better monitoring for microcks)

**Comment by lbroudoux** [comment]
> About my use case, it might be a bit different from other users but I think is quite valid.
I'm planning to use Microks to decouple dependencies between several services during Load Testing. Basically, I want to exercise different parts of my system individually in different Load Tests and I want to configure mock APIs using Microcks.

The use-case is great! In case you're happy with what you've done and want to share more, we welcome contributions to our blog https://microcks.io/blog 😉 

> I have a few more ideas if you want I'll be happy to discuss (ideas which will involve better monitoring for microcks)

Sure! Do not hesitate also joining the Zulip chat on https://microcksio.zulipchat.com. Regarding monitoring, I am currently working on #411. It will bring Prometheus exporters for webapp and async-minion components.

**Comment by lbroudoux** [comment]
Regarding the performance tests above, it could be nice re-launching one of them with a new environment variable `JAVA_MAJOR_VERSION`=`11` on the microcks deployment. This will set other JVM ergonomics and allow JVM to run in auto-tune mode reusing cgroup constraints and limits. This is the default settings for new versions of Helm chart and Operator.

**Comment by lbroudoux** [comment]
Just created #541 to track the evolution related to adding a flag for disabling analytics.

**Comment by miguelchicoespin** [comment]
> The use-case is great! In case you're happy with what you've done and want to share more, we welcome contributions to our blog https://microcks.io/blog 😉

I would love to contribute for sure!!! Once I'm done with all the work I want to do we can consider it!!

> Regarding monitoring, I am currently working on #411. It will bring Prometheus exporters for webapp and async-minion components.

That would be perfect!! Yes, I'll keep an eye to that one as well, it would be really useful for my use case

**Comment by miguelchicoespin** [comment]
> Regarding the performance tests above, it could be nice re-launching one of them with a new environment variable `JAVA_MAJOR_VERSION`=`11` on the microcks deployment. This will set other JVM ergonomics and allow JVM to run in auto-tune mode reusing cgroup constraints and limits. This is the default settings for new versions of Helm chart and Operator.

Hi!!,
I've added the two env variables to my deployment
`- name: JAVA_OPTIONS
     value: "-XX:+TieredCompilation -XX:TieredStopAtLevel=2"
  - name: JAVA_MAJOR_VERSION
     value: "11"
`

And I've executed one test:

### 1.5.0-SNAPSHOT with Statistics enabled
* 3 Pod with 1cpu and 1Gi memory
* New default env variables added
* **5 minutes with 750 concurrent users** (`siege -t300s -c750 http://microcks:8080/rest/First+Mock+API/1.0.0/hello\?name\=Testing`)
#### Results
```
Transactions:		      249908 hits
Availability:		      100.00 %
Elapsed time:		      299.67 secs
Data transferred:	        6.20 MB
Response time:		        0.40 secs
Transaction rate:	      833.94 trans/sec
Throughput:		        0.02 MB/sec
Concurrency:		      331.48
Successful transactions:      249908
Failed transactions:	           0
Longest transaction:	        2.52
Shortest transaction:	        0.03
``` 

I think performance is a bit worse in fact using those variables but that's can be related with my kubernetes version and a lot of other factors

**Comment by lbroudoux** [comment]
In theory, `JAVA_MAJOR_VERSION` should be better but `JAVA_OPTIONS` should be worse (we change it just to make the startup faster). So I'll try letting `JAVA_OPTIONS` empty. 

Great for the blog post! We'll keep in touch!

**Comment by miguelchicoespin** [comment]
You're absolutely right!!!
Using just the JAVA_MAJOR_VERSION env variable performance much better


### 1.5.0-SNAPSHOT with Statistics enabled
* 3 Pod with 1cpu and 1Gi memory
* JAVA_MAJOR_VERSION env variable added
* **5 minutes with 750 concurrent users** (`siege -t300s -c750 http://microcks:8080/rest/First+Mock+API/1.0.0/hello\?name\=Testing`)
#### Results
```
Transactions:		      418773 hits
Availability:		      100.00 %
Elapsed time:		      299.87 secs
Data transferred:	       10.38 MB
Response time:		        0.04 secs
Transaction rate:	     1396.52 trans/sec
Throughput:		        0.03 MB/sec
Concurrency:		       51.23
Successful transactions:      418775
Failed transactions:	           0
Longest transaction:	        1.22
Shortest transaction:	        0.03
```

**Comment by lbroudoux** [comment]
Hi @miguelchicoespin,
Hope this new year will find you well !
Would you be available for a chat in DM somewhere ? 
Let me know - either through LinkedIn or mail at `laurent` at `microcks.io` ;-)

**Comment by miguelchicoespin** [comment]
Hi @lbroudoux 
Sure! I'll contact you on LinkedIn
