### ISSUE TITLE
Allow resolution of external references on OpenAPI file

### ISSUE THREAD

**Issue by lbroudoux** [microcks/microcks#548]
As of today, we have a reference resolution mechanism that is used on import time for AsyncAPI spec file. This has been added in #306 in order to support Avro schema references. It also has been used later on for gRPC support addition (one protobuf file may referenced other external protobuf files).

For unknown reasons, it hasn't been added to OpenAPI support yet. However, referencing JSON Schema files from OpenAPI files is now a very common practice (though I personally think that you then have to be very cautious on how you manage versioning of everything 😉 )

We should had this reference resolution mechanism for OpenAPI. 

It means that references will be discovered at import time but I see options on how to implement it:
1. Do not modify OpenAPI file and add extra contracts for JSON Schema to keep everything "as is".  This mean that during tests we'll have to dereference everything and create an inlined OpenAPI spec in order to ease validation,
2. Dereference everything at import time and modify OpenAPI file. This mean that we'll not have to touch everything during tests and it'll speed up things. However, user could be lost seing the import result mentioning only 1 OpenAPI file,
3. Dereference everything at import time and modify OpenAPI file, but also add extra contracts for JSON Schema to prove we discovered everything.

What do you think? Do you see any other alternatives?

My personal preference goes to `#3` that could be a nice trade-off. Let me know!

**Comment by lbroudoux** [comment]
Hi @redben! Feature is now ready. If you want to put out some tests....

**Comment by redben** [comment]
Nice! Thanks I'll try it out :)
