### ISSUE TITLE
Ability to use Wiremocks stubs

### ISSUE THREAD

**Issue by Krazybug** [microcks/microcks#550]
As we often use Wiremock during the development cycle, it would be really interesting to be able to import Wiremock stubs written in JSON directly in Microcks and to delegate the dispatch and  the response handling to them like in this example.

`{
    "request": {
        "method": "GET",
        "url": "/some/thing"
    },
    "response": {
        "status": 200,
        "body": "Hello world!",
        "headers": {
            "Content-Type": "text/plain"
        }
    }
}`

Benefits:

- larger flexibility to compose dynamic mocks (request matching and dynamic responses)
- simple solution for performance testing  
- you could reuse mocks provided by other contract testing tools like [Pact](https://bitbucket.org/atlassian/wiremock-pact-generator).   
...

Also wiremock is implemented with Java which could simplify this kind of integration and if we  also may be able  to  upload or import binaries mocks - which are standalone jars - from an artifacts repository (Nexus, ...)  it will also increase manyfold the potential of reusability.

**Comment by lbroudoux** [comment]
Thanks for creating this issue. Will have a look at it.
