### ISSUE TITLE
Problem setup microcks, /api/services -> ERROR 500

### ISSUE THREAD

**Issue by Renanh** [microcks/microcks#552]
Good afternoon, when I do the standard installation (installing my keycloak application) it really works, but I didn't import the real keyclaok, but it's already giving this test of everything.

console error:
![image](https://user-images.githubusercontent.com/8283925/152465648-020859d1-0500-4c29-b9d3-2af08e024461.png)

helm-values:
![image](https://user-images.githubusercontent.com/8283925/152465722-13d617ab-d1b4-443d-9bb9-da4e05a78658.png)

ConfigMap:
[configmap.txt](https://github.com/microcks/microcks/files/7999767/configmap.txt)

Command:
helm install -f helm/values/microcks-helm-config.yaml microcks microcks/microcks -n microcks

External Keyclaok:

![image](https://user-images.githubusercontent.com/8283925/152466092-138b231f-8d91-49df-91d6-6afa428d8bea.png)

**Comment by Renanh** [comment]
Export  Helm:
[realm-export.json.txt](https://github.com/microcks/microcks/files/7999786/realm-export.json.txt)

hiding domain = ****

**Comment by Renanh** [comment]
![image](https://user-images.githubusercontent.com/8283925/152466474-c926e58f-e121-494e-b81f-3a491c597472.png)

**Comment by lbroudoux** [comment]
Hello! If Keycloak public and private url are the same, you just have to set up the url attribute. Could you try this ?
