### ISSUE TITLE
Bearer token payload missing user roles/403 Forbidden errors

### ISSUE THREAD

**Issue by mahgo** [microcks/microcks#553]
I'm using an existing Realm in Keycloak (for Apicurio Studio) so I used this file: https://github.com/microcks/microcks/blob/6776ea9357bcfbd72383189c9f27cd3616e92b9b/install/keycloak-microcks-realm-addons.json and did a partial import into the Keycloak realm. Many of my API requests seem to be failing with a 403 Forbidden error, and it seems to be because my bearer token payload is missing the roles that the user is in (user, etc). Here's an example of my payload (with personal data removed)

```
{
  "exp": 1644197120,
  "iat": 1644196820,
  "auth_time": 1644196816,
  "jti": "17f71802-1fec-4033-8c8c-933fb76d17ed",
  "iss": "https://{keycloakurl}/auth/realms/apicurio",
  "sub": "4ba5833c-963e-4716-b09d-53e822d20a02",
  "typ": "Bearer",
  "azp": "microcks-app-js",
  "nonce": "72e642a7-a79b-4e73-ac7c-9f1b0dec388b",
  "session_state": "049549e4-fd4f-4e2f-955f-8969622c1716",
  "acr": "1",
  "allowed-origins": [
    "https://{microcksurl}"
  ],
  "scope": "openid email profile",
  "sid": "049549e4-fd4f-4e2f-955f-8969622c1716",
  "email_verified": true,
  "name": "{name}",
  "microcks-groups": [],
  "preferred_username": "{email}",
  "given_name": "{givenname}",
  "family_name": "{familyname}",
  "email": "{email}"
}
```

Here's a screenshot showing that the user has the "user" role:
![image](https://user-images.githubusercontent.com/4499646/152724330-a035b70b-df72-4446-b1a0-65b0b4281bbb.png)

Here's an example of the microcks requests failing:
![microcks403](https://user-images.githubusercontent.com/4499646/152724729-c066f383-04a2-40fe-936f-ecada9a96257.png)

Edit: I'm using Keycloak 16.1.0.

**Comment by mahgo** [comment]
@lbroudoux Do you know why this might be?

**Comment by mahgo** [comment]
Looks like setting "Full Scope allowed" as ON, as per https://microcks.io/blog/integrating-in-apicurio-keycloak/ did the trick. However microcks-groups is still empty. It must be outdated. It seems to be using the roles from "resource_access" now.

**Comment by lbroudoux** [comment]
Hi there !

```json
{
  "exp": 1645007593,
  "iat": 1645007293,
  "auth_time": 1644994695,
  "jti": "12e992a6-7df7-4390-9a84-fcf375dfb557",
  "iss": "https://{keycloaksurl}/auth/realms/microcks",
  "aud": [
    "realm-management",
    "microcks-app"
  ],
  "sub": "b8871706-b9aa-4975-93d0-a34d66101137",
  "typ": "Bearer",
  "azp": "microcks-app-js",
  "nonce": "af0bf5b1-7c73-4175-8d85-11de8ae74efa",
  "session_state": "c413873f-3546-4071-a8a4-2b5bd967d6e8",
  "acr": "1",
  "allowed-origins": [
    "https://{microcksurl}""
  ],
  "resource_access": {
    "realm-management": {
      "roles": [
        "manage-users",
        "manage-clients"
      ]
    },
    "microcks-app": {
      "roles": [
        "manager",
        "admin",
        "user"
      ]
    }
  },
  "scope": "openid profile email",
  "email_verified": false,
  "microcks-groups": [],
  "preferred_username": "admin"
}
```

The `resource_access` part is missing from your original token.

The `microcks-groups` requires to setup a protocol mapper like described here: https://github.com/microcks/microcks/blob/master/install/keycloak-microcks-realm-addons.json#L85
It has been introduced after the blog post was written ;-)

**Comment by mahgo** [comment]
Turning on "Full Scope allowed" got the "resource_access" showing up, and everything seems to be working. Yeah I have that mapper set up but it doesn't seem to do anything. Is it actually required though? Since "resource_access" seems to have fixed everything.
