### ISSUE TITLE
Docker Compose Microks installation not working on windows

### ISSUE THREAD

**Issue by aygalinc** [microcks/microcks#554]
Hello ! 

I want to try the sample of microks but docker compose setup does not work on my windows laptop. 
Seems like the keycloak container does not start .

![image](https://user-images.githubusercontent.com/4963050/153569707-e5238ea3-149e-42fb-bf0a-625d52c568b1.png)

Does anyone encounter this issue ? 

On website, home page should be updated due to new install docker compose layout (no more microks.yml file) : 
![image](https://user-images.githubusercontent.com/4963050/153569956-199d2b9e-0fb3-4158-baee-04400c87118f.png)

**Comment by aygalinc** [comment]
Workaround here : https://github.com/microcks/microcks/pull/427 fixes the start up.
Seems like keycloak not switch by default on H2 with Docker Compose version v2.2.3 on Windows 10.

**Comment by lbroudoux** [comment]
Hi there!

Thanks for raising this issue. I'll update the website asap.
Workaround #427 was never really validate. However if it fixes the windows setup, it could be added easily to the file...
I do not have a Windows machine at hand but will ask to other team mates. I'll let you know.

Anyway, in the meantime, do you that a "keycloakless" version of docker-compose exists ?
You can try `docker-compose -f docker-compose-devmode.yml up -d` for lighter experience.

**Comment by aygalinc** [comment]
I do not know. 
I try to follow the website set up. 
Just discover the website repo so I create a PR for doc adjustement & dev mode install : 
https://github.com/microcks/microcks.io/pull/44

**Comment by lbroudoux** [comment]
#427 is now merged!
