### ISSUE TITLE
Add option to set initial payload for dynamic mocks

### ISSUE THREAD

**Issue by hguerrero** [microcks/microcks#570]
When using dynamic mocks, you can set the resource that created the CRUD operations, however, you will need to POST an item to return results. It could be better if we can define an example from the beginning in this dialog.

![image](https://user-images.githubusercontent.com/1001939/156238126-9183343e-affd-4794-8974-1eed3d70df38.png)

**Comment by lbroudoux** [comment]
Great idea! Moreover this first example could be used to generate a more detailed Swagger/OpenAPI/AynsAPI bootstrap contract. We could infer this example shema and then customize the contracts. What do you think?

**Comment by hguerrero** [comment]
Yes, similar as how apicurio does when creating a new Data example

**Comment by lbroudoux** [comment]
Now done either for REST based and Event based APIs (see #582). This reference payload is then used to generate a type JSON schema in both specification artifacts.
