### ISSUE TITLE
when I use jsonBody as a dispatcher, for any situation, the first recorded response is being returned

### ISSUE THREAD

**Issue by Uilen1** [microcks/microcks#578]
when I use jsonBody as a dispatcher, for any situation, the first recorded response is being returned

![image](https://user-images.githubusercontent.com/42755635/157323086-4a128246-5b14-48aa-8090-ee40a4380450.png)

**Request1(expected "response200"):**

![image](https://user-images.githubusercontent.com/42755635/157325038-3d8a5f76-a410-40ee-bb20-9a98db2866fa.png)

**Request2(expexted "response400"):**

![image](https://user-images.githubusercontent.com/42755635/157325098-03205005-0953-4043-bfb9-19244b81fb58.png)

**Comment by lbroudoux** [comment]
Hey @Uilen1!

Could you explain what went wrong and how you solved it? Is it a matter of missing or hard to understand documentation?

Thanks,
