### ISSUE TITLE
Use of XPath functions in QUERY_MATCH Xpath expression (SoapUI)

### ISSUE THREAD

**Issue by malins** [microcks/microcks#579]
Hello,

i would like to use XPath functions such as concat as part of my XPath expression, but in SoapUIXPathBuilder only lines starting with '/' are considered. In my opinion this check doesn't make sense. Would it be possible to relax this check?

**Comment by lbroudoux** [comment]
Hi @malins 

Could you provide a sample on what you want to achieve with relaxed constraint? IIRC, we just considering `/` starting lines to get the XML Path we have to evaluate... I'd like to fully understand how you apply XPath functions to this.

Thanks,

**Comment by malins** [comment]
I want to concatenate two elements for matching, e.g.:

concat(//SomeElement/text(),'_',//OtherElement/text())

This is perfectly valid XPath, but is not recognized as XPath "line" because it doesn't start with a slash.

**Comment by lbroudoux** [comment]
Ok got it! Will check if possible.

**Comment by lbroudoux** [comment]
Hey @malins 

This is an easy enhancement and I've checked the `concat` function is correctly supported. Will push the path in `1.5.x` branch that will produce a `nightly` tagged container image.
