### ISSUE TITLE
Memory requirements customizables when running as a container

### ISSUE THREAD

**Issue by hguerrero** [microcks/microcks#58]
When deploying microcks as a container, make it possible to pass the runtime the Xmx Xms variables to the JVM so we can customize the amount of memory provided.

**Comment by lbroudoux** [comment]
This are very valid requirements for our images! I'm considering tackling #62 as a base step for this task.

**Comment by lbroudoux** [comment]
As new container image is now based on Fabric8 Java image, all the flags liste on (run-java.sh)[https://github.com/fabric8io-images/run-java-sh/blob/master/fish-pepper/run-java-sh/readme.md] are now available for JVM ergonomics customization.
