### ISSUE TITLE
Unauthorized access to documentation

### ISSUE THREAD

**Issue by claorden** [microcks/microcks#595]
Hi,

We have recently started using Microcks to share our APIs and have encountered the following issue, the documentation of the service can be accessed without going through the authentication process by simply sharing the direct link.

![image](https://user-images.githubusercontent.com/8665841/162379960-d211f20e-3841-4e77-9a14-c8c12b46d33a.png)

Corresponding link would be: http://localhost:8080/api/documentation/Service%20test-v1.json/OPEN_API_SPEC

Any ideas?

Thank you very much in advance.

Best,

Carlos.

**Comment by lbroudoux** [comment]
Hey 👋 
It works as expected: the `/documentation` endpoint is not secured.

**Comment by claorden** [comment]
Okey, thanks for the response @lbroudoux .

**Comment by lbroudoux** [comment]
Hey @claorden 

Just to let you know that we've opened the [GitHub Discussions](https://github.com/microcks/microcks/discussions) for Microcks. So do not hesitate using them for quick question like this one or if you want to discuss opportunity of adding / changing things in Microcks.

Cheers,
