### ISSUE TITLE
Unable to update the value of the file upload size via operator.

### ISSUE THREAD

**Issue by Madiha20** [microcks/microcks#607]
We have installed Microcks using `https://github.com/microcks/microcks-ansible-operator` and the size of the Postman collection we are trying to upload is around 4.8MB. Currently this is only possible if we uncomment and update the value in docker-compose.yml. Is there a way to provide this option of param configuration to be propagated to operator as we have install Microcks on OpenShift using microcks-ansible-operator.

<img width="893" alt="image" src="https://user-images.githubusercontent.com/88466826/171136980-7403f44f-3294-43a9-948a-5dc2a062cf70.png">

**Comment by lbroudoux** [comment]
Now implemented in both Operator and Helm chart.
