### ISSUE TITLE
Service not found when launching test through the API (NullPointerException)

### ISSUE THREAD

**Issue by le-yams** [microcks/microcks#610]
Hi,

When I try to launch a test  against a given service (through the api with microcks-cli) it fails with the following stacktrace in microcks server logs:

> java.lang.NullPointerException: null
at io.github.microcks.service.TestService.launchTests(TestService.java:75)
at io.github.microcks.web.TestController.createTest(TestController.java:121)
...

From what I saw in the code this only could happen if the specified service was not found in the following piece of code (`TestController.java` starting L98):

```java
if (test.getServiceId().contains(":")) {
   String name = test.getServiceId().substring(0, test.getServiceId().indexOf(':'));
   String version = test.getServiceId().substring(test.getServiceId().indexOf(':') + 1);
   service = serviceRepository.findByNameAndVersion(name, version);
} else {
   service = serviceRepository.findById(test.getServiceId()).orElse(null);
}
```

The thing is that I get the error even when specifying an existing service (well displayed in the UI, I also checked in the mongo database). I tried to use the 'id' or the 'name:version' format, both are failing.
Any idea where this could come from?

Notes: 
 * I'm using the docker-compose stack (master, commit 073200620b3f9b1525985cb0492dd8995738119b).
 * launching a test from the UI works

**Comment by lbroudoux** [comment]
Thanks for opening this issue. I'll try to reproduce it.
Have you tried looking at the logs from main microcks container? The identifier of the service (as encoded by microcks-cli) should appear there. You'd also be able to see if there's some differences with the one sent from the UI.

**Comment by avinash-avm031** [comment]
@lbroudoux I see 500 error with Null pointer exception when I started microcks using docker container.

    "timestamp": 1680092585319,
    "status": 500,
    "error": "Internal Server Error",

From the docker log I see this.

threw exception [Request processing failed; nested exception is java.lang.NullPointerException: Cannot invoke "io.github.microcks.domain.Service.getOperations()" because "service" is null] with root cause

java.lang.NullPointerException: Cannot invoke "io.github.microcks.domain.Service.getOperations()" because "service" is null
        at io.github.microcks.web.RestController.execute(RestController.java:130)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

Image - quay.io/microcks/microcks:next

**Comment by avinash-avm031** [comment]
@lbroudoux  Issue has been fixed after adding version for the mock created.

**Comment by lbroudoux** [comment]
Thanks for the feedback!
