### ISSUE TITLE
Response of wrong operation returned when no exact dispatching

### ISSUE THREAD

**Issue by imod** [microcks/microcks#614]
we have noticed the following strange behaviour, which fully blocks us now:
Given two operations:

`GET /pastry/{name}`
`GET /pastry/{name}/details`

both have there own examples. If I now call `GET /pastry/mycaffee/details` - where `mycaffee` is the value for name, but don't have an example defined for this value - I will get the mock response from `GET /pastry/{name}`.
So it seems, that if there is no matching mock for a given value, it just ignores the path and drops back to the path higher in the hierarchy.

**Comment by imod** [comment]
@lbroudoux many thanks, do you know if the microcks-operator accepts sha as image idenitfier - e.g. for this exact change it would be:
```
spec:
   version: sha256:bf561691961bf24a8e04fe27ba4c5fc396fee173b96d8b4f564614bc2eec9703
```

**Comment by lbroudoux** [comment]
Unfortunately no. The `spec.version` is used as a tag to build the images from various components (main, minion and postman runtime)... So specifying a sole image sha256 cannot work.

At the moment I don't see any opportunity - nor free time for me - to release 1.5.3 sorry... However `nightly` is now plugged on `1.6.x` branch. So as long as we do not rollback the PR, the fix must not disappear from new `nightly` images.

Are you heading to production in coming days/weeks?

**Comment by imod** [comment]
so far this is fine, no problem. Just wanted to understand.
But one thing coming up on our site soon is, that we will not be able to connect to the internet anymore - so we will need to provide all the images from an internal registry. This is a security measure, to prevent from supply chain attacks.

**Comment by lbroudoux** [comment]
OK noticed! Maybe we could add a `spec.registry` in the CRD. Once specified it would be used in place of the default `quay.io`. What do you think?
