### ISSUE TITLE
Queue and binding not created in RabbitMQ

### ISSUE THREAD

**Issue by 4ebyrek** [microcks/microcks#618]
Hi everybody !!

You create cool tool, but i thing i found bug. Queue and binding not created in RabbitMQ after importing .yaml file.
microcks, microcks-minion version is 1.5.2
this is my config file
[rabbit-test.txt](https://github.com/microcks/microcks/files/8967829/rabbit-test.txt)

**Comment by lbroudoux** [comment]
Hey @4ebyrek,
Could you please add here more details on the process you're following, results you expect to see and those you actually get? I'm in the process of writing a guide for RabbitMQ, I could review and integrate your use-case if provided.

**Comment by lbroudoux** [comment]
Hey @4ebyrek 
Re-read your message and its true that queue and binding are not created on the RabbitMQ side when starting the mocks : we only create the exchange and then it's up to you to declare associated queues and bindings depending on how you want to consume messages.
