### ISSUE TITLE
Dispatcher URI_PARTS does not ignore url-parts not mentioned in rule

### ISSUE THREAD

**Issue by ChristianLangmann** [microcks/microcks#619]
When having an API with multiple URL-Path-parameters and a dispatchers  not including all of those parameters, the missing ones are not ignored when selecting the response.

For example a path .../{a}/{b} and a dispatcher URL_PARTS with rule "a" and provided examples for parameter a does not find the correct response ignoring parameter b. This actually works when using query-parameters (URL_PARAMS).

Attached is a simple openAPI-Spec describing this behaviour.
[mock-test - issue.yaml.zip](https://github.com/microcks/microcks/files/8977656/mock-test.-.issue.yaml.zip)

> curl http://localhost:8080/rest/mock-test/1.0/base/a1/undefined 
should return {"res":"A-1"}
> curl http://localhost:8080/rest/mock-test/1.0/base/a2/undefined 
should return {"res":"A-2"}

but they return the same result.

The log shows:
i.github.microcks.web.RestController     : Request body: null
i.github.microcks.web.RestController     : Found resourcePath: /base/a2/undefined
i.github.microcks.web.RestController     : Found a valid operation GET /base/{a}/{b} with rules: a
i.github.microcks.web.RestController     : Dispatch criteria for finding response is /a=a2/b=undefined
i.github.microcks.web.RestController     : No responses found so far, tempting with just bare operationId...

**Comment by lbroudoux** [comment]
Hi @ChristianLangmann, thanks for creating this issue. Could you please specify the version of Microcks you're using ? I think we made some changes in `1.6.x` so that I'm not should it would event match the correct operation...

**Comment by ChristianLangmann** [comment]
Hi Laurent,

I’m using Microcks 1.5.3. 

Best regards
Christian
---
Christian Langmann | Solution Architect

codecentric AG | Große Elbstraße 14 | 22767 Hamburg | Deutschland
mobil: +49 (0) 173. 6447742
www.codecentric.de | blog.codecentric.de | www.meettheexperts.de

Sitz der Gesellschaft: Solingen | HRB 25917| Amtsgericht Wuppertal
Vorstand: Rainer Vehns (Vorsitzender) . Ulrich Kühn . Lars Rückemann
Aufsichtsrat: Patric Fedlmeier (Vorsitzender) . Klaus Jäger . Jürgen Schütz . Michael Hochgürtel

Diese E-Mail einschließlich evtl. beigefügter Dateien enthält vertrauliche und/oder rechtlich geschützte Informationen. Wenn Sie nicht der richtige Adressat sind oder diese E-Mail irrtümlich erhalten haben, informieren Sie bitte sofort den Absender und löschen Sie diese E-Mail und evtl. beigefügter Dateien umgehend. Das unerlaubte Kopieren, Nutzen oder Öffnen evtl. beigefügter Dateien sowie die unbefugte Weitergabe dieser E-Mail ist nicht gestattet.

**Comment by lbroudoux** [comment]
Thanks Christian for the associated PR. I'm currently reviewing it.

**Comment by lbroudoux** [comment]
Thanks a lot, Christian for the diagnosis and full PR!

Applied your simple openAPI-Spec on `1..6.x` and got this results:

```sh
$ curl http://localhost:8080/rest/mock-test/1.0/base/a1/undefined
{"res":"A-1"}
```
with logs:
```
18:02:17.994  INFO 72833 --- [080-exec-1] i.github.microcks.web.RestController     : Servicing mock response for service [mock-test, 1.0] on uri /rest/mock-test/1.0/base/a1/undefined with verb GET
18:02:17.995 DEBUG 72833 --- [080-exec-1] i.github.microcks.web.RestController     : Request body: null
18:02:18.009 DEBUG 72833 --- [080-exec-1] i.github.microcks.web.RestController     : Found resourcePath: /base/a1/undefined
18:02:18.071  INFO 72833 --- [080-exec-1] org.mongodb.driver.connection            : Opened connection [connectionId{localValue:3, serverValue:37}] to localhost:27017
18:02:18.137 DEBUG 72833 --- [080-exec-1] i.github.microcks.web.RestController     : Found a valid operation GET /base/{a}/{b} with rules: a
18:02:18.140 DEBUG 72833 --- [080-exec-1] i.github.microcks.web.RestController     : Dispatch criteria for finding response is /a=a1
18:02:18.167 DEBUG 72833 --- [    task-1] i.g.m.listener.DailyStatisticsFeeder     : Received a MockInvocationEvent on mock-test - v1.0
```

AND

``sh
$ curl http://localhost:8080/rest/mock-test/1.0/base/a2/undefined
{"res":"A-2"}
```
with logs:
```
18:02:23.571  INFO 72833 --- [080-exec-2] i.github.microcks.web.RestController     : Servicing mock response for service [mock-test, 1.0] on uri /rest/mock-test/1.0/base/a2/undefined with verb GET
18:02:23.572 DEBUG 72833 --- [080-exec-2] i.github.microcks.web.RestController     : Request body: null
18:02:23.572 DEBUG 72833 --- [080-exec-2] i.github.microcks.web.RestController     : Found resourcePath: /base/a2/undefined
18:02:23.578 DEBUG 72833 --- [080-exec-2] i.github.microcks.web.RestController     : Found a valid operation GET /base/{a}/{b} with rules: a
18:02:23.579 DEBUG 72833 --- [080-exec-2] i.github.microcks.web.RestController     : Dispatch criteria for finding response is /a=a2
18:02:23.584 DEBUG 72833 --- [    task-2] i.g.m.listener.DailyStatisticsFeeder     : Received a MockInvocationEvent on mock-test - v1.0
```

Awesome!
