### ISSUE TITLE
Form-URL-Encoded Request body parsing not working in Script

### ISSUE THREAD

**Issue by geekdeb** [microcks/microcks#620]
How to handle **Form-URL-encoded** request bodies in the dispatcher using SCRIPT ?
For JSON requests we are using **JSONSlurper** class. 

Please guide for Form-URL-encoded requests.

Thanks,
GeekDeb

**Comment by lbroudoux** [comment]
Hi there,

sorry for lack fo documentation on `SCRIPT` dispatching...

Request body is generally made available through `mockRequest.requestContent` that will give you raw string representation of body.

Assuming you're doing a GET (with a body that is a bad practice :-() or other but no `application/x-www-form-urlencoded` content-type, you may check with:

```groovy
log.info("body: " + mockRequest.requestContent)
```

However in the case of the `application/x-www-form-urlencoded` content-type request and `POST`, `PUT` or `PATCH` verb, content in decoded and put into a Java HttpServletRequest at the SpringBoot level. `mockRequest` allows you to access it using the `request` attribute like :

```groovy
log.info("foo: " + mockRequest.request.getParameterValues("foo"))
log.info("key1: " + mockRequest.request.getParameterValues("key1"))
``` 

Parameters can also be extracted from URL after the `?` (but a bad practice :-( )

Hope it helps,

**Comment by geekdeb** [comment]
Thanks for the response. I am using the below code to parse.

```
def body = mockRequest.requestContent;
def map = body.split('&').collectEntries{e->
                  e.split('=').collect{ URLDecoder.decode(it,"UTF-8") }
}
println map.key1;
println map.key2;
```
So map.key1 gives the value of key1. I am good now :). Thanks again :)

**Comment by lbroudoux** [comment]
Great! Can you close this issue? BTW do not forget to star the project if you like what we're doing here 😉
