### ISSUE TITLE
improve the error messages for OPEN API SCHEMA tests

### ISSUE THREAD

**Issue by imod** [microcks/microcks#626]
We use the OPEN API SCHEMA tests on microcks own endpoints to validate the mocks itself. Often we get schema validation errors which are very hard to identify the exact issue.

The mocks/examples are provided via postman collection - for example for for a POST request some JSON input and some JSON in the response. I now just got this error back:
```
instance failed to match all required schemas (matched only 1 out of 2)/n
```
OK, I guess either the request payload or the response do not match the schema - but which one? and where is the error exactly?

**Comment by lbroudoux** [comment]
Hey @imod 

Yes, validation messages can be a bit cryptic if you're not a JSON Schema expert. BTW they're not defined by Microcks as we rely on an external library for this. That said, they can maybe be customized ... I'll have a look at this...

In your current case, is the message correct (despite being cryptic)? Is it really a problem regarding an `all` sub-schemas validation failure?

**Comment by imod** [comment]
@lbroudoux getting improved validation messages would be great, but in the meantime it would even help if the error message would tell which of the validated payloads are actually failing.

`instance failed to match all required schemas (matched only 1 out of 2)`

only says the 1 out of 2 have failed, but the user has no idea whether it is the request or the response which failed the validation.

**Comment by lbroudoux** [comment]
Hi @imod,

During `OPEN API SCHEMA` tests we just validate the request against its defined schema. My guess here is that you should have a complex construct of schemas composition using `all` or something like that. I think that's the reason of partial message validation.

I'll try to find some free cycle to dive deep in validation to see if we can enhance things for the future.

**Comment by imod** [comment]
oh, you only check the request against the schema? thats actually a bummer, I was only looking for the exact opposite. 
I always point the `OPEN API SCHEMA` against microcks own endpoint to check if all the mock responses are actually following the contract/spec. This now makes it quite useless for me now :(

**Comment by lbroudoux** [comment]
I mean `response` and not request, sorry... I edited my above comment.

**Comment by imod** [comment]
reading your above response again, what do you mean with "schemas composition using `all`"? You mean a OAS having references to other external documents? we don't have this, its always just one singel OAS file containing the complete spec, no ref to any external/second artifact/document.

**Comment by lbroudoux** [comment]
I was thinking of a JSON schema composition if you have some kind of polymorphism/abstraction in your data. They can be defined inline in the OpenAPI file without no external ref. Would you want to share a simple reproducer so that I can check?
