### ISSUE TITLE
Keycloak 18 is not compatible

### ISSUE THREAD

**Issue by trinhpham** [microcks/microcks#628]
Hello, I have an up to date Keycloak deployment (version 18) already. I did follow the guide to integrate with external keycloak service, but it seems doesn't work. Chrome devtools shows that there's a 404 error request to step1.html of keycloak.
Quick search gets me to a thread on SO that the client version of webapp (I saw it's 14) is not matched with server version.
I've tried to update by myself but failed to build, look like I need more guidance.
Could anyone help?

**Comment by lbroudoux** [comment]
Hey @trinhpham,

Updating to the latest Keycloak-X is something we should handle in near future. It's great to share your experiment with it. I think you probably had to also update the JS lib that is included on the client-side. It is referenced into the `package.json` descriptor that comes into `/webapp/src/main/webapp` folder. After that you'll need to rebuild your own container image for webapp. Please consider doing this into the `1.6.x`  branch that is the one we're currently woirking on.

**Comment by trinhpham** [comment]
I tried, but it doesn't work :(
Have to deploy keycloak 14 for temp.
Will bak to this when I have time

**Comment by lbroudoux** [comment]
This will be tracked in #691 and addressed for Microcks 1.7
