### ISSUE TITLE
Microcks 1.5.2 RBAC label/domain manager : problems with such "manager/label"users

### ISSUE THREAD

**Issue by GuillaumeGONANO** [microcks/microcks#639]
Hello.

Using Microcks 1.5.2, we are facing behaviors that are not expected ones according to documentation :
A standard user with “manager for domain=pastry” (/microcks/manager/pastry) cannot
   1.	Delete a Mock that is assigned a label “domain=pastry”
   2.	Edit labels on such a Mock (assigned the label “domain=pastry)

The related doc. :
  https://microcks.io/documentation/using/advanced/organizing/#rbac-security-segmentation
  https://microcks.io/documentation/administrating/users/#group-membership

The attached file provides more details & steps to reproduce problem/behavior.

Thanks for your help & reply
[Microcks1.5.2_RBAC_Managers_Problem.docx](https://github.com/microcks/microcks/files/9207407/Microcks1.5.2_RBAC_Managers_Problem.docx)
.

**Comment by lbroudoux** [comment]
Hi,

Thanks a lot for using Microcks and for this issue. I just made a quick test on the latest `1.6.x` that has - theorically - no changes on this feature and was not able to reproduce it ...

I've been through your document and from your trace I suspect an issue with the way the JWT is propagated to the backend. A quick check on your side would be to capture - from the browser developer tools - the authorization bearer header and decode it (with jwt.io for example) to check it out.

A valid token should look like below with roles and extracted groups : 
 
```json
{
  "exp": 1659021153,
  "iat": 1659020853,
  "auth_time": 1659020810,
  "jti": "c2df16b8-34ce-42f8-b8de-05e9031e704d",
  "iss": "http://localhost:8180/auth/realms/microcks",
  "aud": "microcks-app",
  "sub": "c9faeef9-d772-4e93-8f52-ba390f40b2b4",
  "typ": "Bearer",
  "azp": "microcks-app-js",
  "nonce": "b776206a-67c6-4936-8edd-7627393b0fdf",
  "session_state": "d115ac60-2234-40cb-92f8-24b6f7b6a20f",
  "acr": "0",
  "allowed-origins": [
    "http://localhost:4200",
    "https://localhost:8080"
  ],
  "resource_access": {
    "microcks-app": {
      "roles": [
        "user"
      ]
    }
  },
  "scope": "openid profile email",
  "email_verified": false,
  "name": "Sarah Doe",
  "microcks-groups": [
    "/microcks/manager/authentication",
    "/microcks/manager/pastry"
  ],
  "preferred_username": "sdoe",
  "given_name": "Sarah",
  "family_name": "Doe",
  "email": "sdoe@gmail.com"
}
```

Try to think of what's could go wrong though...

**Comment by GuillaumeGONANO** [comment]
Many thanks for the clue, Laurent

You're right, actually we don"t have the "microcks-groups" :-(
Here's the full result of our "authorization: Bearer" token decoded in https://jwt.io/ :
`{
  "exp": 1659132754,
  "iat": 1659096755,
  "auth_time": 1659096754,
  "jti": "a960c7ee-40e7-43de-9c69-951b44a766af",
  "iss": "https://keycloak-service.dev.echonet/auth/realms/microcks",
  "aud": "microcks-app",
  "sub": "719b5eca-501d-40e2-80a7-7bcb0a9a84ce",
  "typ": "Bearer",
  "azp": "microcks-app-js",
  "nonce": "2dde932b-697a-4b3d-8984-9ab1fdb59b77",
  "session_state": "653c1bc6-ae3f-49a3-8dec-6d9fefafc184",
  "acr": "1",
  "allowed-origins": [
    "*"
  ],
  "resource_access": {
    "microcks-app": {
      "roles": [
        "user"
      ]
    }
  },
  "scope": "openid email profile",
  "email_verified": true,
  "name": "Guillaume GONANO",
  "preferred_username": "825456",
  "given_name": "Guillaume",
  "family_name": "GONANO",
  "email": "guillaume.gonano@externe.bnpparibas.com"
}`

**Comment by lbroudoux** [comment]
Yes this is certainly due to the upgrade as we added a new token mapper to support this feature in 1.4 if I remember correctly. I'll have a look at it but realm definition must have been updated accordingly. Let me check.

**Comment by lbroudoux** [comment]
Have a look at install/keycloak-microcks-realm-full.json on line 137. Here is the mapper definition.

**Comment by leilaslimani** [comment]
Hello,
Thank you for your reply. 
Problem solved with the last version of  install/keycloak-microcks-realm-full.json, the version of our realm definition was not updated accordingly to RBAC.
what is the best way to update a realm configuration when we have a major change ?

**Comment by lbroudoux** [comment]
I think that importing the partial JSON on top of existing realm config should only update the new / changed elements but it has to be tested 😉
