### ISSUE TITLE
Dynamic array response

### ISSUE THREAD

**Issue by mflasquin** [microcks/microcks#640]
Hi,
I know that is possible to use dynamic parameter or request parameter in response example. But it is possible to build a response with a json array that will fit with a request array.

For example, I have a request similar to :

`[
    {
        "id": "1111",
        "productsWithQuantity": [
            {
                "quantity": 1,
                "product": {
                    "erpId": "1234"
                }
            },
            {
                "quantity": 5,
                "product": {
                    "erpId": "5678"
                }
            }
        ]
    },
    {
        "id": "2222",
        "productsWithQuantity": [
            {
                "quantity": 2,
                "product": {
                    "erpId": "91011"
                }
            }
        ]
    }
]
`

I want a response with similar content (with some other fields but especially the same number of elements)

Thanks

**Comment by lbroudoux** [comment]
Hi @mflasquin 

As of today, this is not directly possible. As you may know, you'll be able to reuse response array elements information but you'll need to know the size of an array. There's no direct notation for placeholder in response to replace by an array in request whatever the type and size of array... 

That said, that should be difficult nor impossible to implement ... We'd need to think about a way and notation to express this. Any idea of how you'd like to use such a feature ?

**Comment by dorianbrun** [comment]
Hi @lbroudoux,

I'm interested by this subject and would like to know if there is a way to achieve this dynamic response in the future releases, with SCRIPT Dispatcher for instance ?

Something that can iterate on the array in a request payload and then build an array response.

Thanks,

**Comment by lbroudoux** [comment]
Thanks to #681 and with explanations provided in #751, this is now possible!
