### ISSUE TITLE
hitting localhost:8080 fails because authentication doesn't work

### ISSUE THREAD

**Issue by DeanPack** [microcks/microcks#641]
I'm following the getting started guide found here: 
https://microcks.io/documentation/getting-started/
after I run docker compose up -d the microcks-sso container fails with the error:
```
microcks-sso | User with username 'admin' already added to '/opt/jboss/keycloak/standalone/configuration/keycloak-add-user.json'
```

**Comment by lbroudoux** [comment]
Hey @DeanPack 
Sorry for the very long response time but totally skip this one... Did you have the opportunity to run another test since then? Is it still occurring? Thanks,
