### ISSUE TITLE
OpenAPI spec for contracts link returns error

### ISSUE THREAD

**Issue by VinayBhalerao** [microcks/microcks#65]
After a successful import of the spec, click on the below link per screenshot

![microcks-ui](https://user-images.githubusercontent.com/7827135/47444109-98829500-d76a-11e8-9df2-b38bf3a1b99e.png)

It navigates to http://microcks.dil.opentry.me/api/resources/5bdxxxxxx and below error is displayed

![microcks_dil_opentry_me_api_resources_5bd092e0c5836b0001282179](https://user-images.githubusercontent.com/7827135/47444172-bc45db00-d76a-11e8-9878-ca17d4650c5e.png)

**Comment by lbroudoux** [comment]
Thanks for opening this issue. This bug is related to migration to new UX. It should be easy to fix.
