### ISSUE TITLE
Installation on Windows with podman fails

### ISSUE THREAD

**Issue by kervoaz** [microcks/microcks#665]
Hello,

I have encountered 2 issues during installation of Microcks on my Windows laptop with Podman:

- **error:** short-name resolution enforced but cannot prompt without a TTY
   **cause:** mongo and keycloak images cannot be pull because name are not fully qualified
  **solution:** need to add "docker.io/" in the template 

- **error:** Failed to initialize authentication subsystem
**cause:** ip is not discovered by run-microcks.sh
**solution:** for local usage, need to force host_ip to localhost in run-microcks.sh

probably due to my corporate laptop, impossible to install on minikube via helm...

Hope this help

**Comment by lbroudoux** [comment]
This has been fixed in later releases of the Podman suport.
