### ISSUE TITLE
Stateful behaviour

### ISSUE THREAD

**Issue by alexec** [microcks/microcks#667]
Hi,

I'm trying to find a OSS API simulation framework that supports **statefule behaviour**, i.e.:

* You can define the behaviour of each operation using a Turing complete programming language, rather than a DSL/CSV/file.
* That behaviour has access to read and update state.

This is so I can build an API sandbox platform using that framework. 

Tools like WireMock are not good enough because they often only do mocking, i.e. dummy example responses to requests. 

Could Microcks work?

Alex

**Comment by lbroudoux** [comment]
Hi @alexec,

As of today, Microcks does not provide the kind of stateful behaviour you describe. We try to provide "smart mocks" by including some features like:

* [Variables Reference Expressions](https://microcks.io/documentation/using/advanced/templates/#variable-reference-expressions) to reuse elements of incoming request to build response elements,
* [Function Expressions](https://microcks.io/documentation/using/advanced/templates/#variable-reference-expressions) to include some variations in response,
* [Custom dispatchers](https://microcks.io/documentation/using/advanced/dispatching/) to customize request-to-response routing,
* and have discussions around [Response context customizaiton](https://github.com/microcks/microcks/issues/621).

Our closest feature to statefulness is called [Direct API](https://microcks.io/documentation/using/dynamic/#rest-api) but we see it more as a way to have a quick sandbox for CRUD operations on WIP design.

I'd be really happy to pursue discussion to be sure to understand what you have in mind and if we can make things change for future releases. Do you already have use-case/usage scenario in mind? Projections on how you'd like to use that feature? Any samples/illustrations will be of great help!

**Comment by lbroudoux** [comment]
Closing for no response. Please open a new discussion if wanted to chat on this topic again.
