### ISSUE TITLE
[HELP] Update specification need Minion restart

### ISSUE THREAD

**Issue by manuel-padovani** [microcks/microcks#675]
Hello,

I have a (long time) working installation of asyc-microcks and it works great for my sandbox purposes. 
I appreciated so much your continuos improvement for any kind of requests/suggests coming from the community.

...but now I need some help :)

When I update the specification in Microcks Web App, then I need to manually restart async minion in order to get update propagated. I've read through documentation that it should works automatically.

Just to give some architecture info I have the following:

1. Azure App Service: Microcks Web App (quay.io/microcks/microcks:1.6.0) + postman (quay.io/microcks/microcks-postman-runtime:1.5.0)
2. Azure App Service: Keycloak (jboss/keycloak:14.0.0)
3. Azure Container Instance: Async minion (quay.io/microcks/microcks-async-minion:1.6.0-fix-2)+ kafka + zookeeper (quay.io/strimzi/kafka:0.30.0-kafka-3.1.0)
4. Azure Container Instance: Artemis MQ (for MQTT purposes vromero/activemq-artemis:latest-alpine)
5. Azure Cosmos DB with MongoDb API (instead of pure MongoDB container)

With previous version I was never able to make it works "automatically" and with the newer again nothing, so I'm prety sure that I have some configuration missing or bad implemented. I can't understand which service need to communitace with others in order to make everything works.

Thanks
Manuel

**Comment by lbroudoux** [comment]
Hey @manuel-padovani 
A bit on the rush today but will try to get back to you as soon as possible.
Cheers,

**Comment by lbroudoux** [comment]
Hey @manuel-padovani 

Thanks for your question. As you guessed, updating an AsyncAPI specification within Microcks should trigger real-time propagation of the mock definition to the `async-minion` component that updates its mock messages.

Here's below a first check list of things that pops out of my mind:

1. Ensure that `async-api.enabled=true` into microcks web app `application.properties` config file,
2. Turn on `DEBUG` log level and check the logs on microcks main container, when publishing a new spec version, you should see something like:
```
18:31:21.866 DEBUG 59130 --- [080-exec-5] i.g.microcks.service.ServiceService      : Service [User signed-up API, 0.1.1] exists ? true
18:31:21.926 DEBUG 59130 --- [080-exec-5] i.g.microcks.service.ServiceService      : Service change event has been published
18:31:21.926 DEBUG 59130 --- [    task-3] i.g.m.l.ServiceChangeEventPublisher      : Received a ServiceChangeEvent on 633c5fb1c15dcd6640a62f88
18:31:21.926  INFO 59130 --- [080-exec-5] i.g.microcks.service.ServiceService      : Having imported 1 services definitions into repository
[...]
18:31:21.931 DEBUG 59130 --- [    task-3] i.g.m.l.ServiceChangeEventPublisher      : Processing of ServiceChangeEvent done !
```
If you don't see this line with `ServiceChangeEventPublisher`, you may probably have an issue connecting to your Kafka broker from the web app pod.

3. Check the logs on the `async-minion` for same timestamp and you should have something like the lines below. An service `UPDATED` event is received, operation is found as a candidate for mocking, schema is updated in local registry and mocks are produced just after:
```
2022-10-04 18:31:21,952 INFO  [io.git.mic.min.asy.AsyncMockDefinitionUpdater] (vert.x-eventloop-thread-0) Received a new change event [UPDATED] for '633c5fb1c15dcd6640a62f88', at 1664901081929
2022-10-04 18:31:21,952 INFO  [io.git.mic.min.asy.AsyncMockDefinitionUpdater] (vert.x-eventloop-thread-0) Found 'SUBSCRIBE user/signedup' as a candidate for async message mocking
2022-10-04 18:31:21,975 INFO  [io.git.mic.min.asy.SchemaRegistry] (vert.x-eventloop-thread-0) Updating schema registry for 'User signed-up API - 0.1.1' with 1 entries
2022-10-04 18:31:23,619 INFO  [io.git.mic.min.asy.pro.ProducerManager] (QuarkusQuartzScheduler_Worker-9) Producing async mock messages for frequency: 3
2022-10-04 18:31:23,620 INFO  [io.git.mic.min.asy.pro.KafkaProducerManager] (QuarkusQuartzScheduler_Worker-9) Publishing on topic {UsersignedupAPI-0.1.1-user-signedup}, message: {"id": "HhsalLj1j880W95xcx1R9qLFSoc74tOB", "sendAt": "1664901083620", "fullName": "Laurent Broudoux", "email": "laurent@microcks.io", "age": 41} 
```
If you don't see anything coming from Kafka, you may have a connection issue. I think your Microcks web app component connection is OK to retrieve the schema as you said it's working on restart. When restarting the minion is calling the API to fetch candidate AsyncAPIs.

Hope it helps!

**Comment by lbroudoux** [comment]
Hey @manuel-padovani 

Looks like you Kafka bootstrap service host is identified as `kafka` on port `19092` but cannot be resolved. Depending on how you setup your environment, you'll have to adapt the `kafka.uri` custom resource property or `values.yml` to match the hostname and port of Azure Container Service running the Strimzi kafka.

**Comment by manuel-padovani** [comment]
Hey @lbroudoux ,

I'm sorry for late reply but others topic has taken me outside for a while.

I'm using the `docker-compose` deploy method and I've checked the `application.properties` file and looks like following:

```
# Access to Kafka broker.
%docker-compose.kafka.bootstrap.servers=mymicrocksbackend.northeurope.azurecontainer.io:19092

# Do not save any consumer-offset on the broker as there's a re-sync on each minion startup.
%docker-compose.mp.messaging.incoming.microcks-services-updates.enable.auto.commit=false
%docker-compose.mp.messaging.incoming.microcks-services-updates.bootstrap.servers=mymicrocksbackend.northeurope.azurecontainer.io:19092
```

in WebApp `docker-compose` file I've set up the following environment value:

`   - KAFKA_BOOTSTRAP_SERVER=mymicrocksbackend.northeurope.azurecontainer.io:19092`

I think that everythings is properly configured , but webapp logs still writes "kafka:19092", it is wired.

Thank you
Manuel

**Comment by lbroudoux** [comment]
🤔 Mmm ... seems properly configured to me .... Anywhere in your config where you can still have this `kafka:19092`? Made a quick search on code an there's no such hard-coded value ...

**Comment by lbroudoux** [comment]
Hey there!
Sorry for the very long delay... Could you share an update on this one please?

**Comment by manuel-padovani** [comment]
Hey,

not good news from my side. I could not be able to resolve and I still need to restart my backend container time by time.
