### ISSUE TITLE
Microcks Getting Started doesn't work, fails with error on MacOS M1

### ISSUE THREAD

**Issue by dewrich** [microcks/microcks#676]
Running Docker on MacOS M1

1. After following the directions to "cd microcks/install/docker-compose", the following errors occurred on startup:

microcks-sso              | 15:51:24,142 ERROR [org.jboss.modcluster] (ServerService Thread Pool -- 58) MODCLUSTER000034: Failed to start advertise listener: java.net.SocketException: Protocol not available (Error setting socket option)
microcks-sso              | 	at java.base/java.net.PlainDatagramSocketImpl.socketSetOption0(Native Method)
microcks-sso              | 	at java.base/java.net.PlainDatagramSocketImpl.socketSetOption(PlainDatagramSocketImpl.java:91)
microcks-sso              | 	at java.base/java.net.AbstractPlainDatagramSocketImpl.setOption(AbstractPlainDatagramSocketImpl.java:352)
microcks-sso              | 	at java.base/java.net.MulticastSocket.setInterface(MulticastSocket.java:477)
microcks-sso              | 	at org.jboss.mod_cluster.core@1.4.3.Final//org.jboss.modcluster.advertise.impl.AdvertiseListenerImpl.init(AdvertiseListenerImpl.java:151)
microcks-sso              | 	at org.jboss.mod_cluster.core@1.4.3.Final//org.jboss.modcluster.advertise.impl.AdvertiseListenerImpl.start(AdvertiseListenerImpl.java:161)
microcks-sso              | 	at org.jboss.mod_cluster.core@1.4.3.Final//org.jboss.modcluster.ModClusterService.init(ModClusterService.java:166)
microcks-sso              | 	at org.wildfly.mod_cluster.undertow@23.0.2.Final//org.wildfly.mod_cluster.undertow.UndertowEventHandlerAdapterService.start(UndertowEventHandlerAdapterService.java:83)
microcks-sso              | 	at org.wildfly.clustering.service@23.0.2.Final//org.wildfly.clustering.service.AsyncServiceConfigurator$AsyncService.lambda$start$0(AsyncServiceConfigurator.java:117)
microcks-sso              | 	at org.jboss.threads@2.4.0.Final//org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
microcks-sso              | 	at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1990)
microcks-sso              | 	at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1486)
microcks-sso              | 	at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1377)
microcks-sso              | 	at java.base/java.lang.Thread.run(Thread.java:829)
microcks-sso              | 	at org.jboss.threads@2.4.0.Final//org.jboss.threads.JBossThread.run(JBossThread.java:513)
microcks-sso              |

============================================================================================

microcks-sso              | 15:51:30,915 ERROR [org.jgroups.protocols.UDP] (ServerService Thread Pool -- 58) failed setting interface to /172.23.0.3: java.net.SocketException: Protocol not available (Error setting socket option)
microcks-sso              | 15:51:30,922 ERROR [org.jgroups.protocols.UDP] (ServerService Thread Pool -- 58) failed setting interface to /172.23.0.3: java.net.SocketException: Protocol not available (Error setting socket option)
microcks-sso              | 15:51:30,926 ERROR [org.jboss.msc.service.fail] (ServerService Thread Pool -- 58) MSC000001: Failed to start service org.wildfly.clustering.jgroups.channel.ee: org.jboss.msc.service.StartException in service org.wildfly.clustering.jgroups.channel.ee: java.lang.IllegalStateException: java.net.SocketException: Protocol not available
mic

**Comment by lbroudoux** [comment]
Thanks for opening this issue. The documentation needs an update as when running on MacOS M1, you'd need to replace the `jboss/keycloak:14.0.0` with `wizzn/keycloak:14`. Think I'm gonna push another docker-compose file....

**Comment by dewrich** [comment]
@lbroudoux thanks for the quick response, during my surfing in the code I found that Docker image change and it works.  Should I close this issue or let it be the driver to improve the doc?

**Comment by lbroudoux** [comment]
Please keep it open so that I'll remember I'll have to update the doc.

**Comment by lbroudoux** [comment]
Doc is now updated.
