### ISSUE TITLE
Getting started behind a proxy

### ISSUE THREAD

**Issue by dbl81** [microcks/microcks#693]
Hi,
I'm trying to follow the _getting started_ guide, but I run into a exception because of our corporate proxy.

I have used the docker-compose version because I would like to quickly spin up a Microcks instance in order to play a bit with it.
Looking at the docker-compose logs I can see that all the containers are up and running.

I tried to import the [openapi 3 example](https://raw.githubusercontent.com/microcks/microcks/master/samples/APIPastry-openapi.yaml) with the _vannilla_ Microcks docker-compose installation and it doesn't work as expected because of our corporate proxy.

The import process stops:
![image](https://user-images.githubusercontent.com/43345110/203045122-9ce62e53-a679-4b73-ab7a-669a9b2320c8.png)

Looking at **logs**:

> microcks    | 11:51:47.548  INFO 1 --- [080-exec-4] i.g.microcks.service.ServiceService      : Importing service definitions from https://raw.githubusercontent.com/microcks/microcks/master/samples/APIPastry-openapi.yaml
microcks    | 11:51:55.864 ERROR 1 --- [080-exec-9] i.g.microcks.service.ServiceService      : Exception while downloading https://raw.githubusercontent.com/microcks/microcks/master/samples/APIPastry-openapi.yaml
microcks    |
microcks    | java.net.ConnectException: Connection timed out (Connection timed out)

Surfing your issues board I found this one:
https://github.com/microcks/microcks/issues/353

So I have configured our corporate proxy in the docker-compose.yml, with the following properties:
* PROXY_HOST
* PROXY_PORT
* PROXY_USERNAME
* PROXY_PASSWORD
* PROXY_EXCLUDE

Now I can start the import job successfully :
![image](https://user-images.githubusercontent.com/43345110/203047293-5286847d-6882-403e-afb6-406eca910545.png)

but the api doesn't appear in the _APIs | Services_ page.
Looking at the logs:

> microcks    | 11:57:30.016  INFO 1 --- [080-exec-1] i.g.microcks.service.ServiceService      : Importing service definitions from https://raw.githubusercontent.com/microcks/microcks/master/samples/APIPastry-openapi.yaml
microcks    | 11:57:30.103 ERROR 1 --- [080-exec-1] i.g.microcks.service.ServiceService      : Exception while downloading https://raw.githubusercontent.com/microcks/microcks/master/samples/APIPastry-openapi.yaml
microcks    |
microcks    | java.net.UnknownHostException: http://PROXY_HOST:PROY_PORT
microcks    |   at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:229)
microcks    |   at java.base/java.net.Socket.connect(Socket.java:609)
microcks    |   at java.base/java.net.Socket.connect(Socket.java:558)
microcks    |   at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:182)
microcks    |   at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:508)
microcks    |   at java.base/sun.net.www.http.HttpClient$1.run(HttpClient.java:560)
microcks    |   at java.base/sun.net.www.http.HttpClient$1.run(HttpClient.java:558)
microcks    |   at java.base/java.security.AccessController.doPrivileged(Native Method)
microcks    |   at java.base/sun.net.www.http.HttpClient.privilegedOpenServer(HttpClient.java:557)
microcks    |   at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:598)
microcks    |   at java.base/sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:266)
microcks    |   at java.base/sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:373)
microcks    |   at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:216)
microcks    |   at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1208)
microcks    |   at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1081)
microcks    |   at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:193)
microcks    |   at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1592)
microcks    |   at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1520)
microcks    |   at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:250)
microcks    |   at io.github.microcks.util.HTTPDownloader.handleHTTPDownloadToFileAndHeaders(HTTPDownloader.java:161)
microcks    |   at io.github.microcks.service.ServiceService.importServiceDefinition(ServiceService.java:134)
microcks    |   at io.github.microcks.service.JobService.doImportJob(JobService.java:73)
microcks    |   at io.github.microcks.web.JobController.startJob(JobController.java:174)
microcks    |   at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
microcks    |   at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
microcks    |   at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
microcks    |   at java.base/java.lang.reflect.Method.invoke(Method.java:566)
microcks    |   at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
microcks    |   at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:150)
microcks    |   at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:117)
microcks    |   at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895)
microcks    |   at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808)
microcks    |   at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
microcks    |   at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1067)
microcks    |   at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:963)
microcks    |   at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
microcks    |   at org.springframework.web.servlet.FrameworkServlet.doPut(FrameworkServlet.java:920)
microcks    |   at javax.servlet.http.HttpServlet.service(HttpServlet.java:684)
microcks    |   at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
microcks    |   at javax.servlet.http.HttpServlet.service(HttpServlet.java:764)
microcks    |   at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)
microcks    |   at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
microcks    |   at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
microcks    |   at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
microcks    |   at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
microcks    |   at io.github.microcks.web.filter.CorsFilter.doFilter(CorsFilter.java:47)
microcks    |   at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
microcks    |   at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
microcks    |   at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
microcks    |   at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
microcks    |   at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
microcks    |   at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
microcks    |   at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
microcks    |   at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
microcks    |   at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
microcks    |   at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
microcks    |   at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:96)
microcks    |   at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
microcks    |   at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
microcks    |   at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
microcks    |   at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
microcks    |   at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
microcks    |   at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
microcks    |   at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
microcks    |   at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197)
microcks    |   at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
microcks    |   at org.keycloak.adapters.tomcat.AbstractAuthenticatedActionsValve.invoke(AbstractAuthenticatedActionsValve.java:67)
microcks    |   at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:660)
microcks    |   at org.keycloak.adapters.tomcat.AbstractKeycloakAuthenticatorValve.invoke(AbstractKeycloakAuthenticatorValve.java:181)
microcks    |   at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135)
microcks    |   at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
microcks    |   at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
microcks    |   at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:360)
microcks    |   at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:399)
microcks    |   at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
microcks    |   at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:890)
microcks    |   at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1743)
microcks    |   at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
microcks    |   at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
microcks    |   at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
microcks    |   at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
microcks    |   at java.base/java.lang.Thread.run(Thread.java:829)
microcks    |
microcks    | 11:57:30.111  WARN 1 --- [080-exec-1] i.github.microcks.service.JobService     : MockRepositoryImportException while importing job 'pastry openapi 3' : https://raw.githubusercontent.com/microcks/microcks/master/samples/APIPastry-openapi.yaml cannot be downloaded

I removed from the log the real proxy_host / proxy_port.

So I have logged in the Microks container (docker exec -it microcks /bin/bash) and I tried to curl my proxy with success:
> bash-4.4$ curl http://PROXY_HOST:PROY_PORT
><HEAD><TITLE>Authentication Required</TITLE></HEAD>
><BODY BGCOLOR="white" FGCOLOR="black"><H1>Authentication Required</H1><HR>
><FONT FACE="Helvetica,Arial"><B>
></B></FONT>
><HR>
>
></BODY>

Again, I removed from the log the real proxy_host / proxy_port.

Can someone help me?
Thank you.

**Comment by lbroudoux** [comment]
Hi @dbl81,
Thanks for opening this issue. Looks like the name resolution doesn't even work in your case... Trying to figure out what could happen..

**Comment by dbl81** [comment]
> Hi @dbl81, Thanks for opening this issue. Looks like the name resolution doesn't even work in your case... Trying to figure out what could happen..

From the log the problem seems to be related to the resolution of the name, but as I have written in my previous message I can reach the proxy from the bash shell inside the container that runs microcks...

As a consequence Microcks services should reach the proxy...am I wrong?
