### ISSUE TITLE
Openshift microcks pod health issue

### ISSUE THREAD

**Issue by lucamaf** [microcks/microcks#7]
There might be issues with the endpoints that are used to verify the health and liveliness of the pod.
If those 2 checks are not removed, OpenShift keeps killing the pod.

**Comment by lbroudoux** [comment]
I've done fresh install minutes ago and cannot reproduce it. Probes have been updated in template as well as in image but you may have a mismatch if running on older image version. 

Could you force updating your image to check ?

Current image digest is sha256:6dd722356f7de2f649497b23329e017eaa087308f7066c353c14b876453f88ef

**Comment by lbroudoux** [comment]
The probe definitions are now `GET /api/health on port 8080 (HTTP)` since 2 weeks now.

**Comment by lucamaf** [comment]
so it was failing, with the latest version image.
I re-added the health checks and now it seems to be working fine.
