### ISSUE TITLE
Auto-generate JSON examples from OpenAPI/Swagger model definition capability

### ISSUE THREAD

**Issue by aniketvsawant** [microcks/microcks#72]
Hi Team,

I want to test all available path from the OpenAPI/Swagger definition, generate data to test the servers, analyse responses code and content, and to verify if the responses are conform to the API definition.

Currently I am testing REST APIs and getting **404 Not Found** for all the APIs which doesn't have examples defined. 

I'm looking for a way to generate default/random data (JSON object) from model definitions.

Does microcks has capability to generate default/random JSON examples from OpenAPI/Swagger model definition if in case of unprovided examples ? 

For example, given this model -

```
"Pet": {
  "type": "object",
  "required": [
    "name",
    "photoUrls"
  ],
  "properties": {
    "id": {
      "type": "integer",
      "format": "int64"
    },
    "category": {
      "$ref": "#/definitions/Category"
    },
    "name": {
      "type": "string",
      "example": "doggie"
    },
    "photoUrls": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "tags": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/Tag"
      }
    },
    "status": {
      "type": "string",
      "description": "pet status in the store"
    }
  }
}
```

I am expecting to generate default/random data and get something like this:

```
{
  "id": 0,
  "category": {
    "id": 0,
    "name": "string"
  },
  "name": "string",
  "photoUrls": [
    "string"
  ],
  "tags": [
    {
      "id": 0,
      "name": "string"
    }
  ],
  "status": "string"
}
```

Thanks.

**Comment by lbroudoux** [comment]
Hi @aniketvsawant,

Thanks for asking this question. Whilst it will be technically faisable to auto-generate response for mocks, this is not an option we have taken for now. 

Our rationale behind Microcks is that it is a platform for long running mocks for speeding up development process AND for enhancing communication and collaboration through different teams, functional experts, developers both on producer side and consumer side. 

That said, we think that there is great value in using real world samples for request / response pairs for common cases as well as edge cases. IMHO, the caveat with generated request and response is that it generally ends with no sense samples that do not serve the communication purpose we have. 

That’s why we tend to make the edition of samples mandatory but as easy as possible by using well known tools like Postman. This is clearly an opinionated  choice. Feel free to share your feelings too ;-)

Cheers,

**Comment by lbroudoux** [comment]
Closing cause no remarks
