### ISSUE TITLE
Update Kafka deployment to use KRaft

### ISSUE THREAD

**Issue by hguerrero** [microcks/microcks#726]
The latest version of Strimzi supports the preview of the KRaft protocol.

We can reduce the number of containers using this configuration instead of the traditional Zookeeper controller.

**Comment by lbroudoux** [comment]
Sure, that's a good idea. Do you know what is the current status of Kraft and its support in Strimizi?

**Comment by hguerrero** [comment]
It is currently experimental support but available. We could enable features and let people select if they want to enable that one.
