### ISSUE TITLE
Support for GRPC option

### ISSUE THREAD

**Issue by anselmhou** [microcks/microcks#729]
First of all, thank you for the great work on the project.  Due to environmental constraints, we have to integrate with the GRPC gateway and define `option (google.api.http)` in our photos e.g.

```
syntax = "proto3";

package io.github.microcks.grpc.hello.v1;

option java_multiple_files = true;

message HelloRequest {
    string firstname = 1;
    string lastname = 2;
}

message HelloResponse {
    string greeting = 1;
}

service HelloService {
    rpc greeting(HelloRequest) returns (HelloResponse){
        option (google.api.http) = {
            post: "/v1/hello/"
            body: "*"
        }
    }
}
```

When trying to import it via the web console importer function, we experience the following exception in the application:

```
08:06:41.266 ERROR 1 --- [080-exec-9] i.g.microcks.service.ServiceService      : Exception while accessing file /tmp/microcks-1672387601167.artifact

java.io.IOException: Protobuf schema file parsing error
	at io.github.microcks.util.grpc.ProtobufImporter.<init>(ProtobufImporter.java:113)
	at io.github.microcks.util.MockRepositoryImporterFactory.getMockRepositoryImporter(MockRepositoryImporterFactory.java:88)
	at io.github.microcks.service.ServiceService.importServiceDefinition(ServiceService.java:170)
	at io.github.microcks.web.UploadArtifactController.importArtifact(UploadArtifactController.java:117)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:150)
```

Our workaround for the problem is to use the following: definition

```
syntax = "proto3";

package io.github.microcks.grpc.hello.v1;

option java_multiple_files = true;

message HelloRequest {
    string firstname = 1;
    string lastname = 2;
}

message HelloResponse {
    string greeting = 1;
}

service HelloService {
    rpc greeting(HelloRequest) returns (HelloResponse);
}
```

Hence, is there any other more graceful way to handle this kind of issue using microcks, i.e. to tell the parser to ignore certain parts of it to skip the validations?

Thank you so much for your attention and participation.

**Comment by lbroudoux** [comment]
Hey @anselmhou !

Thanks for creating this issue. My knowledge of GRPC is quite foundational as I have to admit I never met `option` before 😉 
That said, I'm surprised not to see any `import "google/api/http.proto";` of things like that in your example file...

Actually Microcks is simply wrapping `protoc` and executing it with some flags to compile the proto. The actual command is issued [here](https://github.com/microcks/microcks/blob/1.7.x/webapp/src/main/java/io/github/microcks/util/grpc/ProtobufImporter.java#L82 ). Maybe you can have a look at it and check if it differs from the one you're using in your current workflow?

I'll try to reproduce and do some tests on my side as well.

**Comment by lbroudoux** [comment]
I'll push some files in the above commit and succeeded make it work adding `google/api/annotations.proto` and `google/api/http.proto` in my repo as well as imports in my proto file.

**Comment by lbroudoux** [comment]
I based my additions and tests on https://stackoverflow.com/questions/66168350/import-google-api-annotations-proto-was-not-found-or-had-errors-how-do-i-add

**Comment by anselmhou** [comment]
@lbroudoux highly appreciate your help.

I have created a new importer job and uploaded the google API proto together in the repository will resolve this issue.  It was my misunderstanding of the usage.

Thanks again.
