### ISSUE TITLE
Being able to set full keycloak url

### ISSUE THREAD

**Issue by mhkarimi1383** [microcks/microcks#731]
we are running keycloak with no `/auth` subpath

but we are not able to set that in both `helm` and operator

**Comment by mhkarimi1383** [comment]
@lbroudoux

**Comment by lbroudoux** [comment]
Hey there! This would be addressed with #691 and released with coming `1.7.0`. Stay tuned!

**Comment by mhkarimi1383** [comment]
Ok, I have just removed `/auth` from URL myself and it worked

**Comment by lbroudoux** [comment]
Now directly supported in Helm chart in `1.7.0` branch. See #691
