### ISSUE TITLE
Support Postman Collection directly from Workspace

### ISSUE THREAD

**Issue by JasonMiesionczek** [microcks/microcks#732]
From what I can see, Microcks only currently supports Postman Collections v2.0 format. For our needs this requires us to export our collections and then post them to a gitlab snippet and then use that URL via the CLI to import them. If Microcks supports the v2.1 format, we could use the Postman API directly to get the collection data and not have to perform the manual steps of exporting/updating snippet every time we need to update a mock.

**Comment by lbroudoux** [comment]
Hey Jason,
2.1 version should be supported as well. Maybe documentation has not been updated but we have 2.1 collections in our unit test suites (see https://github.com/microcks/microcks/blob/master/webapp/src/test/resources/io/github/microcks/util/postman/Swagger%20Petstore.postman_collection-2.1.json).
Let me know if you find any issues with 2.1 support though.

**Comment by JasonMiesionczek** [comment]
Ah I see, it is supported, but still requires it to be manually exported. I guess what I'm actually after is the ability to use the response from the Postman API directly, which wraps the collection data in an outer object:

`{"collection":{"info": ... }}`

If the importer could support detecting this it would allow us to fully go from Postman to Microcks without any manual intermediate steps. Thanks!

**Comment by lbroudoux** [comment]
Oh ... Ok. I think I understand ... you mean you'd be able to use the Postman API endpoint as a valid importer job endpoint so you wouldn't need an extra export step ... Is it correct? 

If it's just unwrapping things to get the actual collection ... it could make sense to integrate it into our importer. Would you have a link to the accurate Postman API documentation so that I'll check?

**Comment by JasonMiesionczek** [comment]
Yeah either as an importer job, or ideally extending the CLI tool to take a URL for the `import` command as opposed to a path to a local file.

Here is the docs for the Postman API endpoint: https://www.postman.com/postman/workspace/postman-public-workspace/request/12959542-a6a282df-907e-438b-8fe6-e5efaa60b8bf

**Comment by lbroudoux** [comment]
Yeah, we also had this enhancement in head for the CLI.

**Comment by lbroudoux** [comment]
Hey @JasonMiesionczek!
I think I'm gonna start this one this weekend or next week. Would you be interested in helping out in validating this feature?

**Comment by lbroudoux** [comment]
This is now implemented and available in `next` tagged container image.
