### ISSUE TITLE
[HELP] Can't create a new job

### ISSUE THREAD

**Issue by wlaw868** [microcks/microcks#736]
Hi guys, I'm a new user and trying to set this up for our async api testing. I'm able to deploy using Helm chart v1.6.1, and login to Microcks UI using a newly created user account. When I tried to create a new job using this https://raw.githubusercontent.com/microcks/microcks/master/samples/UserSignedUpAPI-asyncapi.yml, however it has not been successful. After I hit Create, it brings me back to the Import jobs page. I do not see any new job created. I also kubectl logs -f pod but doesn't reveal any good info. Can you suggest next step? Also tell me how to enable more debugs so that I can check it myself? Thanks!

**Comment by wlaw868** [comment]
I updated the configmap with TRACE log level but it doesn't say much about the import error.

```
15:22:50.305 [TRACE] io.github.microcks.web.HealthController - Health check endpoint invoked
15:22:50.305 [DEBUG] org.springframework.data.mongodb.core.MongoTemplate - Executing count: {} in collection: importJob
15:22:50.306 [DEBUG] org.mongodb.driver.protocol.command - Sending command '{"aggregate": "importJob", "pipeline": [{"$match": {}}, {"$group": {"_id": 1, "n": {"$sum": 1}}}], "cursor": {}}' with request id 198 to database microcks on connection [connectionId{localValue:3, serverValue:10913}] to server microcks-mongodb:27017
15:22:50.307 [DEBUG] org.mongodb.driver.protocol.command - Execution of command with request id 198 completed successfully in 1.13 ms on connection [connectionId{localValue:3, serverValue:10913}] to server microcks-mongodb:27017
15:22:50.307 [DEBUG] org.mongodb.driver.operation - Received batch of 0 documents with cursorId 0 from server microcks-mongodb:27017
15:22:50.307 [TRACE] org.mongodb.driver.connection - Checked in connection [connectionId{localValue:3, serverValue:10913}] to server microcks-mongodb:27017
15:22:50.307 [DEBUG] org.springframework.data.mongodb.core.MongoTemplate - find using query: {} fields: Document{{}} for class: class io.github.microcks.domain.ImportJob in collection: importJob
15:22:50.308 [DEBUG] org.mongodb.driver.protocol.command - Sending command '{"find": "importJob", "filter": {}, "sort": {"name": 1}, "limit": 10}' with request id 199 to database microcks on connection [connectionId{localValue:3, serverValue:10913}] to server microcks-mongodb:27017
15:22:50.309 [DEBUG] org.mongodb.driver.protocol.command - Execution of command with request id 199 completed successfully in 0.93 ms on connection [connectionId{localValue:3, serverValue:10913}] to server microcks-mongodb:27017
15:22:50.309 [DEBUG] org.mongodb.driver.operation - Received batch of 0 documents with cursorId 0 from server microcks-mongodb:27017
15:22:50.309 [TRACE] org.mongodb.driver.connection - Checked in connection [connectionId{localValue:3, serverValue:10913}] to server microcks-mongodb:27017
15:22:50.309 [TRACE] io.github.microcks.web.HealthController - Health check is OK
```
Any idea would be appreciated!

**Comment by wlaw868** [comment]
I'm able to import using microcks-cli.
```
./microcks-cli import 'samples/UserSignedUpAPI-asyncapi.yml:true' --microcksURL=http://xxx/api/ --keycloakClientId=microcks-serviceaccount --keycloakClientSecret=xxx
```
Mongo db showing the same as well.
```
> db.service.find()
{ "_id" : ObjectId("63c81789343d54360e2a8f8a"), "name" : "User signed-up API", "version" : "0.1.1", "type" : "EVENT", "metadata" : { "createdOn" : ISODate("2023-01-18T16:00:09.294Z"), "lastUpdate" : ISODate("2023-01-18T16:02:03.961Z") }, "sourceArtifact" : "UserSignedUpAPI-asyncapi.yml", "operations" : [ { "name" : "SUBSCRIBE user/signedup", "method" : "SUBSCRIBE", "bindings" : { "KAFKA" : { "type" : "KAFKA", "persistent" : false } }, "override" : false, "defaultDelay" : NumberLong(10), "resourcePaths" : [ "user/signedup" ] } ], "_class" : "io.github.microcks.domain.Service" }
```
But they are not showing up in the Microcks UI.

**Comment by wlaw868** [comment]
I recreated the cluster and now I'm able to login into keycloak and microcks using HTTPs. Even though I'm using chart v1.6.1, I do not see `server.forward-headers-strategy` config being setup. I manually k edit configmap and did a rolling restart. I still can't import a job.

I login into mongodb using the userM credential, but I do not see any document in microcks db.

Appreciate if you can shed some light. Thanks! @lbroudoux

**Comment by wlaw868** [comment]
@lbroudoux Do you have some time to look at this? Thanks

**Comment by lbroudoux** [comment]
Hey there!
Sorry for the very long delay in response. Was very busy onboarding a new job role and preparing some other great stuff around Microcks. Anyway, is this still an issue for you? Have you finally succeeded in finding another way around?

As for your previous question, `server.forward-headers-strategy=NATIVE` is in fact embedded into the `application.properties` in the JAR file in the container image. So it applies even if you can't see it into the `application.properties` contained in the ConfigMap (values are actually merged).

Let me know your status on this one.

**Comment by lbroudoux** [comment]
Closing this one regarding lack of activity. Fell free to reopen of still encountering this issue and having additional information.
