### ISSUE TITLE
[AsyncAPI] Message headers not properly handled for AMQP/RabbitMQ binding

### ISSUE THREAD

**Issue by pcuriel** [microcks/microcks#737]
Hello.

I have been testing Microcks with RabbitMQ and found that message headers are omitted for mocking and testing.

After setting it up as described [here](https://microcks.io/documentation/guides/rabbitmq-support/) and checking everything works, I modified the [example document](https://github.com/microcks/api-lifecycle/blob/master/account-service-demo-amqp/account-service-asyncapi-1.2.0.yml) to [include CloudEvents headers](https://github.com/microcks/microcks/files/10455534/account-service-asyncapi-1.2.0-with-headers.yml.txt).

And, even though this change does not break anything, headers are not taken into account by Microcks for mocking and testing. 

They do appear in the Mocks section.

![image](https://user-images.githubusercontent.com/1854183/213412508-7410a556-d7d2-4ce6-b740-f1f0b6b2a5b9.png)

<br />

However, mock events generated by Microcks do not include them, as we can check in the RabbitMQ console after binding a queue to the exchange.

![image](https://user-images.githubusercontent.com/1854183/213413370-c4d4cf5d-b9e1-4ff6-b6bb-24517e5d82ad.png)

<br />

Likewise, launching tests which receive non-compliant messages due to missing or malformed headers does not cause them to fail. Here we can see that, for instance, `cloudEvents:id` header is missing and `cloudEvents:time` header is not a valid timestamp value, as required by the schema.

![image](https://user-images.githubusercontent.com/1854183/213414420-58226b3b-461a-4c93-b69e-648b3bc53478.png)

**Comment by lbroudoux** [comment]
Hey @pcuriel!
You're absolutely right: headers are not produced on mock messages for AMQP... Pushing a fix ASAP.

**Comment by pablo-curiel** [comment]
Hi @lbroudoux. Thanks for the quick response and fix! Will this fix also solve the verification in the tests, or just the mock messages part?

**Comment by lbroudoux** [comment]
Just the fix for the headers on mock messages for now. Will check the other part and probably create another issue for it.

**Comment by lbroudoux** [comment]
I've checked the code and you're right: we missed the headers validation ... just focusing on the message payload 😞  Will create an issue to track this one.

**Comment by lbroudoux** [comment]
Closing this one as the remaining concern is now tracked with #755
