### ISSUE TITLE
Unable to upload Raw link with User group role, Activate API giving 403 Error

### ISSUE THREAD

**Issue by vishalmgada** [microcks/microcks#739]
[Hi](url) Team,

In keycloak for our user management we have created three user groups User, Manager and Admin, where we have assigned microcks-app user, manager and admin role respectively. 
When a user linked to user group tries to upload the mock via Github Raw link, he receives 403 error from Activate API. (Refer the screenshot attached). At the same time, if this is done by a user linked to Manager group, the API is import is successful and the mock is created. 

We would not like to give Manager permission to all as it provides access to delete permission. 

Could you please guide us to understand if there is anything which we are missing in configuring the user?
Microcks Version - 1.6.1
Keycloak Server Version - 14.0.0

![image](https://user-images.githubusercontent.com/18324911/213613697-dbf3e0a3-bf22-42eb-a82e-7057f2b813f4.png)

**Comment by vishalmgada** [comment]
@lbroudoux Could you please help with above issue?

**Comment by lbroudoux** [comment]
Hey @vishalmgada 

I took some time to re-check some points and I am afraid we have some inconsistencies in permissions on Import Jobs...
So as of today, it seems that:
* `user` role can import file and create but can't activate/force/stop/edit/delete job in default mode,
* `manager` and `admin` roles are able to import file and create/activate/force/stop/edit/delete job in default mode,
* `manager`, `manager-any`, and `admin` are able to import file and create/activate/force/stop/edit/delete job in [segmented mode](https://microcks.io/documentation/using/advanced/organizing/#rbac-security-segmentation),
* `user` role cannot even import file or create in [segmented mode](https://microcks.io/documentation/using/advanced/organizing/#rbac-security-segmentation).

Whilst the behaviour in [segmented mode](https://microcks.io/documentation/using/advanced/organizing/#rbac-security-segmentation) seems consistent to me, behaviours in default mode looks wrong as a simple user cannot activate job just after having created one...

Maybe should we just add lifecycle actions (activate/force/stop) to `user` in default mode and still reserve edit/delete action to `manager`? What do you think?

**Comment by vishalmgada** [comment]
> Maybe should we just add lifecycle actions (activate/force/stop) to `user` in default mode and still reserve edit/delete action to `manager`? What do you think?

@lbroudoux  - I agree to this.  
Has this been broken in latest release? As I see in previous version microcks:1.2.1, we see this to be working.

**Comment by vishalmgada** [comment]
> In your case, this would imply upgrading the users creating mocks to `manager` - it could be a concern if you have many users but it will also put you on the way to [segmented mode](https://microcks.io/documentation/using/advanced/organizing/#rbac-security-segmentation) that is IMHO the way to go for large installations ... What do you think ?

@lbroudoux  - After reading the documentation of the segmented users, I agree that user group in default and segmented mode should have same permission. 
To mitigate the issue, we have upgraded our users to Manager to resolve this. 
Only concern we have with the manager role is with delete permission that it provides.
