### ISSUE TITLE
Track creation date and last update date on Services and APIs mocks

### ISSUE THREAD

**Issue by lbroudoux** [microcks/microcks#75]
Today Services and APIs do not have any properties for tracking creation date and last refresh date. 

`creationDate` should be initialized when object is created (obviously ;-)) and `lastUpdate` should be updated at each and every reimport of a Service mocks definition.

We'll implement this by adding a new global `metadata` field that will track this dates but also be able to track some others `labels` or `annotations`  (simple lists of Key:Value pairs) _à la_ Kubernetes.

**Comment by lbroudoux** [comment]
Done

**Comment by yoadmike** [comment]
Hi , there is an issue with this lastest addition 
upload of new services file with null pointer exception .. 
if you notice ..exsitingServices Object can be null at that point an that's exactly what happen .
can you please insert that new code under the if(exsitingServices  != null) bracket.

![image](https://user-images.githubusercontent.com/44646697/49002002-fc7feb00-f166-11e8-8851-054d25a3a789.png)
