### ISSUE TITLE
OpenAPI Mocking using body as array and reuse inside response

### ISSUE THREAD

**Issue by AteDev** [microcks/microcks#750]
Hello, i'm facing an issue when using body array, see example below

Openapi
[test.yaml.txt](https://github.com/microcks/microcks/files/10664736/test.yaml.txt)

related part : `bar: "{{request.body/0/foo/bar}}"`

http://localhost:8080/rest/Test/1.0/resources/v1/test with POST method

body as json content-type
`[{"foo":{"bar":123},"quantity":1}]`

result : 
`{
    "status": "OK",
    "items": [
        {
            "status": "OK",
            "request": {
                "body": {
                    "foo": {
                        "bar": "null"
                    },
                    "quantity": "null"
                },
                "response": {
                    "httpStatus": 200,
                    "body": {
                        "foo": {
                            "bar": "null"
                        },
                        "date": "2023/02/06"
                    }
                }
            }
        }
    ]
}`

i was unable to reuse body value, what did i do wrong ?

microcks v 1.6.1

See https://github.com/microcks/microcks/discussions/749

**Comment by lbroudoux** [comment]
Looks like it's actually a bug as the incoming body content is not recognized as JSON. It's a shame but do not consider payload that starts with `[` array marker... Fixing it ASAP.

**Comment by lbroudoux** [comment]
And now fixed! 😉
