### ISSUE TITLE
Fix CVEs

### ISSUE THREAD

**Issue by mot256** [microcks/microcks#757]
If you want anybody serious to actually use this framework, you may want to solve the CVEs in your images. There are (fixable) CVEs still open as far back as 2013!
Just do as trivy scan
`trivy i quay.io/microcks/microcks:latest --ignore-unfixed`

**Comment by lbroudoux** [comment]
Hey there!

Thanks for the kind message. Be sure that we take CVEs tracking very seriously and already have an automated image scanning setup with reports like this [one for the next release]( https://quay.io/repository/microcks/microcks/manifest/sha256:f80b716353022b5fbce48a52f9d69b3cae7923c38a00d8b16b2aec566b02fca2?tab=vulnerabilities).

That said, I give a try on trivy and found some interesting complementary stuff on the Java side. Here's a summary of the report for `trivy i quay.io/microcks/microcks:next --ignore-unfixed`:

```
quay.io/microcks/microcks:next (redhat 9.1)
Total: 8 (UNKNOWN: 0, LOW: 0, MEDIUM: 6, HIGH: 2, CRITICAL: 0)

Java (jar)
Total: 69 (UNKNOWN: 2, LOW: 2, MEDIUM: 35, HIGH: 27, CRITICAL: 3)
```

Thanks to it, I've spotted 1 or 2 enhancements that I'll try to include in next `1.7.0` release. However, you probably know that fixing CVEs is not as easy as preaching it: lots of remaining CVEs come from dependencies you cannot directly influence and real risk really depends on how these deps are actually used in your codebase. That's the case for the old ones (`xmlsec`, `saml` or `xerces` related) that are actually not used directly or indirectly by Microcks.

**Comment by lbroudoux** [comment]
Latest scan on `next` image give the following results:

```
quay.io/microcks/microcks:next (redhat 9.1)
Total: 8 (UNKNOWN: 0, LOW: 0, MEDIUM: 6, HIGH: 2, CRITICAL: 0)

Java (jar)
Total: 68 (UNKNOWN: 1, LOW: 2, MEDIUM: 40, HIGH: 22, CRITICAL: 3)
```

**Comment by lbroudoux** [comment]
See [Quay.io report](https://quay.io/repository/microcks/microcks/manifest/sha256:aba24cf0d5092b733ea70bb78b7adef531908e9387476b8b66981e6e8802d323?tab=vulnerabilities) as well.

**Comment by mot256** [comment]
Yes, I do realize that static scanners do give annoying false negatives. However, many of our customers do not take that as an excuse. So we have to come up with creative ways to solve these issues.

I have noticed that e.g. your base image (in https://github.com/microcks/microcks/blob/master/webapp/src/main/docker/ubi/Dockerfile) is registry.access.redhat.com/ubi8/ubi-minimal:8.6-902, which in itself is the source of most of most of your CVEs. If you sinply use the latest base image from that repository (tag 8.7-1085) you already have a "perfect" score on fixable CVEs (at least from that point on):
`trivy i registry.access.redhat.com/ubi8/ubi-minimal:8.7-1085 --ignore-unfixed`
![image](https://user-images.githubusercontent.com/5630006/221505547-10d935ac-879c-4d6f-8281-c466c7d009b5.png)

**Comment by lbroudoux** [comment]
Thanks.

In fact, we're on branch `1.7.x` for next release and are using `ubi-minimal-9` at the moment. I've updated to latest base image and a "perfect" score right now with `registry.access.redhat.com/ubi9/ubi-minimal:9.1.0-1760.1675784957` ;-)
