### ISSUE TITLE
Rest Mock fail with 401 when passing  Authorization header 

### ISSUE THREAD

**Issue by yoadmike** [microcks/microcks#76]
Hi , assuming microcks is not intended for Authentication tests:

calling REST Mock with Authorization Header [Bearer <Token>] (it's unavoidable as Token is passed along from provider MS to another MS and so on .. )

**Postman as Consumer gets this:** 

{
    "timestamp": 1543171526838,
    "status": 401,
    "error": "Unauthorized",
    "message": "Unauthorized",
    "path": "/rest/xxx-xxx/1.0/xxx/v1/xxxx/xxx" 
}

**in Micorcks Pod Log i get below**
it's like some authentication is done for no reason (Keycloack Invovled , ) 

INFO] org.mongodb.driver.connection - Opened connection [connectionId{localValue:1, serverValue:350640}] to microcks-mongodb:27017
--
  | [INFO] org.mongodb.driver.cluster - Monitor thread successfully connected to server with description ServerDescription{address=microcks-mongodb:27017, type=STANDALONE, state=CONNECTED, ok=true, version=ServerVersion{versionList=[3, 2, 10]}, minWireVersion=0, maxWireVersion=4, maxDocumentSize=16777216, roundTripTimeNanos=1003431}
  | [INFO] io.github.microcks.MicrocksApplication - Started MicrocksApplication in 7.156 seconds (JVM running for 8.276)
  | [INFO] org.mongodb.driver.connection - Opened connection [connectionId{localValue:2, serverValue:350644}] to microcks-mongodb:27017
  | [ERROR] org.keycloak.adapters.BearerTokenRequestAuthenticator - Failed to verify token
  | org.keycloak.common.VerificationException: Failed to read access token from JWT
  | at org.keycloak.TokenVerifier.parse(TokenVerifier.java:318)
  | at org.keycloak.TokenVerifier.getHeader(TokenVerifier.java:332)
  | at org.keycloak.RSATokenVerifier.getHeader(RSATokenVerifier.java:85)
  | at org.keycloak.adapters.rotation.AdapterRSATokenVerifier.verifyToken(AdapterRSATokenVerifier.java:55)
  | at org.keycloak.adapters.rotation.AdapterRSATokenVerifier.verifyToken(AdapterRSATokenVerifier.java:37)
  | at org.keycloak.adapters.BearerTokenRequestAuthenticator.authenticateToken(BearerTokenRequestAuthenticator.java:87)
  | at org.keycloak.adapters.BearerTokenRequestAuthenticator.authenticate(BearerTokenRequestAuthenticator.java:82)
  | at org.keycloak.adapters.RequestAuthenticator.authenticate(RequestAuthenticator.java:68)
  | at org.keycloak.adapters.undertow.AbstractUndertowKeycloakAuthMech.keycloakAuthenticate(AbstractUndertowKeycloakAuthMech.java:110)
  | at org.keycloak.adapters.undertow.ServletKeycloakAuthMech.authenticate(ServletKeycloakAuthMech.java:92)
  | at io.undertow.security.impl.SecurityContextImpl$AuthAttempter.transition(SecurityContextImpl.java:245)
  | at io.undertow.security.impl.SecurityContextImpl$AuthAttempter.transition(SecurityContextImpl.java:268)
  | at io.undertow.security.impl.SecurityContextImpl$AuthAttempter.access$100(SecurityContextImpl.java:231)
  | at io.undertow.security.impl.SecurityContextImpl.attemptAuthentication(SecurityContextImpl.java:125)
  | at io.undertow.security.impl.SecurityContextImpl.authTransition(SecurityContextImpl.java:99)
  | at io.undertow.security.impl.SecurityContextImpl.authenticate(SecurityContextImpl.java:92)
  | at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:55)
  | at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
  | at io.undertow.security.handlers.AuthenticationConstraintHandler.handleRequest(AuthenticationConstraintHandler.java:53)
  | at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)
  | at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64)
  | at io.undertow.servlet.handlers.security.ServletSecurityConstraintHandler.handleRequest(ServletSecurityConstraintHandler.java:59)
  | at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60)
  | at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77)
  | at io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43)
  | at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
  | at org.keycloak.adapters.undertow.ServletPreAuthActionsHandler.handleRequest(ServletPreAuthActionsHandler.java:69)
  | at org.keycloak.adapters.undertow.ServletPreAuthActionsHandler.handleRequest(ServletPreAuthActionsHandler.java:69)
  | at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
  | at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:292)
  | at io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:81)
  | at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:138)
  | at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:135)
  | at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48)
  | at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
  | at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:272)
  | at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:81)
  | at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:104)
  | at io.undertow.server.Connectors.executeRootHandler(Connectors.java:336)
  | at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:830)
  | at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
  | at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
  | at java.lang.Thread.run(Thread.java:748)
  | Caused by: org.keycloak.jose.jws.JWSInputException: com.fasterxml.jackson.databind.JsonMappingException: Numeric value (2505381905734) out of range of int
  | at [Source: [B@65b51add; line: 1, column: 108]
  | at [Source: [B@65b51add; line: 1, column: 95] (through reference chain: org.keycloak.representations.AccessToken["exp"])
  | at org.keycloak.jose.jws.JWSInput.readJsonContent(JWSInput.java:104)
  | at org.keycloak.TokenVerifier.parse(TokenVerifier.java:316)
  | ... 42 common frames omitted
  | Caused by: com.fasterxml.jackson.databind.JsonMappingException: Numeric value (2505381905734) out of range of int
  | at [Source: [B@65b51add; line: 1, column: 108]
  | at [Source: [B@65b51add; line: 1, column: 95] (through reference chain: org.keycloak.representations.AccessToken["exp"])
  | at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:388)
  | at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:348)
  | at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.wrapAndThrow(BeanDeserializerBase.java:1611)
  | at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:278)
  | at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:140)
  | at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3814)
  | at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2945)
  | at org.keycloak.util.JsonSerialization.readValue(JsonSerialization.java:69)
  | at org.keycloak.jose.jws.JWSInput.readJsonContent(JWSInput.java:102)
  | ... 43 common frames omitted
  | Caused by: com.fasterxml.jackson.core.JsonParseException: Numeric value (2505381905734) out of range of int
  | at [Source: [B@65b51add; line: 1, column: 108]
  | at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1702)
  | at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:558)
  | at com.fasterxml.jackson.core.base.ParserBase.convertNumberToInt(ParserBase.java:928)
  | at com.fasterxml.jackson.core.base.ParserBase._parseIntValue(ParserBase.java:866)
  | at com.fasterxml.jackson.core.base.ParserBase.getIntValue(ParserBase.java:694)
  | at com.fasterxml.jackson.databind.deser.std.NumberDeserializers$IntegerDeserializer.deserialize(NumberDeserializers.java:299)
  | at com.fasterxml.jackson.databind.deser.std.NumberDeserializers$IntegerDeserializer.deserialize(NumberDeserializers.java:279)
  | at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:504)
  | at com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:111)
  | at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:276)
  | ... 48 common frames omitted

**Comment by lbroudoux** [comment]
This seems to be a regression (used to work) maybe following #61 ...
Investigating.

**Comment by yoadmike** [comment]
Now it's fine .
