### ISSUE TITLE
Replicas is hard coded to 1

### ISSUE THREAD

**Issue by sarasensible** [microcks/microcks#768]
In the helm chart the microcks replicas value is hard coded to 1, ignoring the microcks.replicas value.

https://github.com/microcks/microcks/blob/1.7.x/install/kubernetes/microcks/templates/deployment.yaml#L10

PR open at https://github.com/microcks/microcks/pull/769

**Comment by lbroudoux** [comment]
Now merged into `1.7.x`. Thanks a lot!
