### ISSUE TITLE
After MetaData addition, upload is no longer possible due to NPE.

### ISSUE THREAD

**Issue by yoadmike** [microcks/microcks#77]
Hi , there is an issue with this lastest addition of MetaData
upload of new services file cause null pointer exception ..
if you notice in code below ..exsitingServices Object can be null at that point an that's exactly what happen .
can you please insert that new code under the if(exsitingServices != null) bracket.

![image](https://user-images.githubusercontent.com/44646697/49002002-fc7feb00-f166-11e8-8851-054d25a3a789.png)

at io.undertow.server.Connectors.executeRootHandler(Connectors.java:336)
  | at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:830)
  | at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
  | at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
  | at java.lang.Thread.run(Thread.java:748)
  | Caused by: java.lang.NullPointerException: null
  | at io.github.microcks.service.ServiceService.importServiceDefinition(ServiceService.java:121)
  | at io.github.microcks.web.UploadArtifactController.importArtifact(UploadArtifactController.java:83)
  | at sun.reflect.GeneratedMethodAccessor69.invoke(Unknown Source)
  | at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  | at java.lang.reflect.Method.invoke(Method.java:498)
  | at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)

**Comment by lbroudoux** [comment]
Sorry for that regression ... Will have a look in the next hours.

**Comment by lbroudoux** [comment]
Hi @yoadmike,
this should have been fixed and is now available in latest docker image.
Please tell me if it's ok for you.
Cheers,

**Comment by yoadmike** [comment]
Hi,
it's fine now .. if it's possible for each fix to add minor version , and have it posted in github so that in such cases i can revert to latest stable build ?

**Comment by lbroudoux** [comment]
You mean within docker image tag name ?
