### ISSUE TITLE
OpenAPI 3.0.0 Base URL not being used by MicroCKS

### ISSUE THREAD

**Issue by TheStarryNight1889** [microcks/microcks#781]
In my api.json I have the following section

``` json
"servers": [
        {
            "url": "/api"
        }
],
```

I have also tried

``` json
    "servers": [
        {
            "url": "https://microcks.x.com/api"
        }
    ],
```

but my Mock URL is always `https://microcks.x.com/rest/X+Api/1.0.2/v1/items` without the `/api` base URL. Whereas is should look like `https://microcks.x.com/rest/X+Api/1.0.2/api/v1/items`

I have checked the logs and there are no errors or warnings. 

I cannot find any documentation in MicroCKS that shows this being configured. 

Am I missing something or does MicroCKS ignore this OpenAPI specification property?

**Comment by lbroudoux** [comment]
Hi there!

This behavior is normal: Microcks does use this information to customize its base URL.

Some explanations for that:
* `servers` is an array, it wouldn't be easy to guess the exact one element to use,
* `servers` is more dedicated to list the production (or QA) environments servers,
* `servers` is not mandatory,
* and finally it would be un-practicable to have different URLs at Microcks ;-)

Microcks is using a dedicated endpoint prefix for each protocol: `/rest`, `/soap`, `/graph` or dedicated port for gRPC and then path information to easily retrieve API name and version.

Hope it helps!
