### ISSUE TITLE
Implement cache solution / improve database access performance

### ISSUE THREAD

**Issue by dorianbrun** [microcks/microcks#784]
### Reason/Context

Hello,

Is there a way to implement a cache solution or an other solution that allow to improve performance and get stable runtimes ?

In my specific case I use k6 to run load test with Microcks and for a reason I do not know, runtimes are inconsistent and not stable and do not allow me to set a precise execution time for my tests.

I do not know if you are familiar with k6 but here is my result after running a test : 

```
data_received..................: 734 kB 7.3 kB/s
     data_sent......................: 640 kB 6.4 kB/s
     dropped_iterations.............: 25     0.249916/s
     group_duration.................: avg=178.4ms  min=105.48ms med=145.13ms max=2.11s    p(90)=174.48ms p(95)=204.82ms
     http_req_blocked...............: avg=5.95µs   min=2.32µs   med=3.44µs   max=289.52µs p(90)=5.2µs    p(95)=6.01µs  
     http_req_connecting............: avg=1.7µs    min=0s       med=0s       max=233.03µs p(90)=0s       p(95)=0s      
     http_req_duration..............: avg=178.28ms min=105.39ms med=145.02ms max=2.11s    p(90)=174.37ms p(95)=204.7ms 
       { expected_response:true }...: avg=178.28ms min=105.39ms med=145.02ms max=2.11s    p(90)=174.37ms p(95)=204.7ms 
   ✓ http_req_failed................: 0.00%  ✓ 0         ✗ 1624
     http_req_receiving.............: avg=50.6µs   min=27.71µs  med=47.82µs  max=186.9µs  p(90)=62.07µs  p(95)=70.72µs 
     http_req_sending...............: avg=22.22µs  min=14.1µs   med=20.23µs  max=118.01µs p(90)=28.14µs  p(95)=32.75µs 
     http_req_tls_handshaking.......: avg=0s       min=0s       med=0s       max=0s       p(90)=0s       p(95)=0s      
     http_req_waiting...............: avg=178.21ms min=105.3ms  med=144.94ms max=2.11s    p(90)=174.3ms  p(95)=204.62ms
     http_reqs......................: 1624   16.234511/s
     iteration_duration.............: avg=178.43ms min=105.51ms med=145.15ms max=2.11s    p(90)=174.51ms p(95)=204.85ms
     iterations.....................: 1624   16.234511/s
     vus............................: 20     min=15      max=20
     vus_max........................: 20     min=15      max=20
```

As you can see there is a big gap between min and max runtime (min=**105.48ms** med=145.13ms max=**2.11s**).

### Description

I don't know why there is such a discrepancy between execution times for the same query but I think it can be more consistent if we use a cache solution.

It would be perfect if we could set a boolean for each request that indicates whether the cache is needed or not.

The cache would be refreshed when a new contract is imported.

**Comment by lbroudoux** [comment]
Hi @dorianbrun,

Thanks for this report! Before talking about solution ("Implementing cache") I'd like to suggest two things.

1) There's a flag called `microcks.mockInvocationStats` (in either Helm values or operator CR) that can be used to turn off processing of invocation statistics. Processing of stats normally happens asynchronously and depending on how you deployed Microcks (in terms of CPU resources), it can have some side effects on mocking endpoints. You can turn this flag to `false` to disable processing and I've heard many community users turning it off when it comes to use Microcks for performance campaign,

2) and probably the most long-term answer - the Microcks MongoDB database has no indexes by default! We let this topic aside in the past, wanting to focus on some others... We don't pretend providing a production-ready MongoDB but we should probably enhance things like : a version upgrade and guidelines/recommendations/samples on how to setup indexes to make things faster when querying the data. We should also probably deliver some benchmarking scripts - I've also started writing things on K6 in the past.

As a summary, I would say : start turning off the stat processing if you need immediate perf. And maybe, feel free to share any findings or methodologies on how we could work on improving the default MongoDB setup.

**Comment by lbroudoux** [comment]
Hey @dorianbrun !
Any news on this one regarding my previous answer? As we're going to start `1.8.x` development stream, I'd like to tackle this topic of database access performance. Would you like to jump aboard the discussion?

**Comment by lbroudoux** [comment]
I just created a new #870 issue to track the global topic of how to measure performance of a Microcks installation.
