### ISSUE TITLE
Disable keycloak on k8s/helm

### ISSUE THREAD

**Issue by snarasin1** [microcks/microcks#789]
### Reason/Context

There should be a way to enable/disable keycloak in deployment.

### Description

 This is already supported in the code using KEYCLOAK_ENABLED flag, just that the variable has to be exposed to turn it on/off while deploying.

**Comment by lbroudoux** [comment]
Hi @snarasin1 

As of today, it's not possible to disable Keycloak using operator or Helm chart as we consider it as a vital part of the mocking infrastructure. This is just allowed for local use-cases through docker-compose. However, we'd be very happy to discuss the use-cases you foresee and why we should consider making it an option.

That said, there should be a way to achieve this today (even if I'm not having tested it). Could you try the following and check if it do the trick:
* Put `keycloak.install=false` in your `values.yaml` or your `MicrocksInstall` CR,
* Put a fake URL in `keycloak.url`, something like `https://keycloak.acme.com` might be ok,
* Put an extra env var in `microcks.env` with name `KEYCLOAK_ENABLED` and value `false`.

Let us know how things are going,

**Comment by snarasin1** [comment]
hi @lbroudoux It does the trick. Thanks!
I was trying out just adding KEYCLOAK_ENABLED in microcks.env before, where it didnt work.

we have local kind cluster where we deploy microcks helm charts and we dont want to use keycloak.
