### ISSUE TITLE
Fix regression: after having changed to Undertow, Keycloak adapter checks JWT bearer even on mocks

### ISSUE THREAD

**Issue by lbroudoux** [microcks/microcks#79]
Change from Tomcat to Undertow add a major regression on secutiry : Keycloak adapter tries to validate JWT Bearer event on public API (not configured as `security-constrained`).

Keycloak adapter allow calling them with no Bearer ; however when a Bearer is present, it will try validating it event if it's a fake bearer or a propagated one that comes from another issuer. This is regular cases when invoking REST or SOAP mocks from other programs.

This is a behavioral difference comparing to Tomcat. Within Tomcat the keycloak adapter first checks if there's a security constraint before trying to validate any existing Bearer. This is the behaviour we want ; so we have to remove all changes done within #61

**Comment by lbroudoux** [comment]
This typically causes #76

**Comment by yoadmike** [comment]
Works Perfect now ..
