### ISSUE TITLE
microcks service type as ExternalName

### ISSUE THREAD

**Issue by snarasin1** [microcks/microcks#790]
### Reason/Context

to communicate microcks from different namespace (without ingress).

### Description

currently "microcks.serviceType" is configurable in values files. but when it is set as ExternalName, its mandatory to have spec.externalName in template, which is not present.

**Comment by lbroudoux** [comment]
Thanks for raising this issue. Seems legit to integrate `spec.externalName` for that specific type of Service but I'm curious about the use-case as I never used `ExternalName` types service ... Could you explain in which context it could be useful ? (as cross-namespaces communication should also be possible for `ClusterIP` service no?)

**Comment by lbroudoux** [comment]
Hey @snarasin1 
Coming back to this. This is an easy change but I really don't see the case on why you'd need the Microcks install procedure to declare Microcks itself as a Service of type `ExternalName`... I can imagine the use-case where you'd declare a single Microcks Service being `ExternalName` in a namespace that doesn't have Microcks deployed. However, you don't need Microcks Helm chart to generate it for you in that case. Could you give more details, please?

**Comment by snarasin1** [comment]
Hey @lbroudoux , I raised this issue when i was exploring to achieve cross-namespace communication, and its possible with clusterIp as you mentioned. so the changes are no more needed for my usecase. 

but i guess still the changes requested is valid, if someone try to use servicetype as external name
