### ISSUE TITLE
enabling mayastor does not create the storage of /dev/disk/by-uuid on Virtual machines

### ISSUE THREAD

**Issue by narindergupta** [microcks/microcks#791]
### Describe the bug

Create a Microk8s cluster and trying to enable the mayastor plugin, After enabling the plugin i can list the storage from the local disk rootfs. When i tried to create a new storage using the file below

 cat msppool 
apiVersion: "openebs.io/v1alpha1"
kind: MayastorPool
metadata:
  name: microk8s-kafka-cos3-pool2
  namespace: mayastor
spec:
  node: kafka-cos3
  disks: ["/dev/disk/by-uuid/?????????????????????????"]

microk8s kubectl get msp
NAME                        NODE         STATUS   CAPACITY      USED   AVAILABLE
microk8s-kafka-cos1-pool    kafka-cos1   Online   21449670656   0      21449670656
microk8s-kafka-cos3-pool2   kafka-cos3   Error    0             0      0

**Comment by yada** [comment]
Hi Narinder,

Guess your issue is on the wrong project. You are dealing with [Microk8s](https://github.com/canonical/microk8s), not [Microcks](https://github.com/microcks) (us): yes names are very similar but projects do not have the same purpose ;-)

We may plan to create a Microcks community addon for Microk8s but this is another story.

Closing this issue as not related to Microcks.

Regards,
Yacine

**Comment by narindergupta** [comment]
When i tried with 1.26 getting following error in control logs

 Apr 22 04:14:46.435 ERROR core::pool::service: error: gRPC request 'create_pool' for 'Pool' failed with 'status: Cancelled, message: "Timeout expired", details: [], metadata: MetadataMap { headers: {} }'
    at control-plane/agents/core/src/pool/service.rs:240

  Apr 22 04:14:56.435 ERROR core::pool::service: error: gRPC request 'create_pool' for 'Pool' failed with 'status: Cancelled, message: "Timeout expired", details: [], metadata: MetadataMap { headers: {} }'
    at control-plane/agents/core/src/pool/service.rs:240

**Comment by yada** [comment]
Narinder, please read my previous message: you are on the wrong project.
📢 **"Microcks" ≠ "microk8s" ;-)**
