### ISSUE TITLE
Add a delete endpoint for the APIs

### ISSUE THREAD

**Issue by lucamaf** [microcks/microcks#8]
at the moment for the Services and Jobs there are just GET and POST action.
To enable a complete automation scenario you would need at least a DELETE action as well.

**Comment by lbroudoux** [comment]
It should arrive after 0.5.0 milestone release. I was waiting for #3 before properly implement this.

**Comment by lbroudoux** [comment]
Delay this one as ownership strategy for Service is not yet defined

**Comment by lbroudoux** [comment]
UX for this is now available on the `new-ux-0.7.x` branch of repo or using `new-ux-latest` tag on the container image.

**Comment by lucamaf** [comment]
not sure if this is only for Services created through APIs but seems like there is no way to delete them still through GUI

**Comment by lbroudoux** [comment]
There’s now a way to do that if your user has admin role. Check Keycloak
console to assign role to user if needed.

Cheers,

Le lun. 8 avr. 2019 à 08:07, Luca Ferrari <notifications@github.com> a
écrit :

**Comment by lucamaf** [comment]
thank you, that solved it!
