### ISSUE TITLE
Randomize REST Response Example

### ISSUE THREAD

**Issue by yoadmike** [microcks/microcks#80]
Hi **lbroudoux**

can you please help with an example of how to randomize a response variable
what do i have: 
i have an example json where i want to randomize one of the fields in response .. was not able to understand how it's done in postman so that microcks will be able to understand .

**Comment by yoadmike** [comment]
@lbroudoux  , what do you say ? .. possible to implement  initially?.. it's very useful.

**Comment by lbroudoux** [comment]
Yes, I start thinking about it ... Have start studying some stuffs like Mustache and JMustache implementation for that.

However, in best case scenario, I could only start something by the beginning of next yeat. Too busy before finalizing 0.7.0 and having my day job ;-)

**Comment by lbroudoux** [comment]
#94 was created for handling discussions and tasks around this new feature.
