### ISSUE TITLE
GraphQL multi-queries of different operations throws exception

### ISSUE THREAD

**Issue by sbonaiva** [microcks/microcks#801]
### Describe the bug

I'm enabling the use of Microcks in my company and I found a problem with GraphQL mocks.

Our mobile applications, in a single request, perform multiple queries on different operations and this works fine on the Apollo Server, for example:

```graphql
query ($brand: Brand!) {
  configuration(brand: $brand) {
    font
    color
  }
  content(brand: $brand) {
    title
    description
  }
}
```
However, importing the GraphQL schema + Postman Collection with examples and making this request, I get error 500 and the message in the body `Cannot invoke "String.length()" because "text" is null`.

Analyzing the stack trace, the exception was thrown by the GraphQL Controller on line 256. This happens because when parsing the aggregated response an alias is always expected, but in this case it is not necessary. 

[microcks-graphql-stacktrace.txt](https://github.com/microcks/microcks/files/11334469/microcks-graphql-stacktrace.txt)

Complementing the query with aliases works.

```graphql
query ($brand: Brand!) {
  configuration: configuration(brand: $brand) {
    font
    color
  }
  content: content(brand: $brand) {
    title
    description
  }
}
```
Obviously, aliases are mandatory for multiple queries in the same operation for deduplication purposes. As for multiple queries in separate operations, this may be optional.

So locally, I made a small change to `GraphQLController.execute` and got the expected behavior.

```java
if (graphqlResponses.size() > 1) {
   ObjectNode aggregated = mapper.createObjectNode();
   ObjectNode dataNode = aggregated.putObject("data");
   for (GraphQLQueryResponse response : graphqlResponses) {
      dataNode.set(
         StringUtils.isNotBlank(response.getAlias()) ? response.getAlias() : response.getOperationName(), 
         response.getJsonResponse().path("data").path(response.getOperationName()).deepCopy()
      );
   }
   responseNode = aggregated;
}
```
I'm suggesting this change based on a real scenario, where refactoring the mobile client layer to use aliases can be a bit more complicated.

Best Regards

### Expected behavior

Multiple GraphQL queries on different operations should run successfully, with or without aliasing.

### Actual behavior

Several GraphQL queries on different operations are returning error when alias is not used.

### How to Reproduce?

1. Import a GraphQL Schema + Postman Collection with two or more operations
2. Create a query with multiple operations and don't use aliases

### Microcks version or git rev

1.7.0

### Install method (`docker-compose`, `helm chart`, `operator`, `docker-desktop extension`,...)

docker-compose

**Comment by lbroudoux** [comment]
Hey! Thanks for this awesome analysis and suggestion! 👏 
Would you be OK to submit a PR? I think you've got everything at hand to do so.
Let me know and thanks again 🙏

**Comment by sbonaiva** [comment]
Hi @lbroudoux, thanks for the opportunity.
Based on the contributing guide, I submitted the PR. 
Let me know if I'm missing something.

**Comment by lbroudoux** [comment]
Thanks again @sbonaiva for the contribution! Looking forward to hearing more about your success with Microcks! 😉
