### ISSUE TITLE
No mock generated for parameter in GET-URL

### ISSUE THREAD

**Issue by siom79** [microcks/microcks#808]
### Describe the bug

Upload an openapi-File with a path that contains a parameter:
```yml
paths:
  "/invoices/{contractId}":
    get:
      summary: Returns all invoices for a given contract.
      operationId: getByContractId
      parameters:
        - name: contractId
          in: path
          required: true
          schema:
            type: string
```
No mock is generated, the mock tab in den operations block is empty.

### Expected behavior

A mock is generated an its URL is shown in the operations block of the endpoint.

### Actual behavior

The mock tab is completely empty.

### How to Reproduce?

Upload the following simple openapi.yml:
```yml
---
openapi: 3.0.2
info:
  title: my-title
paths:
  "/invoices/{contractId}":
    get:
      summary: Returns all invoices for a given contract.
      operationId: getByContractId
      parameters:
        - name: contractId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Pastry'
              examples:
                pastries_json:
                  value:
                    - name: Baba Rhum
                      description: Delicieux Baba au Rhum pas calorique du tout
                      size: L
                      price: 3.2
                      status: available
                    - name: Divorces
                      description: Delicieux Divorces pas calorique du tout
                      size: M
                      price: 2.8
                      status: available
                    - name: Tartelette Fraise
                      description: Delicieuse Tartelette aux Fraises fraiches
                      size: S
                      price: 2
                      status: available
components:
  schemas:
    Pastry:
      title: Root Type for Pastry
      description: The root of the Pastry type's schema.
      type: object
      properties:
        name:
          description: Name of this pastry
          type: string
        description:
          description: A short description of this pastry
          type: string
        size:
          description: Size of pastry (S, M, L)
          type: string
        price:
          format: double
          description: Price (in USD) of this pastry
          type: number
        status:
          description: Status in stock (available, out_of_stock)
          type: string
      example:
        name: My Pastry
        description: A short description os my pastry
        size: M
        price: 4.5
        status: available
```

### Microcks version or git rev

1.7.0

### Install method (`docker-compose`, `helm chart`, `operator`, `docker-desktop extension`,...)

docker-compose

**Comment by lbroudoux** [comment]
Hi there!

In order to be able to route according a path parameter, you should define example values for this path parameter too. Please check the documentation [here](https://microcks.io/documentation/using/openapi/#path-parameters) and see in the **Pastry API** sample that we have defined [path parameter examples](https://github.com/microcks/microcks/blob/master/samples/APIPastry-openapi.yaml#L53) for the different pastries in the "GET pastry by name" operation.

For your mock to work, you'll have to define `examples` in the `contractId` path parameter section.

Let us know if it helps.

**Comment by lbroudoux** [comment]
You can also check https://microcks.io/documentation/guides/openapi-101/ for step-by-step guide on path parameter dispatching.

**Comment by siom79** [comment]
But why do I need to specify an example in this case? I have defined that `contractId` is a string. Shouldn't it be possible to start a mock and dispatch this URL?

**Comment by lbroudoux** [comment]
The dispatching is based on the value of this `contractId` string to allow you to express different use cases. 

For example:
* In the case of contract id `abcdef` you may want to return a `200` response with content for contract of type `A`,
* In the case of contract id `ghijkl` you may want to return a `200` response with content for contract of type `B`,
* In the case of contract id `mnopqr` you may want to return a `404` response to illustrate an error on your API.

Values matching allows us to illustrate the different use cases and to do that with near-to-real-life values.

**Comment by siom79** [comment]
I understand the use case of examples but do not understand why it is necessary/mandatory. If I want do return different responses based on the parameter then I need examples. But if I just want to return a response then I don't need examples at all (you can even generate a response based on the schema with default values for all the different data types without examples).

**Comment by lbroudoux** [comment]
I agree with you that generating a response based on schema is technically feasible.

However, this is not something we promote and implemented as we attach very strong importance to having real-world values in the example. This is for us the best way to illustrate the business domain of an API in a detailed way. 

For more information on Microcks' background and beliefs, I can recommend you read the [Why Microcks?](https://microcks.io/blog/why-microcks/) blog post.

**Comment by siom79** [comment]
OK, if you insist that examples are mandatory then I would at least expect an warning/error message when importing the openapi spec. It took me a complete hour to realize that I need to provide examples for parameters to generate a mock.

**Comment by lbroudoux** [comment]
Oh sorry if you lose some time on this... We try to explain it clearly within [OpenAPI usage documentation](https://microcks.io/documentation/using/openapi/#conventions) but looks like we failed. Would you have some suggestions on how to make this more visible?

Also, we could think about outputting some warning about incomplete samples at the import time. Will think about how to enhance that.
