### ISSUE TITLE
Unable to interpret an OpenAPI JSON specification with spaces

### ISSUE THREAD

**Issue by MathisGoichon** [microcks/microcks#812]
### Describe the bug

I get an error when I import an OpenAPI JSON specification in which there are spaces as follows: 
```json
{
  "openapi" : "3.0.0",
    "info" : {
    "version" : "1.0.0",
    "title" : "Swagger Petstore",
    ...
  }
  ...
}
```

The error is as follows: 
```
11:32:00.773 DEBUG 1 --- [80-exec-10] i.g.m.web.UploadArtifactController       : Content type of Petstore_spaces.json is application/json
11:32:00.776  INFO 1 --- [80-exec-10] i.g.m.u.MockRepositoryImporterFactory    : Have not found any explicit marker so applying the default SoapUI Project importer...
Error at line 1, column 1
org.apache.xmlbeans.XmlException: error: Content is not allowed in prolog.
```

In addition, I receive a reply in 200 with the message that the import was successful.

On the other hand, when I remove the spaces, I no longer have a problem with interpretation:
```json
{
  "openapi": "3.0.0",
    "info": {
    "version": "1.0.0",
    "title": "Swagger Petstore",
    ...
  }
  ...
}
```

### Expected behavior

I would like to be able to put an OpenAPI specification in JSON format without having to worry about whitespace, as long as the JSON file is valid. Also, I would like to receive an error message instead of a 200 Success.

### How to Reproduce?

This folder contains a working Petstore.json file and a non-working Petstore_spaces.json file : [Petstore.zip](https://github.com/microcks/microcks/files/11452055/Petstore.zip)

### Microcks version or git rev

1.7.0

### Install method (`docker-compose`, `helm chart`, `operator`, `docker-desktop extension`,...)

docker-compose

**Comment by lbroudoux** [comment]
Hey there! Thanks for raising this issue. We must have a failing regexp... Looking into this.

**Comment by lbroudoux** [comment]
Dammit! Screwed my commits and those ones also include tests for #813 ... Looking carefully for the next CI run 😜

**Comment by MathisGoichon** [comment]
It seems to work fine, thank you!
