### ISSUE TITLE
GetDrivers.wsdl file is missing in the repository

### ISSUE THREAD

**Issue by ludovic-pourrat** [microcks/microcks#813]
### Describe the bug

Hello,

The build is failing in the App module due to a missing GetDrivers.wsdl file which retrieved from `/Users/lbroudou/Development/github/microcks/GetDrivers.wsdl` 

### Expected behavior

The build should pass.

### Actual behavior

Build is failing.

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Microcks 1.7.1-SNAPSHOT:
[INFO] 
[INFO] Microcks ........................................... SUCCESS [  0.078 s]
[INFO] Microcks Model ..................................... SUCCESS [  3.445 s]
[INFO] Microcks Util ...................................... SUCCESS [  3.690 s]
[INFO] Microcks EL ........................................ SUCCESS [  0.614 s]
[INFO] Microcks App ....................................... FAILURE [ 20.634 s]
[INFO] Microcks Async Minion .............................. SKIPPED

### How to Reproduce?

N/A

### Microcks version or git rev

master

### Install method (`docker-compose`, `helm chart`, `operator`, `docker-desktop extension`,...)

mvn install

**Comment by lbroudoux** [comment]
Also, can you specify your Maven version as well? It seems to have some impact on the test engine that is picked for running the tests.

**Comment by ludovic-pourrat** [comment]
Maven & JDK  version

lpourrat@Ludovics-MacBook-Air microcks % mvn --version
Apache Maven 3.8.6 (84538c9988a25aec085021c365c560670ad80f63)
Maven home: /Users/ludovicpourrat/Tools/maven
Java version: 18.0.2.1, vendor: Oracle Corporation, runtime: /Library/Java/JavaVirtualMachines/jdk-18.0.2.1.jdk/Contents/Home
Default locale: en_FR, platform encoding: UTF-8
OS name: "mac os x", version: "13.3.1", arch: "aarch64", family: "Mac"

Thanks for the help.

**Comment by lbroudoux** [comment]
Hey! I cannot reproduce it at the moment as having the missing file error doesn't break the build on my side... However, I understand that having a missing file warning is not expected 😉 

I tried to fix this by fixing the original SoapUI file that is missing a `definitionCache` for being able to catch the WSDL locally. However, I screwed my commit, and push is now attached to #812 ... Looking for the next CI/CD result.

PS: BTW I've made those changes on `1.7.x` where development currently happens. I  encourage you to switch to this branch if you plan any contrib or PR 😉

**Comment by lbroudoux** [comment]
Just run the test suite for `App` again and got:

```
[INFO] Results:
[INFO] 
[INFO] Tests run: 132, Failures: 0, Errors: 0, Skipped: 0
```

**Comment by ludovic-pourrat** [comment]
Works on the 1.7.x branch.

Many thanks.

**Comment by lbroudoux** [comment]
Yes warning has disappeared from CI! See https://github.com/microcks/microcks/actions/runs/4959731225/jobs/8874249597#step:4:2931
