### ISSUE TITLE
Microcks returns HTTP 500 when calling non-existent API

### ISSUE THREAD

**Issue by hguerrero** [microcks/microcks#819]
### Describe the bug

When calling a non-existent service using GraphQL, the server returns HTTP 500

```
{
    "timestamp": 1684525088128,
    "status": 500,
    "error": "Internal Server Error",
    "path": "/graphql/Book+Graph+API/1.0"
}
```

### Expected behavior

It should return HTTP 404 or another code

### Microcks version or git rev

1.6.0

### Install method (`docker-compose`, `helm chart`, `operator`, `docker-desktop extension`,...)

docker-desktop extension

**Comment by hguerrero** [comment]
I agree that 404 maybe not be the correct response, but we certainly need to avoid throwing the HTTP 500. Something in the 400 range makes sense. 406 or 415 could be good options.

**Comment by lbroudoux** [comment]
Assigning this to the next release (`1.8`?) as we cannot change this behavior for the next patch version (`1.7.1`)

**Comment by edeandrea** [comment]
I would argue that 404 is exactly the correct response. The client asked for something which doesn't exist, which is what 404 means.

**Comment by lbroudoux** [comment]
We discussed this topic while reviewing a PR [here](https://github.com/microcks/microcks/pull/1007) with @sfraigneau.  

It looks like we have different cases to handle, and I've come to the proposition below. Could you please check it out and tell us what you think? Ideally, the different cases must be handled in the same way across the different supported protocols.

1. Service + version pair cannot be found. They are unknown from Microcks => returns a `404`
2. We're missing a resource (WSDL or something else) that is mandatory to validate input => returns a `412` (client placed a validation precondition on the request, but it cannot be fulfilled)
3. Validation is executed and fails => return a `400`
4. Dispatcher rules evaluation (Script or `JSON_BODY`) fails => returns a `500`
5. Response cannot be found from evaluated dispatch criteria => returns a `400` (client provides inadequate dispatch criteria)
6. Response can be found but clearly indicates that it is an unknown resource => returns a `404`

Thanks for your help in sorting this out.

**Comment by lbroudoux** [comment]
Changes are now applied to both `RestController` and `GraphQLController`.
