### ISSUE TITLE
Microcks white screen (1.6.1)

### ISSUE THREAD

**Issue by adel-chouchane** [microcks/microcks#820]
I am using microcks and I am getting this error : refused to frame 'https://keycloak.*******' because an ancestor violates the following Content Security Policy directive: "frame-ancestors 'self'".

Does anyone have a solution please ?
Thanks ^^

**Comment by lbroudoux** [comment]
What is the version of the external Keycloak? We've tested 1.6.0 with version 14. Not sure that new versions based on Keycloak X (>= 18.0) would work though...

**Comment by lbroudoux** [comment]
Hi @adel-chouchane 
Sorry for the long delay but was very busy releasing the `1.7.1` and preparing some other stuffs.
Did you finally find a solution or workaround on this? Have you checked this stackoverflow thread: https://stackoverflow.com/questions/72805440/keycloak-error-on-console-violating-content-security-policy-directive-frame?
