### ISSUE TITLE
replicas from values.yaml not used in deployment template 

### ISSUE THREAD

**Issue by sbr82** [microcks/microcks#821]
### Describe the bug

```
microcks:
  replicas: 1
```
from values.yaml not used in deployment template

### Expected behavior

```
microcks:
  replicas: 1
```
from the values.yaml is not used in the deployment template, therefore this configuration does not have effect.

If microcks should not be scaled then I suggest that the replicas property to be removed from the values file, otherwise please use the value in the deployment template.

### Actual behavior

value in replicas does not take effect

### Microcks version or git rev

1.7.0

### Install method (`docker-compose`, `helm chart`, `operator`, `docker-desktop extension`,...)

helm-chart

**Comment by lbroudoux** [comment]
Hey! Thanks for raising this issue. This one has actually been fixed here (https://github.com/microcks/microcks/issues/768) and it will be released with next `1.7.1`. You can use the chart from branch `1.7.x` if you wish.
