### ISSUE TITLE
Add documentation on HTTPS setup

### ISSUE THREAD

**Issue by lbroudoux** [microcks/microcks#83]
Following #81 documentation is needed on how to complete HTTPS setup using certificates generated with custom CA

**Comment by lbroudoux** [comment]
It will be of great help @nmasse-itix !

**Comment by arjunprasad2143** [comment]
Could you please help us with some documentation on this.
I have installed microcks using microcks-operator.v1.5.0 on openshift 4.9. We had done the initial install with generatecert true value. But now we want to add a certificate. I have added a secret with the certs and given the ingressSecretRef option mentioning the secret. But seems like ingress is not being deployed. Could you please direct me to some documentation or guide me on the steps to deploy a cert
