### ISSUE TITLE
Provide a CloudFormation template for AWS

### ISSUE THREAD

**Issue by lbroudoux** [microcks/microcks#85]
As it is done withe Azure in microcks/microcks-azure component, we'd like to provide simple, demo purposed, CloudFormation template for AWS.

I've initialized stuffs but being a newbee at AWS stuffs, help is welcomed !!

**Comment by rj2704** [comment]
Hi @lbroudoux, I want to work on this issue. I have good knowledge of CloudFormation. Can you please elaborate on this issue?

**Comment by lbroudoux** [comment]
Hi @rj2704!

Thanks for your proposition: You're more than welcome!

At the time of writing, I was thinking of something very simple that could just be a wrapper around the `docker-compose` way of installing things on a single VM. However, it would have to take care of gathering a public IP/URL with a proper certificate so with maybe a traefik or ngynx reverse-proxy in front to handle the TLS stuff.

But... it was so a long time ago 😉 It can definitely be challenged, reviewed, and enhanced to what's state-of-the-art on AWS! The ultimate goal is to make the install experience leaner for someone having knowledge of AWS and wanting to set up things for a quick evaluation of Microcks.

**Comment by JensenJose** [comment]
Hey @lbroudoux, could you gimme a bit more details on what exactly has to be done using CloudFormation, I'll be glad to help you out.

**Comment by lbroudoux** [comment]
Hey @JensenJose, 
thanks for your message. 
TBH, I was thinking of something straightforward like the one explained above (`docker-compose wrapper + reverse proxy with TLS). However, I'm definitely not an expert on AWS stuffs so suggestion are more than welcome!
