### ISSUE TITLE
Review Getting Started 🚀  guide with usage of hub.microcks.io

### ISSUE THREAD

**Issue by lbroudoux** [microcks/microcks#852]
This issue aims to review https://microcks.io/documentation/getting-started/ so that it now describes how to load samples from the Hub (embedded into Microcks) instead of loading each sample using their URLs.

BTW 1: As the review of this documentation will finally be done after the `1.8.0` release and the introduction of the `microcks-uber` image, I wonder if it wouldn't be even easier to change the "Getting Started" guide so that it uses a simple `docker run` command made possible with uber instead of the docker-compose method...

BTW 2: https://microcks.io/documentation/getting-started-test/ probably needs to be reviewed, too. It could be nice to do it in the same pass.

**Comment by kengneruphine** [comment]
Hello @lbroudoux, thanks for tagging me on this issue.
I want to work on it.

Please, could you provide more details on the issue? Thanks

**Comment by kengneruphine** [comment]
Hello @lbroudoux, Just to clarify, is the microcks.io repository being used for this issue, right?

**Comment by lbroudoux** [comment]
Oh yes sure! Sorry for missing that point. Also, we're using a pretty old version of [Hugo](https://gohugo.io/) for rendering the website - if you want to test rendering, you'll have to install Hugo 0.90.1 and just run `hugo serve`. It renders everything and then starts on port `1313` so that you just have to hit `http://localhost:1313` in your browser to navigate a local copy of the website.

**Comment by kengneruphine** [comment]
Hi @lbroudoux, do you have a sample .env file for this website? If yes, please could you share it with me.
I have errors like `<getenv "HUGO_ENV">: error calling getenv: access denied: "HUGO_ENV" and <getenv "REPOSITORY_URL">: error calling getenv: access denied: "REPOSITORY_URL" is not whitelisted in policy "security.funcs.getenv `when I run the `hugo serve` cmd.

**Comment by kengneruphine** [comment]
I succeeded in installing v0.90.1 so I have the website running locally on my machine

**Comment by kengneruphine** [comment]
Hello @lbroudoux, I have sent a pull request on this issue. Please could you have a look at it?

**Comment by lbroudoux** [comment]
Complete by @kengneruphine! Thank you very much!
