### ISSUE TITLE
Write a "compatibility matrix" or "tested configuration matrix" page

### ISSUE THREAD

**Issue by lbroudoux** [microcks/microcks#859]
### Describe the bug

As of today, we don't have any place in the documentation where one can find all the versions of all the dependencies used within Microcks. By "dependency" I mean runtime dependencies, not the ones that are embedded into container images.

People may expect some pieces of information regarding the configuration we use during the development and test phases (not talking about QA yet). I think people may like to know:
* Kubernetes versions tested,
* Keycloak versions tested,
* MongoDB versions / distributions tested,
* Jenkins versions, 
* ...

+ internal Microcks components compatibility matrix (Which version of `microcks-cli` to use with which version of `microcks` main component? etc...)

It would be nice to produce such a new page.

**Comment by SaxenaAnushka102** [comment]
Hello @lbroudoux ! Can I please get to know more about the dependencies that need to be added to the documentation? I'd love to contribute to this, thanks!

**Comment by lbroudoux** [comment]
Hello @SaxenaAnushka102, thanks for the proposition!

As stated above, the goal would be to track the tested configurations of Microcks easily. I think we should distinguished 2 different things:
* Microcks internals - aka the versions of the components Microcks is relying on to run its core services: MongoDB, Keycloak, Kafka, Kubernetes, Docker-compose, Docker Desktop, etc.
* Microcks ecosystem - aka the versions of the components that interact with Microcks APIs (typically all the components coming from the repos `microcks-*`): the Jenkins plugin, the CLI, the GitHub Actions, the Backstage plugin, the Docker Desktop Extension, the Testcontainers lib, the Go client, etc...

Maybe you could start listing around those 2 things and think about a way to display things?

Ideally, we should also think about how the community users may contribute a new "tested configuration". Imagine I deploy Microcks using - for example - MongoDB Atlas, I'd like to inform others that I tested this configuration successfully... It could be also nice to think about a specific issue or workflow to ease the lives of people who want to share their config?

What do think?
