### ISSUE TITLE
Build and provide a benchmarking suite

### ISSUE THREAD

**Issue by lbroudoux** [microcks/microcks#870]
### Reason/Context

As of today, we don't have any formal and easy way to measure a Microcks installation performance. However, this could be very useful in a number of contexts:
* Internally: we may have a formal way to check that new features, bug fixes, and technology upgrades don't degrade performances. We'd also have a way to ensure that improvements actually bring enhancements in performance (time, and resource consumption)
* Externally: this may help community users to ensure their setup will address their needs regarding projected usage. This can also allow building capacity planning more easily, answering questions like: what number of replicas do I need? When will I need to scale-up? What is my actual consumption of resources regarding the number of APIs/number of consumers I have? ...

### Description

We'd like to have a simple-to-use benchmarking suite that allows us to simulate virtual users that are both using the UI and the mocking/testing APIs.

Ideally, the proposition of "browsing users" vs "API calls" should be configurable depending on expected usage. Also in the "API calls" category, we'd like to be able to configure the proportion of calls on different API types. For example, we may need to configure:
* 10% "browsing users" and 90% "API calls"
* In the "API calls", having:
  - 10% being SOAP mock requests, as we still have some legacy
  - 70% being REST mock requests, as it's the mainstream usage
  - 20% being GraphQL mock request, as we started to explore this technology,
  - 0% being gRPC mock request, as we don't have gRPC at the moment.

### Implementation ideas

[K6](https://k6.io/) seems to be a great candidate for writing such scripts and handling configuration in JSON/JavaScript files. It can be run locally or using instances on the cloud. The results may be exported and analyses through free tier of K6 Cloud to benefit from standards graphs and/or dashboards.

**Comment by yada** [comment]
+1 and maybe it could be the opportunity to do and add some sustainability metrics using the Kubernetes Efficient Power Level Exporter ([Kepler](https://sustainable-computing.io/))?

To dig further and see if a community effort can be done on this issue (benchmarks with or not sustainability metrics)?

**Comment by davidszegedi** [comment]
Kepler (deployed on the Kubernetes hosting platform for Microcks) could provide cpu and memory power consumption levels (in watts) at a pod/replica granularity, thus could cover the resource consumption energy footprint requirement.

**Comment by lbroudoux** [comment]
Keeping it open as we know @alainpham is working on it! 🚀 🙏

**Comment by lbroudoux** [comment]
I fixed some bad requests in the script and make the `WAIT_TIME` between browsing requests configurable.

I get the following result on my Mac M2, running Microcks on Java 17, with a max heap at 400MB, with `INFO` log level, with statistics disabled and with the `WAIT_TIME` set to `0.1`:

```sh
$ docker run --rm -i -e BASE_URL=${MICROCKS_BASE_URL} -e WAIT_TIME=0.1 grafana/k6:${K6_VERSION} run - < bench-microcks.js

          /\      |‾‾| /‾‾/   /‾‾/   
     /\  /  \     |  |/  /   /  /    
    /  \/    \    |     (   /   ‾‾\  
   /          \   |  |\  \ |  (‾)  | 
  / __________ \  |__| \__\ \_____/ .io

  execution: local
     script: -
     output: -

  scenarios: (100.00%) 4 scenarios, 85 max VUs, 2m45s max duration (incl. graceful stop):
           * browse: 20 looping VUs for 1m0s (exec: browse, gracefulStop: 30s)
           * invokeRESTMocks: 200 iterations for each of 40 VUs (maxDuration: 2m0s, exec: invokeRESTMocks, startTime: 5s, gracefulStop: 30s)
           * invokeGraphQLMocks: 100 iterations for each of 20 VUs (maxDuration: 2m0s, exec: invokeGraphQLMocks, startTime: 10s, gracefulStop: 30s)
           * invokeSOAPMocks: 5 iterations for each of 5 VUs (maxDuration: 2m0s, exec: invokeSOAPMocks, startTime: 15s, gracefulStop: 30s)
           
[...]

running (1m04.0s), 14/85 VUs, 10271 complete and 0 interrupted iterations
browse             ↓ [ 100% ] 20 VUs  1m0s         
invokeRESTMocks    ✓ [ 100% ] 40 VUs  0m12.7s/2m0s  8000/8000 iters, 200 per VU
invokeGraphQLMocks ✓ [ 100% ] 20 VUs  0m06.9s/2m0s  2000/2000 iters, 100 per VU
invokeSOAPMocks    ✓ [ 100% ] 5 VUs   0m16.0s/2m0s  25/25 iters, 5 per VU

     ✓ status code should be 200
     ✓ pastryCall status is 200
     ✓ eclairCall status is 200
     ✓ eclairXmlCall status is 200
     ✓ eclairXmlCall response is Xml
     ✓ millefeuilleCall status is 200
     ✓ allFilmsCall status is 200
     ✓ aFilmCall status is 200
     ✓ aFilmFragmentCall status is 200
     ✓ andrewCall status is 200
     ✓ karlaCall status is 200
     ✓ karlaCall body is correct
     ✓ laurentCall status is 500
     ✓ laurentCall body is fault

     checks.........................: 100.00% ✓ 46385      ✗ 0    
     data_received..................: 132 MB  2.0 MB/s
     data_sent......................: 7.8 MB  122 kB/s
     http_req_blocked...............: avg=40.83µs  min=291ns   med=1.04µs  max=18.4ms   p(90)=5.04µs   p(95)=8.37µs  
     http_req_connecting............: avg=33.21µs  min=0s      med=0s      max=18.35ms  p(90)=0s       p(95)=0s      
     http_req_duration..............: avg=17.22ms  min=1ms     med=12.57ms max=782.36ms p(90)=28.2ms   p(95)=36.67ms 
       { expected_response:true }...: avg=17.21ms  min=1ms     med=12.57ms max=782.36ms p(90)=28.2ms   p(95)=36.66ms 
     http_req_failed................: 0.05%   ✓ 26         ✗ 48709
     http_req_receiving.............: avg=80.43µs  min=6.5µs   med=22.66µs max=29.12ms  p(90)=129.29µs p(95)=235.55µs
     http_req_sending...............: avg=15.04µs  min=1.58µs  med=4.95µs  max=9.27ms   p(90)=22.33µs  p(95)=36.83µs 
     http_req_tls_handshaking.......: avg=0s       min=0s      med=0s      max=0s       p(90)=0s       p(95)=0s      
     http_req_waiting...............: avg=17.12ms  min=902.5µs med=12.49ms max=782.34ms p(90)=28.08ms  p(95)=36.49ms 
     http_reqs......................: 48735   756.508316/s
     iteration_duration.............: avg=194.32ms min=10.5ms  med=52.16ms max=5.57s    p(90)=101.2ms  p(95)=177.01ms
     iterations.....................: 10285   159.652981/s
     vus............................: 14      min=14       max=85 
     vus_max........................: 85      min=85       max=85 


running (1m04.4s), 00/85 VUs, 10285 complete and 0 interrupted iterations
browse             ✓ [ 100% ] 20 VUs  1m0s         
invokeRESTMocks    ✓ [ 100% ] 40 VUs  0m12.7s/2m0s  8000/8000 iters, 200 per VU
invokeGraphQLMocks ✓ [ 100% ] 20 VUs  0m06.9s/2m0s  2000/2000 iters, 100 per VU
invokeSOAPMocks    ✓ [ 100% ] 5 VUs   0m16.0s/2m0s  25/25 iters, 5 per VU
```

**756.508316/s** !! 🚀
