### ISSUE TITLE
Documentation for service account not working with Keycloak 20.0

### ISSUE THREAD

**Issue by ludovicc** [microcks/microcks#878]
### Describe the bug

Keycloak 20.0 has changed a lot its API, and the documentation about Service accounts does not work anymore.

In particular, the following call fails:

curl -X POST https://keycloak.microcks.example.com/auth/realms/microcks/protocol/openid-connect/token

I was not able to find an alternative way to generate the OpenID token, even the default microcks-serviceaccount has disappeared.

**Comment by lbroudoux** [comment]
I've updated the doc and the screenshot to the new version of Keycloak. Thanks again for your feedback.
