### ISSUE TITLE
JMS/ActiveMQ Support

### ISSUE THREAD

**Issue by smfaizalkhan** [microcks/microcks#879]
### Reason/Context

Hi @lbroudoux 

I have been looking at the microcks ,We are using JMS /ActiveMQ as our Messaging Broker .And i couldn't find activemq/jms support in ./minions/async/src/main/resources or the Java code in the producer folder 

Any plans to add it ?

### Description

Support for JMS/ActiveMQ Support

### Implementation ideas

Add ActiveMQ/JMS support in async minions

**Comment by lbroudoux** [comment]
Hello @smfaizalkhan!

JMS support (independent of whether it is ActiveMQ or other providers) would be a great addition. We also discussed adding AMQP 1.0 in the past [here](https://github.com/microcks/microcks/issues/402) and I think this one is directly implemented by ActiveMQ.

The challenge I foresee with JMS is that it's actually an interface set definition and not a protocol on its own. To have it working you have to integrate the specific jar libraries that come from your MOM provider. And as of today, we do not have any mechanism that allows integrating additional jar files within Microcks class-loader... 

This has to be something to work on before properly adding support to JMS AsyncAPI binding in Microcks. However could be something useful for other use-cases as well like: plugging your own scripting libraries or embedding some kind of custom middleware components in Microcks.

Back to your topic: is it pure JMS or ActiveMQ/AMQP 1.0 support you'd need? Do you have any roadmap/hard requirements for that or are you just evaluating at the moment? Thanks for your insights!

**Comment by smfaizalkhan** [comment]
hi @lbroudoux 
Thanks for coming back 
Yea i agree to the point that JMS being an interface and we need MOM libraries 
But i was  under the impression that how AWS SQS is supported by microcks ,so i tot it will adding activemq libraries and adding support to ActiveMQ 

Coming to our requirment ,yes we do use ActiveMQ for websocket based applications

**Comment by lbroudoux** [comment]
Don't know if you checked it out but support for WebSocket is already there in Microcks. 

From an AsyncAPI spec having a WebSocket binding, Microcks can:
* Provide you with WebSocket endpoints and mimic producer of messages without developing it,
* Connect to an external WebSocket endpoint (in your case - as I understand it - provided by ActiveMQ) and consume messages to check they're conformant with the schema from the AsyncAPI spec.

Have you tried this one?

**Comment by lbroudoux** [comment]
OK got it! I was thinking your needs were FE only. 
Have you already evaluated Microcks on other protocols to see if it fit well your needs? If you're convinced it's the good pick and you'd need some new protocols, we could envision collaboration on delivering this new feature.
Let me know what is your agenda and how you see things.

**Comment by lbroudoux** [comment]
@smfaizalkhan up 😉

**Comment by smfaizalkhan** [comment]
Hi @lbroudoux  .
Sorry for  the late update .We are using NIO TRANSPORT with OpenWire protocol 
openwire+nio://xxxx:yyyy
Would like to go fwd

**Comment by hguerrero** [comment]
@smfaizalkhan are you using ActiveMQ 5?

**Comment by smfaizalkhan** [comment]
@hguerrero  we are using 5.15.9 version
rmohr/activemq:5.15.9

**Comment by smfaizalkhan** [comment]
@lbroudoux @hguerrero 
I tried to pull in the code and tried adding activemq by adding the BindingType as OPENWIRE and tried to build it locally using this instructions 
https://github.com/microcks/microcks/blob/master/CONTRIBUTING.md

But after running the docker build command  i get the below result that Skipping Docker build

![image](https://github.com/microcks/microcks/assets/22238550/0311e5df-aa84-4e17-8198-a62fb061e5ee)

**Comment by lbroudoux** [comment]
Oh sorry! My bad! I've committed a test in the `pom.xml` file of /webapp.
You'll have to change line `461` to:
```xml
<dockerDirectory>src/main/docker</dockerDirectory>
```

Also it appears that it does no longer work on Mac M1, so I've used this command on my machine:
```sh
mvn -Pprod package && docker build -f src/main/docker/Dockerfile . -t lbroudoux/microcks:nightly
```
Finally, I have to change the reference of the image in the docker-compose to this `lbroudoux/microcks:nightly`
