### ISSUE TITLE
OpenAPI mock service

### ISSUE THREAD

**Issue by doranych** [microcks/microcks#88]
Is it possible to start microcks openapi 3 mock service for specification without any examples? 

Why i can't start dynamic mock for that? 
It seems like bug.
Because pure model specification enought to build examples dynamicly.

Thx for answer

**Comment by doranych** [comment]
Yes, you heard me right.
> An OpenAPI spec with some CRUD operations and some controllers ? 

It's possible, that I don't know some details for that. But I have not seen OpenAPI 3 controllers. 
>An OpenAPI spec with CRUD operations that have examples and some that don't

You have fully qualified models and methods. It means, that you don't need examples at all. For obvious reasons
> An OpenAPI spec with inconsistent schema between CRUD operations (for instance one schema for the POST that has a payload without id, and a schema with id for other operations) ?

It can be solved using the model, when ID field is not required. It means, that in some cases you no need to send it. But always receive.
>How would you handle the HTTP status codes (200, 201, 404, 409, 500) defined in the specification ? by convention (return to a POST is 201 no matter what is defined in the spec, etc.) ?

Is it possible, to have more than one successful status in same endpoint? I'm not sure about it. 
So you can always return defied success response. Or error, for example, on validation.


Most of all, i asked about mock it self for OpenAPI 3 specification without examples. 
It'll be nice, if you can run static mock for specification without any examples. 
because otherwise it makes not required field to be required

**Comment by lbroudoux** [comment]
Closing this one as unfortunately this is not something we promote.

We do think examples are a great way to enrich contract with helpful and realilstics informations on how things are supposed to work. We do not think pure randomized, generated, even if syntactically correct examples are really helpful for understanding what the designer of the API had in mind when writing his contract.
