### ISSUE TITLE
Unable to Import an XML File of size 1MB 

### ISSUE THREAD

**Issue by sunilg009** [microcks/microcks#890]
### Describe the bug

Trying to import a file size of 1MB having mocked request and response.

### Expected behavior

Upload should be successful

### Actual behavior

RESTProjectAugust17th.xml Importation error on server side (<html> <head><title>413 Request Entity Too Large</title></head> <body> <center><h1>413 Request Entity Too Large</h1></center> <hr><center>nginx</center> </body> </html>       )

### Microcks version or git rev

Version 1.7.1-fix-1

**Comment by lbroudoux** [comment]
Hey there! Thanks for opening this issue. As you seem to have Nginx in front of Microcks, have you checked that the upload limit is not coming from Nginx? IIRC the default upload size in Microcks is 2MB but can be setup to more.

**Comment by lbroudoux** [comment]
@sunilg009 Any news on this issue?

**Comment by yada** [comment]
@sunilg009 up, do you have any update and feedback on this old issue? Can we close?

**Comment by lbroudoux** [comment]
Closing this issue with `invalid` status as we don't get additional information.
