### ISSUE TITLE
Not eliminating the Service after deleting the corresponding Job

### ISSUE THREAD

**Issue by lucamaf** [microcks/microcks#9]
I created a Service which wasn't really working as expected so I stopped the corresponding Job and deleted it, but the Service is still there (which is not supposed to be the case).
![screenshot from 2017-12-15 15-11-17](https://user-images.githubusercontent.com/1726883/34045734-8517516a-e1aa-11e7-98f8-74a09a2d393e.png)
![screenshot from 2017-12-15 15-11-03](https://user-images.githubusercontent.com/1726883/34045738-8aa50ae6-e1aa-11e7-88f6-d5744e05b2c0.png)

**Comment by lbroudoux** [comment]
I think deleting Service and deleting Job should be 2 different things. You may want to stop scrapping a source because Service is deprecated ; however you still want to let the Service in registry for some time ...
What to do you think?

**Comment by lucamaf** [comment]
I agree, but at the moment there is no way to delete the Job right?

**Comment by lbroudoux** [comment]
You're right: Services cannot be deleted for now. I was waiting to implement #3 before adding this feature.

**Comment by lbroudoux** [comment]
Deleting service is now possible on `new-ux-0.7.x` branch and decorelated from deletion of importer Job.
