### ISSUE TITLE
Integrate Microcks with AWS IAM

### ISSUE THREAD

**Issue by dhiemaz** [microcks/microcks#91]
I have successfully deploy Microcks on my local laptop, and we have plan to deploy Microcks on AWS. Based on what I check in prequisite Microcks gihub

Pre-requisites
NodeJS (version >= 8.0) and associated tools : NPM and ng-cli (npm install -g ng-cli)
Java Development Kit (version >= 8) and Apache Maven (version >= 3.0)
Keycloak 3.4.0
MongoDB 3.2

that Microcks use Keycloack (https://www.keycloak.org/). 

So my question is It possible to change Keycloack IAM in Microcks with AWS IAM ?

Thank you

**Comment by nmasse-itix** [comment]
Hi @dhiemaz,

Microcks is tightly coupled with Keycloak: namely Keycloak is the component that handles authentication and access control on Microcks. 

But, do not worry, it's a technical component that should not require administration. 

If you are already using AWS IAM, you can configure Keycloak to delegate user authentication to AWS IAM. You can also retrieve user privileges from AWS IAM to set the correct access rights in Microcks. 

According to the AWS IAM Documentation, you should be able to setup a SAML federation between AWS IAM and Keycloak. You can also configure Keycloak to bypass the Keycloak login page: this way your users won't have to deal with Keycloak: they will only see the AWS IAM login page. 

Let us know if you succeed with this setup !

**Comment by lbroudoux** [comment]
If it could be of any help, I've found this [blog post](https://stories.scandiweb.com/sign-in-to-amazon-aws-using-saml-protocol-and-keycloak-as-identity-provider-e3798387de99) that describe this configuration.

There's also this [part of Keycloak's doc](https://www.keycloak.org/docs/latest/server_admin/index.html#default_identity_provider) that mention how to configure a default Identity Provider to bypass the login page.
