### ISSUE TITLE
Unable to configure two same REST endpoints with different http method [GET,POST]

### ISSUE THREAD

**Issue by sunilg009** [microcks/microcks#914]
### Describe the bug

I have added 2 REST Endpoints with same name , where having different http method GET,POST.
ex:=
API1 [GET] = http://localhost:8080/dummy/test
API2 [POST] = http://localhost:8080/dummy/test [with Request Body]

### Expected behavior

we should see 2 request endpoints one for POST and other for GET

### Actual behavior

Issue facing in after uploading the xml in microcks cluster.

we see that one request endpoint [GET] is exposed , Instead of 2 request endpoints.

### How to Reproduce?

<?xml version="1.0" encoding="UTF-8"?>
<con:soapui-project id="a03bb5d7-34ef-4aae-bf68-d2210799eeb4" activeEnvironment="Default" name="REST Project 5" soapui-version="5.7.0" xmlns:con="http://eviware.com/soapui/config"><con:settings/><con:interface xsi:type="con:RestService" id="4ec17fef-2c0e-475a-803c-4babff2aa5cf" wadlVersion="http://wadl.dev.java.net/2009/02" name="http://localhost:8080" type="rest" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"><con:settings/><con:definitionCache/><con:endpoints><con:endpoint>http://localhost:8080</con:endpoint></con:endpoints><con:resource name="test" path="/dummy/test" id="fec9013f-55e3-42f6-9b43-502b537c7dcc"><con:settings/><con:parameters/><con:method name="Method 1" id="8805d567-cac1-4f42-925b-254c450985e0" method="GET"><con:settings/><con:parameters/><con:representation type="RESPONSE"><con:mediaType>application/json</con:mediaType><con:status>200</con:status><con:params/><con:element xmlns:test="http://localhost/dummy/test">test:Response</con:element></con:representation><con:request name="Request 1" id="f5efe8fc-e472-4276-afe9-23f1b5f6f55c" mediaType="application/json"><con:settings/><con:endpoint>http://localhost:8080</con:endpoint><con:request/><con:credentials><con:authType>No Authorization</con:authType></con:credentials><con:jmsConfig JMSDeliveryMode="PERSISTENT"/><con:jmsPropertyConfig/><con:parameters/></con:request></con:method></con:resource><con:resource name="test" path="/dummy/test" id="37c887af-4675-4663-9194-be72cb191d7b"><con:settings/><con:parameters/><con:method name="Method 1" id="894f8ea9-e2a9-4756-8589-5715a4e08a0b" method="POST"><con:settings/><con:parameters/><con:representation type="REQUEST"><con:mediaType>application/json</con:mediaType><con:params/></con:representation><con:representation type="RESPONSE"><con:mediaType>application/json</con:mediaType><con:status>200</con:status><con:params/></con:representation><con:request name="Request 1" id="0b1897ce-65f5-42f9-8d0f-2f692032f871" mediaType="application/json" postQueryString="false"><con:settings><con:setting id="com.eviware.soapui.impl.wsdl.WsdlRequest@request-headers">&lt;xml-fragment/></con:setting></con:settings><con:endpoint>http://localhost:8080</con:endpoint><con:request>{
	"user" : "test"
}
</con:request><con:credentials><con:authType>No Authorization</con:authType></con:credentials><con:jmsConfig JMSDeliveryMode="PERSISTENT"/><con:jmsPropertyConfig/><con:parameters/></con:request></con:method></con:resource></con:interface><con:testSuite id="5761cff2-5535-40ab-90ac-127e19749024" name="TestSuite"><con:settings/><con:runType>SEQUENTIAL</con:runType><con:testCase id="fb1b5437-bad1-41ad-b8dc-79af833f54a3" failOnError="true" failTestCaseOnErrors="true" keepSession="false" maxResults="0" name="TestCase 1" searchProperties="true"><con:settings/><con:testStep type="restrequest" name="GETDummy Request" id="33e4f203-02e6-460d-9bb9-7c6c6ee00626"><con:settings/><con:config service="http://localhost:8080" resourcePath="/dummy/test" methodName="Method 1" xsi:type="con:RestRequestStep" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"><con:restRequest name="GETDummy Request" id="f5efe8fc-e472-4276-afe9-23f1b5f6f55c" mediaType="application/json"><con:settings><con:setting id="com.eviware.soapui.impl.wsdl.WsdlRequest@request-headers">&lt;xml-fragment/></con:setting></con:settings><con:endpoint>http://localhost:8080</con:endpoint><con:request/><con:originalUri>http://localhost/dummy/test</con:originalUri><con:credentials><con:authType>No Authorization</con:authType></con:credentials><con:jmsConfig JMSDeliveryMode="PERSISTENT"/><con:jmsPropertyConfig/><con:parameters/></con:restRequest></con:config></con:testStep><con:properties/></con:testCase><con:testCase id="6f99057e-d3d2-4b86-8ce0-276ba531ada0" failOnError="true" failTestCaseOnErrors="true" keepSession="false" maxResults="0" name="TestCase 2" searchProperties="true"><con:settings/><con:testStep type="restrequest" name="POSTDummy Request" id="05fd678a-fce2-4160-8ce1-a8529674c03b"><con:settings/><con:config service="http://localhost:8080" resourcePath="/dummy/test" methodName="Method 1" xsi:type="con:RestRequestStep" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"><con:restRequest name="POSTDummy Request" id="f5efe8fc-e472-4276-afe9-23f1b5f6f55c" mediaType="application/json" postQueryString="false"><con:settings><con:setting id="com.eviware.soapui.impl.wsdl.WsdlRequest@request-headers">&lt;xml-fragment/></con:setting></con:settings><con:endpoint>http://localhost:8080</con:endpoint><con:request>{
	"user" : "test"
}</con:request><con:originalUri>http://localhost/dummy/test</con:originalUri><con:credentials><con:authType>No Authorization</con:authType></con:credentials><con:jmsConfig JMSDeliveryMode="PERSISTENT"/><con:jmsPropertyConfig/><con:parameters/></con:restRequest></con:config></con:testStep><con:properties/></con:testCase><con:properties/></con:testSuite><con:restMockService id="9266f966-52fa-4400-b9e4-361d86ff5435" port="8080" path="/" host="MMD5CG0161G54" name="CorrServiceDummyMocks"><con:settings/><con:properties><con:property><con:name>version</con:name><con:value>8.5</con:value></con:property></con:properties><con:restMockAction name="/dummy/test" method="GET" resourcePath="/dummy/test" id="f660b13b-f5e1-4ab7-aecc-2b4354e5af8c"><con:settings/><con:defaultResponse xsi:nil="true" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"/><con:dispatchStyle>SEQUENCE</con:dispatchStyle><con:dispatchPath>/*&#13;
// Script dispatcher is used to select a response based on the incoming request.&#13;
// Here are few examples showing how to match based on path, query param, header and body&#13;
&#13;
// Match based on path&#13;
def requestPath = mockRequest.getPath()&#13;
log.info "Path: "+ requestPath&#13;
&#13;
if( requestPath.contains("json") )&#13;
{&#13;
    // return the name of the response you want to dispatch&#13;
    return "JSON Response"&#13;
}&#13;
&#13;
&#13;
// Match based on query parameter&#13;
def queryString = mockRequest.getRequest().getQueryString()&#13;
log.info "QueryString: " + queryString&#13;
&#13;
if( queryString.contains("stockholm") )&#13;
{&#13;
    // return the name of the response you want to dispatch&#13;
    return "Response Stockholm"&#13;
}&#13;
else if( queryString.contains("london") )&#13;
{&#13;
    // return the name of the response you want to dispatch&#13;
    return "Response London"&#13;
}&#13;
&#13;
&#13;
// Match based on header&#13;
def acceptEncodingHeaderList = mockRequest.getRequestHeaders().get("Accept-Encoding")&#13;
log.info "AcceptEncoding Header List: " + acceptEncodingHeaderList&#13;
&#13;
if( acceptEncodingHeaderList.contains("gzip,deflate") )&#13;
{&#13;
    // return the name of the response you want to dispatch&#13;
    return "GZiped Response"&#13;
}&#13;
&#13;
&#13;
// Match based on body&#13;
def requestBody = mockRequest.getRequestContent()&#13;
log.info "Request body: " + requestBody&#13;
&#13;
if( requestBody.contains("some data") )&#13;
{&#13;
    // return the name of the response you want to dispatch&#13;
    return "Response N"&#13;
}&#13;
*/&#13;
</con:dispatchPath><con:response name="GETDummy Response" id="c656c541-41e4-4a68-a111-2f000f342f2c" httpResponseStatus="200" mediaType="application/json"><con:settings/><con:responseContent>{
	"name" : "test"
}
</con:responseContent></con:response></con:restMockAction><con:restMockAction name="/dummy/test" method="POST" resourcePath="/dummy/test" id="9ecc25fe-75ee-4a83-9a55-f7c3f835f75d"><con:settings/><con:defaultResponse xsi:nil="true" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"/><con:dispatchStyle>SEQUENCE</con:dispatchStyle><con:dispatchPath>/*&#13;
// Script dispatcher is used to select a response based on the incoming request.&#13;
// Here are few examples showing how to match based on path, query param, header and body&#13;
&#13;
// Match based on path&#13;
def requestPath = mockRequest.getPath()&#13;
log.info "Path: "+ requestPath&#13;
&#13;
if( requestPath.contains("json") )&#13;
{&#13;
    // return the name of the response you want to dispatch&#13;
    return "JSON Response"&#13;
}&#13;
&#13;
&#13;
// Match based on query parameter&#13;
def queryString = mockRequest.getRequest().getQueryString()&#13;
log.info "QueryString: " + queryString&#13;
&#13;
if( queryString.contains("stockholm") )&#13;
{&#13;
    // return the name of the response you want to dispatch&#13;
    return "Response Stockholm"&#13;
}&#13;
else if( queryString.contains("london") )&#13;
{&#13;
    // return the name of the response you want to dispatch&#13;
    return "Response London"&#13;
}&#13;
&#13;
&#13;
// Match based on header&#13;
def acceptEncodingHeaderList = mockRequest.getRequestHeaders().get("Accept-Encoding")&#13;
log.info "AcceptEncoding Header List: " + acceptEncodingHeaderList&#13;
&#13;
if( acceptEncodingHeaderList.contains("gzip,deflate") )&#13;
{&#13;
    // return the name of the response you want to dispatch&#13;
    return "GZiped Response"&#13;
}&#13;
&#13;
&#13;
// Match based on body&#13;
def requestBody = mockRequest.getRequestContent()&#13;
log.info "Request body: " + requestBody&#13;
&#13;
if( requestBody.contains("some data") )&#13;
{&#13;
    // return the name of the response you want to dispatch&#13;
    return "Response N"&#13;
}&#13;
*/&#13;
</con:dispatchPath><con:response name="POSTDummy Response" id="def200e9-36ad-4a5f-8680-e28578ba60d9" httpResponseStatus="200" mediaType="application/json"><con:settings/><con:responseContent/></con:response></con:restMockAction></con:restMockService><con:properties/><con:wssContainer/><con:oAuth2ProfileContainer/><con:oAuth1ProfileContainer/></con:soapui-project>

### Microcks version or git rev

Version 1.7.1-fix-1

### Additional information

Have added the sample XML project in "**How to Reproduce section "**

**Comment by lbroudoux** [comment]
Hey there! Thanks for opening this issue. 
I'm not sure to understand what you're trying to achieve as the `http://localhost:8080/dummy/test` URLs are not produced by Microcks that uses URL scheme like `<microcks>/rest/<api name>/<api version>/<api path>`...
Also, as it is pasted, your SoapUI project does not look like a valid XML... Can you upload it directly in the issue of putting it into a Gist so that I can try importing it?
Thanks,

**Comment by lbroudoux** [comment]
Hey there! Any news/follow-up on this issue?
We can try reproducing if you provide a valid SoapUI project that illustrates what's wrong vs what you expect.

**Comment by yada** [comment]
@sunilg009 could you please send us some feedback on this issue please?
