### ISSUE TITLE
Path Parameter as undefined when imported from SOAP UI

### ISSUE THREAD

**Issue by RitikaSingl** [microcks/microcks#919]
### Reason/Context

Need: Need to Mock many requests where only path parameter is changed.

Help: As this will save our time of mocking n number of requests as we can create a dispatcher script for the different requests and response

Motivation: This will help many users who has the same requirement

### Description

No this is not a breaking change. This should read path parameter from the soap ui and set it in microcks on the basis of request

**Comment by lbroudoux** [comment]
Thanks a lot for opening this issue @RitikaSingl! We'll not be able to put it under the `1.8.0` release umbrella, but looking forward to integrating it into the next one!
