### ISSUE TITLE
Microcks compatible API secured Oauth2

### ISSUE THREAD

**Issue by crismarfr** [microcks/microcks#92]
Hello
I'm having trouble accessing secure APIs with Oauth2 tokens. Is microcks compatible with secure API calls via the Oauth2 or basic Oauth mechanism?
I would like to call the SSO to retrieve an Oauth2 token and pass this token on API calls.
Can you confirm the good chip management with Microcks?
Thank you in advance
cordially
Christophe

**Comment by lbroudoux** [comment]
Hi @crismarfr !

Thanks for trying out Microcks. Yes what you are trying to do is possible on the latest version (`0.7.0`) of Microcks through the usage of the `microcks-serviceaccount` client of the Keycloak `microcks`realm that is able to realize the Direct Access Grant OAuth flow.

This is what is using the Jenkins plugin right now - you may want to have a look [here](https://github.com/microcks/microcks-jenkins-plugin/tree/master/src/main/java/io/github/microcks/jenkins/plugin/util) for Java samples. There's also some explanations on this [thread](https://github.com/microcks/microcks/issues/69#issuecomment-438580970).

You should get what you need there. Keep us in the loop ;-)

Cheers,

**Comment by crismarfr** [comment]
Hi 
Thanks you for your response but i would like to mock secured API with Oauth2 token exposed on my spring cloud microservice platform. I design my mock with Postman et generate token with Authorization section in Postman. When i import my collection in microcks, i don't see Authrorisation information (token etc ...) in the API imported. Can you help me ?
Thank you
Cordially
Christophe

**Comment by lbroudoux** [comment]
Ha ok !
You should see required Authroization information as headers onto the different request samples.
For now we do not check this headers presence but this is on our roadmap !

**Comment by lbroudoux** [comment]
This relates now to the feature request tracked into #93

**Comment by lbroudoux** [comment]
Now that #93 is closed, closing this one.
