### ISSUE TITLE
Be able to add external examples (with relative paths) & follow JSON pointer

### ISSUE THREAD

**Issue by oliviernguyenquoc** [microcks/microcks#921]
### Reason/Context

Following this [discussion](https://github.com/orgs/microcks/discussions/916), I would like to propose an new feature:

Be able to follow and load an external reference (an external json file path, a relative path).

The goal is to be able to have examples in json (external files) that can be used in both openAPI 3.1 specs and in other tests of my API.

### Description

Here an example:

In ./spec.yaml, an openAPI 3.1 spec with an external link:

```yaml
---
openapi: 3.1
info:
  title: API Pastry - 2.0
  version: 2.0.0
  description: API definition of API Pastry sample app
  contact:
    name: Laurent Broudoux
    url: http://github.com/lbroudoux
    email: laurent.broudoux@gmail.com
  license:
    name: MIT License
    url: https://opensource.org/licenses/MIT
components:
  examples:
    pastries_json:
      summary: Some delicious pastries
      externalValue: './examples/an_external.json'
   single_pastry:
     summary: A unique delicious pastry
     externalValue: './examples/an_external.json#/0'
paths:
  /pastry:
    summary: Global operations on pastries
    get:
      tags:
      - pastry
      responses:
        "200":
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Pastry'
              examples:
               pastries_json:
                 $ref: '#/components/examples/pastries_json'
          description: Get list of pastries
      operationId: GetPastries
      summary: Get list of pastries
  /pastry/{name}:
    summary: Specific operation on pastry
    get:
      parameters:
      - examples:
          Eclair Cafe:
            value: Eclair Cafe
          Eclair Cafe Xml:
            value: Eclair Cafe
          Millefeuille:
            value: Millefeuille
        name: name
        description: pastry name
        schema:
          type: string
        in: path
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pastry'
              examples:
                $ref: '#/components/examples/pastries_json#/0'
```

In ./examples/an_external.json:

```json
[
  {
    "name": "Baba Rhum",
    "description": "Delicieux Baba au Rhum pas calorique du tout",
    "size": "L",
    "price": 3.2,
    "status": "available"
  },
  {
    "name": "Divorces",
    "description": "Delicieux Divorces pas calorique du tout",
    "size": "M",
    "price": 2.8,
    "status": "available"
  },
  {
    "name": "Tartelette Fraise",
    "description": "Delicieuse Tartelette aux Fraises fraiches",
    "size": "S",
    "price": 2,
    "status": "available"
  }
]
```
Note that the second path uses the same reference to #/components/examples but with a JSON Pointer (RFC 6901) to select the first element of an array.
I made also a JSON pointer for the second example to be able to test this case too.

Those files could be either:
- In a repository linked to Microcks
- Mounted in Microcks container

Thank you for your work.
You (mic)rocks !

**Comment by lbroudoux** [comment]
Thank you for opening and giving details on this issue @oliviernguyenquoc! We'll not succeed in putting it within the `1.8.0` release (that is already late), but consider adding it for the next one. Hope to be able to give you visibility on that shortly!

Cheers,

**Comment by lbroudoux** [comment]
Hi @oliviernguyenquoc,
I'm going to start working on this one. Still interested in it? Will you have some availabilities to help in testing and validation?

**Comment by oliviernguyenquoc** [comment]
Hi ! 

I had to switch to another project. I may have some time to make some test but it will hardly be more extensive than the one posted just above.

I'm keep looking at this issue, keep you update if i'm able to test the feature but you can't fully count on me for the moment.

Sorry 😬

**Comment by lbroudoux** [comment]
As per the specification, `externalValue` seems to have a different goal than the one you used it for: `This provides the capability to reference examples that cannot easily be included in JSON or YAML documents.`

I think that the preferred way to achieve what you're trying to do would be to use a `$ref` like proposed below:

```yaml
---
openapi: 3.1
info:
  title: API Pastry - 2.0
  version: 2.0.0
  description: API definition of API Pastry sample app
  contact:
    name: Laurent Broudoux
    url: http://github.com/lbroudoux
    email: laurent.broudoux@gmail.com
  license:
    name: MIT License
    url: https://opensource.org/licenses/MIT
components:
  examples:
    pastries_json:
      summary: Some delicious pastries
      $ref: './examples/an_external.json'
   single_pastry:
     summary: A unique delicious pastry
     $ref: './examples/an_external.json#/0'
paths:
  [...]
```

I'm currently evaluating implementing this in #984 and I think it would make more sense to reserve `externalValue` usage to non-text based examples like mentioned in this discussion: https://github.com/orgs/microcks/discussions/977 

What do you think?

**Comment by oliviernguyenquoc** [comment]
Makes completely sense for me. I didn't get the difference between externalValue and $ref to be honest.

Ok for you if I create a new idea suggestion on [APIcurio github](https://github.com/Apicurio/apicurio-studio)  to handle external example in json  ? 
It would be so great to have a better example management and still be able to use the duo apicurio / microcks at the same time.

**Comment by lbroudoux** [comment]
Certainly! Please do so! Can we close this issue and thus track the use of external examples in JSON files in #984?
