### ISSUE TITLE
Allow dynamic content for mock response

### ISSUE THREAD

**Issue by lbroudoux** [microcks/microcks#94]
Whilst we promote defining real work samples as source for Microcks mocks responses, we may find some use-cases where it's worth having some kind of dynamically generated content for response.

Those use-case encompass: 
* random numbers that may be defined in a range,
* today's date or today's + an amount of time (for validity date for example),
* response part expressed from request part (body part, header, query param)

This new feature goal is to define or to reuse a kind of expression language that can be used to express templatized mock response part. As first candidate, we may think of Mustache language and JMustache implementation. However we'll have to define a subset of what can be manage into our mocks.

Ideally, this templating / expression language may be shared with some other tooling like Apicurio or Postman that aim to provide easy to use editors for the mock samples.

**Comment by ecyrbe** [comment]
Take a look at https://github.com/typicode/json-server
It does dynamic json mocking with low code/ zero code

**Comment by lbroudoux** [comment]
Hi @ecyrbe ,

Thanks for the comment !
> Take a look at https://github.com/typicode/json-server
> It does dynamic json mocking with low code/ zero code

I think that is very analogous to what we are doing using _Backend as a Service_ or _Dynamic Mocks_ as it is documented here: https://microcks.io/documentation/using/dynamic/. Feel free to comment if I miss the point.

Regarding this issue, I will put some new code here very very soon ;-)

**Comment by lbroudoux** [comment]
Done ;-)
