### ISSUE TITLE
Indent 2 or 3?

### ISSUE THREAD

**Issue by bodiam** [microcks/microcks#941]
### Describe the bug

Hi there,

I'm trying to clean up some code for Microcks, but I don't understand the formatting. The `editorconfig` says indent with 2 spaces, which is fine, but the code is indented with mostly 3(?) spaces, and unformatted at a lot of other places. 

I don't know what the style is, and it would be easier to contribute if the style was perhaps a bit more consistent, so I don't introduce a lot of changed just for the sake of formatting.

Cheers,

Erik

**Comment by lbroudoux** [comment]
Hey there! Sorry for inconsistencies in formatting. I think the general rules applied until now have been:
- 3 spaces for Java code
- 2 spaces for HTML/TS/CSS code

**Comment by bodiam** [comment]
@lbroudoux yes, I got the impression, thanks. First time in 20+ years I see an indent of 3 spaces :)
