### ISSUE TITLE
Docker compose: Broken Keycloak config

### ISSUE THREAD

**Issue by Apoorva64** [microcks/microcks#943]
### Describe the bug

Application does not launch

The Issuer "http://localhost:18080/realms/microcks" provided in the configuration did not match the requested is
suer "http://keycloak:8080/realms/microcks"

### Expected behavior

Application launches xD

### Actual behavior

Fails at keyclock config in WebApp

### How to Reproduce?

Launch docker compose

### Microcks version or git rev

master

### Install method (`docker-compose`, `helm chart`, `operator`, `docker-desktop extension`,...)

docker-compose

**Comment by lbroudoux** [comment]
Damned! I forgot to report some of latest changes coming with #920 to docker-compose configuration...
