### ISSUE TITLE
Allow testing on endpoint that only returns 204 responses

### ISSUE THREAD

**Issue by jtama** [microcks/microcks#944]
### Reason/Context

As of now Mickrocks doesn't generate tests for endpoints that don't return response contents because OpenAPIImporter is building expected responses based on the reponse content examples (https://github.com/microcks/microcks/blob/master/webapp/src/main/java/io/github/microcks/util/openapi/OpenAPIImporter.java#L263).

This is really important as many creation endpoints can return 204 reponses without any body but still needs to be tested.

### Description

Introduce a way to match excepted result with request examples. 

I don't think it's gonna be a breaking change, as it is an addition

### Implementation ideas

As the OAS specification says, responses objects may be extended, so we could this to add link between a response and a request samples as per the following : 

```yaml
  /api/dummy:
    put:
      operationId: dummy
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DummyDto'
            examples:
              nominal:
                summary: valid dummy request
                value: |
                  {
                    "beatles": "are the best"
                  }
              incorrect:
                summary: invalid dummy request
                value: |
                  {
                    "beatles": "are all dead"
                  }
      responses:
        "204":
          description: No Content
          x-ref: nominal
        "418":
          description: Not Authorized
          x-ref: incorrect
      security:
        - oidc:
            - class_write
```

Note that it could even be used by generated contract : https://github.com/eclipse/microprofile-open-api/blob/main/api/src/main/java/org/eclipse/microprofile/openapi/annotations/responses/APIResponse.java

And it's processed by smallrye at least : https://github.com/smallrye/smallrye-open-api/blob/main/core/src/main/java/io/smallrye/openapi/runtime/io/response/ResponseReader.java#L191

**Comment by dontfreakout** [comment]
Hello, is there any way I can help with this? 
We are using a lot of endpoints (usually, create or delete) with 201 or 204 with empty responses.

For mocking, we are using [#682](https://github.com/orgs/microcks/discussions/682) as a workaround, but testing does not work for obvious reasons.

I like how elegant `x-ref: ` solution is. Maybe we can use `x-microcks-ref` as there already are other Microcks extensions.

**Comment by lbroudoux** [comment]
Hi @dontfreakout and @jtama,

I removed the `stale` label and put a `keep-open` one, as this is definitely something we want to integrate.
The problem at the moment is the priorities and the necessary time to work on this...

**Comment by lbroudoux** [comment]
Hey there!

I finally found some time to implement this as part of the incoming `1.9.0` and I'd like to ask you - @jtama and @dontfreakout - for review.

Based on above proposition, I've done things a bit differently like this:

```yaml
  /api/dummy:
    put:
      operationId: dummy
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DummyDto'
            examples:
              nominal:
                summary: valid dummy request
                value: |
                  {
                    "beatles": "are the best"
                  }
              incorrect:
                summary: invalid dummy request
                value: |
                  {
                    "beatles": "are all dead"
                  }
      responses:
        "204":
          description: No Content
          x-microcks-refs:
            - nominal
        "418":
          description: Not Authorized
          x-microcks-refs: 
            - incorrect
      security:
        - oidc:
            - class_write
```

The extension property is now called `x-microcks-refs` as suggested by @dontfreakout, and is actually an array (so `refs`) so that you can associate more than one example request to no content response.

The new `quay.io/microcks/microcks:nightly` image now contains these changes.
Let me know what you think about it!

**Comment by dontfreakout** [comment]
Wow @lbroudoux 
this is better than I imagined. The fact that it is an array is a great bonus.
I will test it on Monday. Thank you for letting me know and have a nice weekend :slightly_smiling_face:

**Comment by jtama** [comment]
This is great ! I will also gobe it a try this week, it will be a most valuable feature.

**Comment by lbroudoux** [comment]
Done some complementary tests this morning, and everything seems to work fine (after some adaptations 😉 ). I'm closing this one as a first step to be able to release the `1.9.0` version. Feel free to re-open a complementary issue afterwards so that we'll build upon this one.

**Comment by jtama** [comment]
Sorry schedule is a bit full right now...
