### ISSUE TITLE
Allow Http exchanges recording

### ISSUE THREAD

**Issue by robertonav20** [microcks/microcks#949]
### Reason/Context

Hi,
i see the dashboard page and the graph of stats but the only report is the number of invocation for all or for each API.
In a context when the application is deployed inside a cluster is hard to see what call receive, so i think is a good improve add a page where describe the all incoming request to see input and output

### Description

In a context when the application is deployed inside a cluster is hard to see what call receive

### Implementation ideas

I don't know the metrics part of applications if you have some idea, i can work on it and suggest a pr

**Comment by robertonav20** [comment]
I'm thinking about a solution and I found this
https://docs.spring.io/spring-boot/docs/2.1.0.M1/reference/html/production-ready-http-tracing.html

Spring offers a way to trace all http by default the latest 100 calls, but is possible to implement the own repository to store and query

**Comment by lbroudoux** [comment]
Hi Roberto,
Thanks for raising this issue. I propose renaming it to `Allow Http exchanges recording` if it's ok for you.
I think we've got several initiatives/issues that may be related to that:
* Provide a Grafana dashboard for Microcks. See #871 
* Allow to get details on how dispatching choices are made. See #874 

I understand your need is a bit different as you'd like to get detailed payloads on Http exchanged realized on a Microcks instance. Is it correct?

I see it as a specific need that may directly impact consumed resources and the performance behavior of the application, and I wonder if we shouldn't support it as a user/deployment-time customization. In the past, we allowed providing extra properties for configuring your Spring Boot context (see #698) and are looking how to extend your application with custom lib (see #931).

I imagine we can allow user to provide additional props like `management.endpoint.httpexchanges.enabled=true` and embed addition Jar where a Spring Configuration would provide the required `HttpExchangeRepository`.

What do you think of this approach?

**Comment by robertonav20** [comment]
Hi @lbroudoux,
yes of course, the possibility to enable or disable a feature with a default behavior is always the best approach to introduce something of new.
I try to describe what i say before with an example, imagine you have a kubernetes cluster which contains Application A and Microcks and you want to call Microcks and receive call from it for integration/testing purpose.
If something goes wrong, at the moment you are blind because you don't see what's happening, the only solution is go deep inside the logs of microcks and other application (in the best case is one  😆)

So the best solution is trace every call, with "tracing" enabled, and query that data from ui.
How to make it?

Simple solution:
1. Trace every call in with spring style HttpTrace object which contains Request/Response
2. Store them in a configured map inside heap like spring or if they are a lot of data, persist in async mode inside mongo and if you want optimize is possible use a buffer before persist, or use a message broker directly and then persist into mongo
3. Query them from ui

Of cource this solution is limited by infrastructure resource and use case, in my case is enough a configured map inside heap microcks-uber

Strong solution:
1. Trace every call in with spring style HttpTrace object which contains Request/Response
2. Use search index engine like ElasticSearch or Grafana Loki
3. Query them from ui

What are you think of my suggestions?
