### ISSUE TITLE
Configurable CORS

### ISSUE THREAD

**Issue by apoorva256** [microcks/microcks#956]
### Reason/Context

When Front application requests Mock server with "include credentials" enables. Browser does not accept "*" as CORS.

### Description

This will not have breaking changes

### Implementation ideas

https://github.com/microcks/microcks/blob/master/webapp/src/main/java/io/github/microcks/web/RestController.java#L385

Add a configuration parameters here

**Comment by lbroudoux** [comment]
Thanks for the improvement suggestion and the PR.

To go further, I would say that we could add `Access-Control-Allow-Origin` customization at different levels:
* For a whole Microcks instance - that's what you proposed in the PR
-- In that case, it won't probably fit all Service / API version
* For a Microcks Service / API version - think of the inclusion of an extra attribute in `x-microcks` specific attribute or other.
-- in that case, it won't probably fit all frontend clients needs
* For every incoming mock invocation - think of the reuse of location of the incoming request or the use of a global map.
-- might probably fit all cases.

Obviously, I'd prefer to implement case number 3 but need to dig further to see what we can extract and what kind of information we can directly reuse. Any ideas on how to do that are more than welcomed!

**Comment by apoorva256** [comment]
Is it possible to merge my PR for now and discuss in https://github.com/orgs/microcks/discussions/976 about it ?
