### ISSUE TITLE
Add kafka login callback handler support

### ISSUE THREAD

**Issue by Afanas10101111** [microcks/microcks#966]
### Reason/Context

Hi!
I want to add support for a custom Kafka login callback handler to the project.
This will allow to integrate Microcks with the Kafka broker, which uses authorization.

### Description

To do this, I need to add a few lines of code. There will be no breaking changes.
After the improvement all we need is to build microcks-async-minion as legacy-jar, add the property with fully qualified name of our custom handler class, add its library to the classpath.

### Implementation ideas

The idea is to add a property setting here:
https://github.com/microcks/microcks/blob/3088050a14e990cdc55df1215e1351bfcde3ad2d/minions/async/src/main/java/io/github/microcks/minion/async/producer/KafkaProducerManager.java#L290

**Comment by lbroudoux** [comment]
Is this related to the support of `OAUTHBEARER` sasl mechanism?

**Comment by Afanas10101111** [comment]
In my case, yes - I needed to produce mock messages to kafka topic under OAUTHBEARER. As I know, there are few auth mechanisms supported by kafka (https://docs.confluent.io/platform/current/kafka/overview-authentication-methods.html), and I assume that sasl.login.callback.handler.class may be used for any of them. But, truely, I tested OAUTHBEARER only.

**Comment by lbroudoux** [comment]
@ludovic-pourrat: I know you had the same request for feature enhancement and may have done some things on your side. Could you check this one, please?

**Comment by lbroudoux** [comment]
Hey @Afanas10101111!
Sorry for the delay, but I was at KubeCon last week and had to manage priorities.
I'm still interested in this one and will probably have a look at it tomorrow to go forward on merging. One thing I was wondering is the need to change Quarkus packaging to `legacy-jar`: don't we need to apply changes in the `pom.xml` of the module too?

**Comment by Afanas10101111** [comment]
No, no additional changes are required, all we need to do is run `mvn package -Dquarkus.package.type=legacy-jar`. Alternatively we can add `quarkus.package.type` as a property in `minions/async/src/main/resources/application.properties`, but I think it is more suitable for build time, so I added it as part of the instruction in `minions/async/src/main/docker/Dockerfile.legacy-jar`

**Comment by Afanas10101111** [comment]
Hey @lbroudoux 
I want to ask for advice. I want to add basic `OAUTHBEARER` support for the consumer too. Is it correct to make a new pull request and link it to this issue?

**Comment by lbroudoux** [comment]
I think it would be better to have a different PR for that as the mechanism involved may probably be different (I assume we had to extend the Secret concept). 

Also another PR/issue will be easier for discussion and help us having a faster merge process - I'm a bit busy at the moment sorry for long delay...

As a side note, I'd be happy to connect and have a chat on what you're a currently doing with Microcks. Looks super interesting that you have these advanced concerns!!

**Comment by Afanas10101111** [comment]
Yes, I'm thinking about a new PR because I want to discuss some moments with you, the question is whether a new issue is needed :)
My idea is to use the same mechanism with `sasl.login.callback.handler.class`. And I've already made and tested it :)
It's a very basic `OAUTHBEARER` support for the consumer. All the changes (very few) are in `KafkaMessageConsumptionTask.class`.

Don't worry about the delay, there's no rush :)

Thank you for your interest! I'll be happy if these small improvements help someone.
Now I'm just trying to make Microcks more suitable for Kafka with oauth. I also have an idea for future improvements but it looks global and I haven't started researching it yet. But if you have any questions, I'm open to them!

**Comment by lbroudoux** [comment]
PR #967 is now merged but we also need to:
* produce a `microcks-async-minion` container image with the correct layout (moving from default to `legacy-jar`),
* have additional configuration items on both Helm Chart and Operator to enable setting the `sasl.login.callback.handler.class`

**Comment by lbroudoux** [comment]
Hello @Afanas10101111

I changed the async-minion image layout yesterday and did some final tests this morning: everything is now ready and thus OK for `1.8.1` release! I've also updated the Helm chart and the operator, so we're ready to go! 🚀 

Thanks again for your contribution!
