### ISSUE TITLE
use helm install microcks not working 

### ISSUE THREAD

**Issue by tage-zh** [microcks/microcks#968]
### Describe the bug

Hi dear:
I wanna use microcks, and base on the document https://microcks.io/documentation/installing/kubernetes/ try to use helm install microcks into my own k8s cluster (SAP BTP kyma provide the K8S clusters), use those command 
$ helm repo add microcks https://microcks.io/helm

$ kubectl create namespace microcks

$ helm install microcks microcks/microcks --version 1.7.1 --namespace microcks --set microcks.url=microcks.$(minikube ip).nip.io --set keycloak.url=keycloak.$(minikube ip).nip.io

how should i know the $(minikube ip)? 

it always say
WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /Users/XXXXX/.kube/config
WARNING: Kubernetes configuration file is world-readable. This is insecure. Location: /Users/XXXXX/.kube/config
Error: INSTALLATION FAILED: expected at most two arguments, unexpected arguments: —-version, 1.7.0

Thanks

**Comment by yada** [comment]
Hi @tage-zh,

$(minikube ip) is a command to retrieve node IP when installing Micrcocks helm chart on a Minikube cluster (https://minikube.sigs.k8s.io/docs/). This command retrieves the IP address of the specified node. See: https://minikube.sigs.k8s.io/docs/commands/ip/

Using Microk8s (https://microk8s.io/), you can use this command to retrieve the INTERNAL-IP:
```
$ microk8s kubectl get nodes -o wide
NAME       STATUS   ROLES    AGE   VERSION   INTERNAL-IP      EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION     CONTAINER-RUNTIME
yadadesk   Ready    <none>   55d   v1.28.2   192.168.42.139   <none>        Ubuntu 22.04.3 LTS   6.2.0-35-generic   containerd://1.6.15
```

On Kubernetes, use the command below to retrieve the INTERNAL-IP:
`$ kubectl get nodes -o wide`

So, it all depends on the k8s cluster you are targeting (see examples above), but **the cluster IP must be added to the nip.io URLs in the helm install command line.**

I hope it helps you.
Regards,
Yacine

**Comment by lbroudoux** [comment]
Hi @tage-zh,

Any news on this topic?

**Comment by lbroudoux** [comment]
I'm gonna close this one without any further information. Feel free to re-open with additional information.
