### ISSUE TITLE
Pretty print json examples

### ISSUE THREAD

**Issue by hguerrero** [microcks/microcks#971]
### Reason/Context

When looking at the mock examples, the content is shown _as is_.

### Description

When loading a document from OpenAPI, the examples in the mock sections are rendered in the text _as is_. Meaning that some are pretty printed and others are one-liners. It would be good to show them formatted for easy reading.

### Implementation ideas

Run JSON pretty format when displaying JSON examples.

**Comment by lbroudoux** [comment]
I suspect this could be done easily on the client-side while rendering the request and responses boxes
