### ISSUE TITLE
OpenAPI reference not resolved at the examples level

### ISSUE THREAD

**Issue by apoorva256** [microcks/microcks#972]
### Describe the bug

![image](https://github.com/microcks/microcks/assets/147162424/f7275ebc-467c-4bf6-b6cf-80b18ead1a87)
The Reference Resolver is broken. Thus the example is not corrupted

### Expected behavior

The example is imported

### Actual behavior

The example is corrupted

### How to Reproduce?

1. load this yaml file

```yaml
openapi: "3.0.0"
info:
  title: Broken Ref
  version: 2.0.0
paths:
  /v1.0/endpoint:
    get:
      description: Broken Ref

      responses:
        '200':
          content:
            application/json:
              examples:
                $ref: '#/paths/~1v1.0~1endpoint/get/responses/200/headers/x-Some-Header/examples'
          description: redirect to pdf file
          headers:
            x-Some-Header:
              examples:
                example1:
                  value: 'someValue'
              schema:
                type: string

```
2. Go to the Service

### Microcks version or git rev

1.8.0

### Install method (`docker-compose`, `helm chart`, `operator`, `docker-desktop extension`,...)

docker-compose

### Additional information

Resolving with 'swagger-cli'(https://www.npmjs.com/package/swagger-cli) gives
```yaml
openapi: 3.0.0
info:
  title: Broken Ref
  version: 2.0.0
paths:
  /v1.0/endpoint:
    get:
      description: Broken Ref
      responses:
        '200':
          content:
            application/json:
              examples:
                example1:
                  value: someValue
          description: redirect to pdf file
          headers:
            x-Some-Header:
              examples:
                example1:
                  value: someValue
              schema:
                type: string
```

Importing this file works as intended

**Comment by lbroudoux** [comment]
Thanks for opening this one!

Most of the time, `$ref` is used to handle the path to reusable `#/definitions` or `#/components` so we don't have to manage escape characters... So I suspect we don't explicitly manage them at the Microcks level. Will have a look at this in the coming days.
