### ISSUE TITLE
Adding a Formatter to Microcks

### ISSUE THREAD

**Issue by ghost** [microcks/microcks#975]
### Reason/Context

As many devs start working on the project we need a formatter to generalize our code style

### Description

No breaking change

### Implementation ideas

https://github.com/diffplug/spotless

example conf:
```xml
   <plugin>
                <groupId>com.diffplug.spotless</groupId>
                <artifactId>spotless-maven-plugin</artifactId>
                <version>2.27.2</version>
                <configuration>
                    <formats>
                        <!-- you can define as many formats as you want, each is independent -->
                        <format>
                            <!-- define the files to apply to -->
                            <includes>
                                <include>*.md</include>
                                <include>.gitignore</include>
                            </includes>
                            <!-- define the steps to apply to those files -->
                            <trimTrailingWhitespace/>
                            <endWithNewline/>
                            <indent>
                                <spaces>true</spaces>
                            </indent>
                        </format>
                    </formats>
                    <!-- define a language-specific format -->
                    <java>
                        <!-- no need to specify files, inferred automatically, but you can if you want -->

                        <!-- apply a specific flavor of google-java-format and reflow long strings -->
                        <googleJavaFormat>
                            <version>1.15.0</version>
                            <style>AOSP</style>
                            <reflowLongStrings>true</reflowLongStrings>
                        </googleJavaFormat>
                        <toggleOffOn />
                    </java>
                </configuration>
                <executions>
                    <execution>
                        <goals>
                            <goal>apply</goal>
                        </goals>
                        <phase>compile</phase>
                    </execution>
                </executions>
            </plugin>
```
used here https://github.com/Apoorva64/takenoko

**Comment by lbroudoux** [comment]
Hey there!
I give a try at `spotless-maven-plugin` but didn't succeed in achieving what I'd like it to do.
As the whole Java code is now written with indent of 3 spaces, I wanted to keep this basic constraint.

As explained in the doc, order of Formatter steps matters and I thought that I could apply a style but keep my indent using this configuration:

```xml
      <plugin>
        <groupId>com.diffplug.spotless</groupId>
        <artifactId>spotless-maven-plugin</artifactId>
        <version>2.39.0</version>
        <configuration>
          <!-- define a language-specific format -->
          <java>
            <!-- no need to specify files, inferred automatically, but you can if you want -->
            <palantirJavaFormat>
              <version>2.10.0</version>
              <style>PALANTIR</style>
            </palantirJavaFormat>
            <indent>
              <spaces>true</spaces>
              <spacesPerTab>3</spacesPerTab>
            </indent>
          </java>
        </configuration>
        <executions>
          <execution>
            <goals>
              <goal>apply</goal>
            </goals>
            <phase>compile</phase>
          </execution>
        </executions>
      </plugin>
```
However it sticks with 4 spaces indentation!

I also tried removing the `palantirJavaFormat` to only keep the `indent` information but in that case it doesn't fix files with 4 spaces indent saying that they're clean. 

Would you have a basic configuration that is able to respect this constraint as a startup?

**Comment by Apoorva64** [comment]
> Hey there!
> I give a try at `spotless-maven-plugin` but didn't succeed in achieving what I'd like it to do.
> As the whole Java code is now written with indent of 3 spaces, I wanted to keep this basic constraint.
> 
> As explained in the doc, order of Formatter steps matters and I thought that I could apply a style but keep my indent using this configuration:
> 
> ```xml
>       <plugin>
>         <groupId>com.diffplug.spotless</groupId>
>         <artifactId>spotless-maven-plugin</artifactId>
>         <version>2.39.0</version>
>         <configuration>
>           
>           <java>
>             
>             <palantirJavaFormat>
>               <version>2.10.0</version>
>               <style>PALANTIR</style>
>             </palantirJavaFormat>
>             <indent>
>               <spaces>true</spaces>
>               <spacesPerTab>3</spacesPerTab>
>             </indent>
>           </java>
>         </configuration>
>         <executions>
>           <execution>
>             <goals>
>               <goal>apply</goal>
>             </goals>
>             <phase>compile</phase>
>           </execution>
>         </executions>
>       </plugin>
> ```
> However it sticks with 4 spaces indentation!
> 
> I also tried removing the `palantirJavaFormat` to only keep the `indent` information but in that case it doesn't fix files with 4 spaces indent saying that they're clean. 
> 
> Would you have a basic configuration that is able to respect this constraint as a startup?
> 
> cc @Apoorva64

Sorry for the late reply. Do you have a branch where you did the changes?

**Comment by lbroudoux** [comment]
No sorry. Only did local changes in the /commons/util-el module.

**Comment by Apoorva64** [comment]
> Hey there! I give a try at `spotless-maven-plugin` but didn't succeed in achieving what I'd like it to do. As the whole Java code is now written with indent of 3 spaces, I wanted to keep this basic constraint.
> 
> As explained in the doc, order of Formatter steps matters and I thought that I could apply a style but keep my indent using this configuration:
> 
> ```
>       <plugin>
>         <groupId>com.diffplug.spotless</groupId>
>         <artifactId>spotless-maven-plugin</artifactId>
>         <version>2.39.0</version>
>         <configuration>
>           
>           <java>
>             
>             <palantirJavaFormat>
>               <version>2.10.0</version>
>               <style>PALANTIR</style>
>             </palantirJavaFormat>
>             <indent>
>               <spaces>true</spaces>
>               <spacesPerTab>3</spacesPerTab>
>             </indent>
>           </java>
>         </configuration>
>         <executions>
>           <execution>
>             <goals>
>               <goal>apply</goal>
>             </goals>
>             <phase>compile</phase>
>           </execution>
>         </executions>
>       </plugin>
> ```
> 
> However it sticks with 4 spaces indentation!
> 
> I also tried removing the `palantirJavaFormat` to only keep the `indent` information but in that case it doesn't fix files with 4 spaces indent saying that they're clean.
> 
> Would you have a basic configuration that is able to respect this constraint as a startup?
> 
> cc @Apoorva64

There is an issue on it but they are not going to fix it

https://github.com/diffplug/spotless/issues/117

**Comment by lbroudoux** [comment]
Ok... so I found I'd have to look at some other options like https://code.revelc.net/formatter-maven-plugin/ for example...

**Comment by lbroudoux** [comment]
Now done!
