### ISSUE TITLE
Yaml file does not resolve on gitlab

### ISSUE THREAD

**Issue by apoorva256** [microcks/microcks#980]
### Describe the bug

When the base yaml file is in a folder ex: /src/openapi.yaml 

```
4:05:42.021  INFO 1 --- [080-exec-1] i.g.microcks.service.ServiceService      : Importing service definitions from https://gitlab.com/api/v4/projects/51856766/repository/files/src%2Fopenapi.yaml/raw?ref=main
14:05:42.420 DEBUG 1 --- [080-exec-1] g.m.u.RelativeReferenceURLBuilderFactory : Returning a SimpleReferenceURLBuilder
14:05:42.421  INFO 1 --- [080-exec-1] i.g.m.u.MockRepositoryImporterFactory    : Found an openapi: 3 pragma in file so assuming it's an OpenAPI spec to import
14:05:42.422 DEBUG 1 --- [080-exec-1] i.g.microcks.service.ServiceService      : Service [Resolver Failure, 2.0.0] exists ? false
14:05:42.423  INFO 1 --- [080-exec-1] i.g.microcks.util.ReferenceResolver      : Downloading a reference file at https://gitlab.com/api/v4/projects/51856766/repository/files/src%2Fopenapi.yaml/param.yaml
14:05:42.650 ERROR 1 --- [080-exec-1] i.g.m.util.openapi.OpenAPIImporter       : IOException while trying to resolve reference ./param.yaml

java.io.FileNotFoundException: https://gitlab.com/api/v4/projects/51856766/repository/files/src%2Fopenapi.yaml/param.yaml
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1996)
```

file does not resolve

### Expected behavior

file should resolve

### Actual behavior

does not resolve

### How to Reproduce?

Repository: https://gitlab.com/group14475444/open-api-reference-test

1. add Importer job with https://gitlab.com/api/v4/projects/51856766/repository/files/src%2Fopenapi.yaml/raw?ref=main

### Microcks version or git rev

1.8.x

### Install method (`docker-compose`, `helm chart`, `operator`, `docker-desktop extension`,...)

docker-compose

### Additional information

Works with github does not work on gitlab, probably due to URL encode. As we can see the resolver does not remove the filename in the URL. And it dosen't use the right Reference Resolver in the logs

github tested with: https://github.com/apoorva256/openapi-resolver-fail which works

**Comment by lbroudoux** [comment]
Thanks for opening this one. This was supposed to work as we have a specific resolver for GitLab that must take care of appending `?ref=<branch>` when fetching references. Will have a look probably tonight.

**Comment by lbroudoux** [comment]
It appears that GitLab API has changed its response headers from `X-Gitlab-File-Name` to `x-gitlab-file-name` and we had a strict comparison approach. Making this more robust.

**Comment by lbroudoux** [comment]
Fix has been tested on `https://gitlab.com/lbroudoux/public-repo-test` with `https://gitlab.com/api/v4/projects/51974239/repository/files/src%2Fopenapi.yaml/raw?ref=main` import URL. 
It is now available in the `quay.io/microcks/microcks:nightly` container image.
