### ISSUE TITLE
Learn More link points to main webpage

### ISSUE THREAD

**Issue by hguerrero** [microcks/microcks#981]
### Describe the bug

In the Operation detail page of a REST API, the link in the Dispatcher `Learn More` points to microcks.io main page instead of the details of the Dispatcher type.

### Expected behavior

Link to the documentation page

### Actual behavior

Links to the main page

### Microcks version or git rev

1.8

### Install method (`docker-compose`, `helm chart`, `operator`, `docker-desktop extension`,...)

docker desktop

**Comment by lbroudoux** [comment]
Now available in `quay.io/microcks/microcks:nightly` container image
