### ISSUE TITLE
Learn More link opens in same tab

### ISSUE THREAD

**Issue by hguerrero** [microcks/microcks#982]
### Describe the bug

When clicking the `Learn More` links in the Operation section and pages the page loads in the same tab instead of opening a new tab / window.

### Expected behavior

Open the link in a new tab

### Actual behavior

Loads content in the same page and needs to navigate back to get back to microcks.

### Microcks version or git rev

1.8

### Install method (`docker-compose`, `helm chart`, `operator`, `docker-desktop extension`,...)

docker desktop

**Comment by lbroudoux** [comment]
Now available in `quay.io/microcks/microcks:nightly` container image
