### ISSUE TITLE
Microcks does not resolve relative refs in relative file in repository

### ISSUE THREAD

**Issue by ghost** [microcks/microcks#986]
### Describe the bug

Microcks fails to resolve refs that are in an resolved ref.

```yaml
openapi: "3.1.0"
info:
  title: Relative Resolver Failure
  version: 2.0.0
paths:
  /v1.0/endpoint:
    get:
      description: Relative Resolver Failure
      parameters:
        - in: query
          name: param
          required: true
          description: param for testing
          schema:
            type: string
          examples:
            EXAMPLE1:
              value: 1
      responses:
        '200':
          content:
            application/json:
              examples:
                $ref: ./hop1.yaml

          description: Broken Ref Resolver

```
hop1.yaml
```yaml
EXAMPLE1:
  value:
    $ref: "./hop2.yaml"
```
hop2.yaml
```
"EXAMPLE VALUE"
```

When importing microcks does not resolve the example  and shows "$ref" as example name

### Expected behavior

Should resolve and import the example

### Actual behavior

Does not import the example

### How to Reproduce?

1.  import with job the yaml at https://raw.githubusercontent.com/apoorva256/releative-resolver-failure/main/openapi.yaml?ref=main
2. Look at the endpoint in the service the response "EXAMPLE VALUE" will not be present

### Microcks version or git rev

1.8.x

### Install method (`docker-compose`, `helm chart`, `operator`, `docker-desktop extension`,...)

docker-compose

**Comment by apoorva256** [comment]
To fix this we must implement recursive resolving with the downloaded files instead of only searching refs to resolve in the origin file. In here https://github.com/microcks/microcks/blob/1.8.x/webapp/src/main/java/io/github/microcks/util/openapi/OpenAPIImporter.java#L180-L203

**Comment by apoorva256** [comment]
```java 
      // Browse all document references for external JSON schemas
      // only if we have a resolver available.
      if (referenceResolver != null) {

         Set<String> references = new HashSet<>();
         findAllExternalRefs(spec, references);

         while (!references.isEmpty()){
           var ref = references.stream().findFirst().orElseThrow();
           try {
               // Extract content using resolver.
               String content = referenceResolver.getHttpReferenceContent(ref, "UTF-8");
               String resourceName = ref.substring(ref.lastIndexOf('/') + 1);

               // Build a new resource from content. Use the escaped operation path.
               Resource schemaResource = new Resource();
               schemaResource.setName(IdBuilder.buildResourceFullName(service, resourceName));
               schemaResource.setPath(ref);
               schemaResource.setContent(content);
               schemaResource.setType(ResourceType.JSON_SCHEMA);
               ObjectMapper mapper = isYaml ? ObjectMapperFactory.getYamlObjectMapper(): ObjectMapperFactory.getJsonObjectMapper();
               JsonNode actualObj = mapper.readTree(content);
               findAllExternalRefs(actualObj,references);

               if (!ref.startsWith("http")) {
                  // If a relative resource, replace with new name.
                  specContent = specContent.replace(ref, URLEncoder.encode(schemaResource.getName(), "UTF-8"));
               }

               results.add(schemaResource);
            } catch (IOException ioe) {
               log.error("IOException while trying to resolve reference " + ref, ioe);
               log.info("Ignoring the reference {} cause it could not be resolved", ref);
            }
           references.remove(ref);
         }
         // Finally try to clean up resolved references and associated resources (files)
         referenceResolver.cleanResolvedReferences();
      }
      // Set the content of main OpenAPI that may have been updated with dereferenced dependencies.
      resource.setContent(specContent);

      return results;
   }

```
Proposed solution v1. Does not work for refs that have the same name and have originated from different location. Must change how the refs are named

**Comment by lbroudoux** [comment]
Hey @apoorva256!
Why do you close this one? I'm still thinking it's relevant even if I was away and not tackled it yet 😉

**Comment by apoorva256** [comment]
@lbroudoux I had closed this issue as i had solved the problem using the solution described [here](https://github.com/orgs/microcks/discussions/1022). But if your going to tackle it i am glad to reopen it xD.

**Comment by lbroudoux** [comment]
Do you mean you already integrated swagger-parser and plugged it into Microcks?

**Comment by Apoorva64** [comment]
> Do you mean you already integrated swagger-parser and plugged it into Microcks?

I wrote a proxy that does the bundling. So when I create an importer in microcks i use the Url
``` http://mybundler?host=https://gitlab.com&&id=12345&&path=docs/api.yaml
```

**Comment by lbroudoux** [comment]
It would be super interesting to publish something on this approach. Do you plan to write a blog post or something?

**Comment by lbroudoux** [comment]
Think I'm done with #984 😉 I'm going to tackle this one now!

**Comment by lbroudoux** [comment]
Now done!
