### ISSUE TITLE
Starting an ImportJob with API with serviceaccount getting 403 

### ISSUE THREAD

**Issue by hungphamvn** [microcks/microcks#990]
### Describe the bug

Hi there,
Thanks a ton for an awesome project,
We are trying to use `/api/jobs/{id}/start` in Microcks API v1.7 and get the response like the screenshot below.
Could you please help me check this out?
<img width="1147" alt="Screenshot 2023-11-15 at 18 07 56" src="https://github.com/microcks/microcks/assets/17606433/9388722c-09da-43b3-b979-ef9c64d95995">

Many thanks

**Comment by lbroudoux** [comment]
Hey @hungphamvn 

Thanks for your message! Have you been able to check the logs on the microcks server-side? Depending on how you're running you may use `docker logs <container-id>` or `kubectl logs pods/<pod-id>`? It can also be useful to check your encoded JWT bearer token using something like jwt.io to see if contained informations are correct (specifically the roles associated to token).

Cheers,

**Comment by hungphamvn** [comment]
Hi @lbroudoux,
Thanks for your response.
I'm using the default `microcks-serviceaccount` with docker-compose, please help me check whether are JWT bearer token informations correct.
<img width="562" alt="Screenshot 2023-11-16 at 09 23 35" src="https://github.com/microcks/microcks/assets/17606433/d46b0c28-6c7b-4ca5-88fa-926b9d494a82">

**Comment by lbroudoux** [comment]
Ok, I got it!

The default `microcks-serviceaccount` does not have enough privileges to start jobs. Managing job requires having the `manager` role at least. I think this is not mentioned in API documentation and has to be fixed.

So there are 2 ways of making this work:
* Create another service account with `manager` role,
* Add the `manager` role to the default service account.

**Comment by hungphamvn** [comment]
Awesome!!
I went the 2nd way and works like a charm.

Thanks for your time!

**Comment by lbroudoux** [comment]
You can do this via the Keycloak UI. Just pick the « role » thumbnail in
the service account details and add the manager role that is defined under
the microcks-app resource / application.
