### ISSUE TITLE
String format "date" should not be handle as "date-time" 

### ISSUE THREAD

**Issue by Snorkell** [microcks/microcks#997]
### Describe the bug

Hello, thanks for all the work on this tool, you're amazing !!
While testing some of my APIs, I saw that some of the automated test were failing due to a date not being valid

I'm havin the following message :
```
string "2023-09-07" is invalid against requested date format(s) [yyyy-MM-dd'T'HH:mm:ssZ, yyyy-MM-dd'T'HH:mm:ss.[0-9]{1,12}Z]
```` 
But as the official [OpenAPI documentation](https://swagger.io/docs/specification/data-models/data-types/#string) "date" is a valid string format for string like "yyyy-MM-dd"
But in the class [OpenAPISchemaValidator.java](https://github.com/microcks/microcks/blob/master/commons/util/src/main/java/io/github/microcks/util/openapi/OpenAPISchemaValidator.java) at line 308 you override the date format to date-time therefore making the json schema validator failing on validation the date format

```java
        // Convert date format to date-time.
         if (node.has("format") && node.path("format").asText().equals("date")
               && node.path("type").asText().equals("string")) {
            ((ObjectNode) node).put("format", "date-time");
         }
```

### Expected behavior

String date format should stay to date format after extracting json schema from the OpenAPI Specs
```yaml
myBirthDate:
  type: string
  format: date
````
should resolve to 
```json
{
 "myBirthDate":{
    "type": "string",
    "format": "date"
 }
}
````

### Actual behavior

```yaml
myBirthDate:
  type: string
  format: date
````
is resolving to
```json
{
 "myBirthDate":{
    "type": "string",
    "format": "date-time"
 }
}
````

### How to Reproduce?

Make your api return a date in format yyyy-MM-dd while describing the field as string format "date" 

### Microcks version or git rev

1.8.x

### Install method (`docker-compose`, `helm chart`, `operator`, `docker-desktop extension`,...)

test-container, local docker setup

### Additional information

Again thanks for all the work this tool is awesome

**Comment by lbroudoux** [comment]
Thanks for opening this one and for the kind words! 
Do be honest, I don't actually remember why we're doing that.... ;-) I'll have a look at it as soon as possible.
Cheers,

**Comment by lbroudoux** [comment]
Find out why we're doing that 😉 
Got some inspiration from this exiting lib: https://github.com/openapi-contrib/openapi-schema-to-json-schema and didn't realize that `dateToDateTime` conversion was an optional flag those default value is actually `false`.
You're right: I think this conversion should be removed for the sake of correctness.

**Comment by lbroudoux** [comment]
The conversion was removed from both `OpenAPISchemaValidator` and `AsyncAPISchemaValidator`. Thanks for the detailed analysis!
